### ISSUE TITLE
Framedebugger

### ISSUE THREAD

**Issue by Zer0xFF** [jpd002/Play-#1002]
I just want to point out that by detaching the frame debugger as per https://github.com/jpd002/Play-/commit/788abb739dab09d3f8fc692082d04b82fe05fbb3 would orphen the windows as per commit comment, which would result in perhaps unexpected side effect, if you open the frame debugger and "close" the emu and the frame debugger would remain open, but since the main loop is in the emu side of the code all the emu code would continue to run (including any running game, with no means to control it), since the dtor wouldnt trigger until the frame debugger is also closed.

Though I've actually been thinking, the frame debugger code runs independent of the actual emu (beside sharing settings, which might even be best to seperate), so why not build it as an external executable that can be started from the emu instead?

**Comment by jpd002** [comment]
I was wondering why we didn't have the same problem with the standard debugger and I saw that we were calling its close function on the MainWindow. I made something similar for the frame debugger here: https://github.com/jpd002/Play-/commit/305664e4511726dc0fe6c3763856b8d3db345a3c.

Having the frame debugger as a separate executable would be indeed possible, but I don't think it's worth the trouble.

**Comment by jpd002** [comment]
Sorry for hijacking this issue, but is it possible that we forgot to hook up the step action in the frame debugger's VU1 view?

**Comment by Zer0xFF** [comment]
haha, i actually forgot that we already had something for the debugger myself, but ya that should do it.

had a quick look and indeed, seems the old frame debugger had it mapped to F10, this wasn't mapped to at any key on the new UI. I'll have a PR for that soon.
