### ISSUE TITLE
Play! Mobiles

### ISSUE THREAD

**Issue by SweetGTA** [jpd002/Play-#1003]
Play! should focus more on improvisation on mobile devices, I Know It's Not Easy, But PC already has PCSX2, Please focus on Mobile Devices, If Needed, Don't Ask for Donations Only from Paypal / Patreon, it's better for Play! Paid version on Playstore or Appstore, don't be confused about what features if paid, just make it possible for us to change the theme or choose to use an image to create a background, simple .. Not everyone has a Paypal dude, you better be simple .. if this goes on, when can we play ps2 on mobile devices?

**Comment by ArthurVGCP** [comment]
😐

So essentially, you want this to become that other ps2 emulator (the one that starts with d) that can barely run games while taking your money for features that change jack shit on performance and stuff.
