### ISSUE TITLE
Gundam journey to jaburo issue with black screen.

### ISSUE THREAD

**Issue by rbohannon89** [jpd002/Play-#1007]
This happens when you get past the loading screen for the first level. Also the cut scene animation are all messed up as well.  Device I'm using S20 Ultra SD. Running UI 3.0 . Using Play! Jan 25, 2021.
![Screenshot_20210125-183943_Play!](https://user-images.githubusercontent.com/28317298/105779615-ba1be980-5f3c-11eb-8281-8e9c855a8a4c.jpg)
Ps, the emulator will not save even at a menu. Not the memory card save.

**Comment by jpd002** [comment]
Moved here: https://github.com/jpd002/Play-Compatibility/issues/1400.
