### ISSUE TITLE
Please repair

### ISSUE THREAD

**Issue by huaihuai11oo11** [jpd002/Play-#1008]
SCPS-15118
Wild Arms the 5th Vanguard
![Screenshot_20210126_202803_com virtualapplications play](https://user-images.githubusercontent.com/78026051/105845296-8791ef80-6015-11eb-925c-a186f9ab90ce.jpg)

**Comment by jpd002** [comment]
That's a known problem: https://github.com/jpd002/Play-Compatibility/issues/387. Please report game specific issues in the compatibility tracker. Thanks!
