### ISSUE TITLE
Tetris Worlds & Crash Bandicoot: Wrath Of Cortex, stay on black screen.

### ISSUE THREAD

**Issue by Abz1** [jpd002/Play-#101]
Both the games that i mentioned above, only stay on the black screen.

**Comment by seadil** [comment]
On what device and which version did you test?

**Comment by Abz1** [comment]
I tested this on a Motorola RAZR I x890, and on the latest version.

**Comment by MisterHubs** [comment]
It's not an issue with any device, I believe -- neither of those games will show anything.

This is just a guess, but it could be from unimplemented EE/VU instructions; not all are implemented yet.

**Comment by talamir** [comment]
play is not a very good program as i try games and none work and homebrew works but run too slowly and i think it is the problem with dynamaric binary trnslation as pcsx2 seem to have better work on this

**Comment by jpd002** [comment]
@MisterHubs Yes, both FTOI0 and ITOF0 are supported.

@talamir Yeah, PCSX2 is definitively better ATM. Play! has very limited compatibility but things are improving slowly.

**Comment by talamir** [comment]
@jpd002 are you the developper? are you planning on making more games working and faster to?

because i heard you say you are to help with game issues by getting games and helping ones people reported to want to play them but do you really buy all games for ps2 to debug. there are very many.

**Comment by Thunder07** [comment]
@talamir I have it on good authority that the dev own a console shop, so he has access to old storage areas with PS2 games.

**Comment by talamir** [comment]
@thunder07 oh that is good. then every game can easily be checked without hassles of buying

**Comment by Abz1** [comment]
So is this a bug and can it be fixed?

**Comment by jpd002** [comment]
@Abz1 Yes, it can be fixed, I'm getting the games and I will take a look at them once I receive them.

**Comment by Abz1** [comment]
@jpd002 thanks alot! Good luck on this project, I hope it goes far.

**Comment by johnnyleap** [comment]
I haven't tried Tetris Worlds, but I looked into Crash Bandicoot: Wrath of Cortex:

The last thing the IOP tries to do is wake up a thread and it doesn't complete: JR RA, followed by ADDIU R0, R0, $001A. Similarly, SIO2MAN stays waiting for an event flag on the call stack with LW A1 and ADDIU as well just like with Grand Theft Auto: Vice City (ADDIU V0, R0, $0666/$0669).

The final function called on the IOP is a wake up thread as shown above & nothing further with IOP.

With the Emotion Engine, the last function called shows that there was an attempt to write to the translation lookaside buffer (TLB spad=0, kernel=1), followed by an addition with ADDIU and an overflow. The rest of execution rides up on continuous overflows and jump and link syscalls before ending with ADDIU SP, SP, $0040. Possibly an issue with the TLB and the IOP thread failure?

**Comment by jpd002** [comment]
Last time I tried, Tetris World did work at least till the main menu, it just take a little while to load. For Crash Bandicoot, I'm suspecting a problem with IOP HLE.

**Comment by johnnyleap** [comment]
Yeah, Tetris Worlds does go pretty far, but it's unstable and impossible to see what you're doing:

Story mode:
![playtetrisworldsingame](https://cloud.githubusercontent.com/assets/13894398/9889162/b110c098-5be8-11e5-9204-0df6ec9f6136.jpg)

Arcade mode:
![playtetrisworldsingame2](https://cloud.githubusercontent.com/assets/13894398/9889447/0122fe06-5bea-11e5-9081-fe068dfa9b65.jpg)

The music and sound effects work, so I don't know if this would be menu or in-game (it passes menus).

In any case, the problem is mostly with the rendering.

**Comment by Fadi5555** [comment]
Nice.

I hope crash bandicoot the warth of cortex could run like this one.

**Comment by Thunder07** [comment]
Build: master [cbf190f](https://github.com/jpd002/Play-/commit/cbf190f14c8a3d1a03f4fae0aaa89dc53e5f08b2)
OS: Ubuntu 17.04
Game: Tetris World
Serial: SLUS_202.47;1

InGame: 15 fps
Menu: 25fps

not sure when these improvements where made, but beside the low fps and minor graphic issues, the game is playable.

issues:
[Missing Block Color](https://cloud.githubusercontent.com/assets/5013823/25304033/f52513f2-2756-11e7-874d-c7cc983f53c9.png)
[High Res, causes these lines to appear](https://cloud.githubusercontent.com/assets/5013823/25304035/f54e5f6e-2756-11e7-9f52-4c12d1110750.png)
[broken yellow block shadows](https://cloud.githubusercontent.com/assets/5013823/25304034/f54c6b0a-2756-11e7-87cf-ae702c6b77fb.png) the cube outside the tetris.

**Comment by jpd002** [comment]
Don't remember what caused the issue in Tetris Worlds, but yeah, it's running much better than it used to. Also, Crash Bandicoot: Wrath of Cortex is playable now. So, I guess this issue can be closed now.

**Comment by iOS4all** [comment]
@jpd002 to remind you. Crash bandicoot the warth of cortex it has graphic issues. Maybe something missing to show in normal way.
