### ISSUE TITLE
Some games don't show up in android build

### ISSUE THREAD

**Issue by darkpigeon** [jpd002/Play-#1018]
Gungriffon Blaze, for example. No matter how many times i rescan the storage, the game refuse to show up on the screen for me to load it. I hope some ways to browse to the roms manually can be implemented on mobile platforms like android and ios.

**Comment by jpd002** [comment]
Hey! What's the filename of your disc image?

**Comment by darkpigeon** [comment]
> Hey! What's the filename of your disc image?

Gungriffon Blaze (Europe).cue
Somehow it works again in the latest build. Guess i'll close this now.
