### ISSUE TITLE
Back Button, Bug

### ISSUE THREAD

**Issue by adriandennis17** [jpd002/Play-#102]
Play!: Build 2015/7/12

Upon launching Play! if you should press the Return (Back) key, it seems to crash the app
with the new exit option, i think the return key would have the function to exit the app, 
but probably wasn't coded properly..

Device: S4 (GT i9505)

**Comment by Thunder07** [comment]
@LoungeKatt probably need to kill the virtual machine 1s?

**Comment by LoungeKatt** [comment]
Not sure what you're talking about. It doesn't crash for me. I wonder if something got left out with the partial merge. I did have a conflict on the rebase.

**Comment by adriandennis17** [comment]
@LoungeKatt the "return key" or back button
when at Play! main screen if that button is press causes the app to force close.I'm not sure if the same thing will happen if you have Virtual back button.

**Comment by Thunder07** [comment]
http://pastebin.com/5MfkKD61

this is how I fixed it, https://github.com/jpd002/Play-/pull/103

**Comment by adriandennis17** [comment]
@Thunder07 what device did you test the fix on..

**Comment by Thunder07** [comment]
OnePlus One.

**Comment by LoungeKatt** [comment]
@adriandennis17 Capacitive keys and hardware back are only differentiated when you explicitly check for hardware keys. When you reference the keycode, or use an API back reference, it is designed to take either as valid.

**Comment by adriandennis17** [comment]
@Thunder07 Great, ☺

**Comment by adriandennis17** [comment]
@LoungeKatt ok 😅

**Comment by jpd002** [comment]
Yup, actually my bad. As @LoungeKatt said, his branch got completely different code for `onBackPressed` and his changes are only merged partially at the moment.

@Thunder07 Thanks for the fix!

**Comment by itsmachotime7** [comment]
@LoungeKatt Don't act immaturely. I'll delete my comment when you delete yours.

Don't make me regret coming here.

**Comment by jpd002** [comment]
Fixed in today's weekly build (2015-07-19).
