### ISSUE TITLE
Error compiling on Retropie (Raspberry Pi 4)

### ISSUE THREAD

**Issue by Fifi31** [jpd002/Play-#1020]
Hello,
I am trying to build the project on a Raspberry Pi 4.
I did the following :
```
git clone --recurse-submodules https://github.com/jpd002/Play-.git
cd Play-
mkdir build
cd build
cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/arm-linux-gnueabihf/qt5/
cmake --build .
```
The first build gave me this message :
```
Scanning dependencies of target Framework
[  1%] Building CXX object Source/ui_qt/Source/Framework/CMakeFiles/Framework.dir/__/__/src/Base64.cpp.o
c++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
c++: error: unrecognized command line option ‘-msse2’
make[2]: *** [Source/ui_qt/Source/Framework/CMakeFiles/Framework.dir/build.make:63: Source/ui_qt/Source/Framework/CMakeFiles/Framework.dir/__/__/src/Base64.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:240: Source/ui_qt/Source/Framework/CMakeFiles/Framework.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I saw this PR : #916 and decided to remove the flags `-msse` and `-msse2` from the file `Source/CMakeLists.txt`.

I removed the `build` folder and did the same procedure again. This time, the build goes to 62% (with some warnings during the execution), and output me this :
```
Scanning dependencies of target Framework_Vulkan
[ 62%] Building CXX object Source/ui_qt/gs/GSH_Vulkan/FrameworkVulkan/CMakeFiles/Framework_Vulkan.dir/__/__/src/vulkan/CommandBufferPool.cpp.o
In file included from /home/pi/Play-/deps/Framework/src/vulkan/CommandBufferPool.cpp:2:
/home/pi/Play-/deps/Framework/build_cmake/FrameworkVulkan/../../include/vulkan/StructDefs.h:6:76: error: ‘VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT’ does not name a type; did you mean ‘VkPhysicalDeviceFragmentDensityMapFeaturesEXT’?
 #define DECLARE_STRUCT(structName, structId) FRAMEWORK_MAYBE_UNUSED static Vk##structName structName() { Vk##structName result = { structId }; return result; }
                                                                            ^~
/home/pi/Play-/deps/Framework/build_cmake/FrameworkVulkan/../../include/vulkan/StructDefs.h:55:3: note: in expansion of macro ‘DECLARE_STRUCT’
   DECLARE_STRUCT(PhysicalDeviceFragmentShaderInterlockFeaturesEXT, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_INTERLOCK_FEATURES_EXT)
   ^~~~~~~~~~~~~~
make[2]: *** [Source/ui_qt/gs/GSH_Vulkan/FrameworkVulkan/CMakeFiles/Framework_Vulkan.dir/build.make:63: Source/ui_qt/gs/GSH_Vulkan/FrameworkVulkan/CMakeFiles/Framework_Vulkan.dir/__/__/src/vulkan/CommandBufferPool.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:708: Source/ui_qt/gs/GSH_Vulkan/FrameworkVulkan/CMakeFiles/Framework_Vulkan.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
I tried to upgrade libvulkan1 and libvulkan-dev, but nothing changed.
Do you have an idea of what is happening and what can I do to fix this issue ?

**Comment by jpd002** [comment]
What's the version of the Vulkan SDK you have on your build system? I think you need something somewhat recent (like, from last year) to make it compile.

I also saw that Vulkan support is disabled on AArch64, should probably be the same for AArch32 builds:
https://github.com/jpd002/Play-/blob/3fcf2b58cb7c8560b40204de0e2dcc0596b874cf/Source/ui_qt/CMakeLists.txt#L13

I doubt the fragment shader interlock extension is supported on that platform.

**Comment by Fifi31** [comment]
How can I know the version of Vulkan SDK ?

I disabled Vulkan and managed to build the project (I had to add "-lstdc++fs" to the PROJECT_LIBS variable). I am going to configure Retropie to launch it, and test it. Will let you know

**Comment by Zer0xFF** [comment]
RPI has [only recently](https://www.raspberrypi.org/blog/vulkan-update-were-conformant/) gotten a conformant version of Vulkan, v1.0, and so its a bit outdated.

just a quick note about disabling Vulkan on AArch64, the nvidia jetson line up [supports vulkan](https://developer.nvidia.com/embedded/vulkan), so it might be for the best to set a variable to control enabling/disabling much so like this https://github.com/jpd002/Play-/blob/a4ed0f0694556a794419ca836c57cb962c74ffe9/CMakeLists.txt#L16 and since support is rather scarce at this stage for arm unix platforms, it might be best to default it to off.

**Comment by nru1979** [comment]
I got the same problem.
I went further by renaming /usr/lib/arm-linux-gnueabihf/libvulkan.so to /usr/lib/arm-linux-gnueabihf/libvulkan.so.bak and restarting cmake completely.
However it bumped into duplicate definitions later when it started qt5opengl modules. Any clue?

**Comment by clort81** [comment]
Maybe you'd have better results with USE_GLES?
cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUSE_GLES=on

**Comment by jpd002** [comment]
Please check the experimental/linux_arm32_build branch, there’s a few fixes in there that I will merge soon.

**Comment by nru1979** [comment]
Tried your branch, got an error while doing first cmake:
tools/McServTest/CMakeLists.txt:7 (include):
include could not find load file:
Header

Same error 4x, other times its with
tools/SpuTest
tools/VuTest
tools/GsAreaTest
Retrying main checkout

**Comment by jpd002** [comment]
Did you forget to init/update submodules @nru1979? In any case, I've merged the experimental branch in `master` which should have the fixes for ARMv7 build. It's been added in CI (although it's not great ATM), so we should be able to catch errors in the future.
