### ISSUE TITLE
Trapt  SLUS_212.55 [NTSC-U] 

### ISSUE THREAD

**Issue by nachosnponchos** [jpd002/Play-#1039]
https://user-images.githubusercontent.com/51711749/110267669-2561ce00-7f75-11eb-82a8-dfe1eb0ec4b9.mp4

The game state didn't changed in almost 3 years, always Game Over after some seconds in-game. the cut scenes run "fine" and have some good speeds as such but the actual gameplay with never happen. i hope i posting correcting im not sure how all this works. total noob so please excuse me. one video is from the survival mode just to see if maybe it was a story mode thing. but it shows more or less whats going on

https://user-images.githubusercontent.com/51711749/110267555-ec295e00-7f74-11eb-9508-1cb3e6485551.mov

**Comment by literalmente-game** [comment]
This isn't a compatibility tracker for game specific issues, report any new behavior to the already open issue in the correct place https://github.com/jpd002/Play-Compatibility/issues/695
