### ISSUE TITLE
(iOS/iPadOS) Controller Support Improvement

### ISSUE THREAD

**Issue by slavicweebofficial** [jpd002/Play-#1050]
It's good emulator but controller support isn't full (options, share, R3 and L3) are not working. So some games aren't very playable because I have to tap on screen every time I want click those buttons.

**Comment by azade3kit** [comment]
How did you get controller support? I have my PS4 controller connected but it doesn't seem to work.

**Comment by slavicweebofficial** [comment]
idk it just works not fully for me
