### ISSUE TITLE
Play! Latest build apk poor performance on 2D graphics game like KOF 2001

### ISSUE THREAD

**Issue by Gamemulatorer** [jpd002/Play-#1051]
### Screenshot
![Screenshot_2021-04-28-23-08-54-938_com virtualapplications play](https://user-images.githubusercontent.com/37603562/116427774-e8300300-a876-11eb-934b-3a77b3d85962.jpg)

### My phone specs
Helio G85 1ghz GPU 2.0ghz CPU Octacore Processor
Android 10 supported both OpenGL & Vulkan.

**Comment by jpd002** [comment]
Hi!

Was this the case on previous versions?

Thanks!

**Comment by Gamemulatorer** [comment]
> Hi!
> 
> Was this the case on previous versions?
> 
> Thanks!

Yes

**Comment by Gamemulatorer** [comment]
Related https://github.com/jpd002/Play-Compatibility/issues/624
