### ISSUE TITLE
Kingdom heart 2 blur screen

### ISSUE THREAD

**Issue by ajay9634** [jpd002/Play-#1059]
Please fix blur screen of kingdom heart 2
![Screenshot_2021-05-11-13-47-40-30_26c022622f54c9f7d3f2019cc473e591.jpg](https://user-images.githubusercontent.com/78233144/117783471-31f9ef80-b260-11eb-87c6-6cc4cf661a32.jpg)

**Comment by ajay9634** [comment]
My device is realme c3, Helio g70

**Comment by Gamemulatorer** [comment]
Upgrade your phone first before playing that game on Play! Emulator.
Better buy Black Shark 4

**Comment by FatheredPuma81** [comment]
Tested on Moto E4 Plus running Android 7 and can confirm issue exists. Also changing resolution a few times crashed my phone and made it restart on it's own lol.

http://prntscr.com/1of261e
I know, the game is super playable on my phone right?

**Comment by Gamemulatorer** [comment]
Report your issue here instead https://github.com/jpd002/Play-Compatibility/issues?q=Kingdom+Hearts

**Comment by jpd002** [comment]
I'm hoping to resolve this with the Vulkan based renderer. 

I don't know if it can be easily fixed with OpenGL. Also, I wonder if the effect is worse with multipliers other than 1x.

And yeah, please report game specific issues in the compatibility tracker in the future.
