### ISSUE TITLE
Iso file not showing up

### ISSUE THREAD

**Issue by FAROK000** [jpd002/Play-#1063]
I put in my phone storage
Naruto shippuden unltimate ninja 5.iso
Breath of fire 5.iso
yakuza.iso
Shadow of Colosseum.cso
But the yakuza iso didn't showup in da game list
Plus (Naruto shippuden unltimate ninja 5 cover is missing)
I tested the iso in pcsx2 and it worked fine
I am using the latest play version from github action
https://github.com/jpd002/Play-/actions/runs/839440824.
![Screenshot_20210515-121354~2](https://user-images.githubusercontent.com/80482457/118358593-71ce1900-b577-11eb-8088-e9dde1c97263.png)
![Screenshot_20210515-121417~2](https://user-images.githubusercontent.com/80482457/118358601-7bf01780-b577-11eb-9dc2-83f447e20727.png)

**Comment by TheOG00** [comment]
Fixed! !
![Screenshot_20210523-001505](https://user-images.githubusercontent.com/84327903/119243150-2cec4880-bb5c-11eb-986c-19bec6ddfc59.png)

**Comment by jpd002** [comment]
Glad to hear that it works now!
