### ISSUE TITLE
Mobile – black screen 

### ISSUE THREAD

**Issue by TheOG00** [jpd002/Play-#1070]
everything was working normally in
beat down fist of vengeance [SLES_535.05]. when the mission start and after the "ready" fading in ,the screen became black but we still can hear da sound & see the writing with the lil map on the screen.
![Screenshot_20210531-215015~2](https://user-images.githubusercontent.com/84327903/120241826-7d019400-c25b-11eb-8389-54b6fe40d2aa.png)
![Screenshot_20210531-215025~2](https://user-images.githubusercontent.com/84327903/120241843-85f26580-c25b-11eb-9011-8ff9470611ee.png)

All the thanks to VAILL

**Comment by TheOG00** [comment]
![Screenshot_20210531-214916~2](https://user-images.githubusercontent.com/84327903/120242196-37919680-c25c-11eb-9b69-2c29454b1687.png)
I forgot about dat pic

**Comment by darkpigeon** [comment]
I have reported this issue and the commit that caused it on the game's compatibility page. You can close this.
