### ISSUE TITLE
Can i port pcsx2 saves to Play?

### ISSUE THREAD

**Issue by yuritheguy** [jpd002/Play-#1072]
Hi

I wanted to ask this question and if not, maybe this would be the definitive answer when picking among all of the ps2 apk emulators out there, the ability to port progress from pc emulation (.ps2 file) to... What you guys use

Sorry i'm no coder or useful person at all, i just have a bunch of cool savegames and i'd like to play them on my phone, and then port them back to my pc, vice versa. I wish i could be able to convert the files to import and export from Play!

I'm sure that if you guys work this out, this will be the ultimate emulator out there, by far no competition as this feature alone makes me want to play more and more 

Tks

**Comment by TheOG00** [comment]
@yuritheguy
Just try it and find out ...if it doesn't , open an issue about it. 
Don't open an issue with no issue (question) 😝

**Comment by Dragon20C** [comment]
from what I can tell if you unzip that file it should include all the game files and from the little search I did through the play emulator the game saves are saved in a simple folder, this is a guess I assume if you unzip that folder and add the games into plays directory it should be able to read the files since its just a ps2 game save file.

Play Data Files/vfs/mc0/ #This being the play emulator memory card

**Comment by yuritheguy** [comment]
ok i'm closing this issue as i couldnt get anything to work, i researched converting my .ps2 file into other types, tried to open the archive itself in the app, tried to find if i could extract the exact save from the .ps2 file so i could include in a folder or zip file, nothing. I dont even know how this later one would be possible lol

maybe if the app could also read .psu? that would already be such a bless. Maybe the app could read .ps2/.psu files and convert them into save files inside the folder that Dragon20C mentioned

anyway, i guess that the suggestion is still there and is still valid, ideas are ideas. The app is under development and many games that i'd like to play are still unavailable so... it doesnt bother me that much right now

tks yall

**Comment by darkpigeon** [comment]
You can import .psu files but this feature is only available on play!'s windows build (option -> memory card manager -> import)
