### ISSUE TITLE
(iOS Feature Request) add Vulcan to iOS via moltenvk

### ISSUE THREAD

**Issue by Spidy123222** [jpd002/Play-#1079]
![image](https://user-images.githubusercontent.com/64176728/103061747-2cc22f80-4561-11eb-9c3b-d31c999bbcef.png)

Hi I am spidy!

You might ask what is moltenVK. Well it's a conversion layer for iOS and MacOS to convert Vulkan api code to metal api code. Currently iOS has OpenGLES and Vulkan. From other emulator developers I was told that OpenGLES is worse for the reasons of it is not maintained and is depreciated. 

![image](https://user-images.githubusercontent.com/64176728/120910134-2caa7d80-c631-11eb-89a2-60a37413467d.png)

MoltenVK https://github.com/KhronosGroup/MoltenVK

One of the other reasons is that currently metal is updated often and has speed improvements specifically for each iOS device and using a conversion layer can help with using cross platform api's like vulkan. Vulkan isn't a magic pill for performance but it is a consideration on mobile platforms because it's close to desktop graphics apis.

If I remember correctly Vulkan on other platforms for play! Works fine is that right? 

I hope I explained a bit of it well. I'm not used to doing these things.

Thanks for taking your time for reading this.

**Comment by mayweather911** [comment]
I have proposed it some time ago, but not on github, I know that this version also uses DiOS lemulator dolphin for iPhone

**Comment by Spidy123222** [comment]
> I have proposed it some time ago, but not on github, I know that this version also uses DiOS lemulator dolphin for iOS , I think it would increase compatibility and speed

Yeah DolphinIOS does use MoltenVK. It was their main focus to use Vulkan because OpenGLES core didn't run well at all. But I'm unsure if this in topic of this thread or not so I'll leave it here. Increase compatibility is emulator dependent and speed can be possible if done right. Having Vulkan on Apple devices seem to have benefits because of bad Apple drivers.

**Comment by Gamemulatorer** [comment]
Similar request https://github.com/jpd002/Play-/issues/847#issuecomment-820485827

**Comment by Spidy123222** [comment]
> Similar request [#847 (comment)](https://github.com/jpd002/Play-/issues/847#issuecomment-820485827)

hm, so it is. I think I might have totally forgotten about that one. that one is for android. Both platforms android and Ios support vulkan. android is native and ios use a translation layer.

**Comment by jpd002** [comment]
Going to use #847 to discuss this.
