### ISSUE TITLE
Dirge of Cerberus: Final Fantasy VII stuck

### ISSUE THREAD

**Issue by VAILL666** [jpd002/Play-#1080]
stuck after the square enix logo fades away on any play! build ^ ^ 
![Screenshot_20210607-220730_Play!](https://user-images.githubusercontent.com/85144066/121074867-1b9e6f80-c7dd-11eb-9b04-5d406250788e.png)
![Screenshot_20210607-220742_Play!](https://user-images.githubusercontent.com/85144066/121074870-1d683300-c7dd-11eb-823c-f7b0a02d7b2a.png)

**Comment by literalmente-game** [comment]
This is not a compatibility tracker, don't report game specific issues here (this can be closed). There's already an open issue in the correct place and this information isn't new or changed in any way recently https://github.com/jpd002/Play-Compatibility/issues/117
