### ISSUE TITLE
Mobile - Couldn't load state

### ISSUE THREAD

**Issue by TheOG00** [jpd002/Play-#1083]
play! Is always Installed on my phone as usual. after i update it over the old version (without deleting the previous version)
When i run a game to test ,loading state says : couldn't load state.
the loading state was working on the previous version and the save files is available.
New Version 👇
https://github.com/jpd002/Play-/actions/runs/922048250

**Comment by kernle32dll** [comment]
This is to be expected. Save states can break at any time, if new fields are added which were previously not there.

Not much you can do about it - sorry. Use regular memory card saving.
