### ISSUE TITLE
Android In Game Settings Issues

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#1090]
mobile_ingame_settings branch is great! But i found some issues. After open settings from in game, the navbar not hiding

https://user-images.githubusercontent.com/55049420/122451899-d9421300-cfd2-11eb-9d47-67935717f1f3.mp4

**Comment by jpd002** [comment]
Thanks, I'll check it out!

**Comment by TheOG00** [comment]
Yeah 
resolution doesn't change too till we close and open play again

**Comment by jpd002** [comment]
It should be fixed here: https://github.com/jpd002/Play-/commit/c04c12eb17d71c9b6128ec6c5906e406c1b267ca

It's still a WIP, there's a few more things that don't work at the moment 😄

**Comment by TheOG00** [comment]
Ammm the bar and the back button still showing up for me😣

**Comment by ericsonia** [comment]
Now the issues were fixed with this commit: https://github.com/jpd002/Play-/commit/4f86ab0dcddf01983adcf4d35d2b88ba6b0de894

Thanks @jpd002 !
