### ISSUE TITLE
[ANDROID] Play! Cannot scan all of my ps2 games on play! data folder

### ISSUE THREAD

**Issue by Gamemulatorer** [jpd002/Play-#1094]
As the title say

Only four of my games get scan
![Screenshot_2021-06-26-16-26-39-701_com virtualapplications play](https://user-images.githubusercontent.com/37603562/123507360-7ec44900-d69b-11eb-82ec-b22e9114cd15.jpg)

Play! folder and my other games didn't scan like tekken tag and splinter cell
![Screenshot_2021-06-26-16-26-57-355_com mi android globalFileexplorer](https://user-images.githubusercontent.com/37603562/123507389-9ef40800-d69b-11eb-899d-37ecc99b5eea.jpg)

**Comment by jpd002** [comment]
Can you open `Splinter Cell (Demo).cue` in a text editor and show me what's the contents of the file? There could be another problem with the Cue sheet parser.

Thanks!

**Comment by Gamemulatorer** [comment]
FILE "Splinter Cell (USA) (Demo) [SLUS-29048].bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

**Comment by Gamemulatorer** [comment]
FILE "Tekken Tag Tournament (USA).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

**Comment by TheOG00** [comment]
Happened to me before so Yeah better converting them to iso or cso

**Comment by Gamemulatorer** [comment]
> Happened to me before so Yeah better converting them to iso or cso

How do I convert them ro iso/cso file??

**Comment by Gamemulatorer** [comment]
Also my harvest moon is not an iso/cso file but it get scan by play!
FILE "Harvest Moon - Save the Homeland (USA).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

**Comment by TheOG00** [comment]
@Gamemulatorer worked?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer worked?

I don't have pc :(

**Comment by TheOG00** [comment]
@Gamemulatorer so it's up to yu to conver them of wait for jean respond

**Comment by Zer0xFF** [comment]
> 
> 
> FILE "Splinter Cell (USA) (Demo) [SLUS-29048].bin" BINARY
> TRACK 01 MODE2/2352
> INDEX 01 00:00:00

the problem is fairly self evident...
the content of the cue file says the file name should be `Splinter Cell (USA) (Demo) [SLUS-29048].bin` but you have it named `Splinter Cell (USA) (Demo).bin` either fix the cue file, or rename you bin files to match

**Comment by Gamemulatorer** [comment]
> > FILE "Splinter Cell (USA) (Demo) [SLUS-29048].bin" BINARY
> > TRACK 01 MODE2/2352
> > INDEX 01 00:00:00
> 
> the problem is fairly self evident...
> the content of the cue file says the file name should be `Splinter Cell (USA) (Demo) [SLUS-29048].bin` but you have it named `Splinter Cell (USA) (Demo).bin` either fix the cue file, or rename you bin files to match

Thanks it's work now
![Screenshot_2021-07-01-23-10-35-215_com virtualapplications play](https://user-images.githubusercontent.com/37603562/124147800-9a778700-dac1-11eb-81f7-14e5268c2c52.jpg)
But some of my games cover photo failed to load 🤔

**Comment by Gamemulatorer** [comment]
Closing this since my issue is already resolve
