### ISSUE TITLE
The "Use Vulkan" commit keeps crashing on my phone.

### ISSUE THREAD

**Issue by Ktheone** [jpd002/Play-#1095]
Whenever I open a game, the app crashes. It's the 26- 06- 2021 commit.

**Comment by Spidy123222** [comment]
Seeing that you are saying app I'm assuming your meaning mobile devices. What device are you on?

**Comment by Ktheone** [comment]
> Seeing that you are saying app I'm assuming your meaning mobile devices. What device are you on?

Yeah, I meant mobile phones.

**Comment by TheOG00** [comment]
Latest builds doesn't crash on my sd664/sd860 too

**Comment by Gamemulatorer** [comment]
Try the latest development build for ios here
https://purei.org/downloads.php

**Comment by Ktheone** [comment]
> Try the latest development build for ios here
> https://purei.org/downloads.php

Mine is an android.

**Comment by Gamemulatorer** [comment]
> > Try the latest development build for ios here
> > https://purei.org/downloads.php
> 
> Mine is an android.

@jpd002 doesn't implement vulkan on android as of now only on ios where did you get your play! apk that has a vulkan backend!?!? 🤔🤔🤔

**Comment by Spidy123222** [comment]
> > > Try the latest development build for ios here
> 
> > > https://purei.org/downloads.php
> 
> > 
> 
> > Mine is an android.
> 
> 
> 
> @jpd002 doesn't implement vulkan on android as of now only on ios where did you get your play! apk that has a vulkan backend!?!? 🤔🤔🤔

It's one of the current branches and in action while being logged in and go to mobile_vulkan branch and go to android action.

**Comment by jpd002** [comment]
The `experimental/mobile_vulkan` branch has Vulkan enabled on Android. I'm aware that it's broken, we're working on it.

**Comment by Gamemulatorer** [comment]
I try the mobile_vulkan_branch "Disabled reading from depth temporarily." 43202ab
It didn't crash on my phone but have wacky gfx issues
![Screenshot_2021-07-03-18-22-50-589_com virtualapplications play](https://user-images.githubusercontent.com/37603562/124351302-26a5bd80-dc2c-11eb-9155-13431c0ef849.jpg)
Tested on Harvest Moon only.

**Comment by ericsonia** [comment]
> I try the mobile_vulkan_branch "Disabled reading from depth temporarily." [43202ab](https://github.com/jpd002/Play-/commit/43202ab0f2e57408d68d4567d815c621d4ca6f81)
> It didn't crash on my phone but have wacky gfx issues
> ![Screenshot_2021-07-03-18-22-50-589_com virtualapplications play](https://user-images.githubusercontent.com/37603562/124351302-26a5bd80-dc2c-11eb-9155-13431c0ef849.jpg)
> Tested on Harvest Moon only.

@Gamemulatorer please test more games

**Comment by Gamemulatorer** [comment]
Tekken Tag Tournament Play! https://github.com/jpd002/Play-/commit/a1efe4f9ee85c40c5cbf243a05d9183d37b3fb6a expiremental vulkan for mobile
![Screenshot_2021-07-14-00-05-20-965_com virtualapplications play](https://user-images.githubusercontent.com/37603562/125487063-2ad965ab-9749-4b3c-8032-d2897d31c07c.jpg)

**Comment by Gamemulatorer** [comment]
Harvest Moon using play! expiremental_vulkan on mobile commit https://github.com/jpd002/Play-/commit/9323add449b556e5e3734af246c9db09e415ac22
![Screenshot_2021-07-17-10-36-01-412_com virtualapplications play](https://user-images.githubusercontent.com/37603562/126022777-a0cb3295-2a36-4dd0-892c-5ccf1b440b55.jpg)

**Comment by ericsonia** [comment]
> Harvest Moon using play! expiremental_vulkan on mobile commit [9323add](https://github.com/jpd002/Play-/commit/9323add449b556e5e3734af246c9db09e415ac22)
> ![Screenshot_2021-07-17-10-36-01-412_com virtualapplications play](https://user-images.githubusercontent.com/37603562/126022777-a0cb3295-2a36-4dd0-892c-5ccf1b440b55.jpg)

@Gamemulatorer what your device?

**Comment by Gamemulatorer** [comment]
REDMI NOTE 9 Mediatek Helio G85 Mali-G52 MC2 GPU

**Comment by Gamemulatorer** [comment]
Tried other games below,

### Rouge Heart Dungeon
![Screenshot_2021-07-17-14-26-23-068_com virtualapplications play](https://user-images.githubusercontent.com/37603562/126028181-4ea6b7cd-c275-401a-aced-8c9ad7197094.jpg)
Less gfx issue so far in menu only

### Phantasy Star Generation
![Screenshot_2021-07-17-14-27-41-016_com virtualapplications play](https://user-images.githubusercontent.com/37603562/126028200-cd035fea-0a0a-4088-a7bf-66e210162a11.jpg)

### Crash Nitro Cart
![Screenshot_2021-07-17-14-24-14-191_com virtualapplications play](https://user-images.githubusercontent.com/37603562/126028212-13b5b109-3b18-4013-b0f8-12ad8adc07a1.jpg)

### CAPMCOM vs SNK 2
![Screenshot_2021-07-17-14-25-47-606_com virtualapplications play](https://user-images.githubusercontent.com/37603562/126028225-a17a351f-9c33-4341-ae5b-6ccb69f0914f.jpg)
