### ISSUE TITLE
Building and Running for iOS

### ISSUE THREAD

**Issue by yoshisuga** [jpd002/Play-#1096]
I can't seem to build and run the project from Xcode. I can get the project to build successfully but fail at install (see log below).

Tried to create an archive and would get a bitcode failure as well.

These are the steps I used, mostly derived from the GitHub workflow:

1. Install Cmake for my macOS build machine
2. Download the Vulcan SDK:
```
curl -L --show-error --output vulkansdk.dmg https://sdk.lunarg.com/sdk/download/1.2.162.0/mac/vulkansdk-macos-1.2.162.0.dmg?Human=true
hdiutil attach vulkansdk.dmg
export VULCAN_SDK=/Volumes/vulkansdk-macos-1.2.162.0/macOS
```
3. Recursive checkout of repos:`git clone --recurse-submodules https://github.com/jpd002/Play-.git`
4. Run CMake:
```
cd Play-
mkdir build
cd build
cmake .. -G"Xcode" -DCMAKE_TOOLCHAIN_FILE=../deps/Dependencies/cmake-ios/ios.cmake -DTARGET_IOS=ON -DCMAKE_PREFIX_PATH=$VULKAN_SDK -DBUILD_PSFPLAYER=ON
```

5. Open Play.xcodeproj in Xcode
6. Fix Signing Team to my own Team
7. Select Play scheme, Build and Run
8. Build Successful, but fails to install (No code signature found).

I suspect the dependencies aren't getting code signed - there's no embedded frameworks in the project for some reason.

I've also been unsuccessful at getting this to run as a libretro core (had an issue opening the ISO image). 

Any help would be appreciated, thank you!

Install Error:
```
Unable to install "Play"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
--
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800801C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000125af23b8 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000125b30ae1 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x000000010a1fbb7c DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x0000000125b30822 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x00000001259a1999 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.294 + 3534
	5   DVTFoundation                       0x000000010a32e931 __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x000000010a33055b __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff20200623 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff20201806 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff202075ea _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff202080ad _dispatch_lane_invoke + 366
	11  libdispatch.dylib                   0x00007fff20211c0d _dispatch_workloop_worker_thread + 811
	12  libsystem_pthread.dylib             0x00007fff203a845d _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff203a742f start_wqthread + 15
);
}
--


System Information

macOS Version 11.4 (Build 20F71)
Xcode 12.5 (18205) (Build 12E262)
Timestamp: 2021-06-29T15:01:37-10:00
```

**Comment by jpd002** [comment]
Hey!

Yeah, the setup is a bit annoying on iOS because I had to disable code signing to make the thing build on CI. You have to reenable it after generating the Xcode project:

<img width="864" alt="スクリーンショット 2021-06-30 午前9 02 04" src="https://user-images.githubusercontent.com/6760433/123964954-fcc96e00-d981-11eb-891f-5e17d3213ad3.png">

You can also change the setting directly in the CMake platform if you'd like: https://github.com/jpd002/Play-Dependencies/blob/b9e2d00c3ebee8e9e966334729bea3709185b899/cmake-ios/ios.cmake#L27

Also, if you have an jailed device, be sure to sign libMoltenVK.dylib with your own certificate, otherwise, the device will refuse to load the library.

Hope that helps!
