### ISSUE TITLE
Unable to use zipped roms

### ISSUE THREAD

**Issue by Dbrikashabukshan** [jpd002/Play-#1101]
Most ps2 games are huge at around 3 to 5 gigabytes, meaning that most of the time the only way to store them would be through zipping them, however this emulator doesnt try to search for or load any zipped files. Add support for the common 3 zips, zip, 7z, and rar.

**Comment by jpd002** [comment]
ZIP, 7Z and RAR are not seek friendly and not suitable for the emulator. You can use CSO (https://github.com/unknownbrackets/maxcso) or ISZ if you need compressed disc images. CHD will also be available at some point in the future: https://github.com/jpd002/Play-/issues/837.
