### ISSUE TITLE
Graphical bug in Dark Cloud 2

### ISSUE THREAD

**Issue by Mclife96** [jpd002/Play-#1102]
There are some graphical bugs in Dark Cloud 2 (menù and cutscenes). Please, could you try to resolve It? Thank you! 
![Screenshot_2021-07-07-18-40-32-878_com virtualapplications play](https://user-images.githubusercontent.com/86272474/124797714-de034280-df52-11eb-80c0-25144a04fe3d.jpg)

**Comment by Gamemulatorer** [comment]
Move your issue here https://github.com/jpd002/Play-Compatibility/issues/71

**Comment by jpd002** [comment]
Gonna close this, the issues are probably similar to what was reported previously in the compatibility entry. We can discuss it there if you want.
