### ISSUE TITLE
Access to running software's stdout?

### ISSUE THREAD

**Issue by ticky** [jpd002/Play-#1107]
## Quick summary
I'm attempting to use Play to debug some homebrew software, but I can't seem to access any of the stdout logs. Does such a feature exist?

## System Details
- Operating system: macOS 11.4
- Hardware: MacBook Air (M1, 2020)
- Version of Play!: 0.41 & 0.42

## Issue Details
I have a piece of PS2 software I've been working on which prints to stdout, which I know from previous experience is output to a log in emulators like PCSX2, and I can receive the logs via `ps2link` on a real console, but Play is more convenient for quick access on my Mac development machine. I'd love either for the PlayStation's stdout to be forwarded to Play's stdout, a file, or another log viewer.

## Screenshots/Videos
Not really applicable!

Thanks!

**Comment by jpd002** [comment]
Hey there!

You can set `iop.fileio.stdlogging` to `true` in `Documents\Play Data Files\config.xml`.

With that setting enabled, you will have `ps2_stdout.txt` in the same folder with the standard output.

**Comment by ticky** [comment]
Aha! Thanks, I'll give that a shot ☺️

**Comment by ticky** [comment]
Works great, cheers! :)
