### ISSUE TITLE
Dragon ball budokai tenkaichi 3

### ISSUE THREAD

**Issue by ssthunderyt** [jpd002/Play-#1109]
## Quick summary
Please briefly describe what is not working correctly
I can't run dragon ball budokai tenkaichi 3
## System Details
Describe the ambient being used to run Play!
Information needed:
- Operating system (android 11)
- Hardware (mali g76 and mediatek helio g95, for android you can search for your device model here https://www.gsmarena.com/ for specifications)
- Version of Play! I have latest version

## Issue Details
Describe in details the problem you had and the expected behavior dragon Ball budokai tenkaichi series is not supported

## Screenshots/Videos
Drag and drop (or link to) videos or images that could help us understand the problem.

**Comment by Gamemulatorer** [comment]
Move your issue here https://github.com/jpd002/Play-Compatibility/issues/679 also describe your issue.

**Comment by Kin0ki** [comment]
> Move your issue here [jpd002/Play-Compatibility#679](https://github.com/jpd002/Play-Compatibility/issues/679) also describe your issue.

This is Budokai 3, not Budokai Tenkaichi 3. Tenkaichi is 3D and Budokai is 2D/2.5D.

**Comment by Gamemulatorer** [comment]
Ok this issue also reported on play compatibility https://github.com/jpd002/Play-Compatibility/issues/679

**Comment by mayweather911** [comment]
> Bro i have the play! Ps2 emu and Dragon ball budokai Tenkaichi 3 and when launch it doesn't want to go past the loading screen just lets me do pushups do you anything about that just wondering.

Keep doing pushups until you see improvement 😂 I'm kidding , to me when I tried it a month ago it was going , and it was also going at 50 fps

**Comment by Firedragon11514** [comment]
😆 Bro thats good but for me its not looking so good i did 999 pushups vegeta isnt tired🤔tf is happening no intro would play jist constant pushups it doesnt crash no black screens i dont get this.

**Comment by mayweather911** [comment]
> 😆 Bro thats good but for me its not looking so good i did 999 pushups vegeta isnt tired🤔tf is happening no intro would play just constant pushups it doesnt crash no black screens i dont get this.

It worked for me right away, and also well with iOS change iso look for the one I tried may be that it works SLES-54945

**Comment by Firedragon11514** [comment]
Which iOS the device or some file stuff?

**Comment by mayweather911** [comment]
> Which iOS the device or some file stuff?

Search iso with the sles code I gave you , and independent play! Works the same way with iOS and Android, only changes the speed but depends on the device but if a game works here also on Android

**Comment by Firedragon11514** [comment]
Cool ill give it a try 💪

**Comment by Firedragon11514** [comment]
I got you let me give it a try💪

**Comment by Firedragon11514** [comment]
Bro i had the id slus_216.78 for the game it makes a difference.

**Comment by mayweather911** [comment]
> Bro i had the id slus_216.78 for the game it makes a difference.

It may be that one version works, and one does not, mine with SLES-54945 was fine.

**Comment by Firedragon11514** [comment]
That might work have you tried slus_216.78 before?

**Comment by Firedragon11514** [comment]
K

**Comment by Firedragon11514** [comment]
> > Bro i had the id slus_216.78 for the game it makes a difference.
> 
> It may be that one version works, and one does not, mine with SLES-54945 was fine.

Ngl thanks for the feedback it makes sense.
