### ISSUE TITLE
Audio processor flawed and Physics engine lacking 

### ISSUE THREAD

**Issue by OPStellar** [jpd002/Play-#1112]
## Quick summary
Running Soulcalibur III, I'm experiencing:
- Choppy audio and slowed video during high graphics demand
- Rendering issues (see screenshot)

## System Details
I'm running **Play! version 0.42-56-gdf0eddc4 (Jul 28 2021) Qt v5.15.2 - zlib v1.2.11** from **macOS Mojave version 10.14.6 (18G9323)** on a MacBook Pro (15-inch, 2019) with a **2.4 GHz Intel Core i9** CPU, **Radeon Pro Vega 20 with 4GB of VRAM** + Intel UHD Graphics 630 with 1536MB of VRAM (I have it manually set to the Radeon card, running under **Vulkan**) GPUs, **32GB 2400 MHz DDR4** RAM, and a Terabyte of solid state storage.

## Issue Details
When there are no characters being rendered on-screen, the audio flows smoothly, but it becomes very choppy whenever a character appears. At the same time, there is a slowness of the video, but not choppy like the audio. I think the audio is cutting out to compensate for the reduced video refresh rate. Obviously, it is supposed to be smoother.
The render engine is not only slow, but also glitched. This glitching occurs whenever a slightly-moving rendered object that requires extra texture is visible.

## Screenshots/Videos
![image](https://user-images.githubusercontent.com/49218413/128583028-7789fe20-6cbe-47e0-866d-b675c240c2e8.png)
Splotches on skin and clothes are glitches produced by render engine.

**Comment by FatheredPuma81** [comment]
Post this either [here](https://github.com/jpd002/Play-Compatibility/issues/374) (US) or [here](https://github.com/jpd002/Play-Compatibility/issues/418) (EU).
