### ISSUE TITLE
[SLUS]20963 FFXII fps and audio stutter issues

### ISSUE THREAD

**Issue by arcanux76** [jpd002/Play-#1113]
Running on a Samsung S21 Ultra, Android 11, snapdragon 888.  FFXII suffers from fps speed between 8-20fps with severe audio stutters during all FMV.

**Comment by XiaomiRedmi9** [comment]
Move your issue here
https://github.com/jpd002/Play-Compatibility/issues/7

**Comment by arcanux76** [comment]
Comments moved to existing issue and this issue closed.
