### ISSUE TITLE
Play! failed to load savestate on android 11

### ISSUE THREAD

**Issue by Gamemulatorer** [jpd002/Play-#1120]
## Quick summary
Please briefly describe what is not working correctly
Savestate not working on my android 11
## System Details
Describe the ambient being used to run Play!
Information needed:
- Operating system (including the version)
- Hardware (GPU and CPU, for android you can search for your device model here https://www.gsmarena.com/ for specifications)
- Version of Play!
Redmi Note 9 Android 11 Helio G85 Mali-G52 MC2 GPU
## Issue Details
Describe in details the problem you had and the expected behavior
Savestate should work properly
## Logs
```
<<< log_count = 6 >>>
[09-02 15:11:39.565 2418:2418 D/TaskView]
TaskView bind task, task=[id=548 stackId=548 windowingMode=1 user=0 lastActiveTime=181628572, component=ComponentInfo{com.virtualapplications.play/com.virtualapplications.play.MainActivity}] Play!, isLock=false

[09-02 15:11:39.568 2418:2418 D/TaskView]
TaskView bind task, task=[id=548 stackId=548 windowingMode=1 user=0 lastActiveTime=181628572, component=ComponentInfo{com.virtualapplications.play/com.virtualapplications.play.MainActivity}] Play!, isLock=false

[09-02 15:11:39.617 2418:2418 D/TaskView]
TaskView bind task, task=[id=548 stackId=548 windowingMode=1 user=0 lastActiveTime=181628572, component=ComponentInfo{com.virtualapplications.play/com.virtualapplications.play.MainActivity}] Play!, isLock=false

[09-02 15:11:50.057 14773:14773 W/Play!]
surfaceCreated

[09-02 15:12:16.494 2418:2418 D/TaskView]
TaskView bind task, task=[id=548 stackId=548 windowingMode=1 user=0 lastActiveTime=181669658, component=ComponentInfo{com.virtualapplications.play/com.virtualapplications.play.MainActivity}] Play!, isLock=false

[09-02 15:12:16.542 2418:2418 D/TaskView]
TaskView bind task, task=[id=548 stackId=548 windowingMode=1 user=0 lastActiveTime=181669701, component=ComponentInfo{com.virtualapplications.play/com.virtualapplications.play.MainActivity}] Play!, isLock=false

```

**Comment by Gamemulatorer** [comment]
Play! https://github.com/jpd002/Play-/commit/05340772aa4f7b722b7cb63a37d4b4fa16ca09ea what I'm using.

**Comment by jpd002** [comment]
Does it happen with a old save state file or one that you've just created recently?

If it's an old save state, it's possible that it's not compatible anymore. We don't guarantee that save states will work for all future versions of the emulator (the format changes often).

**Comment by TheOG00** [comment]
Yes old save States doesn't work for sure.
Sometimes new savestates can't be loaded
Or can make the screen black
