### ISSUE TITLE
Provide a Flatpak

### ISSUE THREAD

**Issue by j8r** [jpd002/Play-#1122]
Providing a Flatpak will allow Linux users to easily install and keep Play! up-to-date, on any distribution.
Overall, it is more open and less Ubuntu-centric than snap.

I've already ported some applications to it, so I can do it here too.
What I'll need is your approval to submit the `org.purei.Play-` application to Flathub. Of course, I'll ping you when the PR will be submitted.

**Comment by CHJ85** [comment]
+1 on this request.
Only way to install 3rd party apps easily on the steam deck is through flatpak.

**Comment by Zer0xFF** [comment]
Just a small update, I've gotten a flatpak build working locally, https://gist.github.com/Zer0xFF/c0e3187a94cad177941d03fa9b42a4c2

I do believe its just missing 2 things right now:
1) flatpak recommends to keep flatpak setting seperate from a local install
2) add the build process into CI to autoupdate on master updates

I've been busy lately, so this is taking a bit longer than expected.

**Comment by j8r** [comment]
@Zer0xFF do not worry about auto update yet, I can submit a PR after either by using GitHub Actions or Flatpak External Data Checker, after the repository creation - won't be hard.

**Comment by Zer0xFF** [comment]
@j8r can you explain what PR are you going to submit? from my understanding so far, is that we can upload the build directly to  repo, and i believe flathub is one of them, so where does PR come into this?

**Comment by j8r** [comment]
After your package submission will be approved at https://github.com/flathub/flathub, https://github.com/org.purei.Play- should be created. Then, I'll fork the repo  and make a PR to add the auto update of the commit.

**Comment by Zer0xFF** [comment]
alright, i was under the impression that we can use this https://github.com/marketplace/actions/flatpak-builder
but that does not seem to be the case, atlesat not with flathub.

secondly, Ive updated the missing features list, with point 3, which i guess is important for this process

lastly, I've used the name `org.purei.play` for the package, though not sure if jpd002 would prefer that or `org.purei.Play-`.

**Comment by jpd002** [comment]
I prefer `org.purei.play`.

**Comment by j8r** [comment]
@jpd002 the emulator being `Play!`, with an uppercase letter, won't it make more sense to be `org.purei.Play`?

**Comment by Zer0xFF** [comment]
my 2 cents regarding this, unix systems in general prefer lower case naming convention, mainly to make things easier to type.
in that case that also applies to the `-`

**Comment by j8r** [comment]
Maybe but here the uppercase is not really relevant, look at https://github.com/flathub - uppercase letters are perfectly valid.
No big deal anyway.

**Comment by Zer0xFF** [comment]
@j8r I've open PR for flathub repo, if im missing anything, please let me know. PR: https://github.com/flathub/flathub/pull/2981

**Comment by j8r** [comment]
Can be closed, https://github.com/flathub/org.purei.Play is live 🚀.
Thanks @Zer0xFF!

**Comment by jpd002** [comment]
Awesome! Thanks a bunch @Zer0xFF & @j8r!
