### ISSUE TITLE
Version string is outdated

### ISSUE THREAD

**Issue by JKingweb** [jpd002/Play-#1127]
## Quick summary
The version string still states 0.30, which is misleading when using Play! in RetroArch

## Issue Details
The version appears to be defined here: https://github.com/jpd002/Play-/blob/5ab06c4cf195a7e42a6f6579bf7526948426d152/CMakeLists.txt#L24

**Comment by jpd002** [comment]
Hey! Where is your libretro core coming from?

Just down below the line you've pointed out, we're supposed to set the proper version from git describe:
https://github.com/jpd002/Play-/blob/5ab06c4cf195a7e42a6f6579bf7526948426d152/CMakeLists.txt#L33

**Comment by JKingweb** [comment]
Curious. I'm using the Arch package, and [its PKGBUILD](https://github.com/archlinux/svntogit-community/tree/packages/libretro-play/trunk) seems pretty straightforward and doesn't appear to be doing anything weird in the build process.

**Comment by gouchi** [comment]
We are using for the version number [PLAY_VERSION](https://github.com/jpd002/Play-/blob/master/Source/ui_libretro/main_libretro.cpp#L175).

The number version seems correct from the Play! Libretro core coming from the Libretro buildbot.
![play-libretro-version](https://user-images.githubusercontent.com/7869503/135267758-6f8fa501-f0f0-44dd-b6a0-cd451fdf7130.png)

**Comment by Darkhost1999** [comment]
This issue honestly appears to be able to be closed.
Does not look to be a Play! Issue at all.
Libretro-super cores manually imported to Retroarch and the built in core updater all show the correct version string when tested and loading core.
My only belief is if core files or .info files were tampered with would there be an issue.

**Comment by jpd002** [comment]
Closing this for now. Feel free to reopen if there's anything we can do on our end.
