### ISSUE TITLE
iOS version doesn't launch

### ISSUE THREAD

**Issue by 3m4r5** [jpd002/Play-#1135]
it just shows a blank screen
tried installing it from the repo and the ipa file on iPhone 8 Plus iOS 14.3 (jailbroken with checkra1n)

**Comment by 3m4r5** [comment]
I meant the emulator itself,
the app simply shows a blank screen.

I thought either I'm doing something wrong or it only supports A12+ but the community is so small I couldn't find information online, sorry to bother you.

**Comment by 3m4r5** [comment]
It doesn't crash it just shows a black screen, can't send you crash reports.

**Comment by jpd002** [comment]
Oh, gotcha. Can you try starting it while internet connection is disabled? The emulator scans games and fetches boxart at the start, so, it might have an issue downloading them for some reason.

**Comment by 3m4r5** [comment]
I uninstalled play!, reinstalled it, enabled airplane mode and launched it but unfortunately it shows the same black screen, sorry if I wasted your time.

**Comment by 3m4r5** [comment]
I tried a firewall to monitor networking activity but it doesn't request access to anything.

I also tried it in safe mode but with no luck.

it appears to me that the app doesn't launch at all.

**Comment by 3m4r5** [comment]
using a jailbreak tweak that allows me to put apps in windows, it doesn't show black screen it just shows the gray background which made me come to the conclusion that it's just a blank screen ![image](https://user-images.githubusercontent.com/63432932/138021777-c3930aa5-a5d9-4377-a24c-00954a49ae65.png)

**Comment by jpd002** [comment]
Very cool :) Glad it's working.

I'm working on giving better feedback to users on what's happening during the scan process. Could you test this new build to see if anything strange comes up? https://github.com/jpd002/Play-/actions/runs/1396657273

This build has all scanning stuff enabled, but it displays the steps that are being executed instead of just doing the steps synchronously at app load.

Thanks!

**Comment by 3m4r5** [comment]
sorry for the late reply, I just saw yours & tested the last build.

after installing it (before the first launch), there's no "Play!" folder in the files app, and [this](https://user-images.githubusercontent.com/63432932/139561645-78198836-13b4-4fac-98bf-a9663c5bc2bd.MOV) happens at the first launch.

After the first launch the Folder "Play!" show up, I copied "hermes.iso" (one file) to the "Play Data Files" folder and [this](https://user-images.githubusercontent.com/63432932/139561712-41a7e7d7-517c-4b49-87e5-036032f4ac3f.MOV) happens when I relaunch it.

I personally suggest adding "local scanning only" option, and an option to only scan at app launch.

thank you so much for your work!

**Comment by 3m4r5** [comment]
@jpd002 here's a first launch with the firewall enabled: https://user-images.githubusercontent.com/63432932/139562136-07b3d88f-21a3-4432-b164-c9fa309a890f.MOV

**Comment by jpd002** [comment]
Thank you very much for the videos! Gives me a very good idea of what's going on :) I can see that I screwed some things up in my test code, like the result of scanning not being displayed after it's done and scanning happening again when you leave the settings screen (and probably after you come back from playing a game). I'm going to fix these issues.

On Android, it only does a full scan of the device the first time you launch the app. After that, it only scans the folders that are known to contain game files, so, it's much quicker. Something similar could be implemented on iOS. Another idea would be to have a prompt to ask if you'd like to scan all your filesystem for games the first time you launch the emu.

**Comment by jpd002** [comment]
This version should be a bit better: https://github.com/jpd002/Play-/actions/runs/1405568389.

Gonna check to implement the full scan that happens only the first time the app is launched next. I'm going to do something very similar to the Android version and I'm going to add an option in settings to force scan the whole FS again if needed.

**Comment by 3m4r5** [comment]
yeah, this build scans the whole file system on every launch [video](https://user-images.githubusercontent.com/63432932/139709479-74e24e2c-35cd-486a-a633-a57b85f00d70.MOV)

**Comment by jpd002** [comment]
Hello! This new build should only scan the whole filesystem at first launch or if there were no game found: https://github.com/jpd002/Play-/actions/runs/1427047116

There's also a new button in the settings menu to force a rescan of the device if needed.

**Comment by 3m4r5** [comment]
that's great, the button works! [First Launch](https://user-images.githubusercontent.com/63432932/140591171-b9a5009d-0aa4-425b-a248-18f912f881ac.MOV)
also the [Second launch](https://user-images.githubusercontent.com/63432932/140591230-955468fb-c47d-46b9-ac66-04049b2543e6.MOV) is much better (although I faced a [bug](https://user-images.githubusercontent.com/63432932/140591284-920cdd83-effe-4019-bafa-b779f91cdc1c.MOV) once)

**Comment by jpd002** [comment]
Thanks for testing! I guess it's still not perfect, but at least, it's way better than before. I can look at the other issues later. I'm gonna merge the current state of the branch in main once the pipeline succeed!

**Comment by jpd002** [comment]
Branch was merged. Closing this.

**Comment by 3m4r5** [comment]
for sure it's miles better, thank you so much!
