### ISSUE TITLE
the app on iPhone 13 pro max crashes when trying to launch a game

### ISSUE THREAD

**Issue by MrRooTMe** [jpd002/Play-#1136]

**Comment by Alexck002** [comment]
You need to activate JIT

**Comment by Spidy123222** [comment]
Here are different methods to activate jit and why you need to activate jit without a jailbreak. https://spidy123222.github.io/iOS-Debugging-JIT-Guides/

**Comment by MrRooTMe** [comment]
> Here are different methods to activate jit and why you need to activate jit without a jailbreak. https://spidy123222.github.io/iOS-Debugging-JIT-Guides/

Thanks, I've already sorted it out!

**Comment by jpd002** [comment]
Thanks for the documentation @Spidy123222, this is very handy and I might link it in the README. Also just merged the integration with AltServer, which should make things easier for ppl who want to use this method. Closing this.
