### ISSUE TITLE
compile android version error

### ISSUE THREAD

**Issue by hsoftxl** [jpd002/Play-#1141]
D:\StudioProjects\Play-\build_android>gradlew assembleDebug

> Configure project :
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native m
odules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules i
n the project. https://developer.android.com/r/studio-ui/ndk-dir

> Task :compileDebugJavaWithJavac
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

> Task :configureCMakeDebug
C/C++: debug|armeabi-v7a :CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
C/C++: debug|armeabi-v7a :  An old version of CMake is being used that cannot automatically detect
C/C++: debug|armeabi-v7a :  compiler attributes.  Compiler identification is being bypassed.  Some
C/C++: debug|armeabi-v7a :  values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++: debug|armeabi-v7a :  CMake's built-in compiler identification.
C/C++: debug|armeabi-v7a :Call Stack (most recent call first):
C/C++: debug|armeabi-v7a :  D:/Android/SDK/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++: debug|armeabi-v7a :  CMakeLists.txt:8 (project)
C/C++: debug|armeabi-v7a :CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
C/C++: debug|armeabi-v7a :  An old version of CMake is being used that cannot automatically detect
C/C++: debug|armeabi-v7a :  compiler attributes.  Compiler identification is being bypassed.  Some
C/C++: debug|armeabi-v7a :  values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++: debug|armeabi-v7a :  CMake's built-in compiler identification.
C/C++: debug|armeabi-v7a :Call Stack (most recent call first):
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
C/C++: debug|armeabi-v7a :CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
C/C++: debug|armeabi-v7a :  An old version of CMake is being used that cannot automatically detect
C/C++: debug|armeabi-v7a :  compiler attributes.  Compiler identification is being bypassed.  Some
C/C++: debug|armeabi-v7a :  values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++: debug|armeabi-v7a :  CMake's built-in compiler identification.
C/C++: debug|armeabi-v7a :Call Stack (most recent call first):
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
C/C++: debug|armeabi-v7a :CMake Error at CMakeLists.txt:14 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    Header
C/C++: debug|armeabi-v7a :Building for 0.45-42-ge5b1745b.
C/C++: debug|armeabi-v7a :CMake Error at CMakeLists.txt:41 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    PrecompiledHeader
C/C++: debug|armeabi-v7a :CMake Error at tools/AutoTest/CMakeLists.txt:7 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    Header
C/C++: debug|armeabi-v7a :CMake Error at Source/CMakeLists.txt:7 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    Header
C/C++: debug|armeabi-v7a :CMake Error at Source/CMakeLists.txt:13 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    PrecompiledHeader
C/C++: debug|armeabi-v7a :CMake Error at deps/Framework/build_cmake/Framework/CMakeLists.txt:19 (add_subdirectory):
C/C++: debug|armeabi-v7a :  add_subdirectory given source
C/C++: debug|armeabi-v7a :  "D:/StudioProjects/Play-/deps/Framework/build_cmake/Framework/../../../Dependencies/ghc_filesystem"
C/C++: debug|armeabi-v7a :  which is not an existing directory.
C/C++: debug|armeabi-v7a :CMake Warning at deps/Framework/build_cmake/Framework/CMakeLists.txt:26 (find_package):
C/C++: debug|armeabi-v7a :  By not providing "FindICUUC.cmake" in CMAKE_MODULE_PATH this project has
C/C++: debug|armeabi-v7a :  asked CMake to find a package configuration file provided by "ICUUC", but
C/C++: debug|armeabi-v7a :  CMake did not find one.
C/C++: debug|armeabi-v7a :  Could not find a package configuration file provided by "ICUUC" with any of
C/C++: debug|armeabi-v7a :  the following names:
C/C++: debug|armeabi-v7a :    ICUUCConfig.cmake
C/C++: debug|armeabi-v7a :    icuuc-config.cmake
C/C++: debug|armeabi-v7a :  Add the installation prefix of "ICUUC" to CMAKE_PREFIX_PATH or set
C/C++: debug|armeabi-v7a :  "ICUUC_DIR" to a directory containing one of the above files.  If "ICUUC"
C/C++: debug|armeabi-v7a :  provides a separate development package or SDK, be sure it has been
C/C++: debug|armeabi-v7a :  installed.
C/C++: debug|armeabi-v7a :CMake Error at Source/CMakeLists.txt:65 (add_subdirectory):
C/C++: debug|armeabi-v7a :  add_subdirectory given source
C/C++: debug|armeabi-v7a :  "D:/StudioProjects/Play-/Source/../deps/CodeGen/build_cmake" which is not
C/C++: debug|armeabi-v7a :  an existing directory.
C/C++: debug|armeabi-v7a :-- Using Provided BZip2 source
C/C++: debug|armeabi-v7a :CMake Error at Source/CMakeLists.txt:76 (add_subdirectory):
C/C++: debug|armeabi-v7a :  add_subdirectory given source
C/C++: debug|armeabi-v7a :  "D:/StudioProjects/Play-/Source/../deps/Dependencies/build_cmake/bzip2-1.0.6"
C/C++: debug|armeabi-v7a :  which is not an existing directory.
C/C++: debug|armeabi-v7a :CMake Warning at Source/CMakeLists.txt:100 (find_package):
C/C++: debug|armeabi-v7a :  By not providing "FindICUUC.cmake" in CMAKE_MODULE_PATH this project has
C/C++: debug|armeabi-v7a :  asked CMake to find a package configuration file provided by "ICUUC", but
C/C++: debug|armeabi-v7a :  CMake did not find one.
C/C++: debug|armeabi-v7a :  Could not find a package configuration file provided by "ICUUC" with any of
C/C++: debug|armeabi-v7a :  the following names:
C/C++: debug|armeabi-v7a :    ICUUCConfig.cmake
C/C++: debug|armeabi-v7a :    icuuc-config.cmake
C/C++: debug|armeabi-v7a :  Add the installation prefix of "ICUUC" to CMAKE_PREFIX_PATH or set
C/C++: debug|armeabi-v7a :  "ICUUC_DIR" to a directory containing one of the above files.  If "ICUUC"
C/C++: debug|armeabi-v7a :  provides a separate development package or SDK, be sure it has been
C/C++: debug|armeabi-v7a :  installed.
C/C++: debug|armeabi-v7a :CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
C/C++: debug|armeabi-v7a :  An old version of CMake is being used that cannot automatically detect
C/C++: debug|armeabi-v7a :  compiler attributes.  Compiler identification is being bypassed.  Some
C/C++: debug|armeabi-v7a :  values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++: debug|armeabi-v7a :  CMake's built-in compiler identification.
C/C++: debug|armeabi-v7a :Call Stack (most recent call first):
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)
C/C++: debug|armeabi-v7a :CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
C/C++: debug|armeabi-v7a :  An old version of CMake is being used that cannot automatically detect
C/C++: debug|armeabi-v7a :  compiler attributes.  Compiler identification is being bypassed.  Some
C/C++: debug|armeabi-v7a :  values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++: debug|armeabi-v7a :  CMake's built-in compiler identification.
C/C++: debug|armeabi-v7a :Call Stack (most recent call first):
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)
C/C++: debug|armeabi-v7a :CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
C/C++: debug|armeabi-v7a :  An old version of CMake is being used that cannot automatically detect
C/C++: debug|armeabi-v7a :  compiler attributes.  Compiler identification is being bypassed.  Some
C/C++: debug|armeabi-v7a :  values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++: debug|armeabi-v7a :  CMake's built-in compiler identification.
C/C++: debug|armeabi-v7a :Call Stack (most recent call first):
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++: debug|armeabi-v7a :  D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)
C/C++: debug|armeabi-v7a :CMake Error at tools/GsAreaTest/CMakeLists.txt:7 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    Header
C/C++: debug|armeabi-v7a :CMake Error at tools/McServTest/CMakeLists.txt:7 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    Header
C/C++: debug|armeabi-v7a :CMake Error at tools/SpuTest/CMakeLists.txt:7 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    Header
C/C++: debug|armeabi-v7a :CMake Error at tools/VuTest/CMakeLists.txt:7 (include):
C/C++: debug|armeabi-v7a :  include could not find load file:
C/C++: debug|armeabi-v7a :    Header

> Task :configureCMakeDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':configureCMakeDebug'.
> [CXX1405] error when building with cmake using D:\StudioProjects\Play-\CMakeLists.txt: Build command failed.
  Error while executing process D:\Android\SDK\cmake\3.18.1\bin\cmake.exe with arguments {-HD:\StudioProjects\Play- -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=19 -DANDROID_PLATFORM=android-
19 -DANDROID_ABI=armeabi-v7a -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DANDROID_NDK=D:\Android\SDK\ndk\22.1.7171670 -DCMAKE_ANDROID_NDK=D:\Android\SDK\ndk\22.1.7171670 -DCMAKE_TOOLCHAIN_FILE=D:\Android\SDK\ndk\22.1.7171670\build\cmake\a
ndroid.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\Android\SDK\cmake\3.18.1\bin\ninja.exe -DCMAKE_CXX_FLAGS=-frtti -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\StudioProjects\Play-\build_android\build\intermediates\cxx\Debug\54j2v684\obj\armeabi
-v7a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\StudioProjects\Play-\build_android\build\intermediates\cxx\Debug\54j2v684\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -BD:\StudioProjects\Play-\build_android\.cxx\Debug\54j2v684\armeabi-v7a -GNi
nja -DANDROID_ARM_NEON=TRUE -DANDROID_TOOLCHAIN=clang -DANDROID_CPP_FEATURES=exceptions rtti -DANDROID_STL=c++_static}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: D:/Android/SDK/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: D:/Android/SDK/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found ZLIB: D:/Android/SDK/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/arm-linux-androideabi/libz.a (found version "1.2.11")
  -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
  -- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
  -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE
  -- Configuring incomplete, errors occurred!
  See also "D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeOutput.log".
  See also "D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeError.log".

  CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    D:/Android/SDK/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:8 (project)

  CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

  CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

  CMake Error at CMakeLists.txt:14 (include):
    include could not find load file:

      Header

  Building for 0.45-42-ge5b1745b.
  CMake Error at CMakeLists.txt:41 (include):
    include could not find load file:

      PrecompiledHeader

  CMake Error at tools/AutoTest/CMakeLists.txt:7 (include):
    include could not find load file:

      Header

  CMake Error at Source/CMakeLists.txt:7 (include):
    include could not find load file:

      Header

  CMake Error at Source/CMakeLists.txt:13 (include):
    include could not find load file:

      PrecompiledHeader

  CMake Error at deps/Framework/build_cmake/Framework/CMakeLists.txt:19 (add_subdirectory):
    add_subdirectory given source
    "D:/StudioProjects/Play-/deps/Framework/build_cmake/Framework/../../../Dependencies/ghc_filesystem"
    which is not an existing directory.

  CMake Warning at deps/Framework/build_cmake/Framework/CMakeLists.txt:26 (find_package):
    By not providing "FindICUUC.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "ICUUC", but
    CMake did not find one.

    Could not find a package configuration file provided by "ICUUC" with any of
    the following names:

      ICUUCConfig.cmake
      icuuc-config.cmake

    Add the installation prefix of "ICUUC" to CMAKE_PREFIX_PATH or set
    "ICUUC_DIR" to a directory containing one of the above files.  If "ICUUC"
    provides a separate development package or SDK, be sure it has been
    installed.

  CMake Error at Source/CMakeLists.txt:65 (add_subdirectory):
    add_subdirectory given source
    "D:/StudioProjects/Play-/Source/../deps/CodeGen/build_cmake" which is not
    an existing directory.

  -- Using Provided BZip2 source
  CMake Error at Source/CMakeLists.txt:76 (add_subdirectory):
    add_subdirectory given source
    "D:/StudioProjects/Play-/Source/../deps/Dependencies/build_cmake/bzip2-1.0.6"
    which is not an existing directory.

  CMake Warning at Source/CMakeLists.txt:100 (find_package):
    By not providing "FindICUUC.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "ICUUC", but
    CMake did not find one.

    Could not find a package configuration file provided by "ICUUC" with any of
    the following names:

      ICUUCConfig.cmake
      icuuc-config.cmake

    Add the installation prefix of "ICUUC" to CMAKE_PREFIX_PATH or set
    "ICUUC_DIR" to a directory containing one of the above files.  If "ICUUC"
    provides a separate development package or SDK, be sure it has been
    installed.

  CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)

  CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)

  CMake Warning at D:/Android/SDK/ndk/22.1.7171670/build/cmake/android.toolchain.cmake:449 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
    D:/StudioProjects/Play-/build_android/.cxx/Debug/54j2v684/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)

  CMake Error at tools/GsAreaTest/CMakeLists.txt:7 (include):
    include could not find load file:

      Header

  CMake Error at tools/McServTest/CMakeLists.txt:7 (include):
    include could not find load file:

      Header

  CMake Error at tools/SpuTest/CMakeLists.txt:7 (include):
    include could not find load file:

      Header

  CMake Error at tools/VuTest/CMakeLists.txt:7 (include):
    include could not find load file:

      Header

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
14 actionable tasks: 3 executed, 11 up-to-date

**Comment by jpd002** [comment]
Hey there!

Are you sure all your submodules are properly initialized?

You can run this command to make sure everything is good:
`git submodule update --init --recursive`

**Comment by hsoftxl** [comment]
i compile on windows 11 ,  and not work

![image](https://user-images.githubusercontent.com/6965803/141101132-05d41695-7392-4d17-8900-4fc339f353ce.png)

**Comment by jpd002** [comment]
Is there anything in `Play-\deps\Dependencies\cmake-modules`? `Header.cmake` should be in there.

**Comment by hsoftxl** [comment]
there is nothing  how can i get these files.

**Comment by hsoftxl** [comment]
ok i got it
