### ISSUE TITLE
"10 000 Bullets "crash

### ISSUE THREAD

**Issue by Cristobal15** [jpd002/Play-#1143]
ID: SLES-53481
Play version: 0.45-50-g772bc53
Plataform - Android 11
Device - Poco x3 pro (Snapdragon 860, Adreno 640, 8 RAM)
Problem - The Game Crash after to start the tutorial.

The game crash before start the tutorial in load menu.

The game on menu run at 60FPS and it don't have audio problem

"Great work!! This is a amazing emulator".
![Screenshot_2021-11-08-10-12-46-478_com virtualapplications play](https://user-images.githubusercontent.com/76236492/140781855-f112ae97-9169-4bb4-bf66-9d775b628dbc.jpg)

**Comment by literalmente-game** [comment]
This is not where or how you report compatibility, for that use the compatibility tracker https://github.com/jpd002/Play-Compatibility/ and please read https://github.com/jpd002/Play-Compatibility/#guidelines before making any new issue (or reporting information to issues that are already open)

**Comment by jpd002** [comment]
Already reported here: https://github.com/jpd002/Play-Compatibility/issues/845. Thanks!
