### ISSUE TITLE
"Rygar: The Legendary Adventure" crash

### ISSUE THREAD

**Issue by Cristobal15** [jpd002/Play-#1144]
ID: SLUS-20471
Plataform - Android 11
Play version: 0.45-50-g772bc53
Device - Poco x3 pro (Snapdragon 860, Adreno 640, 8 RAM)
Problem - The game crashes when crossing the first door.

The game run at ~40FPS and it don't have audio problem or graphic issues that affect the gameplay

"Great work!! This is a amazing emulator".
![Screenshot_2021-11-07-23-48-25-431_com virtualapplications play](https://user-images.githubusercontent.com/76236492/140782223-d4814d62-6760-4fcd-a559-7b1c3be67cf2.jpg)

**Comment by FatheredPuma81** [comment]
https://github.com/jpd002/Play-Compatibility/issues Please post this there not here.

**Comment by jpd002** [comment]
Thanks for creating the issue in the compat tracker: https://github.com/jpd002/Play-Compatibility/issues/1387.
