### ISSUE TITLE
Submodule commit `f799f60ef6fa8b9676b4102b7dfa169fb40b6c92` does not belong to jpd002/AltKit

### ISSUE THREAD

**Issue by j8r** [jpd002/Play-#1187]
[deps/AltKit](https://github.com/jpd002/Play-/tree/master/deps) is a submodule used by this repository.

This submodule, https://github.com/jpd002/AltKit, has a commit (`f799f60ef6fa8b9676b4102b7dfa169fb40b6c92`) that does not belong to it, see https://github.com/jpd002/AltKit/tree/f799f60ef6fa8b9676b4102b7dfa169fb40b6c92. I've noticed this when working on the Flatpak build (by the way @Zer0xFF in any case you work on it you can let me finish, thanks to have started it :slightly_smiling_face: ).

It exists in the [parent repository](https://github.com/rileytestut/AltKit/commit/f799f60ef6fa8b9676b4102b7dfa169fb40b6c92), and points to the `0.0.2` tag, which doesn't exist on your fork.

To fix this, either the parent project can be used, or the given tag be pushed from it to your fork.

**Comment by jpd002** [comment]
Updated my AltKit fork. Should be good now!

Thanks!
