### ISSUE TITLE
Play! should respect the XDG standard

### ISSUE THREAD

**Issue by j8r** [jpd002/Play-#1189]
Several Linux environment can be special (or not), for instance Flatpak, which has a sandbox for each application,
The XDG standard is used in order to let the application know where to store its data/configuration.

I got the Flatpak build working, but currently have this error:
`filesystem error: cannot create directory: Read-only file system [/home/jrei/.local/share/Play Data Files]`

To solve this, `XDG_DATA_HOME`, and maybe `XDG_CONFIG_HOME` environment variables should be used first, then have the current values as a fallback.

Example values this XDG variables can have:
```
XDG_DATA_HOME=/home/user/.var/app/org.purei.Play/data
XDG_CONFIG_HOME=/home/user/.var/app/org.purei.Play/config
````

**Comment by Zer0xFF** [comment]
this should be straight forward, updating these 2 functions here https://github.com/jpd002/Play--Framework/blob/master/src/PathUtils.cpp#L138 ill take sometime later and test this.
