### ISSUE TITLE
Building collection, scanning games on filesystem

### ISSUE THREAD

**Issue by NtandoNdima** [jpd002/Play-#1227]
When I open the play emulator on my iPhone 7 it takes time to build collection and it also takes time to scan for games on the filesystem 
![Uploading 73F15691-84A6-4FDA-B8BA-B0C442585E44.png…]()

**Comment by tqoo** [comment]
Same issue here
iPad Pro 10.5-inch on iPadOS 15.5 jailbroken on palera1n
Did you find a solution?
