### ISSUE TITLE
Soul Calibur 2 Arcade freezing 

### ISSUE THREAD

**Issue by Arcadeguy781** [jpd002/Play-#1238]
## Quick summary
Please briefly describe what is not working correctly
Soul Calibur 2 freezes after the boot screen 

## System Details
Describe the ambient being used to run Play!
Information needed:
- Operating system (including the version)
- Hardware (GPU and CPU, for android you can search for your device model here https://www.gsmarena.com/ for specifications)
- Version of Play!
- Describe the ambient being used to run Play!
Information needed: Windows 10, AMD Ryzen 9 5800HX, NVIDIA 3070m, and Play! Version 0.59

Operating system (including the version)
Hardware (GPU and CPU, for android you can search for your device model here https://www.gsmarena.com/ for specifications)
Version of Play!

## Issue Details
Describe in details the problem you had and the expected behavior
When I boot Soul Calibur 2 Arcade it freezes on the game initializing screen. It’s supposed to load. 

## Screenshots/Videos
Drag and drop (or link to) videos or images that could help us understand the problem.

**Comment by Arcadeguy781** [comment]
Hangs on that screen

**Comment by jpd002** [comment]
Should be fixed in latest update of the `namco_system_256` branch
