### ISSUE TITLE
fix build_android error

### ISSUE THREAD

**Issue by sirlocalhost** [jpd002/Play-#1243]
Greetings,
![Screenshot 2023-03-09 133410](https://user-images.githubusercontent.com/78411843/224154165-b1213f17-089e-43b4-90c8-fff514fe2215.jpg)

I was building the Android Play- project when I encountered this error
Does anyone know why?

I wanted to know a problem about building the Android project.
I acted exactly according to the documentation, but from the beginning, all the errors were created, and I tried to fix the errors, but new errors appeared.

**Comment by Sykomaniac** [comment]
When cloning, you need to run `git submodule update --init --recursive` from the root of your checkout
