### ISSUE TITLE
Taiko HDD files are not read

### ISSUE THREAD

**Issue by Tomo-Tg** [jpd002/Play-#1261]
## Quick summary
HDD files are not read

## System Details
Describe the ambient being used to run Play!
Information needed:
- Windows10Pro
- GTX745 Corei5-3470 
- 0.61

## Issue Details
As of version 0.57, we were able to read the data on the HDD, but after updating to the latest version yesterday, it stopped reading the files.
The files are located at the following location.
C:\Users\name\Documents\Play Data Files\vfs\hdd\TAIKOMAIN

## Screenshots/Videos

![image](https://github.com/jpd002/Play-/assets/66196203/65922204-1a7e-471e-8893-523fcb064b55)

**Comment by jpd002** [comment]
Hey, seems you're using the old way of using HDD games within the emulator (which was just a workaround). I've updated the emulator to use CHD files for HDD, which you can place in your `arcaderoms` directory like DVDs. It should be in line with what MAME supports.

**Comment by Tomo-Tg** [comment]
I see! I understand.
I'll give it a try.

**Comment by Tomo-Tg** [comment]
It worked fine!
Are the vertical lines on the screen and the low fps due to my misconfiguration, etc.? Or is it a limitation of the current emulation?
![スクリーンショット 2023-07-01 003600](https://github.com/jpd002/Play-/assets/66196203/75907cfb-ccc5-421c-9449-99a1e66fb887)

**Comment by jpd002** [comment]
The bars is a known problem with OpenGL. Vulkan doesn't have this problem, but from your screen shot, I guess your system can't use it. Low frame rate is due to some strange thing the game does on the GS side, changing the color mask many times in-between draws preventing any batching of draw calls. I haven't found a way to fix that atm.

**Comment by Tomo-Tg** [comment]
I see. I understand.
Thank you for your support!
