### ISSUE TITLE
Bloody Roar 3 issues

### ISSUE THREAD

**Issue by Arcadeguy781** [jpd002/Play-#1269]
## Quick summary
Please briefly describe what is not working correctly

Bloody Roar 3 doesn't boot properly on the latest version of the Play! emulator (Arcade version)

## System Details
Describe the ambient being used to run Play!
Information needed:
- Operating system Windows 10
- Hardware AMD Ryzen 9 5900 HX, NVIDIA RTX 3070 8 GB GDD6, Play! version 0.61-71-g16610575

## Issue Details
Describe in details the problem you had and the expected behavior
When I try to boot the game all I see is a black screen 

## Screenshots/Videos
Drag and drop (or link to) videos or images that could help us understand the problem.

**Comment by EmuAl** [comment]
i can confirm this as well
works fine in v61 official but anything after that afaict is black screen

**Comment by strodown** [comment]
yes have a same issue on bloody roar 3

**Comment by jpd002** [comment]
Yep, I screwed something up with HLE PADMAN when I did changes for Taiko no Tatsujin. Fix incoming.

**Comment by jpd002** [comment]
Should be fixed in master now.

**Comment by strodown** [comment]
thx
