### ISSUE TITLE
Add Fate/Unlimited Codes to the arcadedefs

### ISSUE THREAD

**Issue by chris202020202020** [jpd002/Play-#1277]
## Quick summary
256 version A

## System Details
Describe the ambient being used to run Play!
Information needed:
- Windows 11
- 
- 0.62

## Issue Details
voices and ost music are speed up and high pitched please fix it

## Screenshots/Videos
Drag and drop (or link to) videos or images that could help us understand the problem.

**Comment by jpd002** [comment]
Added def for `fateulc`. Seems to run in sys246 (and not sys256).
