### ISSUE TITLE
Time Crisis 4 Stage 2 Area 1 Glitched Map

### ISSUE THREAD

**Issue by kim-sama** [jpd002/Play-#1280]
When you start Stage 2 and into Area 1, the cave you're in is glitched out and blocking your view of the enemies. The issue is on both Vulkan and OpenGL

I'm using Play! v0.62 g58216c31

![スクリーンショット 2023-08-13 134008](https://github.com/jpd002/Play-/assets/40289574/73d09afa-599d-40b0-b59a-d5304c81a958)
![スクリーンショット 2023-08-13 134025](https://github.com/jpd002/Play-/assets/40289574/f5e5d803-0f83-4d59-ba85-8466e33503fc)

**Comment by jpd002** [comment]
Fix in progress in `vu_dynamic_stall` branch.

![image](https://github.com/jpd002/Play-/assets/6760433/4c46ce3e-c6dd-4ce4-90dc-0b11e4f36760)

**Comment by jpd002** [comment]
Fix has been merged in `master`.
