### ISSUE TITLE
Play is not detecting games 

### ISSUE THREAD

**Issue by abhishekgi** [jpd002/Play-#1292]
## Quick summary 
Play is not detecting games i have tried everything, watched videos, read docs , etc 

## System Details
Describe the ambient being used to run Play!
Information needed:
- ipad os 16.6
- ipad 9 wifi A13 Bionic 
- Version of Play!

## Issue Details
Is is not detecting any game 

## Screenshots/Videos
Drag and drop (or link to) videos or images that could help us understand the problem.

**Comment by abhishekgi** [comment]
Someone tell me how to fix this

**Comment by Aynshe** [comment]
> Someone tell me how to fix this

hi,

after adding a ps2 iso game, all the games in the same folder will be displayed.

![chrome_2023-09-02_21-06-25](https://github.com/jpd002/Play-/assets/1908827/6bf956eb-d2a2-4b58-8d5d-f17855735d3b)

**Comment by abhishekgi** [comment]
Bro I am using ipad not mac

**Comment by abhishekgi** [comment]
Can someone tell me the correct way of adding games in iOS

**Comment by Aynshe** [comment]
> Bro I am using ipad not mac

First of all, I'm not your "bro"...

Apart from that, under endroid the iso does not appear either after choosing the folder and scan in setting.

**Comment by jpd002** [comment]
Thanks for helping @Aynshe. Closing since I don't accept this kind of attitude from OP.
