### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by Hydro5** [jpd002/Play-#13]
"Play!" is basically an impossible to search for term. Search engines ignore punctuation, so "play" and "PS2" brings up a thousand unrelated videos and information. 

Please change the program's name back to Purei, which is more unique.

**Comment by seadil** [comment]
I would use purei as official name for the emulator. Purei is an unique name for an emulator and the official website of the emulator is purei.org. It's way better than Play! and easier to distinguish between the verb "play" in search engines.

@jpd002 What are your thoughts about it?

**Comment by shakingboy** [comment]
@seadil I think the name should stay the same. 

It's not impossible for a search engine to recognize unique keywords, punctuation or not.

**Comment by jpd002** [comment]
I'm still undecided on that. I changed from "Purei" to "Play!" a while back and I don't feel like changing back again. But I'm open to other suggestions.

Did a quick "Play PS2 Emulator" on Google and first result was this Github page and second was the official website. So, it's not that bad I guess.

**Comment by vgturtle127** [comment]
I say keep it the same, I like it. :smile:

**Comment by atomic83GitHub** [comment]
Why put a github issue on that? And by the way the actual name is good in my opinion ☺

**Comment by jpd002** [comment]
Yeah, that's pretty old, better off closed.
