### ISSUE TITLE
Bloody Roar 3 not save test menu

### ISSUE THREAD

**Issue by Nicktamer** [jpd002/Play-#1300]
## Quick summary
Bloody Roar 3 namco system 246 version  do not saving the change in test menu, no backupram files create in arcadesave 

## System Details
Describe the ambient being used to run Play!
Information needed:
- Windows 11 with latest update
- Nvidia Gtx 1650 I5 9400F
- Play 0.62

## Issue Details
When you acces the test menu the change aren't saved. No backupram files is created in arcadesave

## Screenshots/Videos
Drag and drop (or link to) videos or images that could help us understand the problem.

**Comment by Hydreigon223** [comment]
It's a know problem with any game running on system 246. System 256 games save fine.

**Comment by Nicktamer** [comment]
It seems to me Soulcalibur 3 and smash court are system 246 and the backupram is created in arcade save and the change of the test menu are saved. So maybe not all of 246 are affected

**Comment by jpd002** [comment]
Bloody Roar 3 and Ridge Racer use an older version of the sys2x6 IOP modules. It's implemented in a separate codepath in the emulator and it was missing the part to handle backup RAM accesses. This should fix it: https://github.com/jpd002/Play-/tree/bloody_roar_3_backupram

**Comment by Nicktamer** [comment]
Oh nice thanks so much that's cool. Did you think it will be merged on the next update at master for testing that?

**Comment by Hydreigon223** [comment]
This explains why Vampire Night was affected as well (another earlier 2x6 title using the older IOP module).

**Comment by jpd002** [comment]
Yes, I'll merge it tomorrow.

> This explains why Vampire Night was affected as well (another earlier 2x6 title using the older IOP module).
Oh yeah, right, I forgot about that one.

**Comment by jpd002** [comment]
Fix merged.
