### ISSUE TITLE
Taiko no Tatsujin 7 cannot be run, and the game has 2 discs, and the other disc is an upgrade disc.

### ISSUE THREAD

**Issue by andymage593** [jpd002/Play-#1310]
**REMOVED**

**Comment by andymage593** [comment]
![taiko7](https://github.com/jpd002/Play-/assets/127004996/7ae40215-bba5-44d0-89f8-bf348494acb8)

**Comment by jpd002** [comment]
Should now be working, some functions were missing in ACCDVD.
