### ISSUE TITLE
Super Dragon Ball Z Black screen at startup

### ISSUE THREAD

**Issue by andymage593** [jpd002/Play-#1325]
13th Gen Intel(R) Core(TM)i7-1370OKF
DDR 5 32.0GB
NVIDIA GeForce RTX2060
Windows 10 64 Bit
Kushi-dyeing pattern: OpenGL
Game“Super Dragon Ball Z”
Black screen at startup
![Stop at system search](https://github.com/jpd002/Play-/assets/127004996/c406fa99-c85a-4cff-8ee4-8189f911b6f0)

**Comment by andymage593** [comment]
There are several other games with the same black screen based on the same principle:
NM00003 Technic Beat
NM00010 Battle Gear 3
NM00015 Battle Gear 3 Tuned
NM00016 Zoids Infinity
NM00025 Zoids Infinity - EX
NM00028 Druaga Online - The Story of Aon
NM00035 The Battle of YuYu Hakusho - Deathmatch! Dark Martial Arts Association

**Comment by Arcadeguy781** [comment]
I'm having the same issues too on the latest build

**Comment by jpd002** [comment]
Should now be working, some functions were missing in ACCDVD.
