### ISSUE TITLE
Namco 2x6 support on IOS, use bios, mcd files

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [jpd002/Play-#1328]
I would like to compare ps2 games to their arcade counter part, and I would like for you to add support for namco 2x6 support on ios. Speaking of which, can you also add bios support? This includes the ps2 bios, as well as the namco 246 and 256 bios. One last thing, could you add support of using mcd memory card files instead of using folders? It's a lot easier for using cheats with something I talked about earlier this year, swapping discs.

**Comment by gtapcfan** [comment]
I would also like to see an Android support for Namco System 2x6 emulation as well cause i would like to play the arcade version of Tekken 5: Dark Resurrection (after being bored of the PSP version but i appreciate the sacrifices that Katsuhiro Harada (the developer of the Tekken series) made for the PSP/PS3 port, they should have released it on PS2 as an exclusive (along with Time Crisis 4) but it's too late for Namco to do it)

**Comment by Arcadeguy781** [comment]
Play doesn’t require a bios since it’s programmed differently than most emulators.

**Comment by kim-sama** [comment]
Namco 2x6 on Play already supports iso, img, and bin.  use iso and img for the dvd rom games

**Comment by Iamthebestintheworld222** [comment]
I'm trying out the arcadedefs on my phone and see if they show up, if they do, this is another step for implementing it, by the way, i'm using 0.67-2.

**Comment by jcstahl1** [comment]
Namco 2x6 games require a decently spec'd PC to run even somewhat smoothly.  i can even imagine how horrendous they would run on a mobile processor.

**Comment by Iamthebestintheworld222** [comment]
probably on modern iphones starting from the 14 or 15.

**Comment by Iamthebestintheworld222** [comment]
is there an arcadedef folder, or can i create one on the main play files menu?

**Comment by Iamthebestintheworld222** [comment]
It shows the arcadedef files, and not the actual names of the arcade software being run.

**Comment by Iamthebestintheworld222** [comment]
It doesn't work, I tried the arcade version of tekken 4, and didn't work.

**Comment by jcstahl1** [comment]
as i said, a mobile processor isn't going to have the power to run the arcade games.

**Comment by Iamthebestintheworld222** [comment]
It can run naomi, naomi2, atomiswave, system sp, and fbneo and mame compatible stuff.

**Comment by Iamthebestintheworld222** [comment]
I don't see that problem.

**Comment by Iamthebestintheworld222** [comment]
Or is it because the dreamcast arcade based hardware is different than ps2 based arcade hardware.

**Comment by Iamthebestintheworld222** [comment]
Maybe, try on 15 pro and 16 pro?

**Comment by jcstahl1** [comment]
> Maybe, try on 15 pro and 16 pro?

what are you not understanding here?  

YOU NEED A PC WITH GOOD SPECS TO GET NAMCO SYSTEM 2X6 GAMES TO WORK AND BE PLAYABLE.  A MOBILE PROCESSOR IS NOT GOING TO BE ENOUGH POWER TO RUN THE GAMES IN IT'S CURRENT STATE.

**Comment by Iamthebestintheworld222** [comment]
The a18 is 4.04ghz, should be able to run them fine, but don't repeat the same thing a third time.

**Comment by jcstahl1** [comment]
processor speed is not directly indicative of processor power.  

i'm not trying to be mean, but you're really beating a dead horse here and just not grasping this concept.  until further optimization of the emulator itself is made, the 2x6 games are not going to run properly, if they run at all.  I'm running a AMD Ryzen 7 5700X, Nvidia RTX3060 GPU and 64GB of RAM, which without question MUCH more powerful of a system than any iPhone, and most of these games still don't run full speed or have issues.  

why do you think the arcade funcitons of Play! are not built into the iPhone/Android versions to begin with?  

it's a simple answer: they don't have the processing power to run them.

**Comment by Iamthebestintheworld222** [comment]
Well, technology is advancing, maybe an iPad version of play can be in the works, and then the arcade games can be played there.

**Comment by Iamthebestintheworld222** [comment]
Well my i9750h and gtx1650 with 16gb ram can play them at full speed with Vulkan driver pretty well.

**Comment by jcstahl1** [comment]
now, you're getting it.  your PC is also much more powerful as a system than your iPhone.  the emulator is also way more optimized for PC than other platforms for a reason.

**Comment by Iamthebestintheworld222** [comment]
Steam deck as well, maybe if 002 can maybe hurry up for more features for the mobile version, and more optimizations that would be cool. I would play parappa 2 start to finish at full speed.

**Comment by jcstahl1** [comment]
even thinking a dev should hurry up is kind of insulting, let alone actually saying it.  they do this in their free time for pretty much no pay other than possilbe Patreon subs.  thinking your iPhone is a powerful piece of gaming hardware capable of playing demanding games & systems designed for PCs is laughable at best, but by all means continue your futile efforts & pointless making github issues of an already well documented incompatibilty with mobile versions of the emulator.  i'm done here.

**Comment by jpd002** [comment]
Closing as this is not really constructive.
