### ISSUE TITLE
Problem with play_libretro.dll to run games Nanco System 2x6 does not accept .zip format

### ISSUE THREAD

**Issue by macsgv** [jpd002/Play-#1335]
## Quick summary
In the standalone emulator Play! I can run Namco System 2x6 games without problems. But when I want to run them in retroarch with the core play_libretro.dll I can't because it doesn't accept the .zip format and if I load the .chd directly it doesn't work either.

## System Details
I am using Retroarch v1.16.0 to run the core play_libretro.dll and as Front-End to launch the games I use ArcadeFlow v1.6..6
Information needed:
- Windows 11 Home Version: 23H2
- Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz - 8,00 GB (7,86 GB usable)
- Intel(R) UHD Graphics 630
- NVIDIA GeForce GTX 1050
- Play! (0.63-44-g08f7ee1c)

## Issue Details
I am using this argument to load the .zip roms along with the .chd of the Namco System 2x6 games, but the games are not loading because play_libretro.dll does not accept the .zip format

# Generated by Attract-Mode Plus v3.0.6
#
executable retroarch.exe
args -f -L cores\play_libretro.dll "[romfilename]"
workdir D:\attract\emulators\MAME - retroarch
rompath D:\attract\roms\arcaderoms\
romext .zip
system Namco System 2x6
import_extras D:\attract\roms\arcaderoms\Namco System 2x6.xml
exit_hotkey Joy0 Button6+Joy0 Button7
artwork boxart \attract\boxart\Namco System 2x6
artwork cartart \attract\cartart\Namco System 2x6

## Screenshots/Videos
Drag and drop (or link to) videos or images that could help us understand the problem.
![1](https://github.com/jpd002/Play-/assets/13799157/b4294ecf-c982-4639-ab88-1c4720e77e37)

![2](https://github.com/jpd002/Play-/assets/13799157/e91606f0-bbc4-487e-a35c-598af4cb48ac)

**Comment by gouchi** [comment]
Please close this issue as it is duplicated of #1241

Thank you.
