### ISSUE TITLE
Tekken 4/5 input issue

### ISSUE THREAD

**Issue by anxious132** [jpd002/Play-#1338]
## Quick summary
Main Inputs are incorrectly mapped? 

## System Details
- Operating system (including the version)
- Windows 11 Latest Version

- Hardware (GPU and CPU, for android you can search for your device model here https://www.gsmarena.com/ for specifications)
  Ryzen 5 5600X / 16GB DDR4 3600 / RTX 2060

- Version of Play!
Latest Release

## Issue Details
Only Button 2 is mapped correctly, two buttons are mapped as 1+2 1+2, one as 3+4.

## Screenshots/Videos
https://streamable.com/2874kj

**Comment by jpd002** [comment]
This was discussed with OP and this is not an issue anymore.
