### ISSUE TITLE
"Invalid ISO9660 Volume Descriptor" when booting Tekken 5 Dark Resurrection 

### ISSUE THREAD

**Issue by TheRadicalLeft** [jpd002/Play-#1345]
## Quick summary
Just as it says in title. I try to boot up Tekken 5 DR, the error message shows up.

## System Details
- Windows 10
- CPU: AMD A10-7800 3.50 GHz GPU: Radeon R7 Graphics
- Automated v0.63-107-geb181875 Jan 15 2024

![image](https://github.com/jpd002/Play-/assets/99574056/b5501c31-e244-4a5a-9162-b6a4e44d938d)

**Comment by Arcadeguy781** [comment]
From what I can tell you need to convert the CHD to cdvd format using chdman

**Comment by Alidonis** [comment]
> From what I can tell you need to convert the CHD to cdvd format using chdman

and how, do I convert a CHD into cDVD ? what parameters do I need to set for CHDMan?

**Comment by kim-sama** [comment]
> > From what I can tell you need to convert the CHD to cdvd format using chdman
> 
> and how, do I convert a CHD into cDVD ? what parameters do I need to set for CHDMan?

chdman extractcd -i "filename.chd" -o "filename.img"

**Comment by jpd002** [comment]
Assuming this is ok considering this: #1355.
