### ISSUE TITLE
Issues when trying to run Play! on my some laptops

### ISSUE THREAD

**Issue by cgdl00** [jpd002/Play-#1361]
## Quick summary
Tried on both Win 10 64-bit laptop, returns failure during installation and application run.

## System Details
Real Machine
- Windows 10 64-bit
- Core 2 Duo CPU, 4 GB of RAM, I don't really know its GPU since it is quite old.
- Version of Play!: 0.63

Virtual Machine (Virtual Box)
- Windows 10 64-bit
- Core i5 CPU (from 4 cores allocated 2 cores), 8 GB of RAM (allocated 8 GB out of 16 GB), AMD Radeon HD 8600M Series.
- Version of Play!: 0.63

Both using SSD (SATA), if that matters.

## Issue Details
I have tried to run Play! on two of my laptops, both are Win 10 64-bit. One of them is directly on the machine, the other in the virtual machine. During installation, although the internet is available, for both it always fails to download VC Redist 2015. By reading the installation code here: https://github.com/jpd002/Play-/blob/master/installer_win32/vcredist2015_x64.nsh#L21 I was able to download the redist manually. For both it always return something like VCRUNTIME and MSVCP (with or without _1) not found. 

(Edit: the error message before installing vc_redist is: "The code execution cannot proceed because VCRUNTIME140.dll/MSVCP140.dll/MSVCP140_1.dll was not found. Reinstalling the program may fix this problem."

the error message after installing vc_redist is: "The code execution cannot proceed because VCRUNTIME140_1.dll/MSVCP140_1.dll was not found. Reinstalling the program may fix this problem.")

I tried for both install VC Redist 2015-2022 (https://aka.ms/vs/17/release/vc_redist.x64.exe). The error message disappeared. However, Play! won't run without any error message. By looking at Task Manager, it opens, then closes after few seconds

**Comment by sector-c** [comment]
I believe this is an issue with your VC Redist install on your computer and not with the emulator itself. You mention installing the x64 versions of the VC Redist but I think you also need to install x86 version.

**Comment by jpd002** [comment]
Thanks for your report @cgdl00 . Regarding your GPU issue, linking a ticket that was opened a while ago: https://github.com/jpd002/Play-/issues/1275.

I'll remove the old redist download code from the NSIS install script as it doesn't make sense anymore. I'll add a link to the new redist packages instead on the readme and website.
