### ISSUE TITLE
"Error while reading directory entry" The iDOLM@STER 

### ISSUE THREAD

**Issue by Migou3221** [jpd002/Play-#1366]
Hello! 
Firstly, I'm genuinely very sorry if this question/issue happens to be dumb. I'm quite neophyte to this scene, please excuse my lack of knowledge. 

Here's my gear; 
- Win10 Pro
- NVIDIA GeForce GTX 1660
- AMD Ryzen 5 2600
- Play version 0.64-43-g8445595b  

As the title suggests, I've been facing this error (cf. attachment) whenever I try to load the game through the bootables list. 

I've tried many things to ensure that I respected the recommandations.
At first, I thought the problem could've came from the rom itself, I consequently acquired two different versions and proceeded to check them with CHDMAN. To no avail since the error still pops up. 

Then I've tried to switch my Play Data Files folder containing the roms from my C disk to another disk, just in case. Which didn't fix anything !
I think I've also respected the way the folders are meant to be agenced when it comes to sytem 2x6 games; which is the following :
arcaderoms/
  idolmtower.zip
  idolmtower/
      NM00022 IDM1-HA (HHD).chd

![image](https://github.com/jpd002/Play-/assets/166335069/0050ed4e-2663-4a74-bca3-0ca4338a88a8)

There's perhaps something very obvious i'm missing? I really don't know what I could have done wrong here. Can anyone help me please?

**Comment by jpd002** [comment]
This error seems to come from the ZIP file reader. Could you verify that your `idolmtower.zip` archive is correct with a compression tool?

**Comment by Migou3221** [comment]
> This error seems to come from the ZIP file reader. Could you verify that your `idolmtower.zip` archive is correct with a compression tool?

Thank you for your answer! 
I ran a test on the zip file with 7zip, no errors come up. Also, I forgot to mention in the post that I've also tried to zip the files both in winrar and 7zip. 
7zip wise i've tried different compression methods (deflate/bzip2/lzma) yet it all leads to the same issue... There might be something i'm missing when it comes to zipping the chd and dongle ?

**Comment by jpd002** [comment]
If you have a hex editor, could you show me the last bytes of your archive? (I guess the last 1024 ones are enough)

![image](https://github.com/jpd002/Play-/assets/6760433/eae5594a-e887-4115-96bc-5c34320300e3)

**Comment by Migou3221** [comment]
![image](https://github.com/jpd002/Play-/assets/166335069/33c852d0-6c8b-4a6e-94fc-5b155e874944)

Looking at yours, mine definitely looks somewhat different...

**Comment by jpd002** [comment]
Ah, I see why it doesn't work. You have the chd file inside the zip which makes it larger than 4GB and this adds the need to parse ZIP64 headers which the emulator doesn't support.

But the good news is that you should be able to remove that chd file from the archive and everything should work fine. Lemme know if that's the case.

Thanks!

**Comment by Migou3221** [comment]
It was definitely the problem! Can't believe I never thought of it earlier! I genuinely thought the chd had to be also zipped.. 

Thank you very VERY much for your time and patience, it works like a charm !! 
![image](https://github.com/jpd002/Play-/assets/166335069/4e84795e-264d-41e9-ad36-924cdc71dced)

**Comment by jpd002** [comment]
Great, glad to hear it works now! Thanks for the confirmation!
