### ISSUE TITLE
A bit unrelated, but does anyone know where to get this nand file?

### ISSUE THREAD

**Issue by cgdl00** [jpd002/Play-#1374]
https://github.com/jpd002/Play-/blob/3d62a053ab9bdb0e72b5c8e2f9b69085fc1e6abc/arcadedefs/akaiser.arcadedef#L7

I usually use Play! for playing Animal Kaiser Evo. However I do notice that the older version of AK are added to the arcadedefs. Does anyone know where to get the nand file for the older AK?

Thank you.

**Comment by jpd002** [comment]
Do not ask where to look for ROMs.
