### ISSUE TITLE
System.cnf file not dound on the cdrom0 device

### ISSUE THREAD

**Issue by Konrad1374** [jpd002/Play-#1383]
## Quick summary
booting a disc image gaves back a warning

## System Details
Information needed:
- Operating system: Win10 22H2
- Hardware: 13600KF + 2080TI
- Version of Play!: Play! v0.66-26-g6a6ff95b - Jun 26 2024

## Issue Details
Describe in details the problem you had and the expected behavior
trying to boot wangan midnight r from a .chd file but it gives back an error. should boot normally based on this [video:](https://youtu.be/zPxyV6F3KAs?si=YvdJXxEoXlB6_1lc&t=4266)

currently not too sure what should happen, could it be a depency issue?(Boost C++ Libraries, DirectX SDK, zlib, bzip2, OpenGL Extension Wrangler Library installed wrongly?)

## Screenshots/Videos
[Screenshot 2024-06-28 191357](https://github.com/jpd002/Play-/assets/27233891/53b7f898-f821-4cae-8a1f-f9b30bfd6a5d)

**Comment by Konrad1374** [comment]
ok so apparently you need 2 sets of files. a .chd and a .zip with(in my chase:wangan midnight r) a .7d, .ic002, .ic002 files
put the .chd in a folder named wanganmr and have the .zip named the same. then put both in Documents/Play Data Files/arcaderoms.
then go inside the emu and doubleclick wangan midnight r

**Comment by jcstahl1** [comment]
the folder & file structure for 2x6 games is listed in the readme on the GitHub page.  this would have saved you from reporting a non existent issue.
