### ISSUE TITLE
I Pray And Hope Play! becomes the best PS2 Emulator For Android

### ISSUE THREAD

**Issue by aluassancylazou** [jpd002/Play-#1384]
## Quick summary
Please briefly describe what is not working correctly

## System Details
Describe the ambient being used to run Play!
Information needed:
- Operating system (including the version)
- Hardware (GPU and CPU, for android you can search for your device model here https://www.gsmarena.com/ for specifications)
- Version of Play!

## Issue Details
Describe in details the problem you had and the expected behavior

## Screenshots/Videos
Drag and drop (or link to) videos or images that could help us understand the problem

**Comment by jpd002** [comment]
Thanks for the good words. Closing this since there's no actual issue.
