### ISSUE TITLE
Play! ?

### ISSUE THREAD

**Issue by aluassancylazou** [jpd002/Play-#1386]
I want to ask will play! version 100,500,1000 will be where will reach it maximum full potential just asking cause the progress your doing your almost to your goals just keep doing what your doing it's working one day you'll be a champion and achiever like the legends Henrik Rygard Stenzek Tahlreth Trixarian <- (& his friends) your in the 0% 50% 100% right now

**Comment by jamesgalllla** [comment]
what are you talking about?

**Comment by jpd002** [comment]
Thanks for the encouragement, this is a project I work on on my free time, so, things can be slow.
