### ISSUE TITLE
Fails to build, missing headers

### ISSUE THREAD

**Issue by xiota** [jpd002/Play-#1387]
## Quick summary

git checkout 0626e113 fails to build because of missing headers.

Adding headers to files allows build to complete.

* `#include <cstring>` to `Source/iop/Iop_Usbd.cpp`
* `#include <algorithm>` to `Source/PadHandler.cpp`
* `#include <cstdio>` to `deps/Framework/tests/TestDefs.h`

## System Details

Arch Linux.  GCC 14.1.1

**Comment by jpd002** [comment]
Thanks for this, making the changes here: https://github.com/jpd002/Play-/commit/8435915c0132087bb719721feed10aea908b3ad3.

**Comment by xiota** [comment]
Do you plan to add this to `master`, or are you waiting for me to test?  I won't be able to try building for the next few hours.  If this is not planned for `master`, the maintainer of the AUR package would need to add a patch.

**Comment by jpd002** [comment]
Thanks for testing! I've merged it to `master`.
