### ISSUE TITLE
Tekken 4 audio plays too fast, causing distortion

### ISSUE THREAD

**Issue by andymage593** [jpd002/Play-#1392]
The audio in Tekken 4 plays too fast, causing distortion, and the opening cg can only be played briefly before quickly jumping to the LOGO state. Previous versions did not have this problem.
![tekken 4](https://github.com/user-attachments/assets/1d0b0c06-5e1a-4a7e-bdfb-247b4e37f96b)

**Comment by jpd002** [comment]
Thanks for the report. Could you try it with a previous version of the emulator (available here: https://purei.org/downloads/play/stable/)?

I tried it on my end with the latest version and the video plays correctly.

**Comment by andymage593** [comment]
Sorry I didn't make it clear, let me say it again, Tekken 4 has 2 problems:
1. The audio frequency is too high, the audio playback speed is too fast, and the pitch becomes higher.
2. The video playback can be played normally, but it will automatically jump when Heihachi Yamashima throws Kazuya Mishima off the cliff, instead of playing it completely.
The old version is too old, for example, ver 0.59

**Comment by andymage593** [comment]
![image](https://github.com/user-attachments/assets/5ef44343-1e63-48e0-a1e2-ed9ac704ad2d)
I deleted this parameter and it became normal.

**Comment by jpd002** [comment]
Oh yeah, that makes sense, Tekken 4 runs on Sys246. Thanks for posting the resolution here.
