### ISSUE TITLE
Taiko no Tatsujin 7 Unlimited Reading

### ISSUE THREAD

**Issue by andymage593** [jpd002/Play-#1394]
![taiko7](https://github.com/user-attachments/assets/34349b8a-fc06-4bd9-9d7a-482aa25d9a0a)
Unable to enter the game, the screen is frozen on this loading interface

**Comment by andymage593** [comment]
Update the simulator and it will run.
![image](https://github.com/user-attachments/assets/f2355d1a-e3f6-4ccb-ab28-045f4649226f)

**Comment by jpd002** [comment]
Should now be working, some functions were missing in ACCDVD. Thanks for confirming @andymage593 !
