### ISSUE TITLE
Dark Cloud [SCUS-97111] Does not boot

### ISSUE THREAD

**Issue by cyberkitsune** [jpd002/Play-#14]
Dark Cloud [SCUS-97111] sits at a black screen, 0 f/s, 0dc/f.

Dumped from original DVD, hash verified with known good on redump. (http://redump.org/disc/5435/)

**Comment by jpd002** [comment]
Got the game to boot:

![dc1](https://cloud.githubusercontent.com/assets/6760433/5851680/9caa6ff2-a1d8-11e4-9ca6-806ff2a55507.png)
![dc2](https://cloud.githubusercontent.com/assets/6760433/5851681/9fa0f96a-a1d8-11e4-9d0d-9dfeab72a4d8.png)
![dc3](https://cloud.githubusercontent.com/assets/6760433/5851682/a1ca88f0-a1d8-11e4-9261-e96f665d1a26.png)
![dc4](https://cloud.githubusercontent.com/assets/6760433/5851683/a364548e-a1d8-11e4-8820-de27c69c0488.png)

Game game seems to run ok now (doesn't crash or hang), but yeah, the visuals are a mess. I'm going to clean up what I've done to make the game boot and I'll push the changes ASAP.

**Comment by jpd002** [comment]
I've pushed the changes needed to make this game boot. There's still many things to fix, I might take a look soon.

**Comment by jpd002** [comment]
Closing this as game boots now. I will come back to this game later to fix the graphical glitches.
