### ISSUE TITLE
(Hosting request) Create a Radicle backup and mirror to protect your development

### ISSUE THREAD

**Issue by hardBSDk** [jpd002/Play-#1410]
[Radicle](https://radicle.xyz/) is a platform for peer-to-peer Git repositories, your repository works like a torrent where anyone can be a seeder of your code.

This will increase the download speed, add a backup and protect the project from GitHub problems.

**Comment by jpd002** [comment]
Interesting, thanks for letting us know about this. I don't think we're big enough for this to be useful to us though.
