### ISSUE TITLE
Mojibribbon not working

### ISSUE THREAD

**Issue by XSonic1** [jpd002/Play-#1418]
## Quick summary
If I click on the game its just a black screen

## System Details
Describe the ambient being used to run Play!
Information needed:
- iOS (16.1.1)
- Hardware
- iPhone 8

- Version of Play!
- 0.67

## Issue Details
When the game is being played, nothing is happening its just a black screen. No sound, no rendering no nothing.
![F75233A6-37BA-4F2D-8A5D-CF660685F992](https://github.com/user-attachments/assets/1db60ed8-55d8-4409-b889-043a7b1c0df2)

**Comment by jpd002** [comment]
Should work with the latest commit. Not sure to which extent it can be played though.
