### ISSUE TITLE
Budokai 3 doesn't boot due to missing MFIFO emulation

### ISSUE THREAD

**Issue by MoochMcGee** [jpd002/Play-#18]
It's just a laconic black screen. It tries to write to MFIFO, so there's a possible lead.

**Comment by jpd002** [comment]
I've bought the game and I'll see what's going on with it.

**Comment by MoochMcGee** [comment]
Never mind, I was being stupid and expecting Debug mode to be fast.

**Comment by jpd002** [comment]
Well, it still doesn't work though, it doesn't go past the logo screens. I got the game, but I still didn't get the chance to analyze the problem yet.

**Comment by MoochMcGee** [comment]
Prolly just needs a patch to skip the intro movie.
