### ISSUE TITLE
PLEASE CONTACT ME!!!

### ISSUE THREAD

**Issue by xKingTutx** [jpd002/Play-#19]
I could not find another way to leave a comment any where so I am using this posting to get oyur attention. Please contact me I am very interested in helping your cause here as the new tablets and phones can push a PS2 emulator now due to apps you can download to dedicate ram and CPU to boost the over all performance of what ever app you apply the settings too which would be this emulator. I help with planning and development of some other hard to find systems Bios (M.A.M.E.) and would love to speak to you my email is vxjamietuttlexv@gmail.com it goes straight to my phone so please contact me any time. I will supply my knowledge and my time to help get this built and working.

**Comment by mantlebreath** [comment]
Why don't you just fork the project and contribute and/or compile and test builds? 

Or wait for builds to test games, then report back results?

**Comment by jpd002** [comment]
@xKingTutx Thanks for your interest in the project.

The Android version is currently under development. It will take some time before it gets to a point where it can play games. Don't hesitate to clone the repo and build if you wish to contribute. Official Android builds will also be available soon for everyone to test (only with demos for a while).

If you've got any questions, please don't hesitate to ask.

**Comment by xKingTutx** [comment]
O wow didnt think i would get a response. I tore down a console and got
what i could out of it.  It may come in handy I will gladly clone it and
see what i can come up with also i will barrow some  code from the working
ps1 app and hopefully use that as a UI for thIs new one. .

**Comment by xKingTutx** [comment]
I will gladly help in any way.

**Comment by KinCoded** [comment]
The UI for the existing PS1 emulators are terrible, go for something similar to PPSSPP.

**Comment by xKingTutx** [comment]
Ahh ok, i was able too get some usable data from the console onboard memory
i was thinking of trying to find a way to get it to work with M.A.M.E.
since some versions of it its open source and well known that way we can
get at least a windows or linex version running then port it over to
android.
