### ISSUE TITLE
Could not find boost static library

### ISSUE THREAD

**Issue by openglhk** [jpd002/Play-#23]
how can i get the libboost.a?

**Comment by jpd002** [comment]
Oh yeah, thanks for the notice, I forgot to push my build script for boost on Android. Gonna do that ASAP.

**Comment by jpd002** [comment]
I've pushed the script I'm using to build boost on Android in my Dependencies repository (https://github.com/jpd002/Play-Dependencies). 

I've also made the changes to the makefile used to build the emulator on Android to reflect the new location of libboost.a. (Available in the android branch)

**Comment by openglhk** [comment]
Thanks, all compile success
