### ISSUE TITLE
Half Life stays on black screen on Motorola RAZR i x890.

### ISSUE THREAD

**Issue by Abz1** [jpd002/Play-#239]
Half life only stays on black screen. Also the frame jumped alot. sometimes i got 2 and 6. however, sometimes i got 21 and 24fps.

**Comment by jpd002** [comment]
Thanks for the report. Is this the phone you're trying to run the game on? http://www.gsmarena.com/motorola_razr_i_xt890-4998.php

**Comment by Abz1** [comment]
@jpd002 yes, that's the one.

**Comment by jpd002** [comment]
Humm, are you able to play other games on that phone? It says it has an PowerVR SGX540 which doesn't seem to support GLES 3.0.

**Comment by Abz1** [comment]
@jpd002 So far, I haven't had any luck, because the ps2 isos are massive. I'm going try one of the working games on the compatibility list and then I'll let you know.

**Comment by jpd002** [comment]
I've made a fix for the black screen problem on Adreno: fb141c71148f2b667be5405236d7aa47a4c79a9f. It's also in today's weekly build. Maybe this fixed your issue.

**Comment by atomic83GitHub** [comment]
This game now work great.

**Comment by atomic83GitHub** [comment]
@jpd002, this can be close, the game work in Play!
