### ISSUE TITLE
android: chaos wars 

### ISSUE THREAD

**Issue by johnlast** [jpd002/Play-#242]
Hello. I just tried to load chaos wars on a 4.4.2 android tablet adreno. The ft bounced around from 6 to 20 for a while then stayed at about 6. The DC stayed at 0. All that showed was a black screen. I waited about a half hour and still black screen. The good news is it loaded the correct box art! Thanks for all your hard work. Oh I also like the new updated look very sleek!

**Comment by literalmente-game** [comment]
Could test the game again and add the results in a new issue here https://github.com/jpd002/Play-Compatibility/issues ? After creating a new issue there, you can close this one here (it's better to have all the game compatibility information in the same place :smiley: )

**Comment by johnlast** [comment]
Will do. It's been a while since I checked on this project. Very exited!

**Comment by literalmente-game** [comment]
This issue can be closed, I've opened an updated entry on the new tracker (https://github.com/jpd002/Play-Compatibility/issues/700)

**Comment by jpd002** [comment]
Thanks!
