### ISSUE TITLE
S6 Edge

### ISSUE THREAD

**Issue by Badwolf0301** [jpd002/Play-#245]
I have Play up and running on my Samsung Galaxy S6 Edge I have tried a couple games now, two out of three of them loaded no problem beside a very low frame rate, so therefore it was hard to play they at all. However both games I did get up and running had absolutely no sound. I'll test some more and see if it is a continuing problem.

**Comment by Thunder07** [comment]
sound has either not been implemented or enabled yet.

**Comment by Badwolf0301** [comment]
Gotcha thanks for letting me know. I also have a Nvidia Shield Tablet I'll do some testing on too.

**Comment by jpd002** [comment]
@Badwolf0301 Thanks for your report. As @Thunder07 said, sound is not supported on Android. It is emulated, but not outputted.

**Comment by Badwolf0301** [comment]
Thanks for letting me know I was hoping it was just because it's still early and not a problem with my devices. Thank you again for letting me know.

**Comment by jpd002** [comment]
Closing this as this is not a problem specific with that device (all games run quite slow on all devices).
