### ISSUE TITLE
(Windows) SpinDrive Ping Pong : Loadable with FPS, but shows nothing

### ISSUE THREAD

**Issue by n1dminhd** [jpd002/Play-#247]
Play! 22-07-2015 Windows 7 64bit

![untitled](https://cloud.githubusercontent.com/assets/4449742/8829983/ea9ec10c-30c3-11e5-8209-8aacdf03c003.jpg)

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/523. This issue can be closed
