### ISSUE TITLE
(Windows) Shaman King - Power of Spirit : Loadable with FPS, but shows nothing

### ISSUE THREAD

**Issue by n1dminhd** [jpd002/Play-#248]
Play! 22-07-2015 Windows 7 64bit

![untitled 2](https://cloud.githubusercontent.com/assets/4449742/8830312/c658a220-30c5-11e5-9f67-0c9680271982.jpg)

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/524. This issue can be closed
