### ISSUE TITLE
(Windows) Superman Returns : Loadable with FPS, but shows nothing

### ISSUE THREAD

**Issue by n1dminhd** [jpd002/Play-#249]
Play! 22-07-2015 Windows 7 64bit

![untitled 3](https://cloud.githubusercontent.com/assets/4449742/8830380/23b4ecb2-30c6-11e5-89d5-0c0cf7fb680c.jpg)

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/525. This issue can be closed
