### ISSUE TITLE
(Windows) Naruto - Uzumaki Chronicles : Loadable with FPS, but shows nothing

### ISSUE THREAD

**Issue by n1dminhd** [jpd002/Play-#251]
Play! 22-07-2015 Windows 7 64bit

![untitled 6](https://cloud.githubusercontent.com/assets/4449742/8830743/252ce372-30c8-11e5-80b9-255e6a68e111.jpg)

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/526. This issue can be closed
