### ISSUE TITLE
(Windows) God Hand : Loadable with FPS, but shows nothing

### ISSUE THREAD

**Issue by n1dminhd** [jpd002/Play-#253]
Play! 22-07-2015 Windows 7 64bit

![untitled 7](https://cloud.githubusercontent.com/assets/4449742/8830839/b26c3026-30c8-11e5-86d4-aef944a1d63f.jpg)

**Comment by jpd002** [comment]
Thanks for the report. I will take a look when I get the chance.

**Comment by atomic83GitHub** [comment]
Any status?

**Comment by jpd002** [comment]
Oh yeah, that's an old one, no idea if it's any better today.

**Comment by atomic83GitHub** [comment]
There is a compat report for that, this can be close.

**Comment by jpd002** [comment]
Yup: https://github.com/jpd002/Play-Compatibility/issues/247.
