### ISSUE TITLE
Metal Gear Solid 2: Sons of Liberty wont boot because of VU issues

### ISSUE THREAD

**Issue by dogmahola** [jpd002/Play-#258]
I came across a user on reddit who said this game can work if they hacked the VU units and bypass issues, but they would not give a build. I was wondering if any dev here can get the game (4 bucks on ebay) and try and commit the fixes/hacks to master so it can be included in the weekly builds? thanks!

EDIT they did not mention the issues, but I am at least just trying to help you with what they said to work.

**Comment by jpd002** [comment]
Thanks for the information. Do you have any link that shows the user saying that he fixed the game?

**Comment by dogmahola2** [comment]
Sorry I forgot where it was and I don't have the link.

**Comment by drainbeam** [comment]
Could this be the issue?

![unknown](https://cloud.githubusercontent.com/assets/13511479/8900030/cc07069a-342a-11e5-8b4a-6720f7d38981.jpg)

The Emotion Engine debugger & disassembly doesn't seem to know what opcode is located there.

I don't use Visual Studio and I am unsure of any ways to look further into it, but I do have the game.

**Comment by jpd002** [comment]
The stuff there is normally the kernel's information. That value is quite weird though as it would most likely make the emulator crash since it's supposed to contain the id of the head of the DMAC handler list (which are supposed to go from 1 to 128).

**Comment by drainbeam** [comment]
Hm ... doesn't crash; instead, sits on a black screen. Nothing seems to be amiss with the VUs as the OP is stating, but that one area might be a hot zone as to why the game is not showing anything.

The exact assembly code for that instruction should be: LQ K0, 18268 (0x47 + 0x5C). I have no idea how the DMAC works on PS2, so I'd really have to read up more on the subject to understand more.

**Comment by titantears** [comment]
I updated the roadmap and included known issues that haven't been added yet:

https://github.com/jpd002/Play-/wiki/Development-Roadmap

Feel free to correct any mistakes (I am not that technical with PS2).

I had no idea where else to put this, so I put it here.

**Comment by LoungeKatt** [comment]
That's probably something to request. It may be different here, but most projects that have a development roadmap use it for the developer to keep others informed about their progress and plans. It may get confusing if everyone starts changing it.

**Comment by jpd002** [comment]
@titantears Thanks for taking time to add information to that page. I've made some changes to what you've written to make it more precise. As @LoungeKatt said, it would be better to request information to be added there.

**Comment by WhitePeopleH8er** [comment]
(I'm the one who OP is talking about)

This is what it gets to (with hacks) but it breaks many other games (input also not working either):

![mgs2playss1](https://cloud.githubusercontent.com/assets/13713140/9241002/fa81570c-415c-11e5-8254-7f2667cb2ae2.jpg)
![mgs2playss2](https://cloud.githubusercontent.com/assets/13713140/9241004/fbea5c1a-415c-11e5-8770-3108df7bb86f.jpg)

Can't be played and moves much slower than what the FPS is showing

I'll explain how I got it working when I get the chance

**Comment by jpd002** [comment]
@WhitePeopleH8er Nice work! I'm pretty sure we can make the hacks cleaner so it doesn't break other games.

**Comment by johnnyleap** [comment]
I've checked it on the debugger and it seems the issue is with IOP threading/wait states.

EE ends with a conditional branch, and the IOP stays stuck at a wait_vblankend thread or with ADDIU.

As for the VUs, none of them show any working code or issues (other than NOP or a load instruction).

**Comment by reinventedz** [comment]
This is some guesswork, but I think I maybe narrowed down the issue:

Everything seems fine until the game continuously keeps repeating the same thing with the IOP and executes a KCEJ (Konami Computer Entertainment Japan) module for SIF and the DVD handler and this seems to keep looping and something isn't done correctly somewhere between setting a DMA buffer & repeated jumps and an action never seems to finish. Also, the FPS shows this as when the game is loaded the FPS constantly stays at the same range or quickly jumps 1 frame up and down as if something is halted/frozen. My guess: something is going wrong with the SIF/IOP DMA or similar.

**Comment by jpd002** [comment]
Yeah, it's most likely an issue with IOP HLE. I've done some improvements and I'm working on some more improvements that I hope will help many games to get to their title screens.

**Comment by jpd002** [comment]
MGS2 boots in the current build (2016-01-24). Main issue was a missing function in MCSERV HLE emulation. The game isn't playable yet though, I think it's due to an audio emulation issue.

![mgs2_01](https://cloud.githubusercontent.com/assets/6760433/12542041/1e70a04e-c2ec-11e5-8714-58d162dd9ff8.jpg)
