### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by xiushudongfang** [jpd002/Play-#26]
How to build for android? I try to run \build_android\build_release.sh.But missing android.bat.
![default](https://cloud.githubusercontent.com/assets/8541580/6724421/98e87b26-ce32-11e4-972b-7fa128b3157e.jpg)

**Comment by jpd002** [comment]
The build scripts rely on two environment variables:
ANDROID_NDK_ROOT -> Points to the NDK's path (ie.: C:\Android\android-ndk-r10d)
ANDROID_SDK_ROOT -> Points to the SDK's path (ie.: C:\Android\android-sdk)

Hope that helps.

**Comment by xiushudongfang** [comment]
@jpd002 thanks,could  I use cygwin in win8.1 to build?

**Comment by xiushudongfang** [comment]
![qq 20150319134537](https://cloud.githubusercontent.com/assets/8541580/6725064/3f952932-ce3e-11e4-944b-f84c7ecd78c8.png)

**Comment by openglhk** [comment]
i think you should EXPORT some path and edit ExternalDependencies.mk.template first

**Comment by xiushudongfang** [comment]
@openglhk  I have no idea about this.

**Comment by openglhk** [comment]
For example:

export ANDROID_SDK_ROOT=/home/user/Downloads/android-sdk-linux
export ANDROID_NDK_ROOT=/home/user/Downloads/android-ndk-r10d
export ANT_HOME=/home/user/Downloads/apache-ant-1.9.4

**Comment by xiushudongfang** [comment]
@openglhk how to config ExternalDependencies.mk.template ?

**Comment by openglhk** [comment]
rename ExternalDependencies.mk.template to ExternalDependencies.mk
and edit as below

BOOST_PATH              := /home/user/Downloads/boost_1_55_0
FRAMEWORK_PATH          := /home/user/Downloads/Framework-master
CODEGEN_PATH            := /home/user/Downloads/CodeGen-master
DEPENDENCIES_PATH       := /home/user/Downloads/Dependencies-master

**Comment by xiushudongfang** [comment]
@openglhk  where can  I get Framework-master,CodeGen-master and Dependencies-master ?  Thanks.

**Comment by jpd002** [comment]
I've added the info for dependencies in the README file:
https://github.com/jpd002/Play-/tree/android#repositories

**Comment by xiushudongfang** [comment]
@jpd002  Thanks a lot .

**Comment by xiushudongfang** [comment]
All works have been done.But it crashed when I launch the app.

![134201](https://cloud.githubusercontent.com/assets/8541580/6746658/47752d2c-cf07-11e4-8ec9-00c03ae14655.png)

![0320134217](https://cloud.githubusercontent.com/assets/8541580/6746656/3fd5b1ae-cf07-11e4-8ed9-56da0a0e14eb.png)

**Comment by xiushudongfang** [comment]
device : note 2 (Samsung N7100)
demo : demo2b.elf
result : black screen

**Comment by xiushudongfang** [comment]
![image](https://cloud.githubusercontent.com/assets/8541580/6747058/88ac742e-cf0e-11e4-9acf-3d7507229009.png)

**Comment by jpd002** [comment]
Awesome! Thanks for the feedback! I'll try to get my hand on another Android device to see what I do wrong.

**Comment by jpd002** [comment]
Closing this issue for now as the initial as been answered. I'll be posting status updates on the first Android port issue (#7).
