### ISSUE TITLE
Save Game Cover To Device

### ISSUE THREAD

**Issue by adriandennis17** [jpd002/Play-#261]
it seems with each launch of Play! it downloads the game cover
wouldn't it be more efficient, when a cover is downloaded its save
to the device..and is in a way sync to the game..so the game will use
the cover on the device instead of downloading again..and if the game
should be deleted the cover will automatically be deleted.

**Comment by Thunder07** [comment]
That's already been covered.

**Comment by adriandennis17** [comment]
oh..so does it also saves the game info ?

**Comment by Thunder07** [comment]
Yes

**Comment by adriandennis17** [comment]
just tested it..doesn't seem to save the info..

**Comment by LoungeKatt** [comment]
Just tested what? Make sure to make a clean build from the current source, otherwise it won't save the info because the feature wasn't integrated yet.

**Comment by adriandennis17** [comment]
I'm talking the info about the game's you might have..if your connected to the net..you can get the info about the game..but if you offline it doesn't show.

**Comment by LoungeKatt** [comment]
What is it with everyone explaining the obvious part of the statement, lol. What did you test? Was it the weekly build, a recent compile, or your toaster oven?

**Comment by Thunder07** [comment]
@adriandennis17 I said if weekly is out..

**Comment by adriandennis17** [comment]
@loungeKatt...😓

What i test: Game info..if you should highlight a game you will see the info about the game..it should also be available offline as @Thunder07 pointed out..but it's not showing while offline..

Build Tested On: 07/26/2015

**Comment by Thunder07** [comment]
I'm guessing you switched of your net to test that?

**Comment by adriandennis17** [comment]
@Thunder07 yes the game cover are now fetching from device..but game info is not available offline..

**Comment by adriandennis17** [comment]
yes..i switch wifi off..that's how i knew the game cover where fetching from my device.

**Comment by Thunder07** [comment]
Hehe your right, description is not showing, although it's being saved, I forgot to actually load it or something. 

@LoungeKatt commit probably already dealt with that?

**Comment by adriandennis17** [comment]
also for .elf demos

when i highlight it to get info, it crashes the app

for .elf why not use one cover for .elf (i made one if you want 😆)

and since there's no database for getting an elf file info and there's no way of reading the info from the file...just give one info for elfs..stating what a elf is... game or app homebrew etc

**Comment by LinkofHyrule89** [comment]
I'm sure this is covered but if it doesn't have info pulled it crashes. Small suggestion eventually there needs to be something that tells people long holding on a game will bring up the info. I didn't even know this function existed. Second suggestion would be whenever the Android TV UI is made you could probably just have it display the info when the game is selected instead of a long hold. Anyways that's awesome it shows the info now keep up the good work.

**Comment by jpd002** [comment]
I've updated the weekly build to include @LoungeKatt's changes which improves many thing with the file picker interface: http://purei.org/downloads/play/weekly/Play-20150726.apk

**Comment by adriandennis17** [comment]
@jpd002 i just tested that build from the link you post..

but it crashes if you try to launch while offline..

and if you should connect to the net and launch it works and while in the app disconnect from the net everything works but closing the app and then opening it again it crashes again.

**Comment by LoungeKatt** [comment]
https://github.com/jpd002/Play-/pull/262

**Comment by jpd002** [comment]
Will be in Sunday's weekly build (2015-02-08).

**Comment by adriandennis17** [comment]
Okay, will close issue.
