### ISSUE TITLE
Play! crashes when i click on game.

### ISSUE THREAD

**Issue by ghost** [jpd002/Play-#263]
When i open a game on Play!, it crashes. furthermore, when i click on clear cache it crashes again. this did not happen before.

**Comment by adriandennis17** [comment]
what's your device 

also did you force stop and then try to clear cache and data

**Comment by Abz1** [comment]
@adriandennis17 yeah, i tried that, but it still crashed. Also my device is Motorola RAZR I x890 and it worked normal before the latest update.

**Comment by LinkofHyrule89** [comment]
It's an x86 device I really wonder why some of them seem to work ok and others it's just crashing. @Abz1 can you get a log using ADB Logcat?

**Comment by LoungeKatt** [comment]
If all goes well, I will try to have my logger tool in a pull request. That will at least pull only the relevant logs into a single file. It should make it much easier to track down where the crash happens.

**Comment by LinkofHyrule89** [comment]
@LoungeKatt good idea that will probably be helpful hopefully we can figure out why some x86 devices work and others don't.

**Comment by Abz1** [comment]
@LinkofHyrule89 ok ill try to download ADB logcat from the playstore.

**Comment by LinkofHyrule89** [comment]
@Abz1 you can also use the Android SDK to do it as well I think that the logcat app requires root but I haven't used it for a while.

**Comment by Abz1** [comment]
I finally fixed the problem. It was a problem on my behalf. The reason why the app crashed and no cover art loaded was because my internet was offline. When the internet was online it never crashed!

**Comment by LinkofHyrule89** [comment]
@Abz1 well that's good to hear but still doesn't fix our other problem :( The problem you explain should be fixed in the next built.

**Comment by acocalypso** [comment]
I do have the same problem on my one plus one.

**Comment by LinkofHyrule89** [comment]
I've not had any problems with the app on my OnePlus One however I also never turn off the internet on my phone. But as far as I know that bug has been fixed and should be in the next build anyways.

**Comment by literalmente-game** [comment]
Could you test again with the latest builds? I'm pretty sure this issue isn't valid anymore and can be closed

**Comment by jpd002** [comment]
Going to close for now since it's pretty scarce on details. Feel free to reopen if you've still got the issue.
