### ISSUE TITLE
Touch Control (fit to screen)

### ISSUE THREAD

**Issue by adriandennis17** [jpd002/Play-#265]
It seems the control doesn't fit to screen or detects the device screen size and adjust the onscreen controls to give it the right fit and space..from the few small device's (4.5 inch) i see posting screenshots the controls appear squinged..

**Comment by orenrocco** [comment]
The controls are designed with OpenGL, but I will take a look at it

**Comment by LoungeKatt** [comment]
@orenrocco They're in the build_android/res/drawable folder. They aren't designed with OpenGL. @adriandennis17 just forgot to mention that this was about the Android build.

**Comment by Thunder07** [comment]
not really. the controls a displayed using standard android [resources](https://github.com/jpd002/Play-/blob/master/Source/ui_android/java/com/virtualapplications/play/EmulatorActivity.java#L49)
it's probably just a limiation of [BitmapFactory.decodeResource](https://github.com/jpd002/Play-/blob/master/Source/ui_android/java/com/virtualapplications/play/VirtualPadView.java#L14) and obviously the feedback is relied through native code

**Comment by LoungeKatt** [comment]
They aren't scaled. It's not a limitation, just not implemented.

**Comment by Thunder07** [comment]
@LoungeKatt there shouldn't be any need, android does most of this for it's resources automatically based on screen size and density.
as i said moving the images from drawable to drawable-xxhdpi or even  drawable-xhdpi should cause them to scale up/down based on whether that device is considered smaller or larger in density (compared to the folder it's in).

**Comment by orenrocco** [comment]
@LoungeKatt alright

**Comment by LoungeKatt** [comment]
The folders will work for an ImageView, yes. This is done by drawing the bitmap to a canvas. I posted the source above. You can see for yourself that they are semi-hardcoded sizes.

**Comment by adriandennis17** [comment]
![tmp_14142-qhd-ad171609522824](https://cloud.githubusercontent.com/assets/4733568/8995078/dd9b7736-36d4-11e5-885d-940d95977d33.jpg)
4inch (540x960)

![tmp_14142-hd-ad17-1161261633](https://cloud.githubusercontent.com/assets/4733568/8995084/e6a80178-36d4-11e5-9821-7c267b065058.png)
4.7inch (1280×720)

![tmp_14142-1080p-ad17545599133](https://cloud.githubusercontent.com/assets/4733568/8995100/f7791cee-36d4-11e5-989a-b2e11d161815.png)
5inch (1080x1920)

![tmp_14142-q hd-ad171229675111](https://cloud.githubusercontent.com/assets/4733568/8995104/015a904e-36d5-11e5-88fb-0ae047e44f14.png)
5.5inch (2560x1920)

above is a few pics of Play! on different size display,

**Comment by LoungeKatt** [comment]
@adriandennis17 The description was clear, it just wasn't tagged "Android"

**Comment by orenrocco** [comment]
Okay I will take a look at it tonight

**Comment by jpd002** [comment]
@adriandennis17 Thanks for showing us what it looks like on different screen resolutions!

**Comment by orenrocco** [comment]
+jpd002 I will send you part of my patch although I am not finished can you please finish it up. I am not able to because I am not feeling very good.

**Comment by Thunder07** [comment]
@orenrocco no one expect you to get things done in a day (except for me :p),
so you can take your time, if you don't feel like being able to get it done at all, you can send a pull request prefixing the title with something like "INCOMPLETE" or something of such sort, and maybe when any of us have time we'll look at it.

**Comment by adriandennis17** [comment]
@orenrocco no rush to get it done as @Thunder07 stated..
get well soon 👍

**Comment by annahana** [comment]
of the topick, is it possible to activat touch on windows tablets on the desktop version?

**Comment by adriandennis17** [comment]
@annahana you have a windows tablet..and theirs no touch control on the screen
and you want to know how to have it enabled, is that what your saying ??

**Comment by annahana** [comment]
yes surface pro 2 i5 4300u

**Comment by jpd002** [comment]
Initial issue is fixed here: 45a133ec3a0294864216d443402d454049082458 Will be in next weekly build.

@annahana Not possible to use touch screen controls on Windows at the moment, sorry.
