### ISSUE TITLE
opengl es2.0 rendering

### ISSUE THREAD

**Issue by dona12345** [jpd002/Play-#269]
i have a note 2 so no opengl 3.0 ,is possible to render ps2 games in opengl es 2.0 like ppsspp?

**Comment by LoungeKatt** [comment]
PPSSPP requires a lot less "power" to run, so that isn't really a fair comparison. Play! is better compared to Dolphin, which also requires 3.0

**Comment by jpd002** [comment]
While not impossible, I'm not planning on adding support for GLES 2.0. The emulator is already too slow to be playable on current generation devices, so, I don't think it would be worthwhile to write code to support older devices so they can play games with bad frame rates.
