### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by AbandonedCart** [jpd002/Play-#271]
It would probably be a good idea to convert all the hard-coded text throughout the app into resources. This way it would support translations. Are there any plans to translate?

One way to go about it is opening up the translations to contributors. There is always someone out there that can take a bunch of English hoopla and translate it into another language. There is also the option to use Google translate as a base and then suggest corrections are submitted.

**Comment by orenrocco** [comment]
+LoungeKatt yea or http://stackoverflow.com/questions/1649676/open-source-language-translation-engine we could use https://lwn.net/Articles/472041/

**Comment by jpd002** [comment]
I didn't have plans to do translation in a close future, but I think it would be nice. I think letting people do the translation would be a better idea. IMO, using automatic translation is not good if you want quality. 

I think extracting the hard-coded strings into resources would be a good first step. Then, we could write a small guide that explains how people can submit translations.

**Comment by Thunder07** [comment]
no harm really, if only for future proof.

**Comment by adriandennis17** [comment]
option to use Google translate as a base and then suggest corrections are submitted. that seems like a good option to me..

**Comment by LoungeKatt** [comment]
For Reicast, we made a bunch of templates using Translate and then let people submit pulls with the fixes or edit the files and submit them to the server to be integrated in a pull by someone on the team. The automated versions were never meant to ship, but they did provide that extra little push for someone to get it done, if for no other reason than to point out where it was wrong.

**Comment by adriandennis17** [comment]
that can also work...
