### ISSUE TITLE
MARK FOR DELETION

### ISSUE THREAD

**Issue by orenrocco** [jpd002/Play-#272]
The ps2 had a developer choice of any mb video ram out of its 32 mb ram system,which  is connect to the GS(Graphic synthesizer )and at runs 150 MHZ and the bus is 128-bit wide. Furthermore, lets say most games use 4mb of video ram then if you do the math you will see that it is in theory capable of transferring about 76 MB pr. frame at 30 frames/sec, which over twice the size of the EE memory. However, this is possible emulatable with the ddr3 ram on android, so I believe we should take this into consideration for development.

**Comment by adriandennis17** [comment]
why not, the more settings the better, 
this could be a speedhack that can be enabled or disabled.

**Comment by MoochMcGee** [comment]
This would just make the emulator more inaccurate. Bad idea all around.

**Comment by orenrocco** [comment]
+MoochMcGeee so you disagree with my idea of virtual vram

**Comment by Thunder07** [comment]
@orenrocco I'd say he disagrees for now, as far as i know and believe @MoochMcGee and @jpd002 probably would like to have accurate emulation 1st before forcing games to run due to pure brutal-force specs.

**Comment by orenrocco** [comment]
@Thunder07 yea now that I thought about it would be inaccurate to employ virtual vram as @MoochMcGee said

**Comment by MoochMcGee** [comment]
Actually, @Thunder07, I think this is a bad idea period. Inaccuracy is
inaccuracy, after all.

**Comment by drainbeam** [comment]
I didn't know that Play! was going for much accuracy in the first place (being a high-level emulator).

Having games (even all of them) run on it doesn't necessarily imply accuracy either.

From my work on emulation development, accuracy can mean many different things:

1.Cycle accuracy; making sure that each instruction simulates the right amount of CPU time as on the emulated system (and reflects that on the host system too) and goes through all the right steps therein.

2.Opcode accuracy; making sure that each instruction is emulated identically to how it would be (or as close as possible) of the emulated system's architecture (correct registers, flags, modes, etc.).

3.Internal design accuracy; making sure that the code and emulator itself mimics the procedural design and architectural setup of the system it is mimicking (such as with intercommunicating hardware, etc.). An example of this would accurately replicating the internal system that reflects a proper architectural markup between how all of the hardware devices communicate with each other, and having the code flow work the same way as well (for example, EE->DMA; GIF->GS; EE->RAM; IOP->RAM; etc.). No matter how you shape it, a JIT/dynamic recompiler will never correctly simulate Von Neuman design/models.

But back on topic of this post, I don't really understand what the intended goal/purpose is of this anyhow.

**Comment by MoochMcGee** [comment]
"From my work on emulation development"
Your profile has no code contributed and no repositories.

"a JIT/dynamic recompiler will never correctly simulate Von Neuman design/models"
MAME has JITs and it's got internal design accuracy.

**Comment by orenrocco** [comment]
@MoochMcGee @drainbeam We are missing the point here while arguing we are trying to improve overall fluidity

**Comment by orenrocco** [comment]
http://arstechnica.com/features/2000/04/ps2vspc/4/

**Comment by MoochMcGee** [comment]
No, we aren't. Increasing VRAM won't increase fluidity at all. It'll just
introduce more inaccuracies to the emulator.

**Comment by orenrocco** [comment]
@MoochMcGee I don't want to increase it I just want to emulate it's connection to the data bus as seen in the Playstation 2 architecture

**Comment by MoochMcGee** [comment]
I don't know where you got that from, because the VRAM isn't in the PS2's memory map.

**Comment by MoochMcGee** [comment]
Anyway, I have come to the conclusion that you don't know what you're talking about.

**Comment by orenrocco** [comment]
@MoochMcGee So your saying that Playstation2 has no video ram

**Comment by jpd002** [comment]
@orenrocco The PS2's video ram is not directly accessible by the main CPU. Every access has to go through the GIF.

**Comment by orenrocco** [comment]
@jpd002 oh

**Comment by orenrocco** [comment]
@jpd002 I need to look at the architecture closer before I say things

**Comment by jpd002** [comment]
@orenrocco Well it's always good to bounce ideas, so no problems :smile:
