### ISSUE TITLE
Resident Evil 4 crashes after couple secs

### ISSUE THREAD

**Issue by NickKader** [jpd002/Play-#273]
http://loungekatt.no-ip.biz:3194/Playstation/report/logs/1438497274743.txt

**Comment by LoungeKatt** [comment]
It looks like the crash is
F/libc    (15585): Fatal signal 6 (SIGABRT), code -6 in tid 15630 (plications.play)
but I can't say that log actually captures everything. The tags were sort of thrown together.

**Comment by jpd002** [comment]
I'll give the game a try once I fix that issue I've been working on for the past week.

**Comment by NickKader** [comment]
Take you time I can't complain since I don't know how to code.

**Comment by Fadi5555** [comment]
Some of games have same situation so I if this fix could effect on that games which crashing it'll be good
Because some games which I have tested it has same situation.

**Comment by jpd002** [comment]
@NickKader Crash seems to happen because of a problem with IOP module version detection. I've tried hard coding the module version, but the game doesn't really go any further even if it doesn't crash.

**Comment by NickKader** [comment]
That's progress though good job.

**Comment by jpd002** [comment]
Finally got the game to work. Still haven't merged the changes, but I will do that soon.

![re4_1](https://cloud.githubusercontent.com/assets/6760433/10874038/6c83d15e-80eb-11e5-9aeb-10b72a652f60.jpg)
![re4_2](https://cloud.githubusercontent.com/assets/6760433/10874037/6c839112-80eb-11e5-8592-e7c1018f6733.jpg)
![re4_3](https://cloud.githubusercontent.com/assets/6760433/10874036/6c813598-80eb-11e5-8806-1df4e4eee862.jpg)
![re4_4](https://cloud.githubusercontent.com/assets/6760433/10874046/891a34b6-80eb-11e5-98d3-28a4356cbafb.jpg)

**Comment by NickKader** [comment]
Awesome

**Comment by Fadi5555** [comment]
That's amazing indeed.
I hope this fix effects on all games that have a black screen or crash.

**Comment by jpd002** [comment]
This was fixed in yesterday's weekly build (2015/11/08), closing.
