### ISSUE TITLE
Screen Rotation (Bug)

### ISSUE THREAD

**Issue by adriandennis17** [jpd002/Play-#277]
If you start Play! in landscape mode...you have to exit and start it again if you want to view
your games in Portrait mode..it seems like it locks whatever view mode it was launch in.

Tested on Build: 8/2/2015

![tmp_10247-screenshot_2015-08-02-22-55-21990140517](https://cloud.githubusercontent.com/assets/4733568/9030624/b94534f6-396a-11e5-991b-26c9d6e8c232.png)
Landscape

![tmp_10247-screenshot_2015-08-02-22-55-03288011239](https://cloud.githubusercontent.com/assets/4733568/9030632/c3189dba-396a-11e5-85ac-206e359d9474.png)
Portrait

**Comment by Thunder07** [comment]
Not a bug, was done to avoid few issues.

**Comment by jpd002** [comment]
Yeah, it was done to avoid issues, but I think we should make it work at some point.

**Comment by adriandennis17** [comment]
oh..k..will close this post..

**Comment by LoungeKatt** [comment]
@jpd002 https://github.com/jpd002/Play-/pull/275

**Comment by adriandennis17** [comment]
@LoungeKatt 👍👍
