### ISSUE TITLE
Apps (Homebrew) 

### ISSUE THREAD

**Issue by adriandennis17** [jpd002/Play-#279]
![2015-08-03 09 27 51](https://cloud.githubusercontent.com/assets/4733568/9053941/5435145a-3a41-11e5-840f-efcd145beb7d.png)

Instead of "Favorites" why not use "Apps" and have that section only show. elf files.
Mixing Games and homebrew apps together doesn't look right to me...
And since theirs no way of getting a cover for these apps why not just have them viewable as a list instead of using the default Play! cover,

"Everything" couldn't it be labeled "Games"..since only games gonna be in that section

**Comment by Thunder07** [comment]
Well as it stands this list holds no function, so that's possible... 
But id imagine the homebrew subset is very small it would make no practical sense... Especially since most homebrew are apps that served a function for the ps2, such as Explorer, cheat engine etc... Which I don't expect you to actually have on an emulator. 
With that said, I won't dismiss this suggestion.

**Comment by adriandennis17** [comment]
@Thunder07 by app homebrew I'm talking about games...i wouldn't use Play! to run say a emulator to play a game..if you get what i mean.

**Comment by Thunder07** [comment]
@adriandennis17 yes, which is exactly why I used 'most' to describe them.
then again, i might be wrong even at that, due to bias selection from my side (aka, i only used app homebrew in the day)

**Comment by adriandennis17** [comment]
well I've done quite the search and found a large number of homebrew games..
and since Play! supports .elf files and theirs a few here http://purei.org/downloads/ps2demos/
instead of mixing them with normal ps2 games..their's a section just for .elf files..

**Comment by LoungeKatt** [comment]
@adriandennis17 I think that would be a good menu item, since the "Everything" item sounds more like "Placeholder"

Selecting favorites can just as easily be undone by selecting recent without needing a whole button.

**Comment by adriandennis17** [comment]
@LoungeKatt Great..and Play! could also start from the "recent" screen and if we want to view all
the games in the folder simply select "Games" a minimal file browser could also be place in that
section..i know it searches game automatically..but a file explorer is needed.

**Comment by LoungeKatt** [comment]
@adriandennis17 Adding a homebrew sorting option is one thing, but a file browser is going backwards. It isn't needed if you keep it all in one directory. Even if all you have is elf files, it has been adjusted that they will show up as valid selections.

**Comment by adriandennis17** [comment]
hmmm...oh i get what you mean...the search is slow the first time..so much so i wish there was an option
to skip the search and just select the folder where my games are stored..

but I don't want to confuse anyone..

**Comment by Thunder07** [comment]
Can't recall if this was implemented if not I probably will do it, 
But a database of your current games/elf is made,
So that all your games will always appear in the app even when if in different folder, basically completely removing the need for a browser, since you'll have access to all your games at all time, obviously when need games are added you'd need to refresh and such.

**Comment by adriandennis17** [comment]
@Thunder07 ok.

**Comment by adriandennis17** [comment]
..

**Comment by LoungeKatt** [comment]
It currently shows the games in the same folder. 

Adding games to a database from other folders would require either selecting them from a file browser, searching all of storage every launch, or entering the path manually. At best it would only automate removing games that are no longer present.

I have a feeling the idea is based on the outcome without considering the performance or convenience costs.

**Comment by Thunder07** [comment]
No need to search every launch, that'll only need to be done 1st time, then the user would need to refresh the list when they add new games. 

There are alot if ways to do it, this is only 1.

I havent really worked the exact logistics that I'd like to use, but I'm currently considering a hybrid, that either allows you to manually add folder/they're automatically add (the folder) of which to search with a global option for a full scan every time.

**Comment by adriandennis17** [comment]
@LoungeKatt i get what your saying if its gonna affect performance i wouldn't suggest it...but it would be convenient..just saying...

@Thunder07 it could be added in the settings.. to change game folder location..and what about adding other folders..say folder 1 and folder 2..and games from 1 and 2 would appear as one in the game section..also this way you can have game on your internal and sd card..your choice..a refresh button could also be place beside the folder to have it rescan the folder for new games..instead of doing a full scan every time..

**Comment by Thunder07** [comment]
@adriandennis17, isn't that what I said in my 2nd paragraph :p

**Comment by LoungeKatt** [comment]
Performance is not a measure of CPU alone. It is also a measure of the time it takes the user to navigate from point A to point B. A process which, by adding all of the extra steps to build their "hybrid" list, is now considerably longer.

The point I am making and have been trying to make all along is this is an emulator. It is not CLZ Games. It doesn't need to have a UI that is so complex it takes more to run than the emulator itself. The ideas are novelty, but not practical. You have the entire UI running in the background right now when the emulator itself is launched. That should be priority 1.

It's not that the ideas aren't good, they just overwhelm the process. It already takes too long to play a game, so what user is going to want to be able to put files all over the SDcard like confetti at the cost of needing to deal with two extra menus, an extra minute of loading, and a bunch of background data to maintain a list. You are thinking about the feature list, not the features. It sounds great on paper, but it is a nightmare when new, inexperienced user have to understand why the hell it took 10 minutes to start playing FFXIII at 10 FPS.

**Comment by adriandennis17** [comment]
@Thunder07  i was just stating one way it could be done, since you there's lots of ways.. 😅

**Comment by Thunder07** [comment]
@LoungeKatt, I appreciate that, but surely I wont push for something that would cause the ui to spend half an hour just to list the games.
granted i haven't built it yet, but when I do, ill make the call if it worth keeping or scraping.

**Comment by LoungeKatt** [comment]
Then perhaps it would be best not to attempt to explain the design until you have tested it. My comments apply to the presentation and no amount of argument will prove an untested theory.

As for my proof, "manually add folder" is an extra UI step and "search with a global option for a full scan every time" is extra work for the app and an extra step for the user. That is, by definition, "needing to deal with two extra menus, an extra minute of loading" despite exaggerating actual processing time.

**Comment by LoungeKatt** [comment]
To be fair, it may help to look at Dolphin and PPSSPP. A lot of the features people have requested (and no doubt will request) come from experience with those.

Keep in mind Dolphin only supports a handful of devices and is more a wishlist item than an installed app for most Android users without an Android console.

PPSSPP, on the other hand, will run on anything down to the lowly Xperia Play. They do not receive many complaints about the UI not being enough or many about setup being too difficult.

**Comment by Thunder07** [comment]
"no amount of argument will prove an untested theory"
I agree.

**Comment by adriandennis17** [comment]
@Thunder07 oh...well sorry if i you think i copied what you said... 😓

**Comment by LoungeKatt** [comment]
By all means, please spend as much time as you like trying to prove it. I fully support that decision.

**Comment by LoungeKatt** [comment]
Just so nobody can say I stacked the deck, I recommend looking into BroadcastReceivers and the Android media library. 
Combine that with a background service that watches for SD connect and disconnect along with boot complete and you may be able to maintain a db completely independent from the UI itself.

**Comment by Thunder07** [comment]
didn't know Android media library can check for iso, bin etc, if so this would come in very handy.

**Comment by LoungeKatt** [comment]
Android media library uses a mediascanner. It detects when a file is changed and populates the meta data for it in a database or adds data for new files. This database is the backend to gallery. It allows gallery to keep tabs on the files spread across the entire phone. Starting to sound familiar yet? Certain actions, such as connecting an external storage source, will trigger the scanner. It does all of this in the background as not to make the gallery take too long to load. Look at that! It's almost like this concept that has been in use since way back on Cupcake is doing what you want without disrupting the UI.

And you thought you were being witty... haha.

**Comment by Thunder07** [comment]
i knew how it work, just didn't know it handled "non-media" stuff as well

**Comment by LoungeKatt** [comment]
It doesn't by default, but the source can be made an independent package.

**Comment by LinkofHyrule89** [comment]
Everything was just the name I picked to to display everything in an Alphabetical unsorted manor so I don't think it's a placeholder it's just a way to see everything that isn't something you favorites port played recently. Feel free to suggest other names that's just the one that I picked.

**Comment by adriandennis17** [comment]
@LinkofHyrule89 when you say "display everything" are you talking about something other than a ps2 game?...if not why call it everything..since it's only games are shown..i think calling it "Games" is a fitting name..just my opinion though...not bashing you, just saying ✌

**Comment by LinkofHyrule89** [comment]
Yeah it might be better to just call it Games I also considered All Games but I see your point.

**Comment by adriandennis17** [comment]
@LinkofHyrule89 Great 👍

**Comment by LoungeKatt** [comment]
"Unsorted", "General" but Games is what the top bar already says, so that may be confusing.
By default, it currently sorts alphabetically by the file name. So "Images (A-Z)" could be valid, too.

Placeholder refers to the idea that it didn't have a descriptive name. It was everything because there was nothing else to really call it.

**Comment by adriandennis17** [comment]
@LoungeKatt i also notice the "Games" at the top bar...but since those navigation was for testing
i didn't point it out.

**Comment by LinkofHyrule89** [comment]
The top bar header should change to be whatever section you're currently in.

**Comment by adriandennis17** [comment]
@LinkofHyrule89  Yep..that's what it should do ✌

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by LoungeKatt** [comment]
@MartinDesigner I see that your only contribution to Github is spam, so I am reporting you for it. 

I honestly hope you have a virus doing this and aren't truly so ignorant as to post full-color advertisements for unrelated products in the issues of other projects.

**Comment by Gamemulatorer** [comment]
> ![2015-08-03 09 27 51](https://cloud.githubusercontent.com/assets/4733568/9053941/5435145a-3a41-11e5-840f-efcd145beb7d.png)
> 
> Instead of "Favorites" why not use "Apps" and have that section only show. elf files.
> Mixing Games and homebrew apps together doesn't look right to me...
> And since theirs no way of getting a cover for these apps why not just have them viewable as a list instead of using the default Play! cover,
> 
> "Everything" couldn't it be labeled "Games"..since only games gonna be in that section

How about this now the name change to unsorted from everything?
![Screenshot_2021-07-23-03-42-33-082_com virtualapplications play](https://user-images.githubusercontent.com/37603562/126699985-679e1a88-c8fe-4a82-a094-b41160342f15.jpg)

**Comment by XiaomiRedmi9** [comment]
Add force landscape the menu on settings > ui
