### ISSUE TITLE
Locating games

### ISSUE THREAD

**Issue by brimaster20000** [jpd002/Play-#283]
On the Nvidia Shield TV it just locates games for hours.

**Comment by LoungeKatt** [comment]
You may want to clear data for the app and try again. 
I just installed, cleared the folder setting, and in 5 minutes was back up and running. I have an sdcard insert as well, so it was also searching that.

**Comment by jpd002** [comment]
@brimaster20000 Are you still having issues with the current build? The code has changed quite a bit since August.

**Comment by jpd002** [comment]
The code has changed quite a lot since 2015. Closing.
