### ISSUE TITLE
Branding guidelines

### ISSUE THREAD

**Issue by LoungeKatt** [jpd002/Play-#284]
Are there any? Certain colors to use, a logo, certain text that should always appear.

I saw a post on Google+ saying a new icon had been requested and I noticed the icon for the community had changed from the app icon (which is what most beta communities use) to just the name in the D3 font that was used for the banner.

@jpd002 You may want to establish a guideline before it gets out of hand. Play! is your brand, after all.

**Comment by LinkofHyrule89** [comment]
I've been taking to him about this and he wants to keep the branding blue that's why I've been switching gears away from the purple theme and most likely we're moving more towards a pure blue instead of what appears to be light purple.

**Comment by jpd002** [comment]
Yeah, I did discuss that with @LinkofHyrule89 and told him I wanted a "brand" what would be the same for all platforms. I didn't think of writing a document though, which would probably be the best way to ensure everyone's on the same page.

**Comment by LinkofHyrule89** [comment]
That's a good idea as for the community banner I just changed it because it's properly sized and fits better on both desktop and mobile. In the future it should be changed to match whatever the new shade of blue ends of being.

**Comment by LoungeKatt** [comment]
@jpd002 I was hoping to prevent any games of whisper down the alley or situations (like the banner) where a new graphic is being added based on a best guess and then it is hours, if not days, discussing what it should actually have looked like.

**Comment by jpd002** [comment]
Yeah, I totally agree with the idea, making everything clearer will prevent frustration for everyone.

**Comment by adriandennis17** [comment]
![2015-08-03 09 27 51](https://cloud.githubusercontent.com/assets/4733568/9053941/5435145a-3a41-11e5-840f-efcd145beb7d.png)

the above looks good to me..if your gonna go with pure blue that can also work..but i like how the UI looks above even the icon..the only think that i was gonna work on was the app icon..

**Comment by LinkofHyrule89** [comment]
Nothing is finalized but most likely we're going with the blue however the dark purple theme will be included to be able to switch to in the settings.

**Comment by adriandennis17** [comment]
![tmp_21199-play1-ad171390953657](https://cloud.githubusercontent.com/assets/4733568/9151294/3d08dd04-3dc3-11e5-882a-6a7a9bc55764.png)

![tmp_21199-play2-ad17-852933296](https://cloud.githubusercontent.com/assets/4733568/9151295/4828fb60-3dc3-11e5-8c38-20ccb6ed134e.png)

im still working on it's not done yet...i was thinking of giving the control a ocean blue feel 
and i went with the D3 Font for the Play! text want to add a gradient color to the text blue at the top sky blue bottom..

does it seem a bit much or should i go back to the drawing board ?

**Comment by LoungeKatt** [comment]
![3d08dd04-3dc3-11e5-882a-6a7a9bc55764](https://cloud.githubusercontent.com/assets/1173913/9151386/fcfeae62-3dce-11e5-8dde-e23828b70fd1.png)

Actual icon size. Just saying...

**Comment by adriandennis17** [comment]
@LoungeKatt it still a work in progress..but ive been reading up on the sizes your dimensions seem wrong how did you resize..

![tmp_21199-playstore-icon2005433715](https://cloud.githubusercontent.com/assets/4733568/9151452/56dc40cc-3dc8-11e5-8980-c5ad5752f729.png)
Playstore icon

![tmp_21199-ic_launcher-692138082](https://cloud.githubusercontent.com/assets/4733568/9151454/7519ba10-3dc8-11e5-9ba9-6d323c2f0a5d.png)
ic launcher

**Comment by LoungeKatt** [comment]
You intended for it to look distorted? I took the larger of the two dimensions (in this case width) and sized it for hdpi (72 px)

**Comment by adriandennis17** [comment]
![tmp_21199-playstore-icon1972913941](https://cloud.githubusercontent.com/assets/4733568/9151468/fdd3aa00-3dc8-11e5-89ad-92cc3045fb79.png)
PlayStore icon (looks big here, but its 512x512)


![tmp_21199-ic_launcher-334872787](https://cloud.githubusercontent.com/assets/4733568/9151470/23226c06-3dc9-11e5-95b1-bf205da6a995.png)
drawable-xxxhdpi ic launcher

**Comment by adriandennis17** [comment]
no i didn't plan on it looking distorted..but i will look into that now.

**Comment by Fadi5555** [comment]
Guys what are these?
Is it a new icon of play!?

**Comment by LoungeKatt** [comment]
The point was that the text will be too small to read on a device.

**Comment by adriandennis17** [comment]
@Fadi5555 could you delete your comment please...and to answer your question.

1.don't know yet...
2. in the near future
3. no eta when any sort of major fix will be done...

**Comment by adriandennis17** [comment]
![tmp_21199-play new concept541449655](https://cloud.githubusercontent.com/assets/4733568/9151613/b552d0b2-3dcd-11e5-8c79-2fcc2781b7ce.png)

![tmp_21199-play new concept 2-734552959](https://cloud.githubusercontent.com/assets/4733568/9151614/c52c1340-3dcd-11e5-8cd5-3769683370d0.png)

@LoungeKatt maybe a big (P) could be use...it's my dayoff so i have the time to come up with a few new design and see which works best..

**Comment by LoungeKatt** [comment]
It's up to you. I don't know that this issue is the best place to discuss it, though. Especially not with all the high resolution images.

This issue has been addressed, so I am closing it.

**Comment by adriandennis17** [comment]
oh my bad..yeah close right away ✌
