### ISSUE TITLE
Automated issue reporting

### ISSUE THREAD

**Issue by LoungeKatt** [jpd002/Play-#286]
I have been testing this for a bit and wanted to see if it sounds like something that would be desired (or even possible) to include in Play!

Requirements:

PHP enabled server with reliable availability
Minimal bandwidth and storage for files

Capabilities:

Device profiling - hardware information (general) and Android version
Crash logs - Targeted logs specific to Play! and related interfaces (ie. GLES)
Indexed reports - Searchable via a website interface
Privacy conscious - External log information ignored
Notification system - Alert user when a log is preferable

This would be similar to what is established for reicast. I have been testing a version designed for Play and it appears to work fairly well. It can catch crashes in the app and will notify the user on the next launch what the crash was and provide the option to report it. There is also a user interface option to report the issue. Both will gather relevant information and redirect the user to the issues on Github with a link that can be posted along with their description of the issue.

This requires server-side support to handle log submission and host the hard copies. It is extremely rare any personal information is logged, but there is always a possible risk with any log.

A sample log will be posted below.

**Comment by LoungeKatt** [comment]
http://loungekatt.no-ip.biz:3194/Playstation/report/logs/1438956545113.txt

**Comment by LoungeKatt** [comment]
@jpd002 Leaving this here for you, but closing it to not clutter up the actual issues.

**Comment by Thunder07** [comment]
I'd imagine this would be simple, but if you don't have this, can you have it enclosed by an if statement for easy disablement(I'd also imagine using it would prevent exception handling during development?), since i hardly think jpd002 would like to get every crash log that happens as I'm working on the app itself.

**Comment by LoungeKatt** [comment]
I recently needed a log, so here is a demonstration of the user-driven method of logging:

![screenshot_2015-08-08-07-55-45](https://cloud.githubusercontent.com/assets/1173913/9150427/44fab9d2-3da6-11e5-9fcf-e1d0eac5a8ba.png)

The "Debug" menu option is clicked

![screenshot_2015-08-08-07-57-47](https://cloud.githubusercontent.com/assets/1173913/9150428/49a2c326-3da6-11e5-9b21-5dbf9b30216a.png)

The file is written to the device, which is followed by another notification that a link has been copied to the clipboard. This accompanies a selection window for how to connect to Github.

![screenshot_2015-08-08-07-59-22](https://cloud.githubusercontent.com/assets/1173913/9150429/4ef0a56e-3da6-11e5-8baf-105b972c0d7a.png)

The log is still available to the user via internal storage and can be opened and viewed. 

![screenshot_2015-08-08-07-59-31](https://cloud.githubusercontent.com/assets/1173913/9150430/5a59e50a-3da6-11e5-854c-f349eb222a61.png)

The automated portion will prompt the user when the application has crashed. It will allow them, much like Google Play reporting, to opt in to reporting or dismiss the notification. Keep in mind, the error will still be printed to logcat. This is providing the *same functionality as Google Play reporting* in a manner that allows the information to be directed to Github and does not require a "market install". The biggest improvement over Google Play reporting is the option to trigger a log without a fatal crash.

This does *not* replace standard logging nor does it *require* users submit their logs. It provides an easy method for those users that *choose* to submit their logs to do so. I hope this will prevent any confusion or questions that may arise from those unfamiliar with Google Play's standard workflow.

**Comment by Thunder07** [comment]
ya I'll say jpd002 is slowly getting the hang of the Play Store, but I'm sure he doesn't mind the explanation.

**Comment by jpd002** [comment]
That would be very cool because it could provide information that's not given by Google Play's crash reporting system, namely, GLES device information and the id of the game that's being played. We could probably host everything needed for that on purei.org.
