### ISSUE TITLE
Error building for Android

### ISSUE THREAD

**Issue by weihan1102** [jpd002/Play-#30]
I try to build Play! for android using the instruction but i failed, i got this error

![aa](https://cloud.githubusercontent.com/assets/4973931/6826100/0ee0b3d2-d33a-11e4-9fbf-f9940865841e.jpg)

**Comment by xiushudongfang** [comment]
Cygwin is needed.Are you chinese？

**Comment by weihan1102** [comment]
Oops, i found my problem....I should use Cygwin terminal instead of cmd
