### ISSUE TITLE
Hanging at Updating Collection 

### ISSUE THREAD

**Issue by TommyGrissom** [jpd002/Play-#307]
Xperia Z3 hanging at Updating Collection on launch. The progress wheel spins, but the task never completes. Doesn't appear that I can cancel the automatic update.

**Comment by Thunder07** [comment]
based on your storage size and content, if might take a while to find the games, so leave it to run for a bit and see if that help.

there is also no point in allowing you to cancel that dialog since no games will appear without it.

**Comment by TommyGrissom** [comment]
It's been running for over 10 minutes now, but nothing. I don't have a large amount of storage, just 16gb internal and a 16gb SD card.

I thought the cancel feature would be helpful if there was an option to specify which folder to look in. I figure it would be quicker to do an inventory of a single folder rather than two entire disks.

**Comment by TommyGrissom** [comment]
I saw someone else was having a similar issue. Cleared the app cache like it was suggested there, and it loaded after just a couple of minutes. App runs just fine now.

**Comment by IllusionMan1212** [comment]
Issue is fixed.
Should be closed.

**Comment by Thunder07** [comment]
not sure if this is "fixed", there are people on google plus reporting this issue.
initially I thought it might be due to real micro SD card not being accessible for whatever reason, but the last report said their phone doesn't have external storage support, since I don't have this issue myself, I can't really debug it.

**Comment by IllusionMan1212** [comment]
I also don't have this issue, and since the person who submitted it got it fixed I thought it should be closed.
I guess this can stay open, but there are a lot of old issues still open for no reason.

**Comment by atomic83GitHub** [comment]
This can be close I guess?
