### ISSUE TITLE
Persona 3 FES Black Screen on load

### ISSUE THREAD

**Issue by Flav900** [jpd002/Play-#309]
Might as well post this bug

So the Game Person 3 FES (Shin Megami Tensei - Persona 3 FES) (SLUS_216.21)

![ps2](https://cloud.githubusercontent.com/assets/11288647/9404758/6600355c-47f2-11e5-8215-819f1b48b262.png)

When loading the game it displays a black screen and just stays on there. The f /s do seem to move up and down but the dc/f just stays at 0. 

I've tested and it happens on both the Windows and the Android version.

As far I can tell, the game is supposed to popup with a message box saying Checking memory card (8MB) (for Playstation 2).

If any type of logs are needed I'll try post them.

I think this same bug also happens to the game's sequel Persona 4.

**Comment by adriandennis17** [comment]
https://github.com/jpd002/Play-/wiki/Compatible-games

Did you check the wiki before posting.. it's already there with the same issue.

**Comment by Flav900** [comment]
My bad... the region is different on the wiki, but I guess it's the same thing really.

**Comment by johnnyleap** [comment]
I have the game and I can try to debug it and see what's wrong and maybe explain it here.

**Comment by Flav900** [comment]
Wow that's amazing. Thanks so much for the finding out and the informative answer! I was no good at trying to figure it out myself.

**Comment by jpd002** [comment]
@johnnyleap Might be a hung SIF RPC call. You can take a look in the `SIF.log` file to see what was called last.

**Comment by johnnyleap** [comment]
@jpd002 I can't seem to find that file. Where/how is it created?

**Comment by jpd002** [comment]
It's created by debug builds and it's located in `{User Profile}\Documents\Play Data Files\logs`.

**Comment by johnnyleap** [comment]
@jpd002 That would require me to build Play! and It seems Visual Studio is required for this, isn't it?

Or are there compilation instructions for building in any other IDEs?

If not, I'll just try to build it without an IDE since VS is just too big and bloated for me.

**Comment by jpd002** [comment]
@johnnyleap Yes, Visual Studio 2013 is required to build on Windows (works with community edition).

**Comment by Flav900** [comment]
@jpd002  I've built Play! In Visual Studio 2013 Community Edition, I've been checking it out every now and again from the git pulls. Let me know if need any logs from me as well.

**Comment by Flav900** [comment]
I'm thinking you can use this link, its the debug build already built. 

So you won't need to build it at all.

http://purei.org/downloads/play/weekly/PlayDebugger-20150823.exe

**Comment by johnnyleap** [comment]
In the latest build Persona 3 FES is now going in-game and is playable with graphics glitches:

![p31](https://cloud.githubusercontent.com/assets/13894398/9985936/cb350516-6024-11e5-998a-9e6014e06098.jpg)
![p32](https://cloud.githubusercontent.com/assets/13894398/9985937/cc973e7e-6024-11e5-9a6d-49926aea8afb.jpg)
![p33](https://cloud.githubusercontent.com/assets/13894398/9985939/ce8f6080-6024-11e5-89c5-227091b50716.jpg)

**Comment by Flav900** [comment]
Wow that's so awesome! 

Thanks so much for checking it out!

I guess just for information purposes I can confirm its sequel Persona 4 works as well now, it also has graphical issues 

![p4](https://cloud.githubusercontent.com/assets/11288647/9986588/a22af486-603e-11e5-9578-1e3454ca3880.png)

![p4_2](https://cloud.githubusercontent.com/assets/11288647/9986600/cb7fd982-603e-11e5-883d-f64075843433.png)

![p4_31](https://cloud.githubusercontent.com/assets/11288647/9986623/34938ed2-603f-11e5-9647-49a3bad894c9.png)

![p4_4](https://cloud.githubusercontent.com/assets/11288647/9986702/19309828-6040-11e5-8ff9-59676c551435.png)

Thanks again to everyone!

**Comment by jpd002** [comment]
Awesome, thanks for testing, I had no idea those games were now working!
