### ISSUE TITLE
Database Table Structure

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#312]
I'm considering changing the database table layout back to the original one, (aka concentrating the serials under a single ID, but otherwise will leave the rest as is), to reduce the entries down to 1500.

@LoungeKatt may I ask why you changed the layout (beside the obvious poor naming of column on my behalf).

**Comment by LoungeKatt** [comment]
Matches the database provided by GamesDB. It's possible to merge their updates when the table names match. Matching doesn't analyze the records just the table name.

**Comment by Thunder07** [comment]
ummmm... TheGamesDB DB only contains 1500, as oppose to the current database with 4000+ entries.
you have each Serial with it own Entry, thus the same GameDB ID would be used multiple time.

A better solution would be to consolidate the serials under a single GameID, but still add any title without a matching GameID (with its associated serial and name), so that should they match, you can update the database with the GameID, no?

GameID=TheGameDB ID

**Comment by LoungeKatt** [comment]
That has nothing to do with the layout. That's overlapping serial numbers. You can mess with that column without changing the entire database. I don't have time to explain sqlite right now so the simple answer is you're suggesting the wrong solution for the problem you're describing.

**Comment by Thunder07** [comment]
the only thing I'm proposing is merging the serials.

**Comment by LoungeKatt** [comment]
That has nothing to do with the layout. That's updating a column and consolidating records.

**Comment by Thunder07** [comment]
well, you got the point... and I take it that yes, I can change that.
