### ISSUE TITLE
L3 and R3 are not supported....

### ISSUE THREAD

**Issue by johnnyleap** [jpd002/Play-#316]
Every button on every platform (excluding iOS) is supported, except L3/R3 buttons.

Any word on why they're not supported? Just never got done, or some other reason?

As far as I know, L3/R3 are handled the same way (e.g. button press,,packet or PADMAN/SIO2MAN call?).

**Comment by jpd002** [comment]
Humm, AFAIK, they're the same as all other buttons. As to why they are not supported, it's just laziness on my part. It can easily be added on the PC version, but, I'm not quite sure how pressing L3/R3 on a virtual pad would work.

**Comment by Thunder07** [comment]
It'll probably just he another button, much like R2/L2, no?

**Comment by adriandennis17** [comment]
@Thunder07  nope..best to make them clickable..similar to the rest of controls..

**Comment by Thunder07** [comment]
@adriandennis17 lol, I was hoping they won't be clickable.

**Comment by jpd002** [comment]
Well, since L3 and R3 are basically "pressing the analog sticks", it would be natural to expect the buttons to be triggered when you touch the analog sticks on the virtual pad. But I think it would be a bit confusing on a touch screen since you don't have any feedback.

**Comment by xxoscarxx28** [comment]
How about additional buttons for L3 and R3?

**Comment by adriandennis17** [comment]
adding more buttons..that will take up more screen space..not a good look.

**Comment by adriandennis17** [comment]
@jpd002 if your talking about some sort of haptic feedback so person can know that L3 & R3
is being pressed..that's not really needed..when the game being played asked for those buttons
to be pressed..if theirs no movement or the game is still asking for the buttons to be pressed then 
the user will know their do it correctly..

a few ideas to add to settings:

enable/disabled L3 & R3 from analog (some games dont use L3 & R3)

add two small buttons near select, start: "L3" "Select" "Start" "R3" which can be enable/disabled (shown/hidden) if users rather a button for "L3" &"R3"

**Comment by jpd002** [comment]
@adriandennis17 I mean, it won't be obvious that you can press the analog sticks to trigger L3 and R3. I'll probably end up adding buttons near select and start (and I like your idea of having an option to hide them).

**Comment by adriandennis17** [comment]
@jpd002 It won't be obvious to those who never played a PS2, anyway since your gonna add buttons
near select and start..it's best to also add the function for L3 and R3 by pressing the analog stick and have this option disabled by default (and can be enabled/disable in settings) that way for those who will
request this kind a feature..it would already be present.

Also for those buttons (L3 & R3) that will be near select, start...it's best to have them (disabled/hidden) by default, since most games don't really use them.

**Comment by jpd002** [comment]
The L3 and R3 buttons are available on Win32 and Android in today's weekly build. I might add an option to hide the buttons on Android later on.
