### ISSUE TITLE
Please support OpenGL ES 2.0 on Mobile device

### ISSUE THREAD

**Issue by zminhquanz** [jpd002/Play-#319]
Like as title , because most of mobile device at the present using OpenGL ES 2.0 , OpenGL ES 3.0 is not much more , so in the furture , can you support it ?

**Comment by Fadi5555** [comment]
Sorry for saying that.
I don't think so at all
Because the creator @jpd002 said he didn't have ip any plans to support OpenGL 2.0.
Because the emulator is already too slow and need a good requirements to run it so OpenGL 2.0 is less than 3.0

**Comment by jpd002** [comment]
As @Fadi5555 mentioned, there are no plans to support GLES 2.0. Sorry about that, even if GLES 2.0 was supported, it wouldn't give interesting results on devices that support only that version (FPS is already quite low on devices supporting GLES 3.0+).
