### ISSUE TITLE
Compile instructions for Mac + other platforms

### ISSUE THREAD

**Issue by forcejackson** [jpd002/Play-#322]
I have been trying to build for Mac to improve some UI stuff, but I am having trouble setting up the compiling for Mac, and I tried for Linux and can't do it either. I was wondering if you could extend compilation instructions with a quick and dirty little write up on how to build for Mac, iOS and Linux.

Nothing much asked, just something like an extension of the readme markdown to include more info/etc.

I see that your website @jpd002 is a bit outdated since it only mentions Windows in some areas and Play! is well beyond just the Win32 platform with support for almost 5 different platforms as of now.

I don't mean to disturb or take away efforts to important stuff like I see the IOP issues and graphics problems need fixing, but if you have free time (anyone reading this), it'd be great to get more helpers who may otherwise be able to contribute but have trouble compiling for certain platforms and etc.

**Comment by jpd002** [comment]
I've updated the OSX project to make the setup a bit simpler: 98a7d44f82bc339a65435768b2a3066ed32eb7d4.

I'll update the Readme file later, but basically, here's what would be needed to build the project on OSX:

1. Checkout https://github.com/jpd002/Play-Build in a folder somewhere on your disk.
2. Build the boost framework using the script in the Dependencies folder. (https://github.com/jpd002/Play-Dependencies/blob/master/BoostMac/boost.sh)
3. Open up the Play! Xcode project and you should be good to go.

If you're still having problems, don't hesitate to post the error message here so I can tell you which part I might have been missing in my instructions.

**Comment by jpd002** [comment]
Actually, I forgot I had to make the same changes to the Framework and CodeGen projects. It's done now. (https://github.com/jpd002/Play--Framework/commit/172ed364604d8c6cd9ecdbd3e425cc42d45df14f & https://github.com/jpd002/Play--CodeGen/commit/2f60b5b8894e423159f682ca38af8884f5b3bd2d).

**Comment by Fadi5555** [comment]
Hi @jpd002 
Is there any improvements for iOS version?
Specially on pixels issue. For more information Please go to (iOS port) I left some comments and questions there.
Thanks.

**Comment by forcejackson** [comment]
@jpd002 Thanks, I think I got it all set up now.

**Comment by Fadi5555** [comment]
@forcejackson do you mean you want to help us to improving Mac & iOS?
If that's right it'll be more helpful. Actually the creator @jpd002 have amazing knowledge of this stuff but he didn't have much time to improve all platforms at once. As well as there is some members here and all of them working and focusing to improve android version. Except one member who is called @LoungeKatt he did many things to improve iOS version.

**Comment by jpd002** [comment]
@forcejackson Great! I've updated the readme file with the instructions. If you've got any other questions, don't hesitate to ask!
