### ISSUE TITLE
Need for Speed Underground 2 not working

### ISSUE THREAD

**Issue by CuldHard** [jpd002/Play-#323]
Hey bro! I downloaded NFSU2 from cool rom last night and I saw it doesn't work. It shows me a black screen. No logos, nothing. Fix that please.

**Comment by CuldHard** [comment]
And now I'm trying to download nfs most wanted (not the black edition) to see if that one works.

**Comment by seadil** [comment]
Stop pirating games, thanks.

**Comment by CuldHard** [comment]
Man, listen. I downloaded nfs underground 2 from cool rom. That is not pirating.

**Comment by CuldHard** [comment]
Ooo.... by the way. I tried nfs most wanted and got somewhere to 30 fps, which is something.......

**Comment by MoochMcGee** [comment]
Yeah it is, dumbass.

**Comment by CuldHard** [comment]
Yeah... thanks for callin' me dumbass. You too

**Comment by CuldHard** [comment]
I'll stop pirating until app is released.
