### ISSUE TITLE
( iOS ) .ipa file version won't install

### ISSUE THREAD

**Issue by scorpio16v** [jpd002/Play-#330]
Hello
I'm triying to install the .ipa for iOS in my jailbreaked iPod touch 6.gen, but the install fails every time.
OS version is 8.4, jb with TaiG jb.
Things i've tried:
- downloading and pushed the spa to the device and installed with IPA Installer.
- installing with iFUNBox
- installing with iTunes

Is there a Cydia Repro that let install PLAY! ?

**Comment by jpd002** [comment]
Have you tried @Fadi5555's method?

Quoting from #16:

--
This is all things you most have:
Install these things from cydia
iFile
Powerapp
Safari downloader+

First of all download ipa file of play! From weekly build.

Then open it through iFile then rename the file from play!.ipa to play!.zip

Then extract it you will find a file which is named payload open it you'll find another file inside it called play.app

Then copy play!.app file to the root of files: /Application then paste it there.

Finally open powerapp then select refresh cache after that select respring.

That's it
after that you'll find play! on home screen.
So if you getting in to it. It'll never crash to you anymore.

--

**Comment by scorpio16v** [comment]
Safari Downloader is flagged as "not compatible" with my device, so I tried a variation of your howto 

- downloaded the .ipa with my Mac and changed file extension to .zip
- paste the Play!.app from payload to Applications folder with iFunBox
- used Powerapp, like you described
- Play! is installed now, but it resumed to springboard after a second. I can see a white screen with Play! on it and the copyright text below in this moment.
- tried an older version of Play!, but the same problem.

**Comment by Fadi5555** [comment]
@scorpio16v I know what's your problem because I faced too
The is because of iOS version. It was crashing on me.
I was facing that whe I was on iOS 8.3 for both iPhone 5s and iPad Air 2.
But when I updated them to iOS 8.4 the crash issue is solved.
Just see my comments on the (iOS port) thread.

**Comment by scorpio16v** [comment]
I bought the iPod Touch 6.gen the day after release and it was on 8.4 since day one. So I can't compare if different iOS versions worked before with Play!
I've read the thread, you've mentioned, but don't understand if it is needed to change the file permissions and if a game must be in a special folder to start before launching the emulator.
I'll read it again, maybe I'm missing some hints, you've done before ?

ps: this issue should be merged with the other mentioned, sorry.

**Comment by jpd002** [comment]
I've created a Cydia repository to host the application: http://cydia.purei.org/. Might be easier to install using this.

**Comment by Fadi5555** [comment]
@jpd002 thank you so much for making this cydia repo. Now it's become more easier to install your amazing project. That really good idea and super easy.

**Comment by scorpio16v** [comment]
Since we can install Play! from cydia, this issue is obsolete.
