### ISSUE TITLE
Menus are unusable for people with altered Windows text sizes.

### ISSUE THREAD

**Issue by disastranagant** [jpd002/Play-#332]
![untitled](https://cloud.githubusercontent.com/assets/3312331/10424862/640179cc-7098-11e5-8bd3-3d98d6350f0e.png)

**Comment by jpd002** [comment]
Thanks for the report. I'll update that dialog to use Windows' dialog manager so that it scale properly with font size.

**Comment by atomic83GitHub** [comment]
What is the status about this?

**Comment by jpd002** [comment]
The UI is now using Qt, should work with different font sizes.
