### ISSUE TITLE
Warship Gunner 2 (SLUS-21387) doesn't boot

### ISSUE THREAD

**Issue by disastranagant** [jpd002/Play-#333]
Have fun getting it to agree with your eventual VIF implementation ;)

**Comment by jpd002** [comment]
Thanks for the report. What's so bad about it's VIF usage?

**Comment by disastranagant** [comment]
In PCSX2 whatever weirdness it does appears to directly conflict with what the Snowblind engine games do.  Fixing fixing one broke the other.

**Comment by jpd002** [comment]
Interesting, looks like a great candidate for a hardware test. I've got some code to make Snowblind games work, which isn't active yet because of issues it causes with other games, so, it'll be nice to see how this game reacts to this.

**Comment by jpd002** [comment]
The reason why it doesn't boot is pretty easy to fix: it tries to write to R0 using QMFC2 (probably to sync a VU register) which clobbers the register because I was not handling this properly. Fixed here: 9fed3e258545367bc20353da4f8ea208baa030fb.

The game looks quite ugly after that, most of the 2D stuff doesn't seem to show up for some reason

**Comment by disastranagant** [comment]
Well, it is a game that routinely maxes out the EE and both VUs.

**Comment by jpd002** [comment]
I've fixed most of the issues and the game seems to be playable now. The hack that fixes Snowblind games isn't active ATM, so, I'll have to figure out how to make both "engines" work properly in the emulator later on.

![warship_1](https://cloud.githubusercontent.com/assets/6760433/11321863/60756b04-909d-11e5-9124-202007f6826b.jpg)
![warship_2](https://cloud.githubusercontent.com/assets/6760433/11321864/61aea9f4-909d-11e5-8535-d09a59cc8d69.jpg)

**Comment by disastranagant** [comment]
A bit of topic but which of the 8 zillion versions of Visual Studio is needed to build this project and its dependencies?

**Comment by jpd002** [comment]
Visual Studio 2015 is needed to build the project on Windows. I personally use the Community Edition which works fine for what I do.

Closing this as the changes are available in today's weekly build.

**Comment by disastranagant** [comment]
Your GS shares a bug with GSDX. Note the bluish grey strip here, it's supposed to be faint fog that gets denser with distance. http://i.imgur.com/nNGvIZ2.png 
And here we have the underwater explosions of a recently dead submarine visible from the surface. http://i.imgur.com/eGHv2Of.png

https://github.com/PCSX2/pcsx2/issues/985

**Comment by jpd002** [comment]
Thanks for reporting this. I've created a new issue.
