### ISSUE TITLE
gta memery card save stats will crash the emulator if memery card manager is used

### ISSUE THREAD

**Issue by annahana** [jpd002/Play-#334]
system windows 7 pro x64
gpu amd radeon hd 6450
cpu intel core i3 2120 
ram 4 gb

testet on last weekly build (has never worked)

if merery card manager is focusing a gta save the emulator will crash

<img width="840" alt="gta" src="https://cloud.githubusercontent.com/assets/13276505/10431951/734aa78a-7108-11e5-943e-e8a6d955805d.PNG">

**Comment by jpd002** [comment]
Thanks for the report. I'll see what I can do about that.

**Comment by jpd002** [comment]
Fixed by 9f417e94bec08350043137f06fbd5676e8be0d26 and 9c93f9a03521ba98f86b6d5ca6692eb29eef3e48. Will be in next weekly build (2015-10-18).

**Comment by annahana** [comment]
patch is working as expected

**Comment by jpd002** [comment]
Thanks for testing!
