### ISSUE TITLE
event flags and semaphores

### ISSUE THREAD

**Issue by shoddybastro** [jpd002/Play-#338]
i trying lot of games and most that do not show anything are showing event flag and semaphore errors in debugger. i don't know what those mean, I checked the project and see event flags i don't know what they repesent. Ar ethere any ways to see what the event flag error codes mean or what that is or if this is an issue to be made of something not emulating correctly? sorry for my bad enligh! i just want to help but i can not find what these mean and i google search and there is no info on them but i do know that of 50 or more game that are not showing stuff is that the debugger is showing event flags and semaphore issues so i thought maybe this problem can be fixed and some of those games will work

here are some examples

OsWaitSema Waiting Semaphore 3, Padman Waiting Event Flag 2, Sio2man Waiting Event Flag 1, etc.

Are those problems meaning what?? Thank you

**Comment by jpd002** [comment]
Threads waiting on semaphores and event flags doesn't mean there's a problem as the IOP is mostly idle and waiting for devices to complete operations. Do you have a specific example (from a specific game) that makes you say that there's a problem?

**Comment by shoddybastro** [comment]
I do not want to start with attitude so I will just close this issue as you are clearly upset that I bring up issue with semaphores and threads.

**Comment by jpd002** [comment]
Sorry if I sounded offensive. I just wanted to know if there was a specific game you were trying to debug because it's quite hard for me to help otherwise since what you describe looks like normal behavior to me.
