### ISSUE TITLE
LEGO Star Wars (1) doesn't work

### ISSUE THREAD

**Issue by Newbie13XD** [jpd002/Play-#339]
As the title suggests, LEGO Star Wars (1) doesn't seem to work. It doesn't give me aa black screen though, rather some random colours.
The FPS lies around 0-5 and the draw calls thingy jumps up to ~600 at times.
If it helps I can provide screenshots and more info

Device: Samsung Galaxy S5 (SM-G900F) running Android 5.0 stock ROM
Game ROM is saved on my SD card

**Comment by jpd002** [comment]
Thanks for the report.

AFAIK, on Windows, sound can be heard, but nothing shows up on the screen indeed. I'll take a look.

**Comment by jpd002** [comment]
Had a quick look today and it seems to be broken because of bad handling of VU integer branching, much like Crash Bandicoot: Wrath of Cortex (#363).

**Comment by bigianb** [comment]
PR #422 fixes this.

**Comment by jpd002** [comment]
Closing this as it's now possible to get in game on the latest builds.
