### ISSUE TITLE
Monster Hunter black screen all the time

### ISSUE THREAD

**Issue by hector1301** [jpd002/Play-#342]
Monster Hunter game screen stays black when trying to run a sony xperia m4 aqua
Android: 5.0, octa core, snapdragon 615, adreno 405., 2gb ram

**Comment by jpd002** [comment]
Thanks for the report. MH2 started working with the changes I did to make RE4 work (#273) but MH1 still don't work unfortunately.

**Comment by jpd002** [comment]
Both games should work now. Compat entries:
https://github.com/jpd002/Play-Compatibility/issues/740
https://github.com/jpd002/Play-Compatibility/issues/281 (this one needs an update)
