### ISSUE TITLE
[iOS] After fix resident evil 4 crash issue now it stays on black screen

### ISSUE THREAD

**Issue by Fadi5555** [jpd002/Play-#346]
Hi all:
well resident evil 4 on the latest build of play! (on 8 November) it fixed the issue of crashing and all that now it becomes playable on windows and android. But on iOS it stays on black screen.
Well @jpd002 said the games compatibility should have the same results on android and iOS because they are sharing the same source codes.
It also happened with persona 4 it playable on Windows and android but on iOS it crashes.
So any idea of how to get them work?
Maybe something missing to be have done the same thing on android.

@jpd002 please can you fix that?

**Comment by jpd002** [comment]
That's odd, I'll look into it.

**Comment by jpd002** [comment]
Ok, I did find an issue in the GLES GS handler that could explain the problem. I'll do some more testing and hopefully have that fixed for this weekend's build.

**Comment by Fadi5555** [comment]
@jpd002 that's nice.
I really hope to add fps counter to see the process of games.

Also did you know what is the issue that stop images cover of game to be appearing?
It would be nice to see them.

**Comment by jpd002** [comment]
I've updated the build on Cydia with the one that has the change that should fix that problem. Could you give it a try and tell me if it's fixed?

Thanks!

**Comment by Fadi5555** [comment]
@jpd002 I downloaded your latest one from the cydia.
But unfortunately it still stuck on black screen I waited it too long but no luck
Any idea please.

**Comment by jpd002** [comment]
Which version of the game do you have? The one I'm testing is SLUS_211.34.

**Comment by Fadi5555** [comment]
Me too it's same version of game
It same game I tried it with my pc it works but on iOS it doesn't work (black screen)

**Comment by Fadi5555** [comment]
???

**Comment by jpd002** [comment]
Sorry, I've been quite busy with work this past week. As for the issue, I've tried on my iPhone 5s and iPhone 6s and the game works on both. I don't have an iPad Air 2 to test on at the moment.

**Comment by Fadi5555** [comment]
I test it on my ipad air 2 on ios 9.0.2
And on my iphone 5s on ios 8.4
But no one of them are run resident evil 4?
Do you have any idea?
Why it doesn't work with me?

**Comment by Fadi5555** [comment]
I had test both USA and Europe version of resident evil 4 but no luck.
It keeps on black screen
![image](https://cloud.githubusercontent.com/assets/10546081/11327235/c5ba7c36-9190-11e5-8314-dd65e9a9970f.png)

![image](https://cloud.githubusercontent.com/assets/10546081/11327244/f4d7c6b8-9190-11e5-810d-ef3187bcdc16.png)

Any idea please? Like what is your method to run on you? However it doesn't work with me?

**Comment by jpd002** [comment]
I'm planning to add the FPS and draw call counter this week, that might help us figure out what's going on (ie.: if we see some draw calls, but still nothing on the screen that will mean the game runs properly and that it's a video output problem).

As for cover images, on my side, I only see Gradius V's cover on iOS. I've got plans to fix that, but it's low priority for now.

**Comment by Fadi5555** [comment]
It will be nice if you add fps counter.

It's really weird about resident evil 4 it run on you only?

Also the controller PS3 can successfully connected and play on it but it's not mapping in right way
Like if you select up it goes down also if you select cross button it select square button.
I think this is easy to remapping it.

Finally I hope you find a solution for resident evil 4 and cover image of games.
Thank you for your hard work.

**Comment by Fadi5555** [comment]
I also tried Gradius V but no luck to see the cover image of it?

I think there's something missing to show covers of games.

**Comment by jpd002** [comment]
Yep, there's definitively something missing for covers, but again, it's low priority for me.

I've updated the build on Cydia. It now has the FPS and Draw Calls counters. Could you tell me how many frames per seconds and draw calls you get after leaving the game running for 5 minutes?

**Comment by Fadi5555** [comment]
After run resident evil 4 the fps counter just go 7/8 per second that's only
Even I leave it more that five minutes but unfortunately it same thing.

![image](https://cloud.githubusercontent.com/assets/10546081/11389328/6e31b26a-9350-11e5-84f3-ddc83cb90149.jpg)

Please can you show me your screenshot of it?

Also do you have idea what's happening?

**Comment by jpd002** [comment]
That's odd... On my side, I'm on 60fps with a non-zero amount of draw calls (can't take a screen shot right now because of technical issues). That means the virtual machine's execution on your device(s) is different from my device(s).

I think I'll have to add the save state feature so you can send me the emulator's state. Once I get your saved state, I might be able to see why the game is stuck there.

**Comment by Fadi5555** [comment]
That's a good idea.
As myself i feeling like sad one.
Because of this.
Why you said your device is different from mine? We all use same iOS devices aren't we? The bad part i test it on my iphone as well as my ipad. So it same thing.

Anyway. That really good idea about save state.

Also i have request about controller. (It just need to remapping buttons to be on right side)

Finally I recommend to put a button to exit from game to go back on games menu.

**Comment by jpd002** [comment]
So, I've uploaded a new version in the Cydia repository. This new version has a "save" button (temporary) that will save the emulator's state after pressing it. It will generate a `state.sta` file in `/private/var/mobile/Documents`.

Could you save the emulator's state when the game is stuck doing the black screen and then send that file over to me? You can send it through e-mail if you wish.

Thanks!

**Comment by Fadi5555** [comment]
Thank you so much for that.
Ok i'll

**Comment by Fadi5555** [comment]
Can you remember me what is your email?
Put it here.
Also is there will be load state for that?

**Comment by jpd002** [comment]
You can find my e-mail address here: http://purei.org/about.php. I will be able to load that state on PC to see where the game is being stuck.

**Comment by Fadi5555** [comment]
I tried many times he said that address not valid
Please another one
Or type it here for make sure

**Comment by jpd002** [comment]
Thanks! Got it!

**Comment by Fadi5555** [comment]
I hope to fix this issue. As well as to fix images of games.

**Comment by jpd002** [comment]
Just a quick update: I tested Persona 4 on iOS and I did get the crash you were talking about. I think RE4's problem might be related to that, but I still need to do some tests.

**Comment by Fadi5555** [comment]
Thank you so much. For trying to fix that issue.

Well I have two questions if don't mind:

What is the state about game (crash bandicoot the warmth of cortex)? It's still until now on black screen.
Do have any idea to make it run?

I saw many things on your commits you support many things. This is image of that
![image](https://cloud.githubusercontent.com/assets/10546081/11621377/7bd96838-9ccc-11e5-9cd5-14fc3dba06e8.png)



So what are these?
to be honest this is make me very happy even if I don't know what they are. because I'm sure these things gonna help the emu to go further and make games run faster I guess.

Thanks

**Comment by jpd002** [comment]
1- I haven't looked it up yet.
2- Yes, but I still don't have a controller to test on iOS. And it's not the highest of my priorities right now.
3- Yeah, the iOS UI needs lots of work. I'd rather fix games not running on iOS before touching that.
4- Those are changes I made to make True Crime: LA boot.

Sorry if the iOS port is not progressing quickly. Hopefully, I'll have more time during Christmas break to work on that.

**Comment by Fadi5555** [comment]
@jpd002 thank you so much for answering on my questions.
Well it's ok. You already did a good job on iOS. But as you said it stills need more work to be on the right way. I'm really hope three things to achieve:
1- enhancing games compatibility more.
2-speed up the games more.
3-fix images of games cover on iOS that not appear on play!'s screen.

**Comment by jpd002** [comment]
I've uploaded a new version of the emulator on Cydia that should fix the issues with RE4 and Persona 4. Please tell me if the problems are now fixed for you. Thanks!

**Comment by Fadi5555** [comment]
Thank you so much for fixing that issue.
Now both resident evil 4 and persona 4 are working without any problems. (The main problem here is the slow as well as no sound) the best part is this fix not fixing only RE4 & Persona no it also fix some games that was only black screen. 

Well after this fix. I really like from you to figure out about image cover of games I hope to find a solution to show them up.
Thanks again for fix this issue

**Comment by tleple** [comment]
That upload  fixed dragon ball budokai tenkaichi 3 menus black screen. But when a fight is started , the play! App closes automatically

**Comment by jpd002** [comment]
Thanks for testing this. Closing this particular issue now that it's fixed. Budokai Tenkaichi 3 already has an opened issue and I've added a link to it.
