### ISSUE TITLE
Incompatibility with .bin/.cue files

### ISSUE THREAD

**Issue by TheLastRar** [jpd002/Play-#35]
I store PS2 CD titles in .bin/.cue, as ImgBurn is not able to accurately store them in .iso files

The files show up in the file selector, but complains about not being able to find "SYSTEM.CNF" when run.

**Comment by jpd002** [comment]
Thanks for the report. CUE/BIN support is indeed broken, I'll have to fix that.

**Comment by TheLastRar** [comment]
.bin files are now loadable on my end (using windows) using recent weekly builds.

**Comment by bobbymc1985** [comment]
Are .bin files compatible with android?

**Comment by jpd002** [comment]
I've added the ".bin" extension to the Android version. 

Closing this as the original issue was fixed by proper sector size handling.
