### ISSUE TITLE
SEGA Ages 2500 Volume 01: Phantasy Star Generation: 1    (SLPM-62362)

### ISSUE THREAD

**Issue by EETFUK** [jpd002/Play-#350]
Hi there are some really weird graphic glitches / issues in game when you are in battle mode or when you want to enter a specific building. Right after starting in the first town you need to enter a building to grab your important items. And in that building you can't do anything because of those graphic issues. 
Also the npc's are invisible when you start the emulator first. After loading again they ar visible. 
The same goes for the game SEGA Ages 2500 Volume 17: Phantasy Star Generation: 2 (SLPM-62553)

Could you please check that out?

**Comment by jpd002** [comment]
Thanks for reporting this. I'll take a look, but I've only got the "Complete Collection" edition which doesn't to run ATM.

**Comment by EETFUK** [comment]
So after the newest update the graphic issue in that house is fixed. Thx for this. But after you exit the house you have insane graphic isses. Can't play because you can't see correct. Another thing: Just the untouched ntsc-J version of SEGA Ages 2500 Volume 01: Phantasy Star Generation: 1 (SLPM-62362) works on play. Of you want to play the english Patches version the game Crashes on both pc and Android.

**Comment by jpd002** [comment]
Yeah, there's still an issue with some UV coordinates going out of bounds and I'm looking for the proper way to fix that. 

I also tried a patched version of the game, but it didn't seem to crash? Where did you get your translation patch?

**Comment by EETFUK** [comment]
Ok well I used this version: "Phantasy Star Generation: 1: Lutz Edition (Version 2.10)" From the pscave site. And it crashes when I trie to enter that house / cave where u find your first weopons and armor. It ried it a few minutes ago on pc.

**Comment by atomic83GitHub** [comment]
There is already a compat report for that game, this should be close.

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/324. Game is now playable, this issue can be closed.

**Comment by jpd002** [comment]
I played the game half way on my Android device and had no outstanding issue. Feel free to comment in compat issue if you still have issues.
