### ISSUE TITLE
Sims burst out SLUS-208.42;1 crashs the emulator before intro

### ISSUE THREAD

**Issue by annahana** [jpd002/Play-#351]
newest weakly build
system windows 7 pro x64
cpu intel core i3-2120
gpu amd radeon hd 6450

<img width="478" alt="sims burst out" src="https://cloud.githubusercontent.com/assets/13276505/11458862/0a1594dc-96c9-11e5-862f-7c034f989771.PNG">

**Comment by jpd002** [comment]
Thanks for reporting this. I don't have that game yet, so, it might take some time before I figure out the issue with the game.

**Comment by atomic83GitHub** [comment]
Any status? Did you have tested recent build?

**Comment by jpd002** [comment]
AFAIK, doesn't crash anymore, but doesn't get past EA logo movie.

**Comment by jpd002** [comment]
Moved here: https://github.com/jpd002/Play-Compatibility/issues/1398.
