### ISSUE TITLE
iOS - Cydia didn't update new packages

### ISSUE THREAD

**Issue by scorpio16v** [jpd002/Play-#353]
I can't see any package of the emulator in Cydia. New package should be from 2.nd December. Last one updated on my device was from November builds.

**Comment by jpd002** [comment]
Have you tried reinstalling the package? I think I screwed up automatic updates when I added that "nosign" version.

**Comment by scorpio16v** [comment]
Yes, you're right. Deleting the app and a new install loads the most recent app version.

**Comment by jpd002** [comment]
Thanks for confirming this. I'll stick to this version naming scheme so that things don't get screwed up later on.
