### ISSUE TITLE
Rachet and Clank 2 doesn't work

### ISSUE THREAD

**Issue by Newbie13XD** [jpd002/Play-#354]
As the title suggests, the said game doesn't work 
Black screen and nothing more

OnePlus Two
64GB, 4GB RAM
Oxygen OS 2.12
Android 5.1.1

**Comment by MoochMcGee** [comment]
You do realize that even PCSX2 has a hard time running Rachet and Clank,
right?

**Comment by Newbie13XD** [comment]
Actually no, I did not realise that.

**Comment by atomic83GitHub** [comment]
This game now boot but only in introduction fmv and in the title menu.

**Comment by atomic83GitHub** [comment]
There is a compat report for that. @jpd002, you can close this.

**Comment by jpd002** [comment]
Indeed:
EU Version: https://github.com/jpd002/Play-Compatibility/issues/81
US Version: https://github.com/jpd002/Play-Compatibility/issues/294
