### ISSUE TITLE
Questions about iOS (JIT) and (metal) graphic chip.

### ISSUE THREAD

**Issue by Fadi5555** [jpd002/Play-#361]
@jpd002 I have two questions if you don't mind
while ago you have fixed the crash of play! On iOS 9 and works again like before when we were on ios 8
And about iOS 8 has JIT works great (this thing is helping the emulators to run games faster) anyway on iOS 9 we missed JIT because of Pangu Jailbreak is not patch vm-protected unlike TaiG Jailbreak.

So my questions:
1-we are using play! And it didn't crash on us anymore (because you fix crash issue on iOS 9) so on this situation are the Play! use JIT? or interpreter mode? If JIT is come available again is this will effect to games? I mean the games will run faster even a little bit more?
 
2-I know play! is support 64 bit do you want to support metal graphic chip as well? Metal always makes games looks gorgeous and reality (many games on store support metal and we can see different between them)

Well I know you always work on it to make it more optimistic and find solutions to make games run faster as well. But I asked these questions to bring you some ideas of how enhancing iOS port of play!.
Well iOS devices have a powerful things and performance specially the latest one like iPad Air 2 and up as well as iPhone 6 and up so we should take the advantages from them.

thanks.....

**Comment by jpd002** [comment]
1- The current build on iOS uses JIT. Don't know why it works for Play! but not for others though.

2- AArch64 (ARM64/ARMv8) support is still a WIP (https://github.com/jpd002/Play--CodeGen/tree/aarch64) and hasn't been enabled yet. Not much point adding support for Metal at the moment since we're not "draw call bound" for most games. But it might come in handy later if we need to use extra GPU features that OpenGL won't provide.

**Comment by Fadi5555** [comment]
Thanks for replying.
I'm really appreciated. But my question here if gonna support AArch64 is will effect on speed games? I mean what's the features come from that? I'm really excited to know. As i told you anything will help to enhancing play! Will be always welcome.
Thanks for explaining.

**Comment by jpd002** [comment]
AArch64 support should improve emulation speed on 64-bits mobile devices, but I don't know by how much yet.

**Comment by Fadi5555** [comment]
I hope the games run faster after support AArch64.
Other thing when we can see sound support of play!?
