### ISSUE TITLE
[Android] Persona 3/4 black screen

### ISSUE THREAD

**Issue by kpowlah** [jpd002/Play-#362]
I been trying to play persona 4 and 3 on my xperia z3 but all I been getting is black screen.

**Comment by jpd002** [comment]
Thanks for reporting this. Do other games work on your phone?

**Comment by kpowlah** [comment]
So far, kingdom hearts works.

**Comment by MrGryphon** [comment]
I also can't play persona 4 on my Galaxy S6

**Comment by jpd002** [comment]
Testing the game on my Xiaomi Mi4 and I'm getting some weirdness too. I did some changes to fix the problems I had and I will post a test build so you guys can confirm that it also fixes your problem.

**Comment by jpd002** [comment]
I've created a new build with the changes I've made to fix the problem on my side: http://purei.org/downloads/play/special/Play-blackscreenfix.apk. Could you guys give this build a try and tell me if it fixes your black screen issue?

Thanks!

**Comment by kpowlah** [comment]
It works and now both games are slow but that might be my phone.

**Comment by MrGryphon** [comment]
This might just be me but I also don't get audio, this might be because the game is slow but just wondering if there is a fix to it

**Comment by MrGryphon** [comment]
Also it works but is slow

**Comment by kpowlah** [comment]
I have that problem too

**Comment by jpd002** [comment]
Thanks for testing. I will see how I can integrate that fix in the main branch. 

Sound is not supported and the emulator is quite slow at the moment, so, what you are getting is the expected result.

**Comment by jpd002** [comment]
The fix has been brought in the main branch and is present in today's build (2016-01-03).

**Comment by OctoNezd** [comment]
I can't launch Persona 4 on 29/08/17 build. I think bug is back? By trying to run version you sent here, emulator says that it can't find SYSTEM.CNF on cdrom0.
Running on Android 7.1.2, LeEco Le 2 CarbonROM
