### ISSUE TITLE
Crash bandicoot the warth of cortex still on black screen.

### ISSUE THREAD

**Issue by Fadi5555** [jpd002/Play-#363]
@jpd002 I saw some people here are spoken about this game but until now it still on black screen.
Please can you fix it to make it run as many games that you fixed the black screen of them?

**Comment by Fadi5555** [comment]
Any idea how it works?

**Comment by jpd002** [comment]
From my quick investigation, the game has the following problems:
- FileIO IOP module HLE is not returning proper value for `Close` RPC call.
- The game relies on some VU branching subtleties which prevents the emulator from executing the microcode properly.
The second problem is quite tricky to fix and will take some time to get right.

**Comment by Fadi5555** [comment]
Thanks for replying
Well to be honest I didn't know that game has these issues. So is this issues include crash bandicoot twinsanity as well or just on this game only? Because i test crash bandicoot nitro kart on pc is playable and on my ios it crashes after selecting a language.

**Comment by Fadi5555** [comment]
@jpd002 anything new about the process of your project (Play!)?
It's has been time we didn't see your work regularly like before.
I hope from you to comeback and complete your amazing project.
Thanks...

**Comment by Fadi5555** [comment]
@jpd002 hi there. Well first of all thanks for merging boxart fix to masters. I can't wait to see this update on cydia.
Second is there any improvement to make crash bandicoot the warth of cortex go further and to become  in-game?

Thanks a lot.

**Comment by Fadi5555** [comment]
@jpd002 crash bandicoot the warth of cortex is now show loading screen only. Can you make goes to in-game please?

**Comment by Keyaku** [comment]
Hi @Fadi5555!

The game now gets past loading screens, menus and loads levels. So far, I haven't noticed an issue, but I can't test it very far (it runs slow on my device so I'll fully test these games when Play! gets to that level.

Until then, the best way you can help is by testing games and telling what goes wrong. I'd also suggest to be pedantic, as in telling exactly what goes wrong so that Jean or any other collaborator can look through it more easily.

If the game works fine on your device now, close this issue and have fun!
To me, it's still slow and has a really annoying beeping sound that I have to pinpoint exactly what's causing it.

**Comment by Fadi5555** [comment]
@keyaku thank you so much for your help.
Don't worry I'll test it and other games as well to see how your work is going far and effective other games which was previously only a black screen.

Please can you do something to stop beeping on games? Like resident evil 4 it's so annoying issue.
About my device is an iPad air 2 which is pretty good device to see the progress of work on it.

Finally if you can give me the deb file of play! To could test your work it's my pleasure.
From now I'll be your tester and give you report about games.
Thanks again for help @jpd002 to keep this project up.

**Comment by jpd002** [comment]
Should work on today's build (available on Cydia).

**Comment by Fadi5555** [comment]
Thank you so much for everything.
What about start and select buttons not mapping on ps3/4 controllers? Can you map them please?
