### ISSUE TITLE
.hack// games black screen

### ISSUE THREAD

**Issue by skompc** [jpd002/Play-#364]
Soi just tried .hack//fragment on my device and it shows a black screen with f/s ranging from 0 to 5... I also found out that all .hack// games do this... So any idea why? I just want your thoughts on this

**Comment by LoungeKatt** [comment]
Same happens with my iPhone. Some games simply aren't compatible yet.

**Comment by literalmente-game** [comment]
Issues for the .hack// games were moved to here https://github.com/jpd002/Play-Compatibility/issues?utf8=%E2%9C%93&q=.hack%2F%2F . This issue can be closed now
