### ISSUE TITLE
When will Play! able to run god of war 1 and 2

### ISSUE THREAD

**Issue by finale444** [jpd002/Play-#365]
GOD OF WAR is very popular series of ps2 so when will god of war running on Play! pls focus god of war make this emulator able to run god of war

**Comment by MoochMcGee** [comment]
Use PCSX2.

**Comment by finale444** [comment]
I Know but PCSX2 Only for Window not Android and I want to play it on my android device And only Play! Emulator build for Android

**Comment by Depersonalized** [comment]
No-one can say exactly when they will be playable in Play! And also, the
God of War games are quite demanding, so you'll probably never be able to
play them on your Android device.

**Comment by finale444** [comment]
Depersonalized , How can you defiantly say that Android device will never emulate god  of war probably i think that you forget about now a days android technologie android power increase day by day and I think that now a days android device ability to emulate PS2 game but only need better emulator like ppsspp,ppsspp work full speed in god of war ghost of Sparta and chains of Olympus on lower device And I hope that JPD002 make the Play! emulator able to play god of war and other popul game i can't say full but playable and in near future android device reach the quality to emulate TOTAL COMPLICATED COMBINED MACHINE ( PS2).

**Comment by MoochMcGee** [comment]
@finale444 What the fuck are you trying to say?

**Comment by finale444** [comment]
I only trying to say and I want to know that I said

**Comment by finale444** [comment]
MoochMcGee, I want to ask you one thing

**Comment by finale444** [comment]
when will you first realease of your emotionless because emotionless is your challenge accepted project as you said and I 'm waiting for your first release

**Comment by MoochMcGee** [comment]
@finale444 Approximately never.

**Comment by jpd002** [comment]
@finale444 There's still so much work to do, I can't answer that question at the moment. @Depersonalized is not wrong, even if the game was supported in the current build, the game would probably not run at good speeds. I think we'll have to wait at least one year to optimize the emulator and to have devices that can handle the processing power to emulate the PS2.

**Comment by cerroverb** [comment]
> No-one can say exactly when they will be playable in Play! And also, the God of War games are quite demanding, so you'll probably never be able to play them on your Android device.
> 
> On Mon, Dec 21, 2015 at 3:58 PM, finale444 [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > I Know but PCSX2 Only for Window not Android and I want to play it on my
> > android device And only Play! Emulator build for Android
> > —
> > Reply to this email directly or view it on GitHub
> > [#365 (comment)](https://github.com/jpd002/Play-/issues/365#issuecomment-166340385).

this didn't age well haha. to be fair it was hard to predict
