### ISSUE TITLE
Prince of persia Sand of Time issue

### ISSUE THREAD

**Issue by finale444** [jpd002/Play-#367]
JPD002 PLS fix the crashesh in prince of Persia sand of time for Android improve the compatibility and speed to prince of Persia sand of time

**Comment by jpd002** [comment]
Thanks for reporting this. I don't have the game right now, so, it'll have to wait till I get my hands on a copy.

**Comment by finale444** [comment]
Thanks for replay,your are right first you get a copy on your hands and I think that it is not so problem with prince of Persia sand of time only need to fix some crashes and give prayable speed you can  watch the video of prince of Persia sand of time on android  link vnd.youtube:cbjUK6boh1A?vndclient=mv-google&vndapp=youtube_mobile&vndel=watch , I will wait for your replay

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/287. Game is now in-game, this issue can be closed
