### ISSUE TITLE
Question about aarch64

### ISSUE THREAD

**Issue by Fadi5555** [jpd002/Play-#368]
@jpd002 hi.
Well I saw many things interesting me. I saw many added support for many things. Please can you tell me what are these if you don't mind?
I'm really curious to know them. Also what is (OP and MD)? I saw them more?

Anyway this is a screenshot for what I mean:
![image](https://cloud.githubusercontent.com/assets/10546081/11986287/e60ea8f2-a9de-11e5-8465-d24f48c0a589.png)

Also there is more of adding support down there.
As I told I just want to know what are these and what will be the advantages of them?
Thanks a lot.

**Comment by jpd002** [comment]
It's a work in progress for AArch64 (arm64) support on Android and iOS. Most of the work has been completed, but there's still some things that need to fixed before I merge it in the main branch.

**Comment by Fadi5555** [comment]
Congratulations about merging 64 bit to main branch. Looking forward to to test it
And  i hope see the difference in speed of running games.

Thanks a lot.

**Comment by Fadi5555** [comment]
I'm sorry to said that. But after merging 64 to iOS but the speed is barely noticeable specially on movies of games also it's not all games effect like resident evil 4 the speed of play doesn't change at all. Is that normal? Because you said it will effect on speed of games?

**Comment by jpd002** [comment]
Yeah, it's normal. From what I've tested, games get, at most, a 25~30% speed increase on the 64-bits version. It also depends on the situation since some games are not bound by EE/IOP/VU execution, so, those might not get much faster because the bottleneck is somewhere else (ie.: draw call or GPU bound).

**Comment by Fadi5555** [comment]
Got your point.
Anyway my device is iPad air 2 i have tested my games list. So far some cutscenes are noticeable of speed a little bit. On game play also a little bit. Excluding resident evil 4 game play its 3-4 fps.

I hope you got major things on it to make games going up to speed. Maybe one day you can make them run at full speed at least for many games. By optimizing it more and more.

Anyway this is a good thing you had done. I hope many good things will come.
Thanks a lot for everything. It's really appreciated

**Comment by jpd002** [comment]
There's still much that can be done, AArch64 support was one thing. The next optimization I want to investigate is accessing RAM directly from jitted EE and IOP code.

**Comment by Fadi5555** [comment]
@jpd002 sorry to tell you this here.
Well please can you tell me what is your framerate on resident evil 4  or any game on you when it start play?
And which device you use to play? Because I guess my iPad Air 2 didn't effect of supporting 64-bit?
Because I tried to download old version of play! It's look like the speed is the same. Please can you look at this? Maybe you didn't commit about iPad Air 2 or something like that. Because you said the speed is increasing about up to 25% on iOS/android devices with 64 bit?
I'm sure there's something wrong with me.

If you can remember about resident 4 when you said it runs on you normally but I get a black screen but when I gave you my save data you fix that. So I'm really sure there something wrong
Just if you have iPad Air 2 or your friends have one try to test it on it and compare between your device and that one.
Sorry to make it too long but I wrote this because of my testing on old version of play! And there is no notice the difference in speed.
Thanks.

**Comment by jpd002** [comment]
It runs at around 4~5fps on my iPhone 6s. I haven't done any profiling on that game, but I'm not sure it's bound by CPU emulation, so, it might explain why there's not much difference between the 32-bits and 64-bits builds.
