### ISSUE TITLE
Happy New Year Jpd002

### ISSUE THREAD

**Issue by finale444** [jpd002/Play-#371]
Happy New Year To All Of You who read this and sorry for write in this issue section because I didn't flash any other way to wish Jpd002

**Comment by phase** [comment]
Yeah, there _really_ needs to be a forum.

**Comment by yorkiesandskittles** [comment]
I successfully reproduced this issue on the development version ( ͡° ͜ʖ ͡°)

**Comment by jpd002** [comment]
Thanks! Happy New Year to everyone! Let's hope 2016 will bring decent PlayStation 2 emulation on mobile devices!

**Comment by finale444** [comment]
thanks for replay jpd002, Yes defiantly but pls don't forget God Of war 1 or 2 pls because this my dream to play god of war On Android device

**Comment by jpd002** [comment]
@finale444 There's no way to tell what 2016 will bring us!
