### ISSUE TITLE
When is Sound Emulation going to arrive?

### ISSUE THREAD

**Issue by Abz1** [jpd002/Play-#372]
Do you have any idea when sound emulation (audio) is going to arrive to play!/on android?

**Comment by Fadi5555** [comment]
I guess @jpd002 is now focusing on speed and compatibility of games before add audio support.
Now pc version has sound support unlike iOS and android still.
Anyway maybe he will add sound soon no body knows.

**Comment by Abz1** [comment]
@Fadi5555 thanks for the reply. Yeah I guess the dev is focusing on emulation rather than audio ATM because it's more important.

**Comment by jpd002** [comment]
Sound is not really appealing if the game's not running at 60fps and there's still many issues with audio emulation. So, I can't really give an ETA, but once the frame rate starts getting interesting, I'll consider enabling audio output.
