### ISSUE TITLE
Dragon ball z tenkaich 3 issue

### ISSUE THREAD

**Issue by finale444** [jpd002/Play-#373]
Jpd002, PLS FIX THE ISSUE IN TENKAICHI 3 CHARACTER NOT SHOW IN SELECT LIST AND IN GAME 
SPEED IS GOOD THAN OTHER GAMES BUT NEED MORE SPEED  FOR PLAING ON ANDROID FIX CHARACTER AND SPEED AND EVERY THING IS PERFECT AND I ALSO WANT TO ASK YOU ONE THING THAT WHEN YOU ADD SOUND FOR ANDROID.

**Comment by seadil** [comment]
Could you show us screenshots of those graphical glitches?

jpd002 is already working on performance improvements (speed), after that comes sound:
https://github.com/jpd002/Play-/issues/372#issuecomment-168574319

Please search and read issues before you post a new one.
And also try to write issues in a readable style. Thanks.

**Comment by finale444** [comment]
Yes I know that my English is not so good but I am trying and 372 is sound issue OK but can you tell me that when will jpd002 fix tenkaichi 3 character issue, NEXT VERSION OR AFTER THAT.

**Comment by jpd002** [comment]
Reported here: #74.
