### ISSUE TITLE
Support for Need For Speed - Most Wanted

### ISSUE THREAD

**Issue by ljubomir993** [jpd002/Play-#374]
Game running, and close..

**Comment by seadil** [comment]
More details would be nice, e.g. your device/platform and which version of the game (Region).

**Comment by ljubomir993** [comment]
My device Sony Xperia Z2 6503, Android Lollipop 5.1.1. Version game I download from here:

http://www.emuparadise.me/Sony_Playstation_2_ISOs/Need_for_Speed_-_Most_Wanted_%28Europe%29/153951


Maybe suggest me, where I can download games, who works on this simulator. Thanks!

**Comment by atomic83GitHub** [comment]
Download a game is not a good solution, they can be broken.
Buy the game that you want to play (not expensive today), and rip it on a pc (imgburn for Windows or Linux equivalent).

**Comment by jpd002** [comment]
Just to give an update on that, it's possible to go in-game now, but there's many visual problems (mostly due to missing PATH3 masking emulation).
