### ISSUE TITLE
DBZ Games!!!

### ISSUE THREAD

**Issue by DekuTrunksSSJ7** [jpd002/Play-#379]
Can you guys work on more games like dbz bt3 and b3!? PLEASE!!!

**Comment by DPersonalized** [comment]
Can people stop posting pointless crap here!? PLEASE!!!

**Comment by MoochMcGee** [comment]
God, this reminds me of the super entitled pokekiddies.
@DekuTrunksSSJ7 Just use PCSX2 you stupid shit.

**Comment by DPersonalized** [comment]
@MoochMcGee Your profile picture fits your post to a T :smile:
