### ISSUE TITLE
Debugger should be free and enabled in release builds

### ISSUE THREAD

**Issue by unknownbrackets** [jpd002/Play-#38]
I remember when PPSSPP was just like Play! - it had Debug, DebugFast (no debugger iirc), Release, etc.

In fact, I think the very first change I made to PPSSPP's jit was [adding breakpoints](https://github.com/hrydgard/ppsspp/pull/439).  By now, conditional breakpoints, memory breakpoints, etc. are all implemented this way in jit.

I was trying to debug the crash in #37 and noticed that 20-30% of time was spent in `MipsExecutor::MustBreak()`, which could probably be nearly free using compiled-in breakpoints.

I definitely think Play! should use the same method - essentially free breakpoints are great.  There's nothing like debugging a game at full speed.

-[Unknown]

**Comment by jpd002** [comment]
That's a good idea. Makes more sense to implement breakpoints that way. If we wanted to make the debugger totally free, we'd also need to change the way information is collected for the frame debugger.

**Comment by unknownbrackets** [comment]
Well, you can just compile that in or not based on if there are breakpoints, and always clear all blocks.

PPSSPP just uses a stack walker.  We don't do any frame tracing.  So we're just like MSVC, getting garbage stack traces when things are garbage.  But it's not so bad.

-[Unknown]

**Comment by MisterHubs** [comment]
Is the debugger not already added? At least on Windows it is part of the weekly, so isn't this resolved?

**Comment by jpd002** [comment]
@MisterHubs I would still like to have the debugger in the release build at some point instead of having a separate build for that purpose.

**Comment by MisterHubs** [comment]
@jpd002 Ah, I get what you mean now, yeah.

**Comment by Gamemulatorer** [comment]
How about this now

**Comment by jpd002** [comment]
Breakpoints are free now (jitted in blocks). We still have a separate debugger build though because there's some overhead in the ability to take frame dumps. I would still love to have the debugger/frame debugger in the official builds, but it's not a priority for me atm (but I can help anyone who'd like to work on that).
