### ISSUE TITLE
Incompatible games and configuración bugs

### ISSUE THREAD

**Issue by tonytorres93** [jpd002/Play-#381]
![screenshot_2016-01-25-21-07-16](https://cloud.githubusercontent.com/assets/16891449/12571656/cbb5fcf6-c3a8-11e5-8a48-14ebd90b89ff.png)
Creó que si logran hacer que corra bien un juego complicado puede correr los demás y sólo pueden dedicarse a la corrección de bugs testeados desde lenovo yoga tablero estoy muy esperanzado con esta app

**Comment by literalmente-game** [comment]
This issue is invalid (not even an issue tbh), and can be closed.
