### ISSUE TITLE
Regression on gta liberty city story [BESLES-54136]

### ISSUE THREAD

**Issue by annahana** [jpd002/Play-#382]
system windows 7 pro x64
gpu amd radeon hd 6450
cpu intel core i3 2120 
ram 4 gb

game do not boot anymore
last version working from 20.12.2015
virst version not working from 03.01.2016

**Comment by jpd002** [comment]
Thanks for reporting this and providing accurate information about the version you've tested. I'll get the game and see what broke.

**Comment by jpd002** [comment]
The game should boot again now in the latest weekly build (2016-03-10). Not playable at the moment though.
