### ISSUE TITLE
Grandia Xtreme doesn't work

### ISSUE THREAD

**Issue by BurnDrifter** [jpd002/Play-#383]
# **

![screenshot_2016-01-31-12-01-17](https://cloud.githubusercontent.com/assets/16985021/12701721/5d272594-c812-11e5-9085-8152779aab4d.png)
**

**Comment by BurnDrifter** [comment]
![screenshot_2016-01-30-16-28-42](https://cloud.githubusercontent.com/assets/16985021/12701722/6d90da2e-c812-11e5-80dc-11e7aaaa71b9.png)

**Comment by BurnDrifter** [comment]
After opening Grandia Xtreme

**Comment by jpd002** [comment]
Which version of the game have you tried? I know the Japanese version should boot at least, but I don't know about the US or EU versions.

**Comment by BurnDrifter** [comment]
I used the US Version(NTSC-U)

**Comment by atomic83GitHub** [comment]
There is a compat report for that game, this should be close.

**Comment by jpd002** [comment]
https://github.com/jpd002/Play-Compatibility/issues/99
Feel free to comment over there if there's still an issue with the game.
