### ISSUE TITLE
iOS port

### ISSUE THREAD

**Issue by Anuskuss** [jpd002/Play-#384]
The app crashes while scanning the home directory (`/private/var/mobile/` || `~/`), because the directory may be too big. Also there might be an `depends:mobilesubstrate` in your `control` file because the icon doesn't always appear.

**Comment by jpd002** [comment]
Thanks. I didn't know about the problem with the icon not appearing after installing. How can you reproduce that problem?

**Comment by Anuskuss** [comment]
When I'm installing the **ipa**, deinstalling and then install the **deb**.

**Comment by jpd002** [comment]
Sorry, it's been a while, but I've uploaded a new test version on Cydia tonight, which now depends on `mobilesubstrate` and which looks for loadable files in `~/Documents` instead of `~`. 

Tell me if it fixes the problems you were having. Thanks!

**Comment by Anuskuss** [comment]
@jpd002 First of all, thanks for replying. I totally forgot about this issue :smile:

I can finally open **Play!**, since you let it search in `~/Documents`. Just a reminder that it became a common practice to create a folder like `~/Documents/Play!/` (eg PPSSPP, iNDS), so you might do that as well. It would also be a nice idea to include a Public Domain ISO in there, for people who just want to test Play!.

Secondly, I want to say that my "recommendation" to include `depands:mobilesubstrate` was totally bs :neutral_face: (since my original post I experimented with packages and found out that it was my fault), so please remove that point.

Additionally you may want to include an icon file for Cydia, so that your `control` looks something like this:
```
Package: com.jpd002.play
Name: Play!
Version: 0.30-20160503
Architecture: iphoneos-arm
Description: PlayStation 2 Emulator
Homepage: http://www.purei.org/
Depiction: http://www.purei.org/index.php
Icon: file:///Applications/Play!.app/AppIcon60x60@2x.png
Maintainer: Jean-Phillip Desjardins <jdp002@gmail.com>
Author: Jean-Phillip Desjardins <jdp002@gmail.com>
Section: Games
```

**Comment by jpd002** [comment]
Thanks for the feedback. I like the public domain ISO/ELF file idea, that would prevent people from thinking the emulator is not working when they first start it.

**Comment by Anuskuss** [comment]
Also can you add this to your `ìndex.php` to make the depiction page in Cydia nicer:
```html
<head>
<meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=0">
</head>
```

I haven't looked much into your HTML but I guess it will work as intended.

**Comment by atomic83GitHub** [comment]
So this is fixed right?

**Comment by atomic83GitHub** [comment]
And what about now?

**Comment by jpd002** [comment]
The port has existed for a while now. Closing this.
