### ISSUE TITLE
(Android) Time Crisis 3 doesn't work

### ISSUE THREAD

**Issue by 47MWCSBN** [jpd002/Play-#385]
![screenshot_2016-02-19-21-28-56](https://cloud.githubusercontent.com/assets/17338150/13178118/d593e7be-d74f-11e5-99c1-e02288f3d72a.png)
![screenshot_2016-02-19-18-35-08](https://cloud.githubusercontent.com/assets/17338150/13178124/de17ad9e-d74f-11e5-955e-f2e842e1b855.png)
I have a blank screen on my android how to fix this?
Im using Advan S4k

**Comment by atomic83GitHub** [comment]
The 2nd work, I will test the 3rd to see if the issue is still here.

**Comment by jpd002** [comment]
Thanks for the report.
