### ISSUE TITLE
Directx 9/10 backend

### ISSUE THREAD

**Issue by dona12345** [jpd002/Play-#387]
For windows 32/64 bit instead of opengl

**Comment by phase** [comment]
DirectX 12 would be nice for Windows 10 users.

**Comment by DasBiest** [comment]
Focusing on such old APIs would be counterproductive.As @phase has said, the only logical API levels would be DX12 and for Win7/8(.1) DX11.

**Comment by annahana** [comment]
yes dx12 for windows 10 would be cool becaus it would make the emulator runable on windows mobil 10 in the future withe accepteble performance. 

dx11 will make in the long run not mach sense becaus most will use vulcan on windows 7/9/8.1 because of performance. but as a fallback for older hartware dx11 wold be nice.

**Comment by DPersonalized** [comment]
Pretty sure 99% of everything that can run DX11 can run DX12.

**Comment by annahana** [comment]
yes if we dont implement feature level 12.0 or 12.1 most hardware will ran good. downt know how dx12 perform with hartware with featur level 10.1

the qustion is what will be with windows 7 and 8.1
vulkan or dx11 becaus old hartware will not become new drivers for vulkan,
or will windows 7 and 8.1 just have opengl

**Comment by atomic83GitHub** [comment]
I think there is no benefit supporting DirectX api. It is Windows only and have less feature than OpenGL/Vulkan.

**Comment by jpd002** [comment]
There's already a DX9 rendering back-end, but it's far from being on par with the OpenGL rendering back-end. Focus is on OpenGL (later, it will be on Vulkan), DX9 is just here to simplify things with the frame debugger (even though that's quite debatable).
