### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by GuilhermeGS2** [jpd002/Play-#388]
Why you guys don't use Buildbot for automated builds, like PPSSPP, PCSX2, JPCSP and other emulators do?

**Comment by jpd002** [comment]
I do use Jenkins for automated builds, but the servers don't have a public address. I might consider making them public if the project gets to a point where more commits are made per day.

**Comment by atomic83GitHub** [comment]
Automated builds are implemented now, @jpd002, you can close the issue.

**Comment by jpd002** [comment]
Yup, builds are now made by TravisCI and Appveyor and are available on [here](http://purei.org/downloads.php).
