### ISSUE TITLE
Use system memory mapping to resemble PS2 memory

### ISSUE THREAD

**Issue by unknownbrackets** [jpd002/Play-#39]
Currently, at least in debug, easily 66% of time is spent in CMemoryMap.  Even if this is better in release, memory access is something that's definitely critical to performance.  And doing it well can also lead to a lot of simplicity.

I realize the ps2 has an MMU and can remap addresses, but as long as the host can do so in 4KB chunks, this task can be delegated (except for special memory ranges) to the CPU.

Both PPSSPP and Dolphin use memory mapping in this way.  PPSSPP doesn't have to deal with special access or remapping, but Dolphin does - I think they backpatch loads and stores in the jit when they first segfault.  PPSSPP has historically just used a few ifs (except in "fast memory" mode, where it just crashes PPSSPP if it accesses bad addresses.)

Baking in checks for ranges of memory and accessing memory with a direct MOV/LDR/etc. (when in a proper range) would probably help a lot.  AFAICT, it currently does not only a func call but also iterates a vector for each (!) lw etc.  Maybe I'm wrong.

Of course, baking it into jit means clearing blocks when the pages change.  Could be a performance problem if there's a game that changes them a lot... not impossible.  Could jump to a custom ABI jit function that would get rebuilt on page change.

-[Unknown]

**Comment by jpd002** [comment]
There's indeed a lot of space for improvement regarding memory accesses in the emulator. The JIT blocks generated for VU microprograms already access VU memory directly, but there's nothing for the EE and IOP blocks yet. I'll look into what PPSSPP and Dolphin do and see how something similar could be implemented in Play!

**Comment by Gamemulatorer** [comment]
How about this now?

**Comment by jpd002** [comment]
There's been some improvements to this done 3 years ago: the EE and IOP now have some kind of mapping table they can use from JITed code to access memory directly without going through a function call.

There's still space for improvement since there's a test to see if the entry in the table is valid that could probably be removed. I don't think this is a priority as there are other bottlenecks that would be more interesting to tackle.
