### ISSUE TITLE
Metal Slug 4 works, but very slowly

### ISSUE THREAD

**Issue by Newbie13XD** [jpd002/Play-#395]
Metal Slug 4, the PS2 version, works, but very, very slowly. I get 1, and very rarely 2, FPS on the into logo(s), takes ages to launch. It sits at a constant 2 draw calls per frame. I wasn't patient enough to get past the logo(s), mainly because it took minutes jisy to get anywhere. 
I thought this game wouldn't be very hard to run, considering that it's 2D, which is why I'm reporting this.
I hope this is to some sort of help, and if not, let me know :)

Phone:
OnePlus 2;
Snapdragon 810
4GB RAM/64GB storage model

**Comment by jpd002** [comment]
Thanks for the report. Funny, Metal Slug 6 works fine... I haven't tried Metal Slug 4 though. Which version (SLUS, SLES, etc.) of the game have you tried?

**Comment by jpd002** [comment]
I've just tried Metal Slug 4 on my Galaxy S7 and it works ok (frame rate varies wildly from 20 to 60fps). Game ID is SLUS-20971.

**Comment by literalmente-game** [comment]
Issue can be closed as https://github.com/jpd002/Play-Compatibility/issues/268 was already made
