### ISSUE TITLE
R2 / L2 Buttons don't work in several games - Android (Gamepad)

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#396]
I've tested some games and some controls (R2 / L2) isn't working properly or not supported?

**Tested on Android Shield TV with Shield controller**
- Sniper 2
- Tokyo Road Race
- Whiteout

and propably more

**Comment by jpd002** [comment]
Thanks for the report. I don't think this is Android specific as these buttons don't seem to work properly in those games too:

- Grandia 2
- Wangan Midnight

I broke something with pressure sensitive buttons at some point when I was changing stuff in SIO emulation, so I'll have to take a look to see what's going on.

**Comment by jpd002** [comment]
Should be fixed by this: 57f4b4f. I'll try to post a new build this week.

Related: #437.

**Comment by atomic83GitHub** [comment]
Any status on it?

**Comment by jpd002** [comment]
Closing this for now. I can't test the games mentioned by @JohnGodgames, but Grandia 2 and Wangan Midnight are fixed. Feel free to comment if the games are still broken.

**Comment by Konrad1374** [comment]
wangan midnight R is broken i think. playing on keyboard but i think it doesnt use the accelerator button to 100%.(after beating a rival it show stats including flat out time, its 0 second every time+the cars never reach their top speed)
