### ISSUE TITLE
Army Men: Sarge's War and others - Graphical issues (blinking / corrupted textures)

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#397]
Tested on **Play-20160417-64**
I've seen this bugs at more games (don't remember now).

**Frame dump from the first image** [here](https://mega.nz/#!7Y9i2TxS!M3Wt3A7hlSxYL_hHDFjLvThsK21Tbl-HmtDNi0b8v3I)

![army men sarge play issue 1](https://cloud.githubusercontent.com/assets/11453507/15029944/2a4fa712-1250-11e6-88e8-f44a1706e5c0.JPG)

![army men sarge play issue 2](https://cloud.githubusercontent.com/assets/11453507/15029959/3a580370-1250-11e6-990d-fa03de18d72e.JPG)

![army men sarge play issue 3](https://cloud.githubusercontent.com/assets/11453507/15029966/41d9fa0e-1250-11e6-9c03-22589a4895ba.JPG)

![army men sarge play issue 4](https://cloud.githubusercontent.com/assets/11453507/15029973/4771233e-1250-11e6-82b3-19411de066cd.JPG)

![army men sarge play issue 5](https://cloud.githubusercontent.com/assets/11453507/15029979/4d3012f8-1250-11e6-8db8-1e5c3bba11af.JPG)

**Comment by jpd002** [comment]
Thanks for reporting this. I'm guessing there's some issues with texture caching. I'll need to get that game to figure out what's going on.

**Comment by jpd002** [comment]
Moved here: https://github.com/jpd002/Play-Compatibility/issues/1397.
