### ISSUE TITLE
Dakar 2 - Graphical issues (Completely black cars)

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#398]
Tested on **Play-20160417-64**
Game has also bugs with shadows and sun glow effect

**Frame dump from the first image** [here](https://mega.nz/#!XVlnCD5Q!KtHL0PU24YDdzE9R6UpGKRsHykAXiDv8V5q6wsPnG-M)

![dakar 2 play issue 1](https://cloud.githubusercontent.com/assets/11453507/15030845/0438bb40-1255-11e6-88f2-03e6ce7e6e64.JPG)

![dakar 2 play issue 2](https://cloud.githubusercontent.com/assets/11453507/15030852/09d3914c-1255-11e6-8215-a4be6438a317.JPG)

![dakar 2 play issue 3](https://cloud.githubusercontent.com/assets/11453507/15030858/0e7037dc-1255-11e6-9f2a-d0d13fa244f3.JPG)

**Comment by jpd002** [comment]
Thanks for reporting this. This is quite peculiar, I'll take a look at the frame dump to see how color is being computed for the cars.

**Comment by jpd002** [comment]
Some of the rendering bugs affecting this game are fixed in the current weekly build. Cars are rendered properly inside the menu but are still black in the actual game and the skybox still clips with the road sometimes.

**Comment by boberto5888** [comment]
Blacked out cars glitch was fixed with the merge of the [castlevania_betterfix branch](https://github.com/jpd002/Play-/compare/9fdd4db52482...d99b3a0a6dfb).

![dakar](https://user-images.githubusercontent.com/22404524/50532009-e9e33380-0acf-11e9-92d0-45e8c5e96a2e.gif)

jpd002/Play-Compatibility#662

**Comment by jpd002** [comment]
Thanks for the update!

Going to close this since info is in compatibility tracker now.
