### ISSUE TITLE
Baldur's gate games - Graphical issues

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#399]
Tested on **Play-20160417-64**
Both of Baldur's gate games have the same bugs...

**Frame dump** [here](https://mega.nz/#!GB13iQZC!URmG7JBwShROkHe2kroKcDv1Hqcz0bvQs97falYt6y0)

![baldurs gate play issue 1](https://cloud.githubusercontent.com/assets/11453507/15031165/1bfb1550-1257-11e6-9846-64a30b228ebc.JPG)

![baldurs gate play issue 2](https://cloud.githubusercontent.com/assets/11453507/15031183/22af50be-1257-11e6-9012-d446aebe6d1b.JPG)

![baldurs gate play issue 3](https://cloud.githubusercontent.com/assets/11453507/15031187/27d0e116-1257-11e6-8d75-85a0b8b5ae57.JPG)

![baldurs gate play issue 4](https://cloud.githubusercontent.com/assets/11453507/15031191/2e5171fe-1257-11e6-9c9b-5b1517f7e11b.JPG)

![baldurs gate play issue 5](https://cloud.githubusercontent.com/assets/11453507/15031196/3620dab4-1257-11e6-9e7f-8214c62cc771.JPG)

**Comment by jpd002** [comment]
Thanks, this is a known issue. I have a [fix](https://github.com/jpd002/Play-/blob/41811e7c1a0be57aa5c5f7cd230667caddcc46fb/Source/ee/Vif.h#L10) for this, but it hasn't been activated properly yet (still need to do some hardware test to verify the behavior).

**Comment by atomic83GitHub** [comment]
Is this issue still valid? @jpd002 What about these hardware tests?

**Comment by jpd002** [comment]
The fix was merged in master a while ago.
