### ISSUE TITLE
Xinput API

### ISSUE THREAD

**Issue by LasagnaPie** [jpd002/Play-#4]
This emulator lacks the Xinput API for Xbox 360 Controller or others via a wrapper 
e.g. Dualshock 4 controller that i use.

http://msdn.microsoft.com/en-us/library/windows/desktop/ee417003(v=vs.85).aspx 

e.g.
"CROSS", XINPUT_GAMEPAD_A 
"CIRCLE", XINPUT_GAMEPAD_B,
"SQUARE", XINPUT_GAMEPAD_X
 "TRIANGLE", XINPUT_GAMEPAD_Y

**Comment by Zero3K** [comment]
Has this been fixed yet?

**Comment by atomic83GitHub** [comment]
I tested a Xbox one controller and it work but the "LT" and "RT" button doesn't work (analog trigger).

**Comment by jpd002** [comment]
This is still an issue. The emulator still uses DirectInput to handle input on Windows.

**Comment by jpd002** [comment]
XInput support is finally available in the latest automated build.
