### ISSUE TITLE
Dynasty Warriors games - Graphical issues (glitchy characters / not visible weapons)

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#402]
Many of Dynasty Warriors games have the same bugs (maybe all)

**Dynasty Warriors 3**

so it should look like
![dyn war 3 pcsx2](https://cloud.githubusercontent.com/assets/11453507/15122690/81345464-1620-11e6-89d5-be1968fd0e77.JPG)

![dyn war 3 play issue 1](https://cloud.githubusercontent.com/assets/11453507/15122109/caae8b4e-161d-11e6-9dcf-37d08849a75e.JPG)

![dyn war 3 play issue 2](https://cloud.githubusercontent.com/assets/11453507/15122123/e03f0bb4-161d-11e6-97f5-3f71471c1337.JPG)

**Frame dump** [here](https://mega.nz/#!qIVE2RIJ!ojksFz26tp6xmQAsZqv6c_CRcXBHTQaYjEVXLz8839s)

**Dynasty Warriors 2** [Video](https://www.youtube.com/watch?v=F9e9X3d271Q)

**Comment by literalmente-game** [comment]
This issue can already be closed (we have up to date entries on the new compatibility tracker https://github.com/jpd002/Play-Compatibility/issues/687 and https://github.com/jpd002/Play-Compatibility/issues/141)
