### ISSUE TITLE
Kingdom Hearts 2 Final Mix (Playtesting)

### ISSUE THREAD

**Issue by KinCoded** [jpd002/Play-#404]
Every time a weekly gets released I'll try this game out on my Sony Xperia Z1 and post results.

As of the latest weekly released May 8 2016 the game boots up properly at an unsteady framerate of 7-30fps, but at a really slow speed. I can select a new game in the menu, select difficulty and audio settings and all that, and start a game. However, the first FMV cutscene fails to load.

I don't know how to get a save file after the opening cutscene, but as soon as i figure that out I'll start trying that.

**Comment by jpd002** [comment]
Unfortunately, Kingdom Hearts 2 doesn't work in Play! at the moment. You can only navigate through the main menu and loading a saved game will just hang the emulator.

**Comment by KinCoded** [comment]
In that case I'll just update this when it starts working.

Though i vaguely remember you or someone else posting in game screenshots. Though that might have been KH1.

**Comment by jpd002** [comment]
It's now possible to get in game, but I wouldn't consider it playable since it's quite unstable (might hang or characters might explode).

**Comment by ramapcsx2** [comment]
@jpd002 
Just a heads up: Make sure you record your funniest emulator messups!
We lost our video of Star Ocean 3 rotating heads and boobs physics video.
That stuff was golden ;p
