### ISSUE TITLE
NHL Games - won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#407]
Tested on **Play-20160508**

**NHL 07**

```
Code Size = 9262208, Stack Size=135168, Max Heap Size = 24122960
Allocating Debug Heap of 0 and data heap of 24122944

```

**NHL 09**

```
Begin processing command line arguments...
Processing command SLUS_217.71;1
Loading data from DVD...
Configuring memory...
Code Size = 7936320, Stack Size=69632, Max Heap Size = 25514384
Allocating Debug Heap of 0 and data heap of 25514368
options.mDebugHeapSize =  0
Setting up allocators.
SystemInitialize()

```

**Comment by JohnGodgames** [comment]
can't provide any logs :(

**Comment by jpd002** [comment]
I've tried NHL 2002 and that version seems to be waiting for some bit to be set in GS CSR. The game boots if I hack in something to have that bit set all the time, but hangs later on with some movie playback issue. 

I'll have to get the other NHLs to see if they are suffering from the same issue.

**Comment by jpd002** [comment]
NHL 2002 is playable with the changes that are currently in master. I'm planning to create an official build this week-end.

**Comment by JohnGodgames** [comment]
Great

**Comment by jpd002** [comment]
Would need retesting, games probably work better now.
