### ISSUE TITLE
Bloody Roar 3 - Graphical issues (missing characters)

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#412]
Maybe dupe of https://github.com/jpd002/Play-/issues/400

Tested on **Play-20160508-64**

**Frame dump** [here](https://mega.nz/#!Gd8y3aSZ!Xg55zQYiB-5biMAKxZKJfbl5ChL3NB7hGbA2OCybtWc)

![bloody roar 3 play 1](https://cloud.githubusercontent.com/assets/11453507/15521473/49d595d0-220c-11e6-9e34-e9616c96671f.JPG)

**Comment by jpd002** [comment]
A bit better now: https://github.com/jpd002/Play-Compatibility/issues/628, not quite there yet.
