### ISSUE TITLE
Obscure: The Aftermath - Graphical issues (glitchy characters)

### ISSUE THREAD

**Issue by JohnGodgames** [jpd002/Play-#413]
Tested on **Play-20160508-64**

**Frame dump** [here](https://mega.nz/#!aVljTAKb!VObUsuogAh_Jlz3XzuESiq_5CmCF7aVk7COjdOZULdI)

![obscure 2 1](https://cloud.githubusercontent.com/assets/11453507/15521973/40ddf7f8-220f-11e6-8578-842fe796878c.JPG)

![obscure 2 2](https://cloud.githubusercontent.com/assets/11453507/15522000/79b1e896-220f-11e6-8699-ed0dcdc40ddc.JPG)

**Comment by IllusionMan1212** [comment]
This issue is addressed [here](https://github.com/jpd002/Play-Compatibility/issues/92)
should be closed

**Comment by jpd002** [comment]
Thanks!

**Comment by jpd002** [comment]
Created an issue for US version since that's the one that was mentioned in this issue: https://github.com/jpd002/Play-Compatibility/issues/121.
