### ISSUE TITLE
iOS Version of Play!

### ISSUE THREAD

**Issue by mk8itra1n** [jpd002/Play-#419]
I recently downloaded the iOS version of Play! after recently discovering that a PS2 emulator exists for it. I downloaded it from the official Cydia repo. The app works fine and I was able to get gran turismo 3 in my documents folder and it showed up in Play! However when I selected the game in play! it went to a black screen and crashed immediately. Since I'm new, can someone fill me in on past updates and future updates to the iOS version of this emulator and how well it runs on this platform like what can it do and what can't it do yet. Thanks so much in advance

My Device...
Device- Apple iPhone 6 Plus
Version- iOS 9.0.2 (Jailbroken)
Processor- Dual Core Apple A8 clocked at 1.4GHz
RAM- 1GB RAM
Play! Version- May 8th Build from Cydia

**Comment by Fadi5555** [comment]
There's is no issue on this app
But you have to try other game like resident evil 4 it should work fine (still slow)

**Comment by mk8itra1n** [comment]
@Fadi5555 Yeah I'll be testing out other games as well. I'll probably try out Sonic Gems Collection next and see if that works. Is there any support for the JIT recompiler or is the emulator using Interpreter?

**Comment by jpd002** [comment]
Unfortunately, Gran Turismo 3 doesn't work yet. Details about game compatibility is available here: https://github.com/jpd002/Play-/wiki/Compatible-games.

The iOS version uses the recompiler, but many games still run very slowly.

**Comment by mk8itra1n** [comment]
@jpd002 It's really impressive you got a PS2 emulator onto iOS and got the JIT Recompiler to work as well. Do you have any future plans to increase game compatibility and increase FPS in the works yet?

**Comment by JohnGodgames** [comment]
Android version uses recompiler or interpreter?

**Comment by mk8itra1n** [comment]
@JohnGodGames Not too sure. Dude you should open up an issue for the android version of Play! as well for any questions about the emulator on that platform if you can

**Comment by jpd002** [comment]
@JohnGodgames Yes, both Android and iOS versions use the recompiler.

**Comment by Fadi5555** [comment]
@jpd002 when you will merge boxart to iOS version?
Sorry to ask here.

**Comment by mk8itra1n** [comment]
@Fadi5555 Boxart is already in the iOS version ![](http://i.imgur.com/M14SUkm.jpg)

**Comment by Fadi5555** [comment]
How? That's weird. Please can you try with other games?
About me it didn't work. Look:
![image](https://cloud.githubusercontent.com/assets/10546081/15658312/b0408ce2-26c3-11e6-9f27-2c8b5fcf8c00.png)

I'll waiting for @jpd002 to merge boxart on master.
Thanks a lot.

**Comment by mk8itra1n** [comment]
It's kinda weird because my boxart looked just like yours when I first installed it. After like an hour or so the boxart started showing up on my device. I'll try out other games to see if the boxart continues to show up

**Comment by jpd002** [comment]
Yeah, merging the boxart branch is next on my TODO list. Haven't got much time to work on the iOS port recently.

**Comment by jpd002** [comment]
I've finally merged the boxart fix for iOS. It should be in the next weekly build.

**Comment by jpd002** [comment]
Also, closing this since there's not much else to say.

**Comment by mk8itra1n** [comment]
Fast forward to 2017 and I got me an iOS device upgrade. Loaded up Gran Turismo 3 on Play! ver 0.30 and it finally boots up completely and I managed to even go ingame surprisingly! I actually was able to achieve 60FPS on most of the menus and the BGM for the menus sound decent with skipping (due to the frequent frame drops to 58FPS). However while going ingame into races or into the Licence test exams, the game drops to a choppy slow motion 9-12FPS. I also should mention that any menu with a race preview such as the main menu of the game & the menu that appears right before you start a race will also cause the game to run at around 9-12FPS as well .Any updates on when we actually might see playable speeds or speed boosts as you mentioned before that the iOS version is using the JIT recompiler? Really amazing work on this emulator tho. My mouth was legit hanging open when the similation mode menu ran full speed. Looks like portable PS2 is almost here!

My Device...
Device- Apple iPhone 7 Plus
Version- iOS 10.1.1 (Jailbroken)
Processor- Quad Core Apple A10 Fusion clocked at 2.36GHz
RAM- 3GB RAM
Capacity- 128GB
Play! Version- 0.30 January 23rd Build from Cydia

**Comment by ramapcsx2** [comment]
Going ingame with the Gran Turismo engine at ~10FPS in 3D is very impressive!
Also the 3D seems perfectly fine, which is quite hard to do in this game engine.

**Comment by mk8itra1n** [comment]
Yeah I was surprised myself. The sound effects of the car ingame are choppy but sound perfectly even at 10FPS. There are texture issues on some courses, some minor and some major (garbage appears on some tracks blocking your view). Nonetheless this is really impressive!

**Comment by iOS4all** [comment]
@mk8itra1n that's really impressive indeed. Thanks for give us a report. This game is extremely powerful and even that you can hand it. Yeah iPhone 7 is petty powerful device.

There's still two missing things to achieve fullspeed.
1-JIT which is achieved already.
2-fastmem which is extremely important to force games to running faster.
3-metal rendering (it's looks like OpenGL rendering) but if we can implement this api the performance will be increased a lot.

**Comment by mk8itra1n** [comment]
@jpd002 @iOS4all Glad to give the report. iPhone 7 is pretty powerful. Still really surprised that you can actually go ingame and the menus run decently. JIT is already implemented & running. Fastmem and metal rendering might finally bring us playable speeds ingame (possible 30-60FPS) and might eliminate minor frame drops in menus keeping it at a stable 60FPS. Auto/Manual configured frameskipping could also help with performance. Will that be added to Play! in the future?

**Comment by iOS4all** [comment]
If we want a normal and stable emu we should implement these things like metal rendering and fastmem beside JIT recompiler. Anyway don't worry @jpd002 is working on it.
It just matter of time. Btw can you give a screenshot of your ps2 games? Just to see if boxart appears.
Thanks.

**Comment by jpd002** [comment]
@mk8itra1n Nice! Looking great! I had no clue Gran Turismo 3 worked that good on an iPhone 7! 

As for making it faster, I don't know what is the bottleneck in that game, but it's most likely VU emulation. I'm looking into ways to make it faster, but it's still theoretical at that point.

Thanks for the report!

**Comment by mk8itra1n** [comment]
@iOS4All Boxart only appears on Gran Turismo 3 so far. Doesn't seem to show up on any other game I add for some reason
![img_0612](https://cloud.githubusercontent.com/assets/12947869/22870119/aae5c7d8-f172-11e6-9888-7dcd0867b204.PNG)
