### ISSUE TITLE
Final Fantasy X-2 doesn't get past intro

### ISSUE THREAD

**Issue by gambrio** [jpd002/Play-#42]
I tried on the latest build and FFX and FFXII both work somewhat but FFX-2 doesn't even start. I read the compatibility list and it says "Loadable with FPS" but it doesn't specify the build/date and I was wondering why it doesn't even boot since all other Final Fantasy games on Play! seem to at least show the intro screen. 

Also, compatibility list shows that the X-2 International version works so it's strange (to me) that other doesn't.

**Comment by MoochMcGee** [comment]
Loadable with FPS doesn't mean that it boots, it means that you can load it
but there's a black screen.

**Comment by gambrio** [comment]
@MoochMcGee Yes I know that's what I meant, it starts but shows nothing:

SLUS-20672, US

**Comment by MoochMcGee** [comment]
Yeah, this is already known AND documented. This issue is completely
unnecessary

**Comment by gambrio** [comment]
Ok, but if I may ask before closing, what is the issue? Is it major or minor?

**Comment by jpd002** [comment]
I haven't looked at why the game isn't running yet, but I don't think it's a major problem. FFX-2 International kinda works (only Last Mission works for some reason), so, there must be a little hiccup somewhere that prevents FFX-2 from running.

**Comment by unknownbrackets** [comment]
Well, I'm able to select "New game" in the US version, although it dies a speedy death after that.  Since it's spending most of its time in CVPU::Cmd_UNPACK, stuff is happening... maybe it or the IPU is not sending back completion properly.

-[Unknown]

**Comment by gambrio** [comment]
@unknownbrackets So it does boot?! What build? I tried before the latest weekly builds were posted yesterday.

**Comment by unknownbrackets** [comment]
Not sure.  I did try it with both #41 and #43 merged, and with a clean rip that matched a redump crc.

-[Unknown]

**Comment by MoochMcGee** [comment]
@unknownbrackets I'd guess #41 is the reason it boots in your build.

**Comment by gambrio** [comment]
@unknownbrackets  Hold on, I'll try and compile and test with the latest stuff and test it...

**Comment by gambrio** [comment]
Nope, it still doesn't work. Either I have a bad ISO or did something wrong.

**Comment by MoochMcGee** [comment]
@gambrio It requires a specific pull request. Not just the latest stuff.

**Comment by gambrio** [comment]
@MoochMcGee Does it work for you or you haven't tested it? I'm thinking it's just a bad ISO, so I'll check that.

**Comment by unknownbrackets** [comment]
I see the white screen and logo even without #41, and it's surely not #43 (don't have a lot of time now, don't want to wait for it to rebuild.)

-[Unknown]

**Comment by MoochMcGee** [comment]
@gambrio I haven't tested it.

**Comment by gambrio** [comment]
Yep, it definitely was a bad ISO (not even PCSX2 would show anything when tested). After successfully getting the ISO from the DVD, now it does show the Square Enix logo at the very least but that's about it.

I'll update the compatibility list.

I guess this issue can be closed until further notice.

**Comment by jpd002** [comment]
@gambrio We can keep the issue open till we figure out what's wrong with the game. On my side, I've ordered a copy of the game and I'll try to see what's going on once I get it.

**Comment by maximu** [comment]
For me working but geometry are buggy and missing 

![image](https://cloud.githubusercontent.com/assets/1274014/7310254/4d699208-ea29-11e4-9dee-6ba12b4f62ce.png)

**Comment by gambrio** [comment]
@maximu Interesting ... that screenshot looks like it's taken during the first FMV video before in-game/the first battle starts. Will the FMV play all the way through if you let it or does Play! crash?

**Comment by maximu** [comment]
@gambrio No crashes detected but anyway play very slow  and unplayable can't view (Flashing screen and several missing here)

Gameplay working with some graphical bugs if use a save converted to psu extension with [mymc](/http://www.csclub.uwaterloo.ca:11068/mymc/) and imported to Play- memory manager .

![image](https://cloud.githubusercontent.com/assets/1274014/7311203/35a0aa3e-ea39-11e4-9dd3-e8423a0ac52f.png)
![image](https://cloud.githubusercontent.com/assets/1274014/7311212/69336652-ea39-11e4-9bad-ce16313b40cd.png)
![image](https://cloud.githubusercontent.com/assets/1274014/7311225/8e8154fa-ea39-11e4-992d-c62591950995.png)

**Comment by unknownbrackets** [comment]
Maybe I just didn't wait long enough after "new game"?  It seemed dead...

-[Unknown]

**Comment by gambrio** [comment]
@maximu Hm ... So you can only get in-game by loading a savegame already in-game? Still counts though.

I guess it can be updated to "in-game" now, but I don't know how well that would stand if you can only get in-game with a specific save format being loaded. I'd think in-game would mean you can actually start a new game and get to the playable part without saves skipping broken sequences/intros, so I'll ponder a bit.....

**Comment by jpd002** [comment]
Just found out the game uses colored points to draw the movie frames and also found a bug in the GS handler:

![ffx-2_01](https://cloud.githubusercontent.com/assets/6760433/7312499/3d332198-ea19-11e4-8dfc-eee20f1cc711.jpg)

The game still hangs after the movie is done playing though.

@gambrio What kind of errors are you getting?

**Comment by gambrio** [comment]
@jpd002 Never mind, the error was my fault (linker settings prior to Play!) and had nothing to do with trouble compiling per se. By the way, that screenshot you show of FFX-2 is identical to the same graphical bugs that occur in PCSX2's OpenGL renderer (the FMVs and parts of the game are split screen like that).

**Comment by jpd002** [comment]
@gambrio That's quite funny. I'm guessing it's using a weird scheme to do its interlaced video output for the movie.

aabef8abf374b94fbc0767a9a20dfd21ec3a66fb fixes the game not proceeding after the movie.

The first battle is playable, but next scene doesn't show up (looks like a VU problem).

![ffx-2_02](https://cloud.githubusercontent.com/assets/6760433/7331728/ad7d6fcc-eaea-11e4-89dd-bcd3a2a242ae.jpg)

**Comment by gambrio** [comment]
@jpd002 Good job. I'll try the US version and see if it works as well.
