### ISSUE TITLE
Code veronica black screen at main menu

### ISSUE THREAD

**Issue by bobbymc1985** [jpd002/Play-#426]
I know the compatibility on this emu is limited at this momment,however is there plans to fix the black screen issue with resi evil code veronica?

**Comment by jpd002** [comment]
Yeah, sure, I'm planning to make all games work! I don't have that game yet, but I'll get it so I can see what's wrong with it.

**Comment by bobbymc1985** [comment]
Im sure u r and doing a fantastic job.ive got as far as the main menu and the selections like load game new game etc are blanked out and remain black

**Comment by atomic83GitHub** [comment]
There is a compat report for that game, this should be close.

**Comment by jpd002** [comment]
Indeed, game works now: https://github.com/jpd002/Play-Compatibility/issues/373.
