### ISSUE TITLE
Play! built on Linux but cannot find compiled binary

### ISSUE THREAD

**Issue by parkerlreed** [jpd002/Play-#427]
````
[parker@x3720 build]$ ls Play-/ Framework/ CodeGen/
CodeGen/:
build_android  build_ios  build_macosx  build_unix  build_win32  include  License.txt  src  tests

Framework/:
build_android  build_ios     build_unix   build_winrt  License.txt  src
build_html5    build_macosx  build_win32  include      Readme.md

Play-/:
build_android  build_unix      ee_functions.xml  installer_win32  Readme.html  Source
build_ios      build_win32     icons             License.txt      README.md    tools
build_macosx   changelog.html  installer_macosx  patches.xml      Settings.md
````

Folder structure is setup correctly.

I go into `Play-/build_unix`, created a `build` directory, ran `cmake ..`, it found all the folders and frameworks, compiled, but all I seem to end up with is

````
[parker@x3720 build]$ find . -type f -executable
./McServTest
./VuTest
./autotest
...
````

And also `libPlay.a` but that's it. Is there a flag I need to set to build the full program?

**Comment by jpd002** [comment]
Nothing's wrong with your setup, the build script doesn't generate any executable at the moment. This is being worked on: https://github.com/jpd002/Play-/pull/423.
