### ISSUE TITLE
Xperia Z5 Premium - Final Fantasy X

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#429]
Graphical bugs after the first save point

![screenshot_20160530-230255](https://cloud.githubusercontent.com/assets/20205862/16492796/52394d22-3ee3-11e6-8caf-cef74715a4c3.png)
![screenshot_20160530-231117](https://cloud.githubusercontent.com/assets/20205862/16492819/709a381c-3ee3-11e6-971e-165051df0b8b.png)
![screenshot_20160706-233027](https://cloud.githubusercontent.com/assets/20205862/16681324/4a424e4a-44f4-11e6-80e4-f6c4a3dd5813.png)

**Comment by atomic83GitHub** [comment]
Have you test the game with the last build?

**Comment by jpd002** [comment]
Maybe related to #69?

**Comment by jpd002** [comment]
It's been a while, but it would be interesting to test with an up to date build:
https://s3.us-east-2.amazonaws.com/playbuilds/6f60107a/Play-release.apk
I fixed an issue that caused similar problems in Jet Li Rise to Honor on Android.
