### ISSUE TITLE
Xperia Z5 Premium - Final Fantasy XII

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#430]
Cinematics don't work, very slow (2 fps in game), graphical bugs
![screenshot_20160708-180154](https://cloud.githubusercontent.com/assets/20205862/16708414/4a57f60a-45f3-11e6-9d4f-f62d218849bd.png)
![screenshot_20160708-180650](https://cloud.githubusercontent.com/assets/20205862/16708416/4ab7c256-45f3-11e6-9a10-91524b83109b.png)
![screenshot_20160708-185203](https://cloud.githubusercontent.com/assets/20205862/16708415/4a79f016-45f3-11e6-9142-4ea7203faf19.png)

**Comment by literalmente-game** [comment]
Outdated information, up to date results can be found here https://github.com/jpd002/Play-Compatibility/issues/7. This issue can be closed now

**Comment by jpd002** [comment]
Since this is the french version, I'm guessing it's actually the EU edition of the game, so, I've created a specific compat entry for that: https://github.com/jpd002/Play-Compatibility/issues/553.
