### ISSUE TITLE
Xperia Z5 Premium - Driv3r

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#434]
This screen appears when I start the game
![screenshot_20160628-145105](https://cloud.githubusercontent.com/assets/20205862/16545137/24155bee-4121-11e6-9cb4-d85dc7f1d89d.png)

**Comment by jpd002** [comment]
My guess is that it's using 16-bits color output from the IPU. It's a known problem that currently affects many games.

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-/issues/434. This issue can be closed now

**Comment by jpd002** [comment]
Thanks for flagging the issue. Compat report for the game is here: https://github.com/jpd002/Play-Compatibility/issues/139.
