### ISSUE TITLE
The Incredible Hulk: Ultimate Destruction square, O, X, & triangle do not respond in the menu

### ISSUE THREAD

**Issue by OnijJoku** [jpd002/Play-#437]

**Comment by jpd002** [comment]
Should be fixed by this: 57f4b4fab153114f78b71e007b334fe500bcec6a. I'll try to post a new build this week.

**Comment by jpd002** [comment]
Closing this for now. I can't test this game, but I'm pretty sure that commit fixed the issue. Feel free to comment if it's not the case.
