### ISSUE TITLE
Final Fantasy XII - Cinematics

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#438]
Why do the cinematics work with the US game but not withe the French game ?
![screenshot_20160710-222930](https://cloud.githubusercontent.com/assets/20205862/16715930/86335fd8-46ee-11e6-8d81-1c1d537296ec.png)
![screenshot_20160710-223209](https://cloud.githubusercontent.com/assets/20205862/16715931/863811b8-46ee-11e6-8c4e-0fb18b5bfe71.png)

**Comment by jpd002** [comment]
Humm, that's odd. What's the game ID for the french version?

**Comment by Fred3576** [comment]
SLES-54355

**Comment by jpd002** [comment]
It works now. The movie is rendered using textured lines.
Compat tracker issue for ref: https://github.com/jpd002/Play-Compatibility/issues/917.
