### ISSUE TITLE
Kingdom Hearts SLUS-20370 has controller issues

### ISSUE THREAD

**Issue by MoochMcGee** [jpd002/Play-#44]
Kingdom Hearts cannot detect a controller in port 1. The screen showing this error is also slightly corrupt.

**Comment by jpd002** [comment]
Humm, that's odd... Can you show me a screen shot of the error screen?

**Comment by jpd002** [comment]
Is this still an issue?

**Comment by jpd002** [comment]
Closing for now because more information is needed to resolve issue. Feel free to reopen if you've got more information.
