### ISSUE TITLE
Final fantasy x bug issue

### ISSUE THREAD

**Issue by ZX3Z** [jpd002/Play-#442]
First sorry about other there's I made my phone is jack, and made me finish with out typing anything. Any way: Yo! This is my first bug report to this emulator, and I'm not sure if it is a major problem but during the video parts in the beginning of the game [Final Fantasy X] when it switches to a new video segment, a black box appears near the start button, I have only one photo of it but it happens around 4 times. It may happen more though out the game as well [not sure haven't gotten very far in it yet]. Hope it gets fixed!﻿

**Comment by ZX3Z** [comment]
Sorry can't seem to send the picture, but I put the same post on the play! Community. The picture is there.

**Comment by literalmente-game** [comment]
If you test the game again, post any new information here https://github.com/jpd002/Play-Compatibility/issues/12. This issue can be closed now
