### ISSUE TITLE
(Win64)(SLPS-25836) Super Robot Wars Original Generations Gaiden Not Working

### ISSUE THREAD

**Issue by Queen-Mansa** [jpd002/Play-#445]
Game boots to a black screen for about 15 seconds before the program crashes. 1 f/s according to the counter.

**Comment by Gamemulatorer** [comment]
Move this issue to https://github.com/jpd002/Play-Compatibility/issues

**Comment by jpd002** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/1347
