### ISSUE TITLE
(Win64) (SLPS-25733) Super Robot Wars Original Generations Not Working

### ISSUE THREAD

**Issue by Queen-Mansa** [jpd002/Play-#446]
Game boots to a black screen for about 10 seconds, the program then crashes. 1f/s according to the counter.

**Comment by DPersonalized** [comment]
If you have a report about how well a game can be played in Play!, then add it to this table:

https://github.com/jpd002/Play-/wiki/Compatible-games

It stops the issue tracker getting saturated and just makes everything more organized.

**Comment by jpd002** [comment]
Moved here: https://github.com/jpd002/Play-Compatibility/issues/1394.
