### ISSUE TITLE
Need for Speed Underground 2 (In-Game)

### ISSUE THREAD

**Issue by GuilhermeGS2** [jpd002/Play-#447]
Loading screens are fine, no bug, but is very slow. Here's some screenshots of main menu and ingame:

![ingame](https://cloud.githubusercontent.com/assets/4109111/17122460/99f1cc32-52a9-11e6-8719-a0e768ae9abd.png)
![menu](https://cloud.githubusercontent.com/assets/4109111/17122461/99f5a672-52a9-11e6-9020-02ea52ee60ae.png)

Version: Jul 24 2016

My PC:
-Intel Core i5 3470 3.2Ghz
-10Gb DDR3 1333Mhz
-GTX 650 1Gb GDDR5 128-bit

**Comment by nfsvsgta** [comment]
Woah nice

**Comment by nfsvsgta** [comment]
Try it on a iphone if possible

**Comment by nfsvsgta** [comment]
Let's hope the broken graphics get fixed

**Comment by nfsvsgta** [comment]
Tried it on ios. Crashes after loading race

**Comment by ps2lucas99** [comment]
Top

**Comment by rozhuk-im** [comment]
Got same on latest version from git @ FreeBSD 12.1, gt1030

**Comment by jpd002** [comment]
Thanks for reporting. 

Also, closing this because it belongs here: https://github.com/jpd002/Play-Compatibility/issues/768. (I saw that you already posted there, so, thank you!)
