### ISSUE TITLE
Final Fantasy X bugs (Android) (French iso)

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#449]
![screenshot_20160721-140422](https://cloud.githubusercontent.com/assets/20205862/17363656/03248400-597c-11e6-94cf-d6af87e8aaae.png)
![screenshot_20160721-145101](https://cloud.githubusercontent.com/assets/20205862/17363657/0336c7fa-597c-11e6-90d1-346d481b84a6.png)
![screenshot_20160723-151504](https://cloud.githubusercontent.com/assets/20205862/17363681/2f615a7a-597c-11e6-82a7-b618028f22e7.png)
![screenshot_20160802-155511](https://cloud.githubusercontent.com/assets/20205862/17363682/2f64a8e2-597c-11e6-98c4-d3100000d99e.png)

**Comment by atomic83GitHub** [comment]
This is a duplicate issue.
