### ISSUE TITLE
Final Fantasy X black screen

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#451]
After meeting Yuna, there's just a black screen and the music continues. It seems PCSX2 users have the same issue.

**Comment by atomic83GitHub** [comment]
It work now, close the issue.

**Comment by atomic83GitHub** [comment]
This issue can be close.

**Comment by literalmente-game** [comment]
Invalid issue (Final Fantasy X is already in-game for a long time now), updated here https://github.com/jpd002/Play-Compatibility/issues/12. This issue can be closed now
