### ISSUE TITLE
(android kit kat) resident evil 4 . 

### ISSUE THREAD

**Issue by Xx220xX** [jpd002/Play-#453]
takes to open (I believe that is normal because the iso has more than 4 gigabytes . Menu a little slow. When you start the game a beep is beeping and the image is waging . As if one frame every three seconds . Grafica exelente . ( one solution would be to add a wing on the configuration to set the graphical thus achieving run the game more fluidly . also a special configuration for audio q also buga and locks . and when opening the iso show on the screen a bar indicating the percentage ( 0 to 100% ) to indicate whether the game will be loaded or not. it q games take up to 5 minutes to start . Thank you . play! Version 00:30
![screenshot_2016-08-22-15-19-19](https://cloud.githubusercontent.com/assets/21207156/17911595/b9851d66-6964-11e6-8914-7dac8dca98f0.png)

**Comment by atomic83GitHub** [comment]
There is acompat report for that game, this should be close

**Comment by jpd002** [comment]
Indeed: https://github.com/jpd002/Play-Compatibility/issues/365.
