### ISSUE TITLE
Final Fantasy X detected as Final Fantasy X-2

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#454]
I had FF X-2 on my phone during a few days and I deleted it but now  the overview and the cover of my FF X iso are remplaced by the ones from FF X-2.
![screenshot_20160827-015554](https://cloud.githubusercontent.com/assets/20205862/18023505/2a102138-6bfa-11e6-8911-70b4312651f3.png)
![screenshot_20160827-015623](https://cloud.githubusercontent.com/assets/20205862/18023506/2a7069e4-6bfa-11e6-95cd-c0b769969286.png)

**Comment by Thunder07** [comment]
not all game serial IDs are in the current database, so sometime the search fails to get the accurate details.

I've updated the list locally, but I didn't get the chance to make the necessary changes to update it with the app, as there were changes to the way it was structured.

**Comment by Fred3576** [comment]
Fixed
