### ISSUE TITLE
Where do i get the latests builds? And whats the difference between pcsx2 and Play! ?

### ISSUE THREAD

**Issue by yahfz** [jpd002/Play-#457]
First of all, thank you so much jdp002 for this.

**Comment by Jordanesquivez** [comment]
www.purei.org
Play is on android and pcsx2 is not... amd the rate of play emulator it will surpass pcsx2

**Comment by jpd002** [comment]
Sorry about that, I didn't have much time to prepare a new build. I'll try to have one ready this week-end.

**Comment by yahfz** [comment]
Sorry if that sounded like i was complaining, i wasn't. Thank you! Is there any tutorials where i can build it myself?

**Comment by jpd002** [comment]
Posted new builds today. Instructions on how to build are available in `README.md`. If you've got specific questions, don't hesitate to create a new issue.
