### ISSUE TITLE
(Android) Sly cooper and the theivious raccoonus hangs at black screen

### ISSUE THREAD

**Issue by minuteworld** [jpd002/Play-#460]
As soon as you boot into it, it just shows a black screen with the f/s constantly switching from 7 to  8.

Tested on Gpd xd 64gig with build 2016/7/24

**Comment by atomic83GitHub** [comment]
There is a compat report for that game, this should be close.

**Comment by jpd002** [comment]
Indeed: https://github.com/jpd002/Play-Compatibility/issues/340.
