### ISSUE TITLE
SSX3 Glitches

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#465]
I've tested SSX3 and there are few prominent glitches, I've posted posted them to an [imgur album](http://imgur.com/a/r7BG1),

to summerise:
- Game : SSX3 - SLES_516.97
- tested on ubuntu (better_efficiency branch), OSX (master) 
- intro video plays but is broken in half - also no sound something common with all FMV i've seen
- there are visible drawing in the menus background of buttons/lines which shouldnt be there
- map/objects arent generally visible but they do glitch in and out for short periods
- other than that, you can run a full level (probably the full game)

Edit: 
as of the last set of commit in master, you get a blank black screen when you try to start a race.
also, the small 'thumbnail' preview of the descent (race map), doesn't show up now.

**Comment by ramapcsx2** [comment]
The game uses GIF Path 3 masking btw.

**Comment by Thunder07** [comment]
issue moved to https://github.com/jpd002/Play-Compatibility/issues/218
