### ISSUE TITLE
Persona 4 graphical glitches

### ISSUE THREAD

**Issue by minuteworld** [jpd002/Play-#467]
https://youtu.be/ZqsM6vzkt-U

Decent speed, major graphical glitches outside of dungeon, minor issues in beggining dungeon. No sound.

**Comment by Thunder07** [comment]
searching online about what @ramapcsx2 [said](https://github.com/jpd002/Play-/issues/465#issuecomment-246115723) about GIF path 3 masking, it seems persona 4 also has the same glitching issue.

**Comment by jpd002** [comment]
Could be related to path 3 masking, I don't do anything special about this in the emulator currently.

**Comment by ramapcsx2** [comment]
I mentioned the feature is used in SSX3 because I know this is how it looks when not supported.
Persona 4 should work fine without P3 Mask support, iirc.

**Comment by jpd002** [comment]
Had a look at a frame dump from the game, seems like there's something fishy going on with image transfers (it's sending more data than the emulator expects?).

**Comment by atomic83GitHub** [comment]
There is a compat report for this, the issue can be close.

**Comment by literalmente-game** [comment]
As already said, this entry has been moved to https://github.com/jpd002/Play-Compatibility/issues/93. This issue can be closed now
