### ISSUE TITLE
How did you get into coding Jpd002? Can you guide me into where do i start?

### ISSUE THREAD

**Issue by yahfz** [jpd002/Play-#468]
I have never been in contact with another coder, so since you are coding a new emulator, i would like to know what do i need and where to go to start coding.

**Comment by yahfz** [comment]
Please, close this thread afterwards, i didn't know how to contact you so i had to make this thread.

**Comment by jpd002** [comment]
Get Visual Studio 2015 ([it's free!](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx)) and check some of the tutorials online. Then, get started on your own projects. Doesn't really matter if you don't finish them, it's always a good learning experience. I've made many emulators before working on Play! and that's how I got to learn everything I know about programming.
