### ISSUE TITLE
Get rid of hard coded path to Framework/Codegen

### ISSUE THREAD

**Issue by ProfessorKaos64** [jpd002/Play-#472]
Can you please add your other repositories as submodules? The hard coded path is quite odd, as using something like pbuilder/sbuild/chroots, must then have these dirs above the build/buildd directory.

**Comment by Thunder07** [comment]
They're not exactly, their is a separate repo  which I believe is mentioned in the readme which had all of the needed repo as submodules.

**Comment by ProfessorKaos64** [comment]
ok, if I clone them into the source root, i'll patch CMakeLists.txt then. When using pbuilder, you are in the source root, so after you tarball pkgname-version.orig.tar.gz, pbuilder starts, then unpacks that as the original source code, which would ignore the level above the source root.

**Comment by Thunder07** [comment]
Ya, i attempt to do something using just script, but if it's a requirement to be building from root, I guess you can move/create build directory into that repo, so you can build from the project root directory, not sure how well it will fit with the project structure though.

**Comment by ProfessorKaos64** [comment]
It's ok, you have more to worry about of course than silly things like this. I'll workaround this for now.
