### ISSUE TITLE
project.properties references missing source

### ISSUE THREAD

**Issue by LoungeKatt** [jpd002/Play-#474]
https://github.com/jpd002/Play-/blob/master/build_android/project.properties#L15

https://github.com/jpd002/Play-Dependencies/tree/master/appcompat

**Comment by Thunder07** [comment]
the source was removed when @jpd002 made the switch to Android Studio, so he probably just missed removing `project.properties`

**Comment by LoungeKatt** [comment]
Are you requesting a pull request or just confirming that it is an issue?

**Comment by LoungeKatt** [comment]
Fixed by https://github.com/jpd002/Play-/compare/master...LoungeKatt:patch-1

**Comment by jpd002** [comment]
@LoungeKatt Just to be sure, do you still need the `project.properties` file to be present? AFAIK, it doesn't need to be there for the Gradle build system to work (tested it locally just now). If not, I'll just get rid of it.

**Comment by LoungeKatt** [comment]
I don't believe it needs to be there at all, but for some reason a generic fetch / rebase never completed the conversion to gradle and ant was still working to build. Figured if nothing else was broken, there was no real need to explore how to force it to replace the existing code and local changes.

**Comment by jpd002** [comment]
Alright, I'll just get rid of it then. Thanks!
