### ISSUE TITLE
Android write request

### ISSUE THREAD

**Issue by yy2001** [jpd002/Play-#478]
@jpd002, first of all, thank you very much for your play! Simulator, let me and my little partner has the hope of playing PS2 games on the phone, I know you are very busy, very little time to program play! But I still hope you can have a big improvement in speed, compatibility is important, but can run ROM but because of the slow speed and can not play, I want you to think about it in terms of speed, thank you, I wish you a speedy development!

**Comment by yy2001** [comment]
Of course, now I am studying C/C++, I hope to be able to develop software with you in the future,

**Comment by jpd002** [comment]
Thanks for your kind words. I'm working daily on getting the compatibility and speed better. I'm confident that at one point, we'll be able to play many PS2 games on mobiles devices with decent speeds, but it'll take some time to get there.
