### ISSUE TITLE
The Mark of Kri : Intro/title screen only means that you can load the game

### ISSUE THREAD

**Issue by n1dminhd** [jpd002/Play-#48]
Game freezes in the 3rd image
Sorry I bag Eng !
![untitled](https://cloud.githubusercontent.com/assets/4449742/7701574/b891e868-fe52-11e4-8522-dedb70b1b344.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/4449742/7701576/bb78c0ba-fe52-11e4-8af6-bc924fc408e2.jpg)
![untitled3](https://cloud.githubusercontent.com/assets/4449742/7701577/bd1643d4-fe52-11e4-813f-60b8c76dbbad.jpg)

**Comment by jpd002** [comment]
Thanks for testing. I'm going to get the game and see what's going on.

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/518, this issue can be closed
