### ISSUE TITLE
Klonoa 2 does not boot

### ISSUE THREAD

**Issue by minuteworld** [jpd002/Play-#481]
black screen.

**Comment by jpd002** [comment]
Probably not just on PC.

**Comment by ramapcsx2** [comment]
On PCSX2 this game boot is very interesting:
For some reason it tries to DMA a near endless stream of data to SPU2 RAM.
Maybe it's not getting the acknowledge interrupt precisely when it wants it..
Might be something to check for :)

**Comment by atomic83GitHub** [comment]
There is a compat report for that game, this should be close.

**Comment by jpd002** [comment]
Indeed: https://github.com/jpd002/Play-Compatibility/issues/169. Closing.
