### ISSUE TITLE
gran turismo 4

### ISSUE THREAD

**Issue by alexfg93** [jpd002/Play-#483]
black screen and crashes on A0001 oneplus one

10-22 14:42:11.773 17552-17552/? W/Play!: surfaceCreated
10-22 14:42:12.974 17552-17601/? A/libc: /usr/local/google/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type std::runtime_error: No suitable emitter found for statement." failed
10-22 14:42:12.974 17552-17601/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 17601 (plications.play)
10-22 14:42:13.080 243-243/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-22 14:42:13.080 243-243/? A/DEBUG: Build fingerprint: 'oneplus/bacon/A0001:6.0.1/MMB29X/ZNH0EAS2JK:user/release-keys'
10-22 14:42:13.080 243-243/? A/DEBUG: Revision: '0'
10-22 14:42:13.080 243-243/? A/DEBUG: ABI: 'arm'
10-22 14:42:13.080 243-243/? A/DEBUG: pid: 17552, tid: 17601, name: plications.play  >>> com.virtualapplications.play <<<
10-22 14:42:13.080 243-243/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
10-22 14:42:13.096 243-243/? A/DEBUG: Abort message: '/usr/local/google/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type std::runtime_error: No suitable emitter found for statement." failed'
10-22 14:42:13.096 243-243/? A/DEBUG:     r0 00000000  r1 000044c1  r2 00000006  r3 00000000
10-22 14:42:13.096 243-243/? A/DEBUG:     r4 9a6ff980  r5 00000006  r6 9a6ff930  r7 0000010c
10-22 14:42:13.096 243-243/? A/DEBUG:     r8 9d4ddb11  r9 aed35880  sl 9e87b180  fp 9a6ff2d4
10-22 14:42:13.096 243-243/? A/DEBUG:     ip 00000002  sp 9a6ff278  lr b6c5742d  pc b6c59b90  cpsr 200b0010
10-22 14:42:13.114 243-243/? A/DEBUG: backtrace:
10-22 14:42:13.114 243-243/? A/DEBUG:     #00 pc 00049b90  /system/lib/libc.so (tgkill+12)
10-22 14:42:13.114 243-243/? A/DEBUG:     #01 pc 00047429  /system/lib/libc.so (pthread_kill+36)
10-22 14:42:13.114 243-243/? A/DEBUG:     #02 pc 0001bbc3  /system/lib/libc.so (raise+10)
10-22 14:42:13.114 243-243/? A/DEBUG:     #03 pc 0001846d  /system/lib/libc.so (__libc_android_abort+36)
10-22 14:42:13.114 243-243/? A/DEBUG:     #04 pc 000164cc  /system/lib/libc.so (abort+4)
10-22 14:42:13.114 243-243/? A/DEBUG:     #05 pc 00019fd5  /system/lib/libc.so (__libc_fatal+24)
10-22 14:42:13.114 243-243/? A/DEBUG:     #06 pc 00018511  /system/lib/libc.so (__assert2+24)
10-22 14:42:13.115 243-243/? A/DEBUG:     #07 pc 001dac8d  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so
10-22 14:42:13.115 243-243/? A/DEBUG:     #08 pc 001dad51  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so
10-22 14:42:13.115 243-243/? A/DEBUG:     #09 pc 001d95f9  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so
10-22 14:42:13.115 243-243/? A/DEBUG:     #10 pc 001d8f81  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so (__cxa_throw+96)
10-22 14:42:13.115 243-243/? A/DEBUG:     #11 pc 0018c131  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so (_ZN6Jitter16CCodeGen_AArch3212GenerateCodeERKNSt6__ndk14listINS_9STATEMENTENS1_9allocatorIS3_EEEEj+372)
10-22 14:42:13.115 243-243/? A/DEBUG:     #12 pc 001840db  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so (_ZN6Jitter7CJitter7CompileEv+334)
10-22 14:42:13.115 243-243/? A/DEBUG:     #13 pc 001036a1  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so (_ZN11CBasicBlock7CompileEv+148)
10-22 14:42:13.115 243-243/? A/DEBUG:     #14 pc 00170fd1  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so (_ZN13CMipsExecutor7ExecuteEi+104)
10-22 14:42:13.115 243-243/? A/DEBUG:     #15 pc 0010f33d  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so (_ZN2Ee10CSubSystem10ExecuteCpuEi+152)
10-22 14:42:13.115 243-243/? A/DEBUG:     #16 pc 00174ea5  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so (_ZN6CPS2VM8UpdateEeEv+32)
10-22 14:42:13.115 243-243/? A/DEBUG:     #17 pc 00175291  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so (_ZN6CPS2VM9EmuThreadEv+292)
10-22 14:42:13.115 243-243/? A/DEBUG:     #18 pc 00176c41  /data/app/com.virtualapplications.play-1/lib/arm/libPlay.so
10-22 14:42:13.115 243-243/? A/DEBUG:     #19 pc 00046ea5  /system/lib/libc.so (_ZL15__pthread_startPv+32)
10-22 14:42:13.115 243-243/? A/DEBUG:     #20 pc 00018c35  /system/lib/libc.so (__start_thread+8)
10-22 14:42:13.796 243-243/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_07
10-22 14:42:13.796 243-243/? E/DEBUG: AM write failed: Broken pipe
10-22 14:42:13.813 856-17689/? W/ActivityManager:   Force finishing activity com.virtualapplications.play/.EmulatorActivity
10-22 14:42:13.838 856-3419/? W/WindowManager: Force-removing child win Window{dbf4394 u0 SurfaceView} from container Window{a5b96f7 u0 com.virtualapplications.play/com.virtualapplications.play.EmulatorActivity}
10-22 14:42:13.849 856-2729/? W/InputDispatcher: channel '5bc6904 com.virtualapplications.play/com.virtualapplications.play.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-22 14:42:13.849 856-2729/? E/InputDispatcher: channel '5bc6904 com.virtualapplications.play/com.virtualapplications.play.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-22 14:42:13.897 856-2875/? W/WindowManager: Failed looking up window
                                               java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@b08b964 does not exist
                                                   at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8811)
                                                   at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8802)
                                                   at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1212)
                                                   at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
10-22 14:42:13.898 856-3774/? W/InputDispatcher: Attempted to unregister already unregistered input channel '5bc6904 com.virtualapplications.play/com.virtualapplications.play.MainActivity (server)'

**Comment by jpd002** [comment]
Thanks for reporting this. Just noticed that a bunch of operations in CodeGen were not implemented on AArch32 and AArch64 target (ouch). Gonna take care of this ASAP.

**Comment by jpd002** [comment]
Should be fixed in today's build. Unfortunately, the game only shows the copyright screen and is not playable yet.
