### ISSUE TITLE
GTA San Andreas (Europe)

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#486]
Many glitches
![screenshot_20161106-012656](https://cloud.githubusercontent.com/assets/20205862/20034626/4b293cea-a3c4-11e6-94a2-5febc311fdbd.png)
![screenshot_20161106-012801](https://cloud.githubusercontent.com/assets/20205862/20034627/4b2e086a-a3c4-11e6-9b98-67a478236fd0.png)
![screenshot_20161106-012835](https://cloud.githubusercontent.com/assets/20205862/20034628/4b31239c-a3c4-11e6-9815-ab34c3318821.png)
![screenshot_20161106-013037](https://cloud.githubusercontent.com/assets/20205862/20034629/4b333fd8-a3c4-11e6-89d5-e50123da4749.png)

**Comment by DiegoGTRatty** [comment]
It loads up, so thats a plus.

Progress. :v

**Comment by Deathlock47** [comment]
It actually works pretty well, there're just bugs within VU emulation that cause missing polygons/collision and flickering
![screenshot_20161206-121517](https://cloud.githubusercontent.com/assets/22158671/21080984/a36a3790-bfcd-11e6-8275-4dda7d2dd09d.png)
![screenshot_20161211-140721](https://cloud.githubusercontent.com/assets/22158671/21081003/146c4a78-bfce-11e6-9b1d-0cda9cb2d790.png)

**Comment by Fred3576** [comment]
What's your device ?

**Comment by Deathlock47** [comment]
@Fred3576 Xperia Z5 Compact

**Comment by Fred3576** [comment]
@Deathlock47 Strange the game crashes few seconds after the cinematic with my Xperia Z5 Premium.

**Comment by Deathlock47** [comment]
@Fred3576 So does mine, however the crash can be avoided by looking right using the right stick

**Comment by Deathlock47** [comment]
The game is semi-playable now, however it still tends to flicker and crash randomly
![screenshot_20170124-163500](https://cloud.githubusercontent.com/assets/22158671/22292770/ea718c24-e31d-11e6-9724-8ef84594ad54.png)
![screenshot_20170124-165512](https://cloud.githubusercontent.com/assets/22158671/22292780/f4fa0edc-e31d-11e6-9ef5-7c949aa689ea.png)
![screenshot_20170124-124907](https://cloud.githubusercontent.com/assets/22158671/22292784/fbb0ce00-e31d-11e6-8a69-32a357833d9d.png)

**Comment by atomic83GitHub** [comment]
There is a compat report for the US version, @jpd002 This can be close right?

**Comment by jpd002** [comment]
Created an issue: https://github.com/jpd002/Play-Compatibility/issues/432.
