### ISSUE TITLE
Naruto ultimate ninja 2 ingame loading problem 

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#487]
The thing I notice is that this naruto game alone goes to menus/title screen, otherwise from all other naruto game they don't ,the game also allows me to enter and select characters and fighting location but whenever its loading.. (as in loading to start the fight).. it enters a loading loop.. yes a loop where it loads forever with 6fp/s 237dc/f no black screen but frames are actually moving so what's causing this?? oh and a next thing... any game with a green coloured intro logo tends to stuck with increasing then decreasing fps (such as naruto shippuden ultimate ninja 4&5 e.t.c)

**Comment by jpd002** [comment]
Interesting, the game seems to be expecting the file descriptor value to be returned by `close` when it should normally return 0 when its successful. Changing the behavior fixes the infinite loop. This will require some more testing before it's integrated in the main branch.

This affects all platforms.

**Comment by Jordanesquivez** [comment]
Oh because... I never thought that this game would go to menu/title screen.. I was frightened that it goes that far.. I was waiting so long to really see the game starts but it seems what you said was happening... also the game, naruto shippuden ultimate ninja storm 4 and 5 I think something is happening at the green colured cyberconnect intro logo I just know it just check it out when u have time...

**Comment by jpd002** [comment]
This is fixed in today's build (2016-12-12). Game looks very weird though even if it's playable.

**Comment by Jordanesquivez** [comment]
@jpd002 thank you very much for this fast and well worth build... I really appreciate your work.. is it hard to work on play! ? oh and a next thing I would like you to try and get naruto shippuden ultimate ninja 4&5 to go to  menus in the next build.. thasks much. ??
