### ISSUE TITLE
[macOS] Keyboard input not working

### ISSUE THREAD

**Issue by tamamadesu** [jpd002/Play-#489]
I'm using mac sierra 10.12.1, so download the Play-20160724.dmg ,  but when I running the app , I don't know how to setting the controller ? , and I also can`t use the keyborad , how can I do, please ?

**Comment by jpd002** [comment]
Controller settings cannot be changed right now on macOS. The key bindings are hardcoded to these settings:

* Square -> A
* Cross -> Z
* Triangle -> S
* Circle -> X
* D-Pad -> Arrow Keys
* Start -> Return or Enter
* Select -> Right Shift
* Analog Left -> (D, G, R, F)
* Analog Right -> (H, K, U, J)

If the keyboard still doesn't work, it might mean something broke in a recent build. I can take a look to make sure.

**Comment by jpd002** [comment]
Closing this because it's probably a duplicate of #663.
