### ISSUE TITLE
sılent hıll 2 problem

### ISSUE THREAD

**Issue by lotrg54** [jpd002/Play-#491]
ı download sılent hıll 2 today and crashes gıve black screen what am ı do ? ıs thıs problem wıll be fıxed ın comıng updates ?

**Comment by atomic83GitHub** [comment]
This game now boot but only in menu and introduction fmv.

**Comment by Margen67** [comment]
What's with the weird i in the title?

**Comment by jpd002** [comment]
I've made some fixes for the game earlier this year. It's as @atomic83GitHub mentioned, still not playable at the moment.

And maybe OP comes from Turkey? They have a dotless i in their alphabet.

**Comment by atomic83GitHub** [comment]
@jpd002, you can close this now :).

**Comment by jpd002** [comment]
Yup. Compat tracker issue: https://github.com/jpd002/Play-Compatibility/issues/159.
