### ISSUE TITLE
(Android) Dragon Ball Z Infinite World

### ISSUE THREAD

**Issue by kuwoh** [jpd002/Play-#492]
Loadable with fps but shows nothing

tried different versions but still same on every one

**Comment by jpd002** [comment]
Which device are you testing the game on? The game works on Windows AFAIK.

**Comment by kuwoh** [comment]
SKK Chronos Ace (or something idk)
Android 6.0

other notes:
other emulators work fine

**Comment by atomic83GitHub** [comment]
There is a compat report for that game, this should be close.

**Comment by jpd002** [comment]
Just for tracking purposes: https://github.com/jpd002/Play-Compatibility/issues/136.
