### ISSUE TITLE
[Win/OSX] Star Wars: Battlefront

### ISSUE THREAD

**Issue by SolarstrikeX2** [jpd002/Play-#493]
**FPS ID:** SLUS_208.98;1

**Status:** Loads on FPS. No further results.

**Notes:** First issue. I hope to be a great help on the project, as I'll try out files as best as I can. Environment is OS X {macOS} 10.11 El Capitan.

**Comment by jpd002** [comment]
Moved to compat tracker: https://github.com/jpd002/Play-Compatibility/issues/278.
