### ISSUE TITLE
Tom and jerry,rayman arena, road rage 3 & Alvin and chipmunks crashes,bugs

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#497]
CURRENT BUILD:- 2016/12/02

Tom and Jerry war of the whiskers

NOTES:This game boots and goes ingame but only if u choose jerry.. but if u select tom the game loads then for a few seconds it crash 

Road rage 3
Notes:this game also boots but whenever you open arcade mode as it loads it crash 

Rayman Arena
Notes: This game dont even boot as it gets to 5fps it crash. alot of game crashes in this build.

Alvin and the chipmunks
Notes;as you open the game.. it shows Alvin logo then I see "this disc is corrupt and an error as occurred please restart the console

**Comment by atomic83GitHub** [comment]
It would be nice to test now, with last version to avoid errors.

**Comment by jpd002** [comment]
Here's the compatibility entries for Tom & Jerry and for Rayman:
https://github.com/jpd002/Play-Compatibility/issues/716
https://github.com/jpd002/Play-Compatibility/issues/734

Please create issues for other game specific issues in the compatibility tracker. Thanks!
