### ISSUE TITLE
dragon ball z infinite world (SLUS_21842)

### ISSUE THREAD

**Issue by aniruddh22** [jpd002/Play-#5]
![untitled1](https://cloud.githubusercontent.com/assets/6180192/3278211/667492ec-f3ae-11e3-9bdc-27a8f355209c.png)
![untitled2](https://cloud.githubusercontent.com/assets/6180192/3278202/64658254-f3ae-11e3-975f-cd2975d93f96.png)
![untitled3](https://cloud.githubusercontent.com/assets/6180192/3278203/646eb66c-f3ae-11e3-9ab5-2ea437a81dcb.png)
![untitled4](https://cloud.githubusercontent.com/assets/6180192/3278204/6472a63c-f3ae-11e3-9b50-11a4c537c7b6.png)
![untitled6](https://cloud.githubusercontent.com/assets/6180192/3278206/65037d88-f3ae-11e3-95d7-9327e7e17dc1.png)
![untitled7](https://cloud.githubusercontent.com/assets/6180192/3278207/655bba7a-f3ae-11e3-9b02-eccf011259ea.png)
![untitled9](https://cloud.githubusercontent.com/assets/6180192/3278208/65b7978c-f3ae-11e3-9aa8-1db66a3f497e.png)
![untitled](https://cloud.githubusercontent.com/assets/6180192/3278219/c26ed58a-f3ae-11e3-9b8e-e55631b75b36.png)

and then it shows a white screen with 300 to 350 fps

**Comment by jpd002** [comment]
Changes I've made last week fixed the in game UI. Besides the shadow bug, game is working properly. I'll come back to the shadow problem later, so, closing the issue for now.
