### ISSUE TITLE
Play! is not working on samsung galaxy tab 3.

### ISSUE THREAD

**Issue by kkkkwwwaaa** [jpd002/Play-#50]
When I select a any demo, emulator has stopped.Why?

**Comment by jpd002** [comment]
Which Galaxy Tab 3 model did you try the emulator on? There's four models available: http://en.wikipedia.org/wiki/Samsung_Galaxy_Tab_series#Samsung_Galaxy_Tab_3

**Comment by kkkkwwwaaa** [comment]
I will used a model SM-T210

**Comment by kkkkwwwaaa** [comment]
ps. sorry for my bad english

**Comment by Xiaomita** [comment]
@kkkkwwwaaa That device has the PowerVR SGX540, which doesn't support OpenGL ES 3.0 or +.

It probably tries to create a context for it and fails, because it is not supported.

**Comment by kkkkwwwaaa** [comment]
thanks.

**Comment by Xiaomita** [comment]
@kkkkwwwaaa No problem. If interested, Xiaomi Mipads are dirt cheap, powerful tablets that DO support OpenGL ES 3.0 and +; those can run Play! without any issues and many other emulators too.

**Comment by kkkkwwwaaa** [comment]
ok, i close it
