### ISSUE TITLE
GTA III - Freezes after intro

### ISSUE THREAD

**Issue by Fred3576** [jpd002/Play-#502]
![screenshot_20161203-010939](https://cloud.githubusercontent.com/assets/20205862/21051170/4370235e-be1f-11e6-9f45-795ac598faa1.png)
![screenshot_20161203-011720](https://cloud.githubusercontent.com/assets/20205862/21051171/43747f8a-be1f-11e6-9bc2-b210e07364db.png)
![screenshot_20161203-011902](https://cloud.githubusercontent.com/assets/20205862/21051172/4379413c-be1f-11e6-9eb3-494b7ba97029.png)

**Comment by atomic83GitHub** [comment]
This can be nice to test it once the Max payne branch is in the master ☺.

**Comment by jpd002** [comment]
Not sure if this is using the same engine. If I'm not mistaken, GTA: Liberty City exhibits a similar problem and I know GTA: San Andreas goes in game even though it's massively broken.

**Comment by atomic83GitHub** [comment]
@jpd002 Is there a compat report for this one?

**Comment by literalmente-game** [comment]
@atomic83GitHub Just created one here https://github.com/jpd002/Play-Compatibility/issues/530. This issue can be closed now
