### ISSUE TITLE
Harvest Moon : Save The Homeland graphical bug

### ISSUE THREAD

**Issue by Joonath** [jpd002/Play-#504]
Device : ZenFone 3 Max
Play Build : Dec. 2, 2016

HM : STH 
5-7 fps, passed the Natsume intro, graphical issue started at running-in-circle-dog intro to main menu and gameplay. Also creepy sfx.
![screenshot_20161218-211850](https://cloud.githubusercontent.com/assets/3736144/21294146/e76025b8-c568-11e6-8028-d6dab268c9a4.jpg)

**Comment by jpd002** [comment]
The "polygon explosion" is due to missing VU FMAC stall emulation. I've experimented with this a little and could get a better result, but still not perfect.

**Comment by jpd002** [comment]
Compatibility report: https://github.com/jpd002/Play-Compatibility/issues/209. 
Current list of game exhibiting fmac-stall issues: https://github.com/jpd002/Play-Compatibility/labels/issue-fmacstall.
