### ISSUE TITLE
Crash Twinsanity does not boot on Galaxy S7 (Exynos) Black Screen! (video included)

### ISSUE THREAD

**Issue by Abz1** [jpd002/Play-#507]
Checked out a video from youtube (androbench) on Crash Twinsanity, and it displays a black screen (android)
https://www.youtube.com/watch?v=FflWaLyfgNQ&t=0s

**Comment by jpd002** [comment]
I don't know if that game is supposed to work on other platforms. I can take a look.

**Comment by Abz1** [comment]
thanks. Hows Vulkan support coming along? i know mobile vulkan drivers arent too good right now.

**Comment by jpd002** [comment]
I've played with Vulkan a bit, but there's nothing in the emulator yet. The biggest hurdle is developing tests to make sure everything works fine.

**Comment by atomic83GitHub** [comment]
There is already a compat report for that game, this should be close.

**Comment by jpd002** [comment]
Indeed: https://github.com/jpd002/Play-Compatibility/issues/56.
