### ISSUE TITLE
Need for Speed Carbon audio drops in/out repeadetly (Android + video included)

### ISSUE THREAD

**Issue by Abz1** [jpd002/Play-#508]
Audio drops in and out. (S7 Exynos)
(video from androbench) https://www.youtube.com/watch?v=TsyDcmhr3RM&t=36s

**Comment by jpd002** [comment]
Thanks for the report. 

This is not specific to this game or the platform. The audio will drop in and out whenever the frame rate isn't 60 fps. There's better ways to handle this, but it's not a priority at the moment.

**Comment by atomic83GitHub** [comment]
@jpd002 You can close this I think?

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/109. This issue can be closed now
