### ISSUE TITLE
(Android) Gran Turismo 4

### ISSUE THREAD

**Issue by Alissonjos** [jpd002/Play-#514]
please fix gran turismo 4 to goes in game
![screenshot_2017-01-02-12-04-57](https://cloud.githubusercontent.com/assets/24876699/21590532/e2256500-d0e3-11e6-98ea-9fb540131896.png)
![screenshot_2017-01-02-12-05-56](https://cloud.githubusercontent.com/assets/24876699/21590533/e24a6918-d0e3-11e6-8d06-648dd9cc4cb7.png)
Lenovo Vibe K5 (snapdragon 615)
Thank you

**Comment by jpd002** [comment]
Goes a bit further now, but still not playable. Compat tracker issues:

- https://github.com/jpd002/Play-Compatibility/issues/2
- https://github.com/jpd002/Play-Compatibility/issues/152
