### ISSUE TITLE
(Android) Gran Turismo 3 SCUS-97102

### ISSUE THREAD

**Issue by Alissonjos** [jpd002/Play-#515]
fix to goes in game please
![screenshot_2017-01-02-13-14-44](https://cloud.githubusercontent.com/assets/24876699/21591682/896383b6-d0ed-11e6-9388-6f0754b41e97.png)
![screenshot_2017-01-02-13-11-21](https://cloud.githubusercontent.com/assets/24876699/21591683/89683c62-d0ed-11e6-90b6-b8d4d1d9b4ef.png)
Lenovo Vibe K5 Thank you

**Comment by jpd002** [comment]
The game should be playable in the next release. I got two branches that fixes most of the issues.

**Comment by Alissonjos** [comment]
thanks

**Comment by iOS4all** [comment]
@jpd002 we really hope to fix the graphics issues on most of the games including crash bandicoot the warth of cortex, ground haunting and rule of rose

**Comment by jpd002** [comment]
Should work now, don't hesitate to reopen the issue if it's not the case.
