### ISSUE TITLE
When we can see the new update of (play!)?

### ISSUE THREAD

**Issue by iOS4all** [jpd002/Play-#516]
@jpd002 hi there. Well it's been awhile without see the new version of play! When the next one will be released? Also is you currently commits include speed up the performance as well as fixing graphics issues?
Also on the sound. even if the game is fully playable but the sound is keeping cutting every moment.
You really did a great job to stop beeping specially on resident evil 4. And we hope to fix cutting sound as well. Anyway thank you for your work. And really appreciated.
Keep going.

**Comment by jpd002** [comment]
No ETA yet, maybe next week-end. New build will mostly have compatibility improvements and some rendering fixes.

**Comment by iOS4all** [comment]
Ok Thanks a lot.
