### ISSUE TITLE
PS2 Demo Discs won't boot

### ISSUE THREAD

**Issue by Sarkie** [jpd002/Play-#518]
I thought I'd test the application on my Android

Using this list.

https://www.emuparadise.me/roms/search.php?query=playstation+2+demo+ISO%27s

None seem to work, but the ISOs seem ok.

**Comment by Thunder07** [comment]
I haven't tried that specific demo, but games tend to be slow to boot up, like FFXV can take up to 3 minutes on my Oneplus One.

**Comment by Sarkie** [comment]
What happens is, they don't appear in the list.

And if I open the .bin file with Play- you get this error, but looking at these files, they *seem* ok.

![screenshot_20170120-155220](https://cloud.githubusercontent.com/assets/283203/22155754/7f2352a2-df28-11e6-8955-dd07d0aeff21.png)

**Comment by Sarkie** [comment]
Ignore me, I think those are PSX demos not PS2.

**Comment by Margen67** [comment]
You should remove that link.
