### ISSUE TITLE
Android: Splinter Cell Demo issues

### ISSUE THREAD

**Issue by Sarkie** [jpd002/Play-#519]
It hangs nearing the end of the progress bar.

There doesn't seem to be anything in adb log worth noting.

Graphics appear squashed.

![screenshot_20170119-203819](https://cloud.githubusercontent.com/assets/283203/22198854/457945d2-e150-11e6-8b5f-8ae5c0b4236f.png)

**Comment by Margen67** [comment]
What version of the game is it?

**Comment by Sarkie** [comment]
The original.

https://en.wikipedia.org/wiki/Tom_Clancy's_Splinter_Cell_(video_game)

**Comment by Margen67** [comment]
Why does it say it's an "early demo" then?

**Comment by Sarkie** [comment]
Ah, well yes its a demo of it. Are demos not supported?

**Comment by Margen67** [comment]
I don't see why they wouldn't be. so I assume no.
It's just that it wasn't specificed in the title.

**Comment by Sarkie** [comment]
ah right, I just try to use demos to test with as smaller, so easier to store on my phone.

**Comment by Thunder07** [comment]
you need to be precise with title and region of the game, since some of them vary in build.
and with demos things change but the time the game is published, so while the demo is broken, the full game might not.

**Comment by Sarkie** [comment]
Is there a Game ID or something similar to differentiate the versions?

**Comment by Thunder07** [comment]
on android there isn't currently a way.

On windows/osx the game ID appears in the title bar when the game is loaded.
however, depends on how the file is names it might contain the ID in the name, it'll look like this `SLUS_2341.9`
also on windows/osx/linux you can mount the ISO and look for a file called that names similar to this `SLUS_2341.9`, this is the game ID

**Comment by atomic83GitHub** [comment]
I had test the pal version of the full game, same issue, infinite loading at the title screen.

**Comment by jpd002** [comment]
Just to clarify, there's no restrictions on demos. And I guess the demo and the full version of the game use the same code, so both are probably broken in the same way.

**Comment by literalmente-game** [comment]
Can you test again and add any new information to the new issue open here https://github.com/jpd002/Play-Compatibility/issues/187? This issue can be close now
