### ISSUE TITLE
FPS or DC/F on Android?

### ISSUE THREAD

**Issue by shakingboy** [jpd002/Play-#52]
Since @gambrio tested and more games continue to be playable, I think it would be a great improvement to have a simple option to tick FPS on or off just for benchmarking purposes. I think that such a feature is good because it's not very hard to implement and it makes a big difference for testing purposes between games and hardware (e.g., Xiaomi Mipad, Nexus 9, NVIDIA Shield K1, ARM32/64 and even upcoming X1 ARM devices too).

@SeannyM could probably manage something like this since it's not too extreme, and it can be a feature that's not as hard to implement for those who aren't as competent yet to make core changes/etc. 

Additionally, @MoochMcGee could probably help with this since he's helped Play! before too.

Such a feature was mentioned on OS X too, so it'll be great to see an option like this sometime in the future.

**Comment by jpd002** [comment]
Totally agree with that, we need an FPS counter in there. It's not my top priority ATM, but I'll be available for questions if anyone wants to implement that.

**Comment by jpd002** [comment]
Added in commit 3f976e7e952646ad226d44dda7164caa197d54c1, will be in next weekly (hopefully with a setting to activate or deactivate it).

**Comment by SeannyM** [comment]
#59 here's a setting that can be used to enable or disable FPS.

**Comment by shakingboy** [comment]
Great! This will be perfect for benchmarks across my Shield TV and tablets.

**Comment by jpd002** [comment]
FPS counter and setting to activate it is available in latest weekly (2015-06-14).
