### ISSUE TITLE
Emergency! Something tremendous just happen

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#521]
Ok so I was playing Kingdom Hearts 2.
 It got good fps.. About 58-60fps intro and title but ingame got about 4 fps.. But something happen.. So I got out of the emulator (I didn't close the app)and checked my email. Then I checked recent apps and I returned to the emulator to play the game and the fps went to 45fps I was so shocked I eventually played the game good (normally as in like I am play it on the console) despite the graphics.I got so carried away I even forgot to take screenshots and I was so happy perhaps it was bug glitch that enhance it .. But I tried what I did before to record it so you could see but it didn't happen again. I was so stupid I even purposely exited the app to see if it would work again... Something Gr8 happened today any ideas??... 
Oh and characters head and the player's pants doesn't show, while a long slope of graphic bug detected onto my players head into the sealing in the game

**Comment by Abz1** [comment]
What decide are you using? This could be because of the DVFS system, meaning when you minimize the app and go back to it the stronger, bigger cores take place but only for a few seconds and then they switch. This is just a guess and it may have to do with something esle, but this issue is effecting dolphin as well.

**Comment by Jordanesquivez** [comment]
@Abz1 I'm using Samsung galaxy tab 3 7.0
Custom rom 7.1 
1.7 ghz 2 cores adreno 305 opengles 3.0
Wow I mean how could this happen this make me even more trustworthy or even certain that this emulator can play games at full speed.. Only if the developer focused on speed

**Comment by Kygies27** [comment]
This gives me alot of hope! I was testing the new build yesterday with some of my fav games (KH included) and in-game was always really slow. I noticed performance drops incredibly after intro/title screen with a huge surge in dc/f up to +1500 which I am concerned may be too many for the phone cpu to handle. Hopefully it can but I wanted other opinions.

**Comment by Evolution0** [comment]
@Jordanesquivez 
> Only if the developer focused on speed

Why go the same route as PCSX2? Adding hacks to increase speed wouldn't be too hard but then you throw accuracy right out the window and have to go back and fix it years later to progress.

**Comment by Jordanesquivez** [comment]
@Evolution0 Perhaps ur right... Better just stick with the current flow of progress.. I honestly have high hopes for this emulator.. This needs incessant work

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/256. This issue can be closed now
