### ISSUE TITLE
detail on how to build play on iphone

### ISSUE THREAD

**Issue by nfsvsgta** [jpd002/Play-#523]
Ok so i recently got a mac and i have an iphone 7 plus on ios 10.2 ( non jailbroken). So i just dont know how to use xcode so can anyone tell how to like install play via xcode to ios

**Comment by LoungeKatt** [comment]
It is possible to [sideload iOS apps using Xcode 7+](http://bouk.co/blog/sideload-iphone/), but that will only allow installing the app. It will not bridge any requirements by the app for jailbroken support, such as certain types of file access or permissions.

**Comment by jpd002** [comment]
Also, setting your build environment for iOS should be simpler with the CMake configuration. The steps should be up to date on the [README](https://github.com/jpd002/Play-/blob/master/README.md) file. You will still need an active iOS developer certificate (which costs 100$) to run the executable on your device.

**Comment by jpd002** [comment]
Closing this for now, feel free to open it again if you need help setting up your build environment.

**Comment by LoungeKatt** [comment]
> You will still need an active iOS developer certificate (which costs 100$) to run the executable on your device.

Not since Xcode 7. https://9to5mac.com/2015/06/10/xcode-7-allows-anyone-to-download-build-and-sideload-ios-apps-for-free/ gives an overview of the changes to the Apple Developer Program, but the link above implies that was already known.

**Comment by jpd002** [comment]
Oh, I didn't know. That's cool, thanks for the info!
