### ISSUE TITLE
Make a way to readout the game ID in emulator

### ISSUE THREAD

**Issue by Nine-H** [jpd002/Play-#525]
Doing game tests takes heaps longer than it should because every time I find a game that sort of works or does something valuable for testing compatibility or emulator stability I have to start up PCSX2 and read the disc id from from the console window. If it doesn't do anything I can't even be bothered.

Help me to help you. I'm testing using a build from git on ubuntu 16.04.

You could change the window title to reflect the selected disc image or make an iso properties window, I don't care, either way saves me plenty of time and clicks.

edit: while I have your attention, what's the preferred way to report game specific issues? I don't want to clutter the bugtracker, but on the other hand there's no room for discussion on the compatibility wiki.

**Comment by Thunder07** [comment]
as of now, the issue tracker here is the only way to report bugs, just do a quick search for previous reports before you report it.

As for the ID request, I'll have a look at it, it shouldnt be much of an issue to add, should i get some free time later today, check this post in an hours time.

**Comment by Nine-H** [comment]
nice! merged before I got your message.

I'll report the segfaults I found, keep an eye on the linux compatibility list on the wiki for my test results and notes. I'm not going to report speed issues because this box is on an i7 870. I want to say well done boys: at this point you could probably define a playable category just for SOTC.

**Comment by jpd002** [comment]
Thanks guys, it's really appreciated!
