### ISSUE TITLE
Segfault while loading Silent Hill 2 Director's Cut

### ISSUE THREAD

**Issue by Nine-H** [jpd002/Play-#528]
Play! immediately segfaults while loading the disc image.

Disc ID: SLES-51156
OS: Ubuntu 16.04
Version: git 510e0407d407e39e0dcd9a632eab966f8442e6d1 built with qt5default
CPU: i7 870
GPU: nVidia GTX 460 1GB

**Comment by jpd002** [comment]
This is my WIP branch for fixing Silent Hill 2: https://github.com/jpd002/Play-/tree/sh2

Crash has been fixed, game goes up to title screen, but not playable yet.

**Comment by ramapcsx2** [comment]
Hey @jpd002, if I read this correctly, you're implementing SIF delays. It'd be wise to check the games Okami and Ecco the Dolphin as well. Okami definitely relies on it and we assume Ecco does as well.

**Comment by jpd002** [comment]
@ramapcsx2 I tested Okami after implementing that change and it still boots. Still need to check Ecco the Dolphin though. Thanks again for the tip!

Closing this issue since fix has been merged and released a while ago. Also, related: #597.
