### ISSUE TITLE
Segfault on Title Screen in Katamari Damacy

### ISSUE THREAD

**Issue by Nine-H** [jpd002/Play-#529]
The Katamari graphics engine starts, and draws some polygons from the 3d menu graphics but a few frames later it segfaults the emulator.

Disc ID: SLUS-21008
OS: Ubuntu 16.04
Version: git 510e0407d407e39e0dcd9a632eab966f8442e6d1 built with qt5default
CPU: i7 870
GPU: nVidia GTX 460 1GB

**Comment by jpd002** [comment]
After a quick investigation, crash seems to be related to memory corruption. Investigating as we speak.

**Comment by jpd002** [comment]
Found the culprit: https://github.com/jpd002/Play-/blob/master/Source/ee/VUShared.cpp#L63. That shouldn't be hardcoded since VU0 memory size is 0x1000 bytes.

**Comment by jpd002** [comment]
The crash is fixed in that branch: https://github.com/jpd002/Play-/tree/katamari. There's still an issue with collision detection though.

**Comment by jpd002** [comment]
Fixed in 2017-05-09 build.
