### ISSUE TITLE
Tokobot plus looping at chapter 1

### ISSUE THREAD

**Issue by minuteworld** [jpd002/Play-#535]
game boots up, the fmvs are 10 f/s and the sound is horrid but it gets to the title screen, I select new game, another fmv appears that runs at 12 f/s, when I skip it, it says chapter one and it just freezes and/or loops indefinably.

ran on a dell inspiron pc 
SLUS_214.71;1
used build from jan 23 2017

if you have any recent builds, I am willing to test them. I really recommend you guys use buildbot.

**Comment by jpd002** [comment]
Moved here: https://github.com/jpd002/Play-Compatibility/issues/1411.
