### ISSUE TITLE
Format other than Iso?

### ISSUE THREAD

**Issue by Kygies27** [jpd002/Play-#539]
Is there a format other than Iso that I can store my games in, preferably something a bit compressed?

**Comment by Margen67** [comment]
There's cso/ciso (compressed iso)

**Comment by Thunder07** [comment]
all platforms support (*.iso *.bin *.isz *.cso) formats, except for OSX that doesn't support bin, but i think that's just because no one added it to the filter list.

**Comment by jpd002** [comment]
If you want any other format to be added to the list, don't hesitate to ask. Closing this for now.
