### ISSUE TITLE
Memory cards not working for some games.

### ISSUE THREAD

**Issue by SonofUgly** [jpd002/Play-#54]
Dragon Quest VIII [SLUS-21207] will make a save file when you start a new game (and it does write to mc0), but it doesn't find any save data in-game.

Kingdom Hearts 2: Final Mix [SLPM-66675] also doesn't seem to load saves, I exported saves from PCSX2 (using mymc) and imported them into Play!, but it doesn't show any save data in-game.
Tried this with a few other games with imported saves and they worked fine.

And Final Fantasy XII [SLUS-20963] crashes when selecting load game, but it's marked as unstable, so it may be unrelated.

**Comment by jpd002** [comment]
Currently investigating the DQ8 bug. Once I fix it, I'll look at the other games.

**Comment by jpd002** [comment]
35948e1a1190dc3d76f7747c963843096886605f fixes DQ8. Moving to KH2.

**Comment by jpd002** [comment]
Fixed KH2: e1b187e6c87a36f1169bc152d3fd3afe9313e157. Now to see what's wrong with FFXII.

**Comment by SonofUgly** [comment]
Nice, tested with yesterdays build and can confirm both DQ8 and KH2FM are working correctly.

**Comment by jpd002** [comment]
Thanks for testing. FFXII's problem is quite different, seems like the IOP runs out of memory trying to load a module. I'll keep looking in that.

**Comment by jpd002** [comment]
Fixed FFXII's load game screen crash:

![ffxii_06](https://cloud.githubusercontent.com/assets/6760433/8391572/bed5c792-1c95-11e5-83e3-4cb97523ea10.jpg)

Still not able to load a game yet, but shouldn't be as much of a problem to fix.

**Comment by jpd002** [comment]
Fix for FFXII is now in master:

![ffxii_07](https://cloud.githubusercontent.com/assets/6760433/8395187/581064e6-1d2f-11e5-9e4d-09fa71b222c9.jpg)

It will be in tomorrow's weekly build. Game is pretty unstable though (can move around but casting a spell will screw things up).

**Comment by SonofUgly** [comment]
Seems it doesn't like either the status ailments, characters, or areas my saves have because it ends up with a black screen, then crashing after loading a save. But all the memory card issues are solved, so this can be closed.

**Comment by jpd002** [comment]
I used that save to do my tests: http://db.gamefaqs.com/console/ps2/save/final_fantasy_xii_j.max

I was able to move out of that area, but the game hung when I tried to cast a spell and the polygons got very screwy when I saw one of the characters cast a spell automatically. Fixing those problems is at the top of my TODO list.

**Comment by SonofUgly** [comment]
I'm getting black screen and crash with that save to. Here's a few saves in various areas, to see if it's just on my end:
[Save 1](http://www.mediafire.com/download/fo7f51zouhkqcoz/SLUS-20963_FF12_03_081_07_44_(6FA6D380).psu)
[Save 2](http://www.mediafire.com/download/kxabdo18r1xh979/SLUS-20963_FF12_04_081_08_51_(DF78D02B).psu)
[Save 3](http://www.mediafire.com/download/gvyur8051cw57ct/SLUS-20963_FF12_05_081_10_53_(607613DE).psu)
[Save 4](http://www.mediafire.com/download/y9bbq46obooncxr/SLUS-20963_FF12_06_038_43_11_(59D65C93).psu)

And my specs just in case:
Phenom II X2
Nvidia 750ti
4GB RAM
Win 7 x64

**Comment by jpd002** [comment]
Tried the first save, seems to work fine on my side:

![ffxii_08](https://cloud.githubusercontent.com/assets/6760433/8401245/e05f4856-1df9-11e5-8f38-0c81f89a494c.jpg)

Are you able to start a new game and see Reks talk to Basch?

**Comment by SonofUgly** [comment]
No, it crashes right after starting a new game. 

Also, checked my ISO against redump, and it is correct.

**Comment by SonofUgly** [comment]
Alright, here's dump files:
[Starting a new game](http://www.mediafire.com/download/3dgw4w5bb5936ty/Play_(New_Game).DMP)
Loading a game (Uploading...)

**Comment by jpd002** [comment]
Thanks for the dumps. The problems seems to come from an SSE 4.1 instruction I'm using which is possibly not supported on the Phenom II X2. I still need to confirm that, but if that's the issue, it shouldn't be a problem to fix.

**Comment by SonofUgly** [comment]
Yeah it's not supported, Phenom II only supports:
SSE2, SSE3, MMX2, 3DNOW, 3DNOW2, SSE4a

**Comment by ziiU** [comment]
Don't see what the purpose would be ... the AMD Phenom 2 X2 is very slow and would be terrible. I'm using an i5-4690K and the game works fine, but it runs barely 20 FPS & you can't even move because there appears to be no way of binding the analog sticks to the keyboard from the emulator's settings.

**Comment by gambrio** [comment]
@ziiU This seems to be one way to help the JIT speedup & more games run fullspeed. -> https://github.com/jpd002/Play-/issues/39

**Comment by SonofUgly** [comment]
Most 3D games with Play! are quite slow on it, so yeah I wouldn't go out of your way to add support for such old hardware - gotta draw the line somewhere.

Good to know what the problem was through.

**Comment by jpd002** [comment]
That problem is really easy to fix anyways, just a matter of detecting if the instruction is supported and selecting a different way to generate code.

**Comment by ziiU** [comment]
I'm NOT suggesting to not bother with the extension support issues, but just making it clear that it's not the big concern with the the emulator not running games fullspeed on powerful CPUs (3D and 2D games). I'm just saying that, if high-end chips can't cut it as of now, older ones won't do any better.

@gambrio How would that improve the speed though? The issue doesn't seem to be with memory.

**Comment by jpd002** [comment]
@ziiU There's a large overhead associated with reading/writing data from/to RAM on the EE and IOP. Using system mapping will probably help a lot.

**Comment by ziiU** [comment]
@jpd002 PCSX2 doesn't use system mapping in its dynamic binary translator and it can still manage to do well on mid-end CPUs for most games at least. Have you looked into PCSX2's dynarec or other means? Not to insult you or your work but maybe because it's more like a JITIL instead of just a JIT too?

**Comment by SonofUgly** [comment]
I meant if it was a big deal, like if you heavily relied on more modern instructions for other things and this was the first of many issues from having only an older instruction set. Newer emulators have already dropped support, and this CPU is only going to get more outdated.
But if it's an easy fix, then disregard.

**Comment by jpd002** [comment]
@ziiU I haven't looked into PCSX2's code generator, so I can't really say what makes theirs faster than Play!'s, but there's still many things that can be improved in Play!'s code generator. There's factors other than code generation that would also need to be taken in consideration if we'd want to do a proper comparison.

**Comment by jpd002** [comment]
Closing this as initial issue has been fixed. Opened a new issue for the SSE4.1 instructions.
