### ISSUE TITLE
Deployment Linking

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#541]
So, whats better than studying... not studying ofc.
So, I've been keeping an eye on your `appveyor_deploy` branch and I was interested in not studying.

unfortunately, I'm not entirely acquainted with how Amazon S3 servers works.. in that whether you'd be hosting the builds there and linking to them, or will you automate their push to your website.

Eitherway, in the mean while, I came up with a clever little trick, I modified a copy of [Directory Lister](http://www.directorylister.com/) to support loading XML from amazon, so that it works as a directory lister and would also load Amazon bucket listing if you want it so.

this is a [demo](http://madnation.net/Play/) hosted on my site of it in action, and you can read README for a quick explanation, if it's something you're interested in I can fork the code and commit it.

Edit: might even be worth while using just using`Directory Lister` over the default view currently on the site

**Comment by jpd002** [comment]
That's an interesting idea, but I'm not sure having people browse though a bunch of folders whose names are commit hashes would be very appealing to them. 

I'm still just experimenting with the idea of deploying builds on S3, I'm still not quite sure what would be the best way to make those builds easily accessible. I was thinking of maybe just dumping the URL to the build in Travis' or AppVeyor's log, but that wouldn't be very obvious to people who don't know the URL is there. 

Another idea I had was to build a kind of interface showing commits on this repository with direct links to builds, but I don't know if it would be feasible to use GitHub's API to do that kind of stuff.

Anyways, I'm still just experimenting, but I'm open to other ideas.

**Comment by Thunder07** [comment]
if the amazon servers provide some form of hook, you can always use that to push things to your site.

but a quick comment on browsing hash folders, even when you have multiplatform deployment working together, thus you'd have multiple files with the same folder name, they won't be divided into folder, (as of yet, i haven't found a way to filter the results based on folder name), so while the name displayed will contain the hash(folder).. e.g `7aa576cb/Play-release-unsigned.apk`, people wouldn't technically be able to browse the hash named folder. with that said, I could always filter out folder name, but then you'd potentially have 10 `Play-release-unsigned.apk` only distinguishable by date published.<- speaking of which, of CI build, it might be worth while adding the commit hash into title, about section, somewhere users can easily find to be able to report issues with specific builds.

the Github API sounds interesting, but keep in mind then, you'd be assuming people know how to navigate github->repo->commit->CI

if i think of some other clever way, I'd let you know.

**Comment by Thunder07** [comment]
another 'cleaner' [attempt](https://madnation.net/Play/dl.php).. bleeding-edge builds.

this current PHP script queries amazon bucket, then cross references the sha hash to get commit details. commit details are saved to speed this process up next time around. Im thinking of also saving amazon bucket details and only allowing checking for updates when required, as oppose to every time I refresh that page.

with that said, the real question is, how do you want to handle deployment?
1) manually publishing updates
2) automate
3) semi-automated
+) link directly to the bucket or to your site.

my 2 cents: you can have a bleeding-edge builds page which will be automated, and also do monthly releases, so you can post change logs and update Play store and cydia.

**Comment by LoungeKatt** [comment]
Sounds like you are trying to describe what is done by reicast and PPSSPP, which can be demonstrated at https://github.com/reicast/reicast-builds and https://github.com/hrydgard/ppsspp-website, if you prefer not re-inventing the wheel

**Comment by Thunder07** [comment]
Solved: automatic downloads
