### ISSUE TITLE
(Mac) Sims 2 Castaway doesn't detect controller

### ISSUE THREAD

**Issue by sern19** [jpd002/Play-#542]
It boots fine
![](https://cloud.githubusercontent.com/assets/23708258/24199595/7f67330c-0f0a-11e7-9450-1639bce16869.png)
then it shows this screen
![](https://cloud.githubusercontent.com/assets/23708258/24199606/8b4baf40-0f0a-11e7-9634-0c0292dd2ce7.png)
I can't test it on Windows

**Comment by gege2** [comment]
How on android?

**Comment by jpd002** [comment]
Probably the same on all platforms. The input code is platform independent. I'm investigating an issue with controllers on Radiata Stories, it might be related.

**Comment by atomic83GitHub** [comment]
What's the status about this?

**Comment by jpd002** [comment]
It still has the same issue AFAIK. Created a compat tracker issue: https://github.com/jpd002/Play-Compatibility/issues/406.
