### ISSUE TITLE
Build server broken?

### ISSUE THREAD

**Issue by Sarkie** [jpd002/Play-#544]
http://purei.org/downloads/play/weekly/

No builds since 
23-Jan-2017 20:11

**Comment by Thunder07** [comment]
the build system has been changed around a month ago, and @jpd002 was ironing out the kinks here and there, as far as I can tell, it's nearly ready so a new build should will be available soon.

**Comment by Margen67** [comment]
There's [this](http://madnation.net/Play/) from https://github.com/jpd002/Play-/issues/541

**Comment by Thunder07** [comment]
while that is my own server and no one but me has access to it, and the Build/Amazon are automated builds based on the repo, I'd still recommend you only make binary downloads from official sources.

**Comment by jpd002** [comment]
I've [posted](http://purei.org/downloads/play/weekly/) the latest Win32 and macOS builds (2017-04-11). Android and iOS will come soon.

**Comment by MarcoEstevez** [comment]
Thanks  :-D

**Comment by Jordanesquivez** [comment]
@jpd002 good day... What are the improvements that has been made in this new build... Is there any improvements in emulation speed??

**Comment by jpd002** [comment]
The [site](http://purei.org/) has been updated with the list of changes. New build will surely come next week.
