### ISSUE TITLE
The latest version of Play! is launching on iPad as an iPhone app.

### ISSUE THREAD

**Issue by iOS4all** [jpd002/Play-#545]
@jpd002 hi there.
As I said in the title. The Play! App is launching on iPad as an iPhone app. This was not happened on the previous versions of Play! At all. This is the first time I see it like that. Maybe you didn't add iPad resolution screen or something like that in this version of Play!

For more info this is a screenshot to see the app launching as an iPhone app
![img_0089](https://cloud.githubusercontent.com/assets/24762554/25054594/bf2e7144-2166-11e7-8cfa-b544556beb18.PNG)

**Comment by jpd002** [comment]
Ah, nice catch, I guess something slipped when I moved the project to CMake. I'll take a look.

**Comment by iOS4all** [comment]
@jpd002 ok take your time. If this done like before you can add the fix version on Cydia.
Thanks.

**Comment by Kvngleek9700** [comment]
I need help with this open gl stuff....idk what it is. Can someone please help me

**Comment by Kvngleek9700** [comment]
@jpd002

**Comment by iOS4all** [comment]
@Kvngleek9700 don't worry @jpd002 will reply as long as he available here.

**Comment by Kvngleek9700** [comment]
Ok. Thank u

**Comment by iOS4all** [comment]
Welcome bro.

**Comment by jpd002** [comment]
Should be fixed in 2017-05-09 build.

**Comment by iOS4all** [comment]
@jpd002 I already test it. Thank you so much for the fix.

**Comment by Kvngleek9700** [comment]
Whats this?
