### ISSUE TITLE
FPS needs locking 

### ISSUE THREAD

**Issue by danny19901** [jpd002/Play-#546]
Beats of rage runs far to fast on latest build for android as before it ran fast at times but now it's constant however audio for game is choppy and laggy but gameplay runs perfect other than the FPS issue.
Auto detect Frame Rate would be a massive deal breaker for this emu along with maybe stretch screen to full screen as that game has black borders

**Comment by jpd002** [comment]
You're talking about [this](https://en.wikipedia.org/wiki/Beats_of_Rage)? I'll take a look.

**Comment by danny19901** [comment]
Yeah that's the game thank you much appreciated

**Comment by jpd002** [comment]
There's FPS locking now in the emulator, should help with this.
