### ISSUE TITLE
Megaman X8 - InGame but no character

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#547]
Build: master [cbf190f](https://github.com/jpd002/Play-/commit/cbf190f14c8a3d1a03f4fae0aaa89dc53e5f08b2)
OS: Ubuntu 17.04
Serial: SLUS_209.60;1

Megaman X8 can run through the Intro and get [In-Game](https://cloud.githubusercontent.com/assets/5013823/25303924/6641fc92-2754-11e7-9677-9c123f42c76e.png) but  the characters don't seem to load. but still produce gunshot sounds.
I used a save i found online to see if there was any difference trying to load other levels, but the game seem to be stuck in an infinite loop after character [Character Selection](https://cloud.githubusercontent.com/assets/5013823/25303923/664159fe-2754-11e7-876a-79cc4c22b366.png), the game doesn't freeze as the background animation is still on-going.

**Comment by jpd002** [comment]
MMX7 exhibits a similar problem. I think it's related to a floating point precision error or maybe a VU flag error?

**Comment by Thunder07** [comment]
moved to https://github.com/jpd002/Play-Compatibility/issues/220

character now show up and we can move around, 
as I noted in the other repo, the initial issue could have been that the character was spawned in an invalid part of the map.

**Comment by jpd002** [comment]
Thanks for closing. 

That problem was caused by the game not using a `VWAITQ` after doing a `VDIV`, `VSQRT` or `VRSQRT`. The FDIV pipeline is not emulated in macro mode. The result was flushed to Q when  `VWAITQ` was executed, but it's now flushed when `VDIV`, `VSQRT` or `VRSQRT` is executed.

There's still an issue in the game though. When you go a bit further in the intro stage, the character decides to go "off" by itself and you can't take control anymore.

**Comment by Thunder07** [comment]
the bug gets more interesting actually, I created a save state before I died to see how far I can go, and when I continue on, I hit a section where I need to double jump to continue ahead... it seemed odd, so I looked at online game play video, and that section was suppose to be played by Zero, yet I control Axel. (ill update the compatibility repo as well)


![slus_209 60 1_09-04-2018_20 50 15 318 bmp](https://user-images.githubusercontent.com/5013823/38519464-d6fe131e-3c37-11e8-8105-b843ff49ac90.jpg)
https://youtu.be/UJNr6G0dM8U?t=571
