### ISSUE TITLE
PuzzleQuest - broken graphics

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#548]
Build: master [cbf190f](https://github.com/jpd002/Play-/commit/cbf190f14c8a3d1a03f4fae0aaa89dc53e5f08b2)
OS: Ubuntu 17.04/OSX
Serial: SLUS_216.92;1

immediately sigfaults after selecting the iso

Edit: New build test:
Build: master [6bb02c3](https://github.com/jpd002/Play-/commit/6bb02c3371bddfeb7479e355a014877c78f2c608)
OS: OSX

now in game with broken graphics.

**Comment by jpd002** [comment]
Could you provide the crash's call stack?

**Comment by Thunder07** [comment]
This is the crash callstack from OSX, I'll see if i can get

from 4 boot attempts i got 2 different callstack, and 2 freezes with no crash.
```
Thread 4 Crashed:
0   com.virtualapplications.Play  	0x0000000103f7a41f CMipsExecutor::Execute(int) + 143
1   com.virtualapplications.Play  	0x00000001040260fe Iop::CSubSystem::ExecuteCpu(int) + 78
2   com.virtualapplications.Play  	0x0000000103f80095 CPS2VM::EmuThread() + 469
3   com.virtualapplications.Play  	0x0000000103f838e0 void* std::__1::__thread_proxy<std::__1::tuple<CPS2VM::Initialize()::$_7> >(void*) + 96
4   libsystem_pthread.dylib       	0x00007fffae319aab _pthread_body + 180
5   libsystem_pthread.dylib       	0x00007fffae3199f7 _pthread_start + 286
6   libsystem_pthread.dylib       	0x00007fffae319221 thread_start + 13
```

```
Thread 4 Crashed:
0   com.virtualapplications.Play  	0x000000010dc40124 CBasicBlock::GetBeginAddress() const + 4
1   com.virtualapplications.Play  	0x000000010dc56ebd CMipsExecutor::PartitionFunction(unsigned int) + 1485
2   com.virtualapplications.Play  	0x000000010dc5646b CMipsExecutor::Execute(int) + 219
3   com.virtualapplications.Play  	0x000000010dd020fe Iop::CSubSystem::ExecuteCpu(int) + 78
4   com.virtualapplications.Play  	0x000000010dc5c095 CPS2VM::EmuThread() + 469
5   com.virtualapplications.Play  	0x000000010dc5f8e0 void* std::__1::__thread_proxy<std::__1::tuple<CPS2VM::Initialize()::$_7> >(void*) + 96
6   libsystem_pthread.dylib       	0x00007fffae319aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffae3199f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffae319221 thread_start + 13
```

**Comment by jpd002** [comment]
Interesting crashes... Not sure what could cause this, maybe a weird IOP module? I'm getting a copy of the game to see what's going on.

**Comment by Thunder07** [comment]
I wish I could speculate XD
but if you want me to run any specific tests let me know.

**Comment by jpd002** [comment]
After a quick investigation, looks like its using PATH3 masking (same issue as SSX3 and others) which is not supported yet.

**Comment by Thunder07** [comment]
Ah, I recall from the [blog post](http://forums.pcsx2.net/Thread-blog-Path-3-Masking-Geometry-Syncing) refraction made on PCSX2 forum, that its mainly a queue handling issue, so hopefully it doesn't prove too difficult when you get to it.

**Comment by jpd002** [comment]
Implementing the queue itself isn't the problem. I wasn't too sure the technique relied on timing, but the post confirms it. Getting that right will be tricky... I guess that's another good case for an hardware test.

**Comment by Thunder07** [comment]
moved to https://github.com/jpd002/Play-Compatibility/issues/219
