### ISSUE TITLE
(Windows) Gran Turismo 2000 PAPX_902.03

### ISSUE THREAD

**Issue by ppsspp213** [jpd002/Play-#550]
Reused the skip movies code from pcsx2 but still it went no further black screen.

Executable Name="PAPX_902.03;1" Title="Gran Turismo 2000" Region="JP">
		<Patch Address="0x0024b898" Value="0x24020001" Description="Cancels movie playing."

**Comment by jpd002** [comment]
That's the prototype version of Gran Turismo 3, right? Not sure if I can get my hands on this.

**Comment by ppsspp213** [comment]
Correct, I can send you an image do you need it in any paticular image
format?, mode 1 or 2? it's a cdrom not a dvd, I don't think it contains any
cdda.

**Comment by jpd002** [comment]
Moved to compat tracker: https://github.com/jpd002/Play-Compatibility/issues/205.
