### ISSUE TITLE
could you give me an idea of how this project is going?

### ISSUE THREAD

**Issue by minuteworld** [jpd002/Play-#554]
sorry for another non-issue thread in the issue tab but I just wanted you to give me an idea of how this project has progress out the years. I've seen you've been working on this alone since 2005? that's quite the dedication you have.

again sorry for starting a discussion in the issues.

**Comment by spring568** [comment]
Just read the news updates on his homepage to get an idea of the progress. It goes all the way back to 2005-08-19

**Comment by jpd002** [comment]
Yikes, that brings back memories. 

I didn't work on the emulator for ~12 years straight. I took a few breaks to work on other projects before going back to work on the project more steadily around 3 years ago (thanks to @bigianb who brought me back). I've never thought I'd get that far, but there's still lots of work to be done.

**Comment by bigianb** [comment]
one day I'll get some personal time to help again too :-)

**Comment by jpd002** [comment]
Closing this as this is not an actual emulation issue. :smile:
