### ISSUE TITLE
Could the emulator can play on zefone?

### ISSUE THREAD

**Issue by odarknighto** [jpd002/Play-#556]
My phone is Asus Zefone 5 x86 and the emulator always black screen in my phone when I Enter game ,is it mean I can't play with my phone??(sorry with poor English >< )

**Comment by jpd002** [comment]
Which game are you trying to play? There's lots of games that still don't work. You can take a look at the [Compatibility Chart](https://github.com/jpd002/Play-/wiki/Compatible-games) to see if your game is supposed to work.

**Comment by odarknighto** [comment]
like the kof2002 is not supported that emulator screen always black screen!
