### ISSUE TITLE
GFX glitches in G-surfers (PAL)

### ISSUE THREAD

**Issue by TheLastRar** [jpd002/Play-#559]
Multiple rendering issues, most noticeable is terrain pop-in.

Disc ID: SLES_50511
OS: Windows 10
Version: Apr 12 2017 Weekly build
CPU: i7 6700K
GPU: AMD R9 380 4GB

![image](https://cloud.githubusercontent.com/assets/4604733/25752988/e1bb8d40-31b1-11e7-9edf-d5afd714efde.png)

**Comment by jpd002** [comment]
Moved to compat tracker: https://github.com/jpd002/Play-Compatibility/issues/275.
