### ISSUE TITLE
About build info inaccurate 

### ISSUE THREAD

**Issue by Kygies27** [jpd002/Play-#560]
![screenshot_2017-05-06-15-34-29](https://cloud.githubusercontent.com/assets/24367147/25772763/8b366f7a-327a-11e7-8857-793a634127f4.png)
When I pressed the about button in the menu on android is told me build ver. 1979/11/30

**Comment by Thunder07** [comment]
this has been brought to our attention and has been [fixed](https://github.com/jpd002/Play-/pull/555) since, the fix will be available with the next release.

**Comment by Kygies27** [comment]
Thanx! 

Also, since I have the chance, thank you for your work on this project! It's pretty amazing to have a PS2 on every platform (and no, not just android).

**Comment by jpd002** [comment]
Fixed in 2017-05-09 build.
