### ISSUE TITLE
[Windows] Cannot map inputs to LT and RT on an Xbox 360 controller

### ISSUE THREAD

**Issue by GeekyFerret** [jpd002/Play-#562]

**Comment by TheAtheistGod** [comment]
I'm having the same issue on an Xbox One controller. It seems like it's because windows registers LT and RT as Z-axis rather than a button. If i try to map LT or RT to analog_left_x, analog_left_y, analog_right_x, or analog_right_y it works fine.

**Comment by atomic83GitHub** [comment]
No, the issue here is Play! use the directinput API which don't support Xbox 360 analog triggers.

**Comment by SergeyLatyshev** [comment]
The same for Logitech F710. Play!-5941b9a9-x86_64 for Linux (Ubuntu).

**Comment by jpd002** [comment]
Moving discussion to #782. This issue was for Xbox 360 controllers on Windows, which shouldn't be a problem anymore since Play! now uses XInput on Windows.
