### ISSUE TITLE
Sonic Heroes - team blast gauge doesn't work

### ISSUE THREAD

**Issue by GeekyFerret** [jpd002/Play-#563]
When the team blast gauge (the blue bar at the top right) fills up, it's supposed to turn yellow and have the R1 button icon below it. In the latest version of Play!, it remains blue and you can't use the team blast attack.

![sonic heroes](https://cloud.githubusercontent.com/assets/28161000/25960135/b9cef1e4-363b-11e7-9eaa-63785633f4cf.png)

**Comment by literalmente-game** [comment]
You can close this issue as I've moved all the information to the game related issue (this tracker is only for emulation issues, game specific issues should be reported here https://github.com/jpd002/Play-Compatibility/issues).
New issue with your reported information is here: https://github.com/jpd002/Play-Compatibility/issues/416
