### ISSUE TITLE
Armored Core does not launch.

### ISSUE THREAD

**Issue by rbohannon89** [jpd002/Play-#564]
I have every armored core games
![screenshot_20170512-090021](https://cloud.githubusercontent.com/assets/28317298/25998996/7c716d34-36f1-11e7-854a-467c3345e18f.png)
 for ps2  and none of them launch. Only black screen.

**Comment by rbohannon89** [comment]
Please help all of us out there who are MechHeads be able to play these games once again.

**Comment by jpd002** [comment]
Got Armored Core 2 to boot on a [branch](https://github.com/jpd002/Play-/tree/ac2) that is pending merging. Unofficial build [here](https://s3.us-east-2.amazonaws.com/playbuilds/f32d2129/Play-release.apk).

**Comment by jpd002** [comment]
There's issues open on the compatibility tracker regarding [Armored Core games](https://github.com/jpd002/Play-Compatibility/issues?utf8=%E2%9C%93&q=is:issue+is:open+Armored+Core). I don't have all these games, so feel free to update the tickets if you test any of the games with a recent version of the emulator and notice any change in compatibility. Thanks!
