### ISSUE TITLE
Latest apk version of play will not install

### ISSUE THREAD

**Issue by paulaz2** [jpd002/Play-#565]
Since the creation of the last three builds of play non of them seems to install in my phone

**Comment by paulaz2** [comment]
![screenshot_20170514-004209](https://cloud.githubusercontent.com/assets/12880627/26030051/3e47cbcc-383e-11e7-9d19-5262c2242b60.png)
Iag Image prove

**Comment by Sarkie** [comment]
Have you removed the old versions?

**Comment by rbohannon89** [comment]
I have the same problem on my tablet but it might be because it's Amazon fire tablet.  For me there is no other version installed.

**Comment by paulaz2** [comment]
#sarkie no other version installed

**Comment by jpd002** [comment]
@paulaz2 Which Android version and phone model?

**Comment by paulaz2** [comment]
Android 6.0 
Infinity hot 4 pro

**Comment by Thunder07** [comment]
@paulaz2: the best I can find about that phone is that it's using Mali-400MP2, which i imagine to be a base variant of [Mali-400](https://en.wikipedia.org/wiki/Mali_(GPU)) which only supports OpenGL ES 2.0. the minimum requirement is OpenGL ES 3.0.

The Question is, has it ever installed, if so, it really shouldn't have, and if it did, it shouldn't even run.

@rbohannon89: which [model](https://developer.amazon.com/public/solutions/devices/kindle-fire/specifications/01-device-and-feature-specifications#opengl-properties-and-limits) is it. if it's the `Fire (2015)` then its also an OpenGL ES 2.0 device.

**Comment by rbohannon89** [comment]
I can tell you everything about it. I'll include a link any help you can give me on how it get it up and running be a huge help to me while I test games on it. Fire Tablet with Alexa, 7" Display, 8 GB, Black - with Special Offers https://www.amazon.com/dp/B00TSUGXKE/ref=cm_sw_r_other_apa_EFlgzb11A4ENB

**Comment by Thunder07** [comment]
@rbohannon89 as I mentioned, your tablet seems to be `5th generation - 2015 release` which doesn't support the newer OpenGL ES 3.0 standards, as such your device is not supported.

**Comment by rbohannon89** [comment]
Understood thank you.

**Comment by paulaz2** [comment]
@Thunder07 you have the wrong version I do run games is openGES 3.0
![screenshot_20170517-091509](https://cloud.githubusercontent.com/assets/12880627/26144708/d2be1b9e-3ae1-11e7-8281-253bfc5a25eb.png)
![screenshot_20170517-091513](https://cloud.githubusercontent.com/assets/12880627/26144722/d8d94382-3ae1-11e7-86be-ce24ba8e8d96.png)

This is my game collection 
![screenshot_20170517-092058](https://cloud.githubusercontent.com/assets/12880627/26145042/ec741a74-3ae2-11e7-8339-cc571e67f6c7.png)

Jet li
![screenshot_20170517-092125](https://cloud.githubusercontent.com/assets/12880627/26145061/fdb2102a-3ae2-11e7-8f44-e4363955b435.png)
![screenshot_20170517-092159](https://cloud.githubusercontent.com/assets/12880627/26145075/078badd6-3ae3-11e7-82d0-671c35e1e0c0.png)
Runs at 2fps eMulator  force closes as in-game start
![screenshot_20170517-092604](https://cloud.githubusercontent.com/assets/12880627/26145113/30d6ab32-3ae3-11e7-813e-47a234c5cfd1.png)
Downhill stuck at loading screen

**Comment by Thunder07** [comment]
@paulaz2 sorry about that, it was hard enough to find the phone.

ok, so are you saying of [this](http://purei.org/downloads/play/weekly/) list, that last one that install was dec 2016?

**Comment by paulaz2** [comment]
@Thunder07 yeah the latest 2017 build does not install.....

**Comment by paulaz2** [comment]
@Thunder07 the latest 20170509 version is even worst
![screenshot_20170518-001840](https://cloud.githubusercontent.com/assets/12880627/26180196/eb47a2a6-3b5f-11e7-8076-d2540295a5df.png)

**Comment by LoungeKatt** [comment]
@paulaz2 That could be a corrupt download. You may have downloaded it before the full file was available. If you download it again and it is still not working, run logcat when you go to install and it will tell you the issue. It will most likely come from the tag "PackageManager"

**Comment by paulaz2** [comment]
@Loungekatt but still apk did not install

**Comment by LoungeKatt** [comment]
> If you download it again and it is still not working, run logcat when you go to install and it will tell you the issue. It will most likely come from the tag "PackageManager"

What was the error message?

**Comment by paulaz2** [comment]
@Loungekatt What is logcat

**Comment by LoungeKatt** [comment]
https://support.symantec.com/en_US/article.HOWTO81826.html

It is a somewhat excessive guide, but it doesn't miss a step.

**Comment by paulaz2** [comment]
I can't run logcat

**Comment by paulaz2** [comment]
@Loungekatt any other solution?

**Comment by paulaz2** [comment]
@Loungekatt any other solution?

**Comment by LoungeKatt** [comment]
If logcat isn't working, you may need to contact the manufacturer for support. That is part of the firmware that should never stop working.

**Comment by Thunder07** [comment]
@paulaz2 can you confirm if [Play-20170123.apk](http://purei.org/downloads/play/weekly/Play-20170123.apk) works or not?

**Comment by paulaz2** [comment]
@Thunder07 the version installed

**Comment by Thunder07** [comment]
That was the last release before the change to cmake, which was accompanied by update of the gradle build system for android, which i suspect is the cause of the issue.

I'm working on something now, but once I get the chance I'll post you an APK using an even newer version gradle and see if that resolves it.

**Comment by LoungeKatt** [comment]
The best test would be to build the current code and test that over making changes. If the version before cmake works, and there are no issues for anyone building locally, then it could be an issue with corruption, outdated binaries, etc on the system for the public builds. Updating gradle wouldn't resolve that, so it should probably be ruled out before further modifying the build process.

**Comment by Thunder07** [comment]
> The best test would be to build the current code from a different machine and test that over making changes.

I agree, the thing was, I suspected it could be the gradle upgrade, and since I was already working on something and had gradle update, it was more convenient to test this theory out 1st (since changing gradle version will rebuild the entire `native` side of the project)

so i will post another apk later to test that as well.

**Comment by paulaz2** [comment]
@Thunder07 it installed

**Comment by Thunder07** [comment]
@paulaz2 can you now try this [Play-release-v1-v2.apk](https://madnation.net/Play/Play-release-v1-v2.apk) (this one is of the same commit as my `android_cleanup` PR, aka without gradle update, with v1 v2 signature, which android studio is forcing me into)( this apk doesnt contain `Play` library for the sake of a faster build)

**Comment by sero583** [comment]
@Thunder07 This is crashing directly on start on my S8

**Comment by sero583** [comment]
Its a exynos one but doesnt matter at all I guess

**Comment by Thunder07** [comment]
@sero583 the latest one is meant to crash, it's an empty shell just got for testing installation.

**Comment by sero583** [comment]
@Thunder07 Ugh didnt knew anyway why doesnt the weekly builds update anymore? Its already much time gone since the latest one, btw I got a Q and thats if you would make PCSX2 android compataible would it be possible to get enough/well FPS?

**Comment by Thunder07** [comment]
@sero583 this project has no association with PCSX2, if you want to know try asking them.

Updates are released when ready, and while they're called weekly builds, they're actually follow a monthly build release.

**Comment by LoungeKatt** [comment]
@sero583 You won't have much luck asking the developers of PCSX2. I ported it a while back and it had even more overhead than this one. The entire project is focused on PC. Even mac is extremely experimental, outdated, and not even published as a compatible platform. Your best bet is to make any attempt you can to provide constructive feedback to @jpd002 to improve this one.

**Comment by sero583** [comment]
@LoungeKatt Well what I can only say about it Dragon Ball Z Budokai Tenkaichi 3 runs well in its menu the sound is very delayed and yeah rendering issues in game are often there and also in the menu for example at animated things like gotens mouth in the main menu. It is very slow as we all know well thats pretty much what I can say, to provide constructive feedback, I also need constructive questions about what the dev/-s would like to know. And yeah its only targeted to PC the name says that but well I dont think that matters much

**Comment by LoungeKatt** [comment]
It matters if you are trying to run it on Android or iOS, neither of which it supports. I can't speak for @jpd002 personally, but details about when and where the graphical issues happen are usually a big help. That makes it easier to track a specific type of rendering or texture. Thanks. 

BTW: The purpose of calling it "constructive feedback" was that it is all too common to get issues like "It crashes! I setted the volume but can't hear it!" which is almost impossible to diagnose.

**Comment by sero583** [comment]
@LoungeKatt Well what I can say is that the sound delay etc. is probably coming from the not well implemented emulator for android, well anyway What I can say is that in DBZ BDK 3 on the home screen sometimes animated things like gohan etc. talking get a black square around the whole animated graphic and that in most games arenas are just gray and you cant really see much except when you load your ki, you slightly see it and when you move around sometimes its blackscreen but going back to old position makes it again "normal" (gray world, only water is blue) ect.

**Comment by LoungeKatt** [comment]
Poorly implemented is a bit harsh considering the drastic difference between Android and PC, but thanks for the details.

**Comment by paulaz2** [comment]
@loungekatt same issues with the latest build.

**Comment by atomic83GitHub** [comment]
This can be close right?

**Comment by LoungeKatt** [comment]
@paulaz2 only you can do that ;)

**Comment by sero583** [comment]
@LoungeKatt No @jpd002 and repo op's also lololol

**Comment by LoungeKatt** [comment]
@sero583 The question was whether or not the issue could be closed, and being @paulaz2's issue, it would only be fair to allow the original author a chance to verify their own issue.

If you can spare some time from trolling, you may notice @paulaz2 is the repo op. If there is no response, I am sure @jpd002 will step in and close it.

It's unfortunate this all has to be explained. It seems like common sense.
