### ISSUE TITLE
Jak X : Loadable with f/s

### ISSUE THREAD

**Issue by TheLastRar** [jpd002/Play-#57]
Game doesn't boot in Play!, showing 60 f/s.

This game also proved rather tricky for PCSX2 to run. requiring .pnach before even showing any of the intro scenes and still has issues.

**Comment by 716Girl** [comment]
https://github.com/jpd002/Play-/wiki you can write this in wiki, no need to create new issue

**Comment by jpd002** [comment]
@TheLastRar Thanks for the report, gonna get the game. Got any idea why they needed to patch the game to make it work?

@716Girl Creating a new issue is ok, it gives me a better idea of the games people would like to see running.

**Comment by TheLastRar** [comment]
@716Girl noted

@jpd002 In PCSX2, the game tries to performs a kernel hook and doesn't like the results, logging this.  
dkernel: HookOrDie() error (new=0x002760b4, old=0x00122c78); aborting.

**Comment by jpd002** [comment]
Moved to compat tracker: https://github.com/jpd002/Play-Compatibility/issues/223. Still doesn't boot AFAIK.
