### ISSUE TITLE
Using non-standard configurations

### ISSUE THREAD

**Issue by AbandonedCart** [jpd002/Play-#570]
The typical configuration for adding signing keys would be to include

```
android {
...
    signingConfigs {
        release {
            storeFile file(KEYSTORE)
            storePassword STOREPASS
            keyAlias KEY_ALIAS
            keyPassword KEYPASS
        }
    }
...
}
```
in the build.gradle file and then create a gradle.properties file in the gradle top level directory with
```
KEYSTORE=/path/to/keystore
STOREPASS=store_password
KEY_ALIAS=key_alias
KEYPASS=key_password
```

so was there any benefit to making an extravagant version with arbitrary conditionals and such?

You could retain making it optional with the conditional on signingConfigs without all the other conditional assignments. It would read if it were enabled or not if it isn't.

**Comment by Gamemulatorer** [comment]
@jpd002

**Comment by jpd002** [comment]
@Gamemulatorer: Friendly warning, please do not tag me on issues like that.

**Comment by Gamemulatorer** [comment]
Sorry 😐

**Comment by AbandonedCart** [comment]
@jpd002 You could have closed the issue if it bothered you. After 3 years, it's fairly obvious that anything being done about it should have already been done.
