### ISSUE TITLE
allow the app to read contents on sd card

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#573]
I was just thinking why not allow the app to play games from a memory card and the internal storage

**Comment by LoungeKatt** [comment]
It doesn't already?
https://github.com/jpd002/Play-/blob/master/build_android/src/main/AndroidManifest.xml#L4

**Comment by Jordanesquivez** [comment]
I've noticed that wherever the first games are... U have to put all other games in that directory/folder... any other folder the game is in, the app will not discover it

**Comment by Thunder07** [comment]
yes, that was done to avoid having to scan the ENTIRE phone every time you close and open the app.
but thats also why you have the option to rescan the entire phone in the settings option.

**Comment by Jordanesquivez** [comment]
@Thunder07 oh I see... I guess I have to work with that...

**Comment by LoungeKatt** [comment]
@Jordanesquivez Yeah, the original design was cut down to avoid long load times, but you can always trick it by using a master folder with a single game and then any subfolders you want placed there. It will detect the master folder and then dig through the subfolders. It depends how much is on your phone and how often it actually changes location.

**Comment by Thunder07** [comment]
@LoungeKatt that won't work either as subsequent scans don't check subdirectories. That was done to avoid scanning the entire phone should the user place iso on the root direct.

**Comment by LoungeKatt** [comment]
@Thunder07 Sounds broken, not efficient. If you want to avoid excessive scans, you leave it to the user to organize their folder structure so games are not in a directory with a lot of unrelated content or subfolders. There is a point where trying to improve the speed of a scan goes from being limited to crippled. This sounds crippled.

**Comment by atomic83GitHub** [comment]
That can be close now?
