### ISSUE TITLE
Atelier Iris: Eternal Mana plays slowly

### ISSUE THREAD

**Issue by Zero3K** [jpd002/Play-#580]
I am playing it via the latest weekly Android build on an Acer Iconia One 8.

**Comment by Zero3K** [comment]
Maybe frameskip could help speed it up.

**Comment by atomic83GitHub** [comment]
I will be better to wait until the emulator is more mature before posting this type of issue :).

**Comment by Zero3K** [comment]
Well, on my GPD WIN, it plays maybe a little too fast in some places. Also, the following issues were noticed in the few minutes I tried playing it (with the latest build on Appveyor):

1. The Opening Video is playing very slowly.
2. I am not hearing the characters speak their lines.

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/528. This issue can be closed now

**Comment by jpd002** [comment]
Been playing this game on my phone lately and I'm suspecting the bottleneck comes from the way things are submitted to the GS thread.
