### ISSUE TITLE
Ultraman Fighting Revolution Rebirth (Android) stuck at start up

### ISSUE THREAD

**Issue by NgJinXiang14** [jpd002/Play-#582]
@jpd002 When i load this game stuck at start up,is play! still not support it? And these people claim that it works ,look at the comments https://youtu.be/LhuDSVfplwE
![screenshot_20170624-021132](https://user-images.githubusercontent.com/6142827/27495004-db8fbcf0-5882-11e7-9177-3292b877f830.png)
![screenshot_20170624-021138](https://user-images.githubusercontent.com/6142827/27495017-e349fe6a-5882-11e7-8aff-788d31794499.png)

**Comment by jpd002** [comment]
Thanks for reporting, I'll look into it.

**Comment by jpd002** [comment]
Moved to compatibility tracker: https://github.com/jpd002/Play-Compatibility/issues/311.
