### ISSUE TITLE
[ Android] ICO crashes immediately after running... extras = kingdom hearts has graphical errors 

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#587]
This makes me feel so sad to see such a nice game crashes, immediately after touched
 could you please take a look into it and also hasn't kingdom hearts graphic bug fix yet..... atleast I thought it was... I saw a guy running it with no graphical issues

**Comment by jpd002** [comment]
Moving this to compat tracker. Feel free to add any new information about the games in there.

- ICO: https://github.com/jpd002/Play-Compatibility/issues/213
- Kingdom Hearts series: https://github.com/jpd002/Play-Compatibility/issues?utf8=%E2%9C%93&q=is:issue+is:open+Kingdom+Hearts
