### ISSUE TITLE
On some of the game Huaping problems

### ISSUE THREAD

**Issue by huaihuai11** [jpd002/Play-#591]
@jpd002 Hello. Thank you for developing the play simulator. The current magic tower mainland 2 and some text games in the dialogue will appear Huaping situation. In addition to heavy equipment armor dust lock will be stuck in the beginning of the plot there. Finally, every time you update the simulator can not let us know in advance

**Comment by Margen67** [comment]
what

**Comment by literalmente-game** [comment]
This is not an issue + doesn't provide any useful info to even make clear if it was an issue report. This should be closed @jpd002

**Comment by jpd002** [comment]
Hi @huaihuai11, I guess you're having an issue with a specific game, but I couldn't find the game you're referring to with the information provided in your post. If you can provide the game's serial number (ie: SLUS_xxx.xx), I could try to see what's going on.

Closing this for now.
