### ISSUE TITLE
Black crash

### ISSUE THREAD

**Issue by Levan7** [jpd002/Play-#594]
I tried starting the Black SLUS 213.76 the emulator crashed.
I tested this on this build Play-20170123-32.exe the platform was on windows 10 x64
Can't find a log output option though.

**Comment by literalmente-game** [comment]
What build, for what system? When you report a problem, make sure to add useful info for a better support. PS: you don't need to reply, just edit your original post to add more details

**Comment by atomic83GitHub** [comment]
With the last version, the game load with fps but show Nothing.

**Comment by jpd002** [comment]
Added compat ticket: https://github.com/jpd002/Play-Compatibility/issues/274.
