### ISSUE TITLE
ONI : crash on loading screen (Windows 10 64bit and Android 6.0)

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#595]
Last stable build

The game ONI can display the intro but crash on the loading screen.

Workaround : there is a patch in PCSX2 that fix this issue , it work in play! 
If the main menu is not display on the screen but the sound is play, switch the emulator to hight resolution (screen refresh issue?) this is a emulator bug , not a patch bug.

Executable Name="SLES_501.76;1" Title="Oni" Region="EU"
		Patch Address="0x001cef7c" Value="0x00000000 // bc0f $001cef7c" Description="Fix hang by skipping branch if copro 0 condition false." 
	Executable

Note: this patch is for pal versions.

Hope get you help.

**Comment by atomic83GitHub** [comment]
I reopen the issue, it's still active and the patch is only for the Pal-F version.

**Comment by jpd002** [comment]
I've added a compatibility report for the game: https://github.com/jpd002/Play-Compatibility/issues/59. I'll close this till we figure out what's the emulation issue breaking the game.
