### ISSUE TITLE
Sillent hill 2 : crash when going ingame (Android 6.0 and Windows 10 64bit)

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#597]
Last stable build.

This game now boot but only in menu and FMV , when going ingame , the game crash. 
Note: It's a prety low game that can possibly run on some Android device.

Hope get you help.

**Comment by jpd002** [comment]
Thanks for closing this.
Compatibility report: https://github.com/jpd002/Play-Compatibility/issues/80
