### ISSUE TITLE
Ratchet and Clank series crash before going ingame (Android 6.0)

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#598]
Last stable build.

The Ratchet and Clank series won't load ingame on Play! 
It would be nice to fix this.

Hope get you help.

**Comment by jpd002** [comment]
I know Ratchet and Clank 3 won't work because of the way VCALLMS is implemented right now. I don't know if all games in the series have the same issue.

**Comment by atomic83GitHub** [comment]
I can confirm that the other games have the issue, and the first one can't go into menu because the background is a 3d environment.

**Comment by jpd002** [comment]
Thanks for confirming!

**Comment by jpd002** [comment]
Compat tickets:
- https://github.com/jpd002/Play-Compatibility/issues/191
- https://github.com/jpd002/Play-Compatibility/issues/81
- https://github.com/jpd002/Play-Compatibility/issues/190
