### ISSUE TITLE
Max payne : crash after the Rockstar Games logo (Windows 10 64bit and Android 6.0)

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#599]
Last stable build
The game Max Payne crash after the Rockstar Games logo.
It would be nice to fix this.

Hope get you help.

**Comment by jpd002** [comment]
This game used to go a bit further, but it never went in game. I'll take a look.

**Comment by atomic83GitHub** [comment]
Its in the pal version, wich have a chose language screen.

**Comment by jpd002** [comment]
The US version has the same issue.

**Comment by jpd002** [comment]
Added some patches to get past the movies. Fixed some CLUT issues and fixed a VIF interrupt issue that was causing random hangs up. The game is playable, but I still need to figure out why the movies crash so I can get rid of the patches.

![capture](https://user-images.githubusercontent.com/6760433/29346196-a83292ca-8211-11e7-9b69-c42b72fde39d.PNG)

**Comment by atomic83GitHub** [comment]
Great job 👍.
PCSX2 must use work around to fix random hangs! and this game is not very difficult to emulate after all.

**Comment by ramapcsx2** [comment]
Check if you fire IRQs from lower SPU2 RAM, the special area up to 0x800 or so.

**Comment by jpd002** [comment]
It could have been that since that particular case is not emulated properly, but the game doesn't seem to use SPU IRQs.

**Comment by ramapcsx2** [comment]
It's been years but I remember there being an auto generated IRQ on the SPU2 lower memory. One game that relies on it firing is this title. Another is Fatal Frame 3, which aparently also doesn't start on Play. So I made the connection ;)

**Comment by jpd002** [comment]
Ah, thanks for the tip! I'll take a look tonight!

**Comment by jpd002** [comment]
I tried the game on a old build which was capable of running the game past the intro movies. The interesting difference between that old build and the current version is the speed at which the audio data DMA transfer is executed. 

Throttling the transfer seems to allow the game to finish movie playback somehow (certainly not in a clean way though), otherwise, the game remains stuck waiting for some kind of rendering routine that gets shutdown prematurely by another thread.

I'll leave the throttling mechanism there (doesn't seem to break things with other games from what I've seen), but I'll have to investigate this further.

**Comment by ramapcsx2** [comment]
SPU2 events and timings are a major compatibility factor. Many games throw the towel when something isn't exactly as they expected. It would be great to have a hardware test for this.

**Comment by jpd002** [comment]
Agreed. I was thinking of writing some tests for this, but I'm still unsure about the best way to isolate the tricky behaviors. I'll see what I can do.

**Comment by atomic83GitHub** [comment]
Any status on this?

**Comment by jpd002** [comment]
Still an issue today, I need to get on those SPU hardware tests.

**Comment by Jordanesquivez** [comment]
@jpd002 Any new build for android?

**Comment by jpd002** [comment]
Soon-ish, I'm working on getting builds automatically available from updates made to this repository.

**Comment by jpd002** [comment]
Compat tracker issue: https://github.com/jpd002/Play-Compatibility/issues/186.
