### ISSUE TITLE
Timesplitters doesn't boot 

### ISSUE THREAD

**Issue by LasagnaPie** [jpd002/Play-#6]
Timesplitters does not boot.
SLES 50078 [PAL] Original Disk.

**Comment by jpd002** [comment]
Thanks to the changes from @bigianb and some other minor fixes I did, the game can now display the introduction movies:

![ts_01](https://cloud.githubusercontent.com/assets/6760433/6773262/ebbc4bac-d0e4-11e4-892b-fe078a9a2f36.jpg)
![ts_02](https://cloud.githubusercontent.com/assets/6760433/6773264/edd3fdcc-d0e4-11e4-98ca-7f083af4dfb9.jpg)

But unfortunately, it crashes right after the movies are done playing. I'm investigating the problem right now, but you can look at the changes I did in the timesplitters branch I've just pushed.

**Comment by jpd002** [comment]
In the latest weekly build, the game can go a bit further:

![ts_03](https://cloud.githubusercontent.com/assets/6760433/6889369/be9f341c-d662-11e4-9d09-ba9384560bfd.jpg)
![ts_04](https://cloud.githubusercontent.com/assets/6760433/6889370/c1e44662-d662-11e4-90e8-dafa7728c800.jpg)
![ts_05](https://cloud.githubusercontent.com/assets/6760433/6889371/c3c47664-d662-11e4-8869-5402c6341cef.jpg)

It crashes after the mission intro movie, so there's still some work required to make this fully playable.

**Comment by jpd002** [comment]
Closing this as game boots now. I will come back to this game later to make it playable.
