### ISSUE TITLE
Pluggable VPU implementation 

### ISSUE THREAD

**Issue by bigianb** [jpd002/Play-#60]
Hi JP, I thought I would post this here rather than emailing. It's great to see the project gaining traction - I'm still very busy with real life, but watching with interest from the sidelines.
I've been tinkering with some very high level emulation for BGDA - basically I want to hook the VPU and GS implementations. So, when a game is loaded, I look to see what the ID is and if there are any specialised VPU / GS handlers available. If so, install those rather than the default ones.
This is pretty easy to do with the GS Handler but things are more tricky for the VPU. The EE currently binds the VIF and VPU constructors at compile time, so they cannot easily be hot swapped later.

I can of course hack something in my branch to do what I want but before doing that was wondering if you had a plan to do this already. I'm trying to keep my branch as close to yours to give myself an easy life when merging :)

**Comment by MoochMcGee** [comment]
this is a horrible horrible idea and should be banned from this emulator

**Comment by jpd002** [comment]
@bigianb While I wasn't planning to do that, I wouldn't have any objection to change the way the VPUs are constructed inside Ee::CSubsystem. Not quite sure about the pluggable part though. Do you want to enhance the game's visuals using the hooks? Are you looking for a way to get rid of that dreaded "DELAYED_MSCAL" thing?

About that, I was planning to write a test in ps2autotests to look into MSCAL's behavior when it's used in the same way BGDA (and other Snowblind games) uses it and hopefully find a proper fix for it.

Good to hear from you again btw :smile:

**Comment by bigianb** [comment]
@jpd002 The delayed MSCAL works fine - in fact the emulation status of BGDA and the other snowblind engine games is now pretty spot on. What I'm looking to do is to use the core play engine to build an engine which gives an enhanced experience for the BGDA games. For stage one, I am aiming to get the display running in progressive scan at native resolution. Stage 2 would then be to allow modding, texture swapping etc (which involves hooking the EE CPU which I already do in my branch).
How to do this - well I know what all the VU calls do, so if I can intercept the MSCAL then I have the vertex information and if I intercept the GIF then I have all the texture information. I don't want to duplicate the VIF decoding, so I want to hook in at the VPU level.

Of course I am also hoping that stage 1 will give me a big speed boost as it will eliminate most of the per frame texture swizzling.
As for the ability to hot swap the VPU handler - I'm not sure what we really gain from the compile time binding. I don't think there is much if any optimisation that the compiler will do between these components as the call interface is quite coarse (i.e. MSCAL) - the rest of what the VIF does is unpacking the FIFO which doesn't really touch the VPU implementation.

**Comment by bigianb** [comment]
I had some time to take a closer look on my train ride this evening. The main blocker is that m_vpu1 is an object in the EE_Subsystem and so its type is fixed at compile time. If it was a pointer or a reference then we would be able to inject an alternative implementation during EE_subsystem construction.

**Comment by jpd002** [comment]
@bigianb Sounds like an interesting idea :smile: I would love to see BGDA in HD.

m_vpu1 is an object inside Ee::CSubsystem just because I'd rather avoid using pointers when they are not needed. If you want to make the change, go ahead (just make sure m_vpu0 is also a pointer) and send a pull request over.

**Comment by bigianb** [comment]
I had a little play this evening with a prototype. The changes are quite small and it compiles ... but it does not work (so no PR yet). For some reason the VIF decoding screws up - I'll look deeper in a day or so.
The changes are in my branch here: https://github.com/bigianb/Play-/tree/injectable_vpu
@jpd002 if you have any comments on the approach before I make a PR (or if you have an idea why it does not work) then it would be great to hear them.

Ian

**Comment by MoochMcGee** [comment]
The reason why this is a bad idea is because it is a giant hack. Also because code is uploaded to the VUs at runtime, which means you'd have to constantly switch out VU handlers. Also, it wouldn't be compatible with homebrew.

**Comment by MoochMcGee** [comment]
Seriously, with hacks this gigantic, you'll be shit-tier in no time.

**Comment by jpd002** [comment]
I think the idea here is to allow writing a specific VPU handler per game and instantiate it once the game is started. Besides, that PR only changes two object types to pointers. It doesn't change the behavior of the emulator at all.

My stance on game specific modifications is that they shouldn't be used to make games work, but are ok if they are used to enhance games (a bit like texture packs in Dolphin). I don't think enhancement mods should be a part of the emulator yet, but if someone wants to be able to experiment in their fork, I don't want to make their life harder.

**Comment by bigianb** [comment]
@jpd002, that's exactly right. It's making the core pluggable so that it can be used unchanged in other projects/forks. In my case that is an enhanced snowblind engine ... but that's just context. Also, having an Inversion of Control (IOC) ability makes any future unit testing a lot easier because components can be mocked and injected.

On systems that support DLL loading I could envision the main program looking for any dlls registered for a given game once a game is selected (but before it is loaded) i.e. hooking into when it reads the system.cnf. These game specific Dlls would not be part of the emulator but developed by different people in different repos.

@MoochMcGee I understand your concern, but it appears that you're thinking the idea is something different. The point is to make the emulator perfect without any game specific hacks ... but to allow game enhancements were possible. In the case of BGDA, we know the functionality of 100% of the VPU1 code and so can completely replace it along with the GS implementation - which enables lots of fun mods to the visuals whilst still keeping the gameplay authentic.

**Comment by ADormant** [comment]
@bigianb Can this modification allow for things like texture replacement and per-pixel lighting? Maybe even 3D model replacement?

**Comment by bigianb** [comment]
@ADormant - yes that type of thing .. for specific games. Its a long term goal though - nothing that will happen soon.

**Comment by ADormant** [comment]
@bigianb Could it be made to work for all games or any game is going to need a specific hack? Dolphin and N64 emulators haven't got model replacement however their texture replacement and per-pixel lighting work for all games.

**Comment by ADormant** [comment]
I also wonder if glitches like these http://forums.pcsx2.net/Thread-Blog-Explanation-of-why-hacks-are-needed-to-fix-upscaling-related-glitches can be fixed with those enhancements for PCSX2 needs hacks to counter them.

**Comment by bigianb** [comment]
@ADormant It will be game specific. For the N64, nintendo provided the library to use the RDP/RSP (the equivalent of the VPU/GS combination in the PS2).  That meant nearly all games used the same libraries for the low level graphics and so it is quite easy to detect what calls are being used and high level emulate them. For the PS2, the situation was different - Sony provided no real high level libraries so each developer did it differently. So - to provide this type of HLE, it is important to know what all the VPU routines do for each game and provide high level replacements for them - that's quite a lot of work for each game.
As  for your second question, high level emulation of the VPU routines would avoid upscaling issues as you would render the mesh at a higher resolution rather than scaling a pre-rendered version.

**Comment by ADormant** [comment]
@bigianb Hmm but Dolphin's GPU emulation is LLE and it can do texture replacement and per-pixel lighting fine for all games. Does Dolphin even use HLE functions for these features? With PPE it may be harder due to PS2 doing lighting calculations on VPU1 instead of the GPU like GC and Wii are doing. However texture replacement should work as long it can dump and reinsert textures.

**Comment by ADormant** [comment]
http://gliden64.blogspot.com/2013/09/hardware-lighting.html
http://gliden64.blogspot.com/2014/11/a-word-for-hle.html

**Comment by bigianb** [comment]
I've no knowledge of dolphin or Wii/GC so cannot comment on that. Texture
replacement without having some meta information about what the game is
doing on the PS2 though is pretty impossible (maybe not actually
impossible, but at least improbable). The texures are passed via DMA to the
GS and the geometry is generally passed via the VPU1 ... the 2 paths are
unrelated and so it's difficult to relate them.
I assume that there is a more unified path in Dolphin and so it can do more
without meta-information.

Ian

**Comment by ADormant** [comment]
> I assume that there is a more unified path in Dolphin and so it can do more
> without meta-information.

@bigianb Then I presume N64 emulators are doing it the same way as Dolphin.

**Comment by atomic83GitHub** [comment]
This feature has been implemented a while ago! This can maybe be close.

**Comment by jpd002** [comment]
Yeah, the PR has been merged a while back and there hasn't been any update on the subject for a long time. Gonna close for now.
