### ISSUE TITLE
Harvest Moon Save the Homeland (Android) 7/31/17

### ISSUE THREAD

**Issue by Hugessfan** [jpd002/Play-#601]
At first it seems like just a black screen, but after waiting a few minutes color slowly started to appear. Not only is the game very slow, but nothing can be seen since the graphics stretch everywhere preventing anything from being seen. Also the audio makes a loud sudden noise every now and then.﻿ The game is currently completely unplayable.
![screenshot_20170731-194837](https://user-images.githubusercontent.com/30610305/28805054-eab2291c-762c-11e7-88f1-e6375d006ee1.png)

**Comment by fagoatse** [comment]
You're better off testing games on desktop. Android is Google's garbage fork of linux meant to serve ADs and not handle high performance tasks such as Play!. You're mileage will vary witch each device due to, usually, poor GPU drivers.

**Comment by Hugessfan** [comment]
As long as people are trying to use Play! on android, I will test any and all games I have interest in. Many people only have android devices, and if nobody tries to help the android version's development by providing feedback and reporting bugs, then many people will feel sad about not being able to play their favorite games of the past. This is why anyone with an android device should try to help!

**Comment by jpd002** [comment]
Same issue happens on PC. This is due to unimplemented FMAC hazard stalls. There's a WIP branch for that (fmac_hazard). Related issue: #504.

**Comment by jpd002** [comment]
Compatibility report: https://github.com/jpd002/Play-Compatibility/issues/209. 
Current list of game exhibiting fmac-stall issues: https://github.com/jpd002/Play-Compatibility/labels/issue-fmacstall.
