### ISSUE TITLE
Request for jade cocoon 2

### ISSUE THREAD

**Issue by Houndead** [jpd002/Play-#603]
Please fix crash when starting the new game, please, i would happy to buy the app in playstore hehehe

**Comment by Houndead** [comment]
Sorry i have to post this in here, cant contact you in gmail you were given in play! Website

**Comment by jpd002** [comment]
Thanks for reporting this. I'll take a look when I get the chance.

**Comment by jpd002** [comment]
Compatibility issue here: https://github.com/jpd002/Play-Compatibility/issues/215.
