### ISSUE TITLE
"No ps2 games found"

### ISSUE THREAD

**Issue by thunderkid07** [jpd002/Play-#605]
Help!! I cant play my Persona 3 FES because it does not appear on the emulator.I have the iso on my SD card. :3

**Comment by thunderkid07** [comment]
Update: It already apeared in tge emulator but now it only shows black screen.

**Comment by jpd002** [comment]
The game might not be supported. I know Persona 4 works somehow, but I have no clue about Persona 3.

**Comment by jpd002** [comment]
Also, closing this as initial issue (games not being found) was resolved.
