### ISSUE TITLE
[Request] Support for dual core (or multicore).

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#606]
Hi everyone.

I have an idea to improve the emulator speed, it would be nice to add support for dual core (or more) if it's possible.This will help android devices to run ps2 games and improve speed on desktop OS.

Hope get you help

**Comment by jpd002** [comment]
The emulator already uses two cores, one for EE/IOP/VU0/VU1 and one for GS. I've been playing with the idea of adding more parallelism to the emulator, but I'm still unsure of the best way to do that without breaking any games.

**Comment by atomic83GitHub** [comment]
Ok so I will close the topic.
