### ISSUE TITLE
Oni 2 death and taxes [dev build]: strange screen error (Windows 10 64bit)

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#608]
Last stable version

The game boot but show this error on the screen.

![image](https://user-images.githubusercontent.com/26351275/29228630-d2c83bd2-7eda-11e7-9691-e8597c5ba8f7.png)

Hope get you help

**Comment by jpd002** [comment]
Funny that they kept their assert messages in their game. Makes it easier to figure out where the problem is. My bet is on an unimplemented module call on IOP.

**Comment by jpd002** [comment]
Compatibility tracker issue: https://github.com/jpd002/Play-Compatibility/issues/188.

**Comment by dvdvideo1234** [comment]
@atomic83GitHub 

Where did you buy the game? I was able to find only the first sequel of the franchise.

**Comment by atomic83GitHub** [comment]
Well it's not available for sale, it's a dev build that you can find with some google research.

**Comment by thecrafer150** [comment]
Where can i find the iso? i've searching for hours but i still haven't found anything..

**Comment by jpd002** [comment]
Please don't ask for download links. Any link will be removed.
