### ISSUE TITLE
PS2VM: Error mounting cdrom0 device: Unsupported operation.

### ISSUE THREAD

**Issue by legluondunet** [jpd002/Play-#609]
Hello,

when I launch Play, I obtain this error message in my terminal:

PS2VM: Error mounting cdrom0 device: Unsupported operation.

and each time I try to open a game image (ISO)

Perrhaps I forgot to install a dependencie?

Thank you for your help.

config:
Ubuntu 17.04 Zesty Zapus 64 bits - NVIDIA GeForce GTX 770 - official Ubuntu Nvidia drivers 375.66 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM

Play compiled from git the 15th august 2017

**Comment by jpd002** [comment]
Hi!

Where are your ISO files located? Are they stored on a remote file system?

Thanks!

**Comment by legluondunet** [comment]
nop, on the local harddsik.

**Comment by Thunder07** [comment]
[this](https://github.com/jpd002/Play-/blob/master/Source/Posix_VolumeStream.cpp#L64) is the problematic line

**Comment by jpd002** [comment]
@Thunder07 It could be the case, but this code is only executed when running a game from a physical disc. Unless @legluondunet has mounted the disc image or something?

**Comment by Thunder07** [comment]
maybe the way the ISO is dumped? (`dd` vs isomaker app) I'm having this issue with only a subset of games.

I traced it to https://github.com/jpd002/Play-/blob/a9a88272f2332d9cdeb855e6be01e8613954a626/Source/OpticalMedia.cpp#L51-L56

https://github.com/jpd002/Play--Framework/blob/91cc6d57ecf01896623363198973dc1fb17b8441/src/Stream.cpp#L114
```
uint64 CStream::GetLength()
{
	uint64 position = Tell();
	Seek(0, STREAM_SEEK_END);
	uint64 size = Tell();
	Seek(position, STREAM_SEEK_SET);
	return size;
}
```

https://github.com/jpd002/Play-/blob/72e04c4f167392781858ba877b9beee0969c2d49/Source/Posix_VolumeStream.cpp#L53-L67

from this, it's either implementing `GetLength()` and overriding it or the implemented `STREAM_SEEK_END` 'fixed' the issue (I returned a dummy value to avoid the crash)

Note:
I'm not on ubuntu at this moment, so I don't have the exact backtrace.

**Comment by legluondunet** [comment]
I already have this message error at Play! launch:

1) launch Play! on a terminal:

$ ./Play 
PS2VM: Error mounting cdrom0 device: Unsupported operation.
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock

2) open an iso file (menu file,  boot disk image):
"PS2VM: Error mounting cdrom0 device: Unsupported operation."

For your informaition, all my isos work great with PCSX2.

**Comment by jpd002** [comment]
@Thunder07 Oh yeah, I didn't take into account physical discs when I implemented the dual layer detection heuristic. There's definitively a problem there. But, are you also hitting that problem while booting disc images?

**Comment by Thunder07** [comment]
ya, I'm getting it on disc ISO images, however its not an issue with bin images (I've also found out that some of my ISOs where actually bins :) ).


```
1   Framework::Posix::CVolumeStream::Seek                                 Posix_VolumeStream.cpp 64  0x55eba566b372 
2   Framework::CStream::GetLength                                         Stream.cpp             117 0x55eba5684110 
3   COpticalMedia::CheckDualLayerDvd                                      OpticalMedia.cpp       56  0x55eba5668c5f 
4   COpticalMedia::COpticalMedia                                          OpticalMedia.cpp       26  0x55eba5668f6b 
5   std::make_unique<COpticalMedia, std::shared_ptr<Framework::CStream>&> unique_ptr.h           791 0x55eba5605c62 
6   DiskUtils::CreateOpticalMediaFromPath                                 DiskUtils.cpp          72  0x55eba5605c62 
7   CPS2VM::CDROM0_Mount                                                  PS2VM.cpp              679 0x55eba55f239e 
8   CPS2VM::CDROM0_Reset                                                  PS2VM.cpp              666 0x55eba55f258c 
9   CPS2VM::ResetVM                                                       PS2VM.cpp              365 0x55eba55f26be 
10  CPS2VM::Reset                                                         PS2VM.cpp              198 0x55eba55f2aa5 
11  MainWindow::BootCDROM                                                 mainwindow.cpp         219 0x55eba558bcdd 
12  MainWindow::on_actionOpen_Game_triggered                              mainwindow.cpp         158 0x55eba558f1ab 
13  MainWindow::qt_static_metacall                                        moc_mainwindow.cpp     196 0x55eba55af4d3 
14  MainWindow::qt_metacall                                               moc_mainwindow.cpp     197 0x55eba55af4d3 
15  QMetaObject::activate(QObject *, int, int, void * *)                                             0x7f4de624c924 
16  QAction::triggered(bool)                                                                         0x7f4de6ef0992 
17  QAction::activate(QAction::ActionEvent)                                                          0x7f4de6ef3380 
18  ??                                                                                               0x7f4de6ef392f 
19  QMetaObject::activate(QObject *, int, int, void * *)                                             0x7f4de624c789 
20  ??                                                                                               0x7f4dd9fac10b 
... <More>                                                                                                          
```

**Comment by jpd002** [comment]
Humm, well, I guess a VolumeStream can be created successfully from a file then. I thought the call to `fstatvfs` would be enough to determine if the specified path is a mounted file system (ie.: coming from a physical disc). Since we need to have a way to obtain the size of the volume anyway, I guess we could use the information in the `f_blocks` field to compute that?

**Comment by Thunder07** [comment]
from what I understand yes, but I can't seem to get the correct size.

**Comment by jpd002** [comment]
So, basically, opening any file that's not a isz or cso would go through the `CVolumeStream` code path. `fstatvfs` works with any fd and will report the info of the filesystem where the file is located.

In any case, it only makes sense to use `CVolumeStream` on files that are located in `dev` since we want to access everything at the block level. So I restricted the usage of `CVolumeStream` accordingly here: ed13a47. @Thunder07 could you confirm that it works with your disc images?

`CVolumeStream` is still broken though, at least, on Linux and FreeBSD. I did a quick test and `fstatvfs` doesn't seem to report a good value for block size and block count. Maybe we need to use `ioctl` to get those?

**Comment by Thunder07** [comment]
yup that seems to have done the trick.

I've tested `ioctl` and its returning the correct value for block/sector size `BLKSSZGET`, i guess if you want block count, you can get volume size 'BLKGETSIZE64' divide it by block size?

**Comment by jpd002** [comment]
@Thunder07 Thanks! I'll merge that commit in master later tonight! Yeah, I was looking at those `ioctls` last night and from what you're saying, it's probably what we need (at least, for Linux).

**Comment by jpd002** [comment]
Fix has been merged. Booting from ISO disc images on Linux should work fine now.

**Comment by legluondunet** [comment]
I can load ISO image, nice work!
