### ISSUE TITLE
Sky Odyssey, Virtua Racing and Vrally3 crash the emulator when they boot (Windows 10 64bit).

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#611]
Last stable build:

"Sky Odyssey", "Virtua Racing" and "Vrally3" crash the emulator when they start:
![crash](https://user-images.githubusercontent.com/26351275/29423160-ff755616-837a-11e7-9630-f5529ffd934a.JPG)

Hope get you help.

**Comment by jpd002** [comment]
Thanks for closing. Links to compatibility reports you've created (for tracking purposes):
https://github.com/jpd002/Play-Compatibility/issues/83
https://github.com/jpd002/Play-Compatibility/issues/85
https://github.com/jpd002/Play-Compatibility/issues/86
