### ISSUE TITLE
Support for non SSSE3 processor.

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#614]
Play! Can't be executed on a processor that doesn't support the SSSE3 instruction set.

It would be nice to update the system requirement in the readme file to precise this.

Hope get you help.

**Comment by Thunder07** [comment]
thats not an AMD issue. you're using an old processor that does not support SSSE3 instruction set.

**Comment by atomic83GitHub** [comment]
Ok so play! don't support SSE2. It would be nice to precise it in the system requirement, (so amd fx and later will work.). Thanks for the info. Amd phenom 2 support SSE2 SSE3 and SSE4a.

Update the issue.

**Comment by Thunder07** [comment]
it's S-SSE3 (Supplemental - SSE3)

**Comment by jpd002** [comment]
This could be fixed easily, only one SSSE3 instruction is needed. I could change code generation to dynamically use SSSE3 instructions when it's available on the CPU.

**Comment by atomic83GitHub** [comment]
I have made a pull request about the system requirement.I will update it if Play! suport under the SSSE3 instruction set.

**Comment by jpd002** [comment]
Thanks. I'll fix that ASAP because this is quite important. 

Also, there's nothing on non-Windows systems that uses cpuid to verify available CPU features (https://github.com/jpd002/Play--CodeGen/blob/94e6caf585874b49feb0764bdfe9ebbad29e252d/src/Jitter_CodeGen_x86.cpp#L206). This is quite bad considering SSE4.1 brings a nice optimization opportunity that's not enabled on other platforms.

**Comment by atomic83GitHub** [comment]
It will be nice to integrate SSE4.1 but in my opinion, I think keep the compatibility with old precessor is a great feature because the emulator support Windows XP.
Or I have an idea, integrate the SSE4.1 feature only in the 64bit version (I am not a coder, just a potential idea).

**Comment by atomic83GitHub** [comment]
This will be very nice for AMD processor because they integrate SSSE3 in the fx series, athlon2 and phenom 2 don't have it (they are nearly at the same level that the i5 5xx) and for WindowsXP support.

**Comment by jpd002** [comment]
There will be a fallback for processors that don't support SSSE3 or SSE4.1. The idea is to keep SSE2 as the bare minimum requirement.

**Comment by sirdanielk** [comment]
That is generous to still support SSE2, but please don't forget about SSE4.1 and higher. I believe none cpu without 4.1 can be suitable for PS2 anyway and produce good FPS

**Comment by jpd002** [comment]
@sirdanielk Agreed, but it's quite easy to support the old SSE2 stuff while enabling new instructions using the info from CPUID, so, it's not much of a big deal if it can allow some more people to play.

- Added the fallback: https://github.com/jpd002/Play--CodeGen/commit/0c4962507796f68f3183a80737ca55d1185f4ed8
- Also added an optimization for SSE4.1: https://github.com/jpd002/Play--CodeGen/commit/f54030b5cc412869c17b6d21b8c2d44fc94e01fd
