### ISSUE TITLE
improving the fpu??

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#616]
I was just wondering if I.proving the GPU would boost performance

**Comment by atomic83GitHub** [comment]
The GPU is not the performance issue on play!, it's the core. and the fpu (and many other part) are improve day by day so I think this topic is useless (and duplicate I think).

**Comment by jpd002** [comment]
It really depends on the game, but in most cases it's not GPU bound. The main bottleneck in 3D games is VU emulation with takes a huge toll on the CPU. There's also issues with communication between the main thread and the GS thread I've been investigating.
