### ISSUE TITLE
Metal gear solid 3 subsistance : memory cards not recognized (Windows 10 64bit)

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#620]
Last stable build

The memory cards are not recognized in the game "Metal gear solid 3 subsistance" (Base version not tested).

![mgs](https://user-images.githubusercontent.com/26351275/29486477-9c158236-84e6-11e7-8b23-8dc89055b1b9.JPG)

Hope get you help.

**Comment by jpd002** [comment]
Got the same error on the japanese version. I haven't looked into it, but I guess something's missing in the McServ HLE module.

**Comment by atomic83GitHub** [comment]
Same issue on shadow of the collosus.

**Comment by jpd002** [comment]
Added info in related compatibility issues:
Metal Gear Solid 3 - Subsistance - https://github.com/jpd002/Play-Compatibility/issues/3
Shadow of the Colossus - https://github.com/jpd002/Play-Compatibility/issues/10
Sonic Heroes - https://github.com/jpd002/Play-Compatibility/issues/11

**Comment by fajar23** [comment]
#620
