### ISSUE TITLE
Remove workaround patch.

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#622]
3 games in play! have a custom patch to avoid hang at loading screen or other issues.
- ONI
- Baldur's gate: Dark alliance
- Outrun

The target is to fix real issue and remove custom patch.

Hope get you help.

**Comment by prafullpcsx2** [comment]
Spongebob is already fixed so my patch isn't needed anymore. I hope the fix can be ported to PCSX2.

**Comment by atomic83GitHub** [comment]
There is a patch for it on PCSX2 but only for one version if I remember, maybe it's the same I don't know.

**Comment by atomic83GitHub** [comment]
If a remember, this game use the same engine as the Incredibles games, so maybe the issue is the same with these games.

**Comment by prafullpcsx2** [comment]
Incredibles patches can also be removed now as this spongebob fix also fixes them.

https://github.com/jpd002/Play-/commit/32b7aa7013b067025f054430195a10039d6700a7

**Comment by atomic83GitHub** [comment]
thanks for the info, so now, only ONI have a boot issue.

**Comment by jpd002** [comment]
@prafullpcsx2 Thanks for confirming, I read those games were made by the same company, so I was suspecting the issue would be the same as Spongebob.
