### ISSUE TITLE
[Win] Error opening images in russian name folders

### ISSUE THREAD

**Issue by shikulja** [jpd002/Play-#624]
The path to the disk image with the Russian folder names does not work. The problem with the encoding.
Add alt + enter fullscreen
Thank you, good luck in the development!

**Comment by jpd002** [comment]
Oh yeah, indeed, that is broken. I'll look into it.

**Comment by jpd002** [comment]
I've made changes to the emulator to improve path handling. Paths with different character encodings shouldn't be a problem in the latest automated build (available [here](http://purei.org/downloads.php)).

**Comment by shikulja** [comment]
work. thx
