### ISSUE TITLE
Quake.elf crash on play！

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#625]
A elf posted on the play！website don´t work with the emulator（regression？）.

Hope get you help.

**Comment by jpd002** [comment]
Have you placed a copy of Quake's game data (ie.: the `id1` folder) in `Play Data Files/vfs/host`?

**Comment by atomic83GitHub** [comment]
No, I will test.

**Comment by BenNottelling** [comment]
Also crashes for with the id1 folder in the correct place. Also doesn't work with other data files

**Comment by atomic83GitHub** [comment]
I will close the issue in favor of this: https://github.com/jpd002/Play-/issues/669
