### ISSUE TITLE
[feature request] Add a Program Log with the emulator.

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#626]
It would be nice to have the possibility to see what is happening when a game crash or don't boot.
It can be an advantage for bug reporting.
This is the PCSX2 Program Log:
![image](https://user-images.githubusercontent.com/26351275/29994967-9a22d4ae-8fdd-11e7-8cc9-76f7ffac0225.png)

Hope get you help.

**Comment by Thunder07** [comment]
the emulator already has a debugger and logging functionality.

I'd imagine the reason it wasn't brought up in issue debugging, was because most reported issues are easy to replicate without asking the users to bring the debugger up.

**Comment by atomic83GitHub** [comment]
Ok thanks for the info, so I will close the topic.

**Comment by jpd002** [comment]
The debugger is left out of official builds to remove any overhead it could cause. The emulator can be build from source with the debugger active for tracing purposes.
