### ISSUE TITLE
Naruto Shippuden: Ultimate Ninja 5 help

### ISSUE THREAD

**Issue by ahumbledevoloper** [jpd002/Play-#627]
Hi,
The game Naruto Shippuden: Ultimate Ninja 5 works fine until after the Bandai logo in the intro, after which the game is just black. Is there any way to fix this or skip the intro? I also checked the frame rate on the screen of my android, it was increasing and decreasing (around 58 f/s, 59 f/s), but the screen remained black. I'm using the latest version of play (08-28-17) on Android Moto G4.

**Comment by jpd002** [comment]
Thanks for reporting, I'll see what I can do.

**Comment by ahumbledevoloper** [comment]
Thank you. Please let me know the solution if you find one.

**Comment by paulaz2** [comment]
Just like same issue with downhill domination.

**Comment by ahumbledevoloper** [comment]
Perhaps, maybe other games also have just black screens in the intro. Hopefully there's a method to skip the intro or it runs properly.

**Comment by ahumbledevoloper** [comment]
Hi jpd, could this issue be present because of an issue with command line parameters in the game, just like with Harry potter Chamber of Secrets and Half Blood Prince?

**Comment by jpd002** [comment]
Could be, you can try the game with the build provided in that issue to see if it works.

**Comment by ahumbledevoloper** [comment]
I tried, didn't work unfortunately. Same issue remains.

**Comment by ahumbledevoloper** [comment]
Do you know what the problem might be

**Comment by ahumbledevoloper** [comment]
![screenshot_20170909-190448](https://user-images.githubusercontent.com/31637546/30245558-45809408-9592-11e7-871c-5ce21b9b74b2.png)
A screenshot of what's going on

**Comment by jpd002** [comment]
Can't look at it right now and I can't give you an ETA either, sorry.

**Comment by ahumbledevoloper** [comment]
Ok that's fine, but please lo into it when you have the time

**Comment by jpd002** [comment]
Moved to compatibility tracker: https://github.com/jpd002/Play-Compatibility/issues/309.
