### ISSUE TITLE
007: NightFire (SLUS-20579) Black Screen of Death (All Systems)

### ISSUE THREAD

**Issue by brand175** [jpd002/Play-#629]
I would love to see this game work. Since none of the 007 games boot and their doesn't seem to be any fps shooters that currently work for this emulator. Build: August 29, 2017

**Comment by MoochMcGee** [comment]
Hey, I played this game on real hardware back in the day as a little kid!
The PS2 version even!

**Comment by brand175** [comment]
@MoochMcGee   I played this game since when i was 4 and i still kick ass at multiplayer. I really wanted to play this on my jailbroken iPad Air. And in the future with my iPad Pro if a jailbreak ever comes out. Also playing on the map Atlantis is where i can see major increase in fps, compared to Phoenix Base or Skyrail on both consoles. About 10-20fps difference depending on how slow your pc is.

**Comment by atomic83GitHub** [comment]
#brand75 [their doesn't seem to be any fps shooters that currently work for this emulator.] , if a remember, Unreal tournament work with the emulator ☺.
But anyway, it will be nice to see it working on Android/ios devices 😃.

**Comment by spring568** [comment]
Seems like a good game to take a look at too. The vp6 videos still have problems with dolphin-emu and the pc version is hard to get working on windows 10.

**Comment by jpd002** [comment]
I'll take a look when I get the chance.

**Comment by jpd002** [comment]
Added compatibility report for this game:
https://github.com/jpd002/Play-Compatibility/issues/31
Closing this because this is not a discussion about the technical reasons that makes this game unbootable.
