### ISSUE TITLE
PS2 Hardware Documentation

### ISSUE THREAD

**Issue by ADormant** [jpd002/Play-#63]
I know it wouldn't be a trivial amount of work but could you @jpd002  consider writing a PS2 hardware documentation like the ones available for the PS1, GBA and DS? Perhaps in collaboration with the PCSX2 devs? Presently not many people understand PS2 hardware thus both Play and PCSX2 lack contributors.
I am talking about something like this
 https://github.com/simias/psx-guide/blob/master/guide.tex
https://svkt.org/~simias/guide.pdf
http://problemkaputt.de/psx-spx.htm
http://problemkaputt.de/gbatek.htm

**Comment by ADormant** [comment]
Perhaps some PS2 wiki would be a good idea too. @jpd002

**Comment by Evolution0** [comment]
http://lukasz.dk/playstation-2-programming/archive/
http://lukasz.dk/playstation-2-programming/an-introduction-to-ps2dev/

Some stuff of note.

**Comment by jpd002** [comment]
@ADormant I like the idea, but yeah, that would be a crazy amount of work. I might consider starting a wiki in the future, but right now, my time is quite limited and I'd rather work on the emulator itself.

**Comment by jpd002** [comment]
While not a direct documentation for the system, there's also https://github.com/unknownbrackets/ps2autotests which goal is to analyze the PS2's behavior using programs built to run on the actual hardware.

**Comment by atomic83GitHub** [comment]
@jpd002 Maybe you can add these info in the readme of Play and close this issue?

**Comment by jpd002** [comment]
Probably not going to happen.
