### ISSUE TITLE
[Android] Cannot build using NDK15+

### ISSUE THREAD

**Issue by acocalypso** [jpd002/Play-#634]
With NDK 15 it isnt possible to compile the project
error: no member named fsetpos and fgetpos in the global namespace

I tried it with NDK16 Beta1 but the error is still there

Edit: According to the git page from NDK the issues should be resolved in NDK16 Beta2

**Comment by jpd002** [comment]
Yeah, I've heard there's problems building boost with the latest NDK versions. On my side, I'm getting an error related to a missing `truncate` function (https://github.com/boostorg/filesystem/issues/65). 

Do you have the same problem?

**Comment by acocalypso** [comment]
Hi yeah im facing the same issue.

**Comment by acocalypso** [comment]
A few commits ago build was possible nur all games in tried crashed the emulator

**Comment by jpd002** [comment]
Where does it crash? Do you have a stack dump?

**Comment by acocalypso** [comment]
Logcat:
`04-04 22:13:12.265 17242-17242/? I/zygote64: Late-enabling -Xcheck:jni
04-04 22:13:12.465 17242-17257/? I/zygote64: The ClassLoaderContext is a special shared library.
04-04 22:13:12.534 17242-17242/com.virtualapplications.play V/Font: Change font:2
04-04 22:13:12.713 17242-17242/com.virtualapplications.play I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
04-04 22:13:12.841 17242-17270/com.virtualapplications.play D/OpenGLRenderer: HWUI GL Pipeline
04-04 22:13:12.920 17242-17270/com.virtualapplications.play I/Adreno: QUALCOMM build                   : fcdb932, I1513509751
    Build Date                       : 01/22/18
    OpenGL ES Shader Compiler Version: EV031.22.00.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
04-04 22:13:12.924 17242-17270/com.virtualapplications.play D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8998.so from current namespace instead of sphal namespace.
04-04 22:13:12.928 17242-17270/com.virtualapplications.play I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
04-04 22:13:12.935 17242-17270/com.virtualapplications.play I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-04 22:13:12.936 17242-17270/com.virtualapplications.play I/OpenGLRenderer: Initialized EGL, version 1.4
04-04 22:13:12.936 17242-17270/com.virtualapplications.play D/OpenGLRenderer: Swap behavior 2
04-04 22:13:12.940 17242-17270/com.virtualapplications.play D/libGLESv1: Successfully load libGLESv2_oneplus.so, this=0x756ed8f008
04-04 22:13:12.941 17242-17270/com.virtualapplications.play D/OpenGLRenderer: Successfully load libhwui_plugin.so, this=0x756dabe558
04-04 22:13:13.175 17242-17270/com.virtualapplications.play D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
    Loading /vendor/lib64/hw/gralloc.msm8998.so from current namespace instead of sphal namespace.
04-04 22:13:14.152 17242-17248/com.virtualapplications.play I/zygote64: Do partial code cache collection, code=25KB, data=27KB
    After code cache collection, code=25KB, data=27KB
    Increasing code cache capacity to 128KB
04-04 22:13:14.153 17242-17248/com.virtualapplications.play I/zygote64: Do partial code cache collection, code=25KB, data=47KB
    After code cache collection, code=25KB, data=47KB
    Increasing code cache capacity to 256KB
    Compiler allocated 7MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
04-04 22:13:14.214 17242-17248/com.virtualapplications.play I/zygote64: Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
04-04 22:13:50.012 17242-17248/com.virtualapplications.play I/zygote64: Do full code cache collection, code=125KB, data=75KB
    After code cache collection, code=125KB, data=67KB
04-04 22:13:50.062 17242-17248/com.virtualapplications.play I/zygote64: Do partial code cache collection, code=125KB, data=73KB
04-04 22:13:50.063 17242-17248/com.virtualapplications.play I/zygote64: After code cache collection, code=125KB, data=73KB
    Increasing code cache capacity to 512KB
04-04 22:13:50.089 17242-17242/com.virtualapplications.play W/Play!: surfaceCreated
04-04 22:13:51.491 17242-17344/com.virtualapplications.play D/libGLESv3: Successfully load libGLESv2_oneplus.so, this=0x74e67f7008
04-04 22:13:52.468 17242-17269/com.virtualapplications.play A/libc: D:\dev\Play-Build\Play\Source\iop\Iop_Loadcore.cpp:149: uint32 Iop::CLoadcore::RegisterLibraryEntries(uint32): assertion "registered" failed
    Fatal signal 6 (SIGABRT), code -6 in tid 17269 (plications.play), pid 17242 (plications.play)
`

**Comment by jpd002** [comment]
Ah, yeah, it happens when you run debug builds on a device. You can safely comment that line. I will remove that assert since it doesn't indicate a problem with the game.

**Comment by Thunder07** [comment]
You're building the app with debug configuration aren't you? I can't start a single game I have with that, you'd need to use release configuration, unless well you're debugging the app.

**Comment by acocalypso** [comment]
@Thunder07 yep I build it with debug configuration. After I commented the assert(registered) Line. Build is working as expected

**Comment by jpd002** [comment]
Changed the title to match the initial problem.

**Comment by jpd002** [comment]
Removed the asserts: 018889ceb501b2bede3ea570cd164c80221656c0. Should stop being annoying.
