### ISSUE TITLE
Yakuza: many black textures.

### ISSUE THREAD

**Issue by Nine-H** [jpd002/Play-#637]
The game gets in game but appears to be rendering to a buffer or fullscreen quad to blur and color correct overworld graphics and this is black, the game appears to function correctly (in the overworld) and the ingame menu is fully functional. Black textures also occur in cutscenes and battles. You can start a battle by following the glowing circle on the minimap and tapping x.

![screenshot from 2017-10-02 21 22 47](https://user-images.githubusercontent.com/20123543/31073497-dbe8b8d0-a7b7-11e7-9668-7381eee3ddf0.png)
.
![screenshot from 2017-10-02 21 17 35](https://user-images.githubusercontent.com/20123543/31073323-30bc7c4e-a7b7-11e7-907e-41bf0878dedb.png)

**Comment by jpd002** [comment]
Thanks for reporting this! Here's the official compatibility issue for that game: https://github.com/jpd002/Play-Compatibility/issues/114. I've added your screen shots in there!
