### ISSUE TITLE
App will not install on HTC One M7

### ISSUE THREAD

**Issue by CristianTaveras** [jpd002/Play-#64]
The emulator won't install on my HTC One M7. Is it a glitch or is it just that my phone isn't compatible with it?

**Comment by jpd002** [comment]
That phone should be compatible. What error are you getting when trying to install it?

**Comment by CristianTaveras** [comment]
It says: There was an error parsing the package.

**Comment by jpd002** [comment]
Which Android version does your phone have? The emulator needs at least Android 4.4 to run.

**Comment by gambrio** [comment]
The newer HTC One M7 models come with KitKat or even Lollipop, so I don't think that would be the issue.

It could be the ROM it's using though, as I've heard of OEM ROMs that can have issues with certain .apks. If not that, it's possible that the annoying package parsing error could have to do with permissions/system settings.

**Comment by CristianTaveras** [comment]
Really? I have set to allow apk to be installed from uknown sources. Is
there something else I could've missed?

**Comment by gambrio** [comment]
Is it KitKat version or later?

**Comment by CristianTaveras** [comment]
I checked and it appeaes my phone is on 4.1 still. Funny because my phone
tells me I have no updates either.

**Comment by gambrio** [comment]
System updates should be provided by the manufacturer/software company as necessary. If they don't provide them you can possibly root the device and install a newer ROM with 4.4+ Android support. 

In any case, it's not working because it's using Jelly Bean.

**Comment by jpd002** [comment]
Closing this since the source of the problem has been found. Hope you find a way to update to 4.4+.

**Comment by CristianTaveras** [comment]
Actually my phone is telling me that I don't have any updates and it claims
that I'm on the latest version.
