### ISSUE TITLE
Can not find PS2 games

### ISSUE THREAD

**Issue by coleman73** [jpd002/Play-#645]
I think my problem is that I don't know how to name the games I have. I currently have half life and grand Turismo 3. I have placed them in the PLAY DATA FILES folder but they are still not found by the emulator. I went to the faq and it has a link to something that will rename the games properly but the post that it links to no longer exists. Anybody know what I can do?

**Comment by literalmente-game** [comment]
1. What plataform you're using the emulator on (Windows, Linux, Android...)?
2. What is the file extension of the games you're trying to find?

**Comment by coleman73** [comment]
I actually just figured it out and got both games to show up. The only problem is that they both run very very slow and the sound cuts in and out even though on the compatibility list for Android (which is what I'm using to answer your question) says both half life and grand Turismo 3 should work

**Comment by literalmente-game** [comment]
Work != playable. Performance will be different for different hardware and you should expect the games to be very slow as even faster computers can't runs most of the games at a good speed on Play! right now. The sound problem is an already known issue too. If you are satisfied with my answer, feel free to close this issue

**Comment by coleman73** [comment]
Alrighty sounds good then
