### ISSUE TITLE
boost dependency osx broken

### ISSUE THREAD

**Issue by Jabrwock** [jpd002/Play-#646]
Latest source (as of Oct 27). Using instructions from readme.md for OS X (Unix Makefiles)

Latest brew installed, latest XCode (9.0.1) & CLT, OS X 10.12.6.

Boost-cmake dependency is having issues building:

`
/Users/mcinnesc/Desktop/Play-Build/Dependencies/boost-cmake/boost/boost_1_64_0/libs/filesystem/src/operations.cpp:1052:11: error: no member named
      'filename_is_dot' in 'boost::filesystem::path'
    if (p.filename_is_dot() || p.filename_is_dot_dot())
        ~ ^
/Users/mcinnesc/Desktop/Play-Build/Dependencies/boost-cmake/boost/boost_1_64_0/libs/filesystem/src/operations.cpp:1052:34: error: no member named
      'filename_is_dot_dot' in 'boost::filesystem::path'
    if (p.filename_is_dot() || p.filename_is_dot_dot())
                               ~ ^
/Users/mcinnesc/Desktop/Play-Build/Dependencies/boost-cmake/boost/boost_1_64_0/libs/filesystem/src/operations.cpp:1656:18: error: use of undeclared
      identifier 'weakly_canonical'
    path wc_base(weakly_canonical(base, &tmp_ec));
                 ^
/Users/mcinnesc/Desktop/Play-Build/Dependencies/boost-cmake/boost/boost_1_64_0/libs/filesystem/src/operations.cpp:1659:15: error: use of undeclared
      identifier 'weakly_canonical'
    path wc_p(weakly_canonical(p, &tmp_ec));
              ^
/Users/mcinnesc/Desktop/Play-Build/Dependencies/boost-cmake/boost/boost_1_64_0/libs/filesystem/src/operations.cpp:1662:17: error: no member named
      'lexically_relative' in 'boost::filesystem::path'
    return wc_p.lexically_relative(wc_base);
           ~~~~ ^
/Users/mcinnesc/Desktop/Play-Build/Dependencies/boost-cmake/boost/boost_1_64_0/libs/filesystem/src/operations.cpp:2033:16: error: no member named
      'lexically_normal' in 'boost::filesystem::path'
      return p.lexically_normal();
             ~ ^
/Users/mcinnesc/Desktop/Play-Build/Dependencies/boost-cmake/boost/boost_1_64_0/libs/filesystem/src/operations.cpp:2040:25: error: no member named
      'lexically_normal' in 'boost::filesystem::path'
          ? (head/tail).lexically_normal()  
            ~~~~~~~~~~~ ^
7 errors generated.
`

**Comment by Thunder07** [comment]
if you have boost installed through brew or at all on the system, you should remove it, else it will cause you endless issues.

**Comment by Jabrwock** [comment]
Turns out macports still had a copy sitting around. Cleaning that up ensured that it no longer complains about that library.
