### ISSUE TITLE
This isn't a big deal or issue.

### ISSUE THREAD

**Issue by rbohannon89** [jpd002/Play-#647]
I would like to know when we might see a new build. Keep up the good work.

**Comment by literalmente-game** [comment]
If this isn't an issue, then this shouldn't be here (I would recomendo for you to close it to avoid confusion). If you want to see news about the emulator, check the official site (http://purei.org/) from time to time.

**Comment by jpd002** [comment]
I've recently added an "automated build" sections in the [downloads](http://purei.org/downloads.php) page. You can grab the latest version there.
