### ISSUE TITLE
Silent Hill 3 Or God Of War Not Working On Snapdragon 650 Adreno 510 Xiaomi Redmi Note 3

### ISSUE THREAD

**Issue by symbianz107** [jpd002/Play-#648]
Silent Hill 3 Or God Of War Not Working On Snapdragon 650 Adreno 510
Only Intro Coming For God Of War And Black screen For Silent Hill 3 Android 5.1

**Comment by jpd002** [comment]
Which version of the games did you try? US, JP or EU?

Thanks!

**Comment by jpd002** [comment]
Both games show intro on Windows and both games were tested recently. If you still get a black screen on Android with the latest automated build, please reopen as this might be an Android only issue.

God of War: https://github.com/jpd002/Play-Compatibility/issues/199
Silent Hill 3: https://github.com/jpd002/Play-Compatibility/issues/157

Thanks!
