### ISSUE TITLE
Detected backdoor in Play!

### ISSUE THREAD

**Issue by Evolution0** [jpd002/Play-#65]
Is this a false positive?

Backdoor.Bifrose is what it is detected as to be exact.

Running latest weekly build from the site.

**Comment by gambrio** [comment]
False alarm ... Play! has no malicious code.

**Comment by jpd002** [comment]
@Evolution0 Which program is reporting the problem? I might be able to contact the company to make them whitelist the executable. There's no backdoor or anything of the like in the emulator.

**Comment by Evolution0** [comment]
Yeah I figured there wasn't, just wanted to at least report it.

Play.exe itself is being flagged by [MBAM](https://www.malwarebytes.org/) as malware the rest of the files are all clear.

SAS detects nothing as well as Avast.

**Comment by jpd002** [comment]
@Evolution0 Thanks for the info! I'll see with them to whitelist the executable.

**Comment by jpd002** [comment]
I've reported the false positive: https://forums.malwarebytes.org/index.php?/topic/169754-false-positive-backdoorbifrose/

**Comment by Evolution0** [comment]
Updated database, rescanned, clean :+1:

**Comment by jpd002** [comment]
Great! Let's hope the same problem doesn't come up with a subsequent weekly build.
