### ISSUE TITLE
MR4 & Super bust a move 2

### ISSUE THREAD

**Issue by NeoMame** [jpd002/Play-#650]
Monster Rancher 4 & Super Bust A Move 2 read but do not load. Just stays on a black sceen but showing it's running at 40-50 fps.

**Comment by jpd002** [comment]
Which version of the games did you try? US, Japan or EU?

**Comment by NeoMame** [comment]
I tried US.

**Comment by jpd002** [comment]
Thanks, I've created the reports for these two games:
https://github.com/jpd002/Play-Compatibility/issues/29
https://github.com/jpd002/Play-Compatibility/issues/30
