### ISSUE TITLE
This isn't an issue!

### ISSUE THREAD

**Issue by M220** [jpd002/Play-#651]
Hi
Thank you for your hard work jpd
I cannot E-mail to JPD Because The Email Posted In Website cannot even get detected by Gmail and it says it's not a real email so i have to say it here : 
I'm gonna ask you when is the release date of next build :D 
because every day i visit your website and see no build there and i can't build my android play! Build for some god damn reasons so im gonna ask you when is the release date of next weekly ( maybe better to say one per two monthly :) ) Play build?
Thank you very much for your hard work ❤
PS2 Has a very large library of games and that was my dream to play them  in android before it actually happen cus of you :) ♡

**Comment by M220** [comment]
Not that i don't want to build , but i can't...
Im in a country that google doesn't Allowed it to use android studio ( but i managed somehow to doenload and install it however but when i want to actually build the apk ,it says that "Already seen doctype" everytime i want to sync gradle , i was in many forums and searched a lot and installed a lot of vpns too i even tried to do it offline with gradle downloaded but it must be online for the first time, so.. it's just not working... )
So please , now that you can build it, build it and upload it in your website so people can see improvment in their phone :)♡ i really be happy to see play! In my device again!

**Comment by jpd002** [comment]
Thanks for your feedback. I'm working on ways to make deployment and testing easier on my side. This will hopefully bring faster releases on all platforms.
