### ISSUE TITLE
Are builds stop being made?

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#653]
Sorry I'm just really curious... Has the emulator stop being developed

**Comment by BenNottelling** [comment]
The last commit to master was 17 hours ago. This is still being developed.

**Comment by Zero3K** [comment]
He meant weekly builds that are uploaded to the website.

**Comment by GuilhermeGS2** [comment]
It has been almost 4 months since they released a weakly build.

**Comment by Margen67** [comment]
There are builds on AppVeyor. https://ci.appveyor.com/project/jpd002/play

**Comment by Jordanesquivez** [comment]
Seriously what's going on? I've been waiting so long for the next build

**Comment by Ireheart** [comment]
Can someone compile the latest Android build?

**Comment by Aguszero** [comment]
Like ppsspp and dolphin,this will be number one if can make it run perfect

**Comment by jpd002** [comment]
I've made the builds made off TravisCI and AppVeyor easily accessible on the [official downloads page](http://purei.org/downloads.php). I'm still figuring out what's the best way to make regular official builds, but if you'd like to test the latest commits, you can use the automated builds even though they might be unstable.

**Comment by Thunder07** [comment]
Adding build date to the page as well might be useful.

**Comment by jpd002** [comment]
Oh, yeah! Will do! Thanks for the suggestion!

2018/03/26 15:55、Thunder07 <notifications@github.com>のメール:
