### ISSUE TITLE
DamonPS2 PRO ripping off Play - Maybe ?

### ISSUE THREAD

**Issue by lightningterror** [jpd002/Play-#655]
I wasn't sure where to post this since I couldn't find a forum, but anyway on the pcsx2 discord we talked this. DamonPS2 PRO , another ps2 emu on android.

Google play store link:
https://play.google.com/store/apps/details?id=com.damonplay.damonps2.pro.ppsspp

Facebook page:
https://www.facebook.com/DamonPS2

It could be that they are using Play!, just renamed as "DamonPS2 PRO " and making money out of it so I thought you guys should check this out.

If the report is false then you can close the issue :smile:

**Comment by Jordanesquivez** [comment]
Well the controls is very similar to that of play

**Comment by Thunder07** [comment]
the control is similar to that of PlayStation...
someone posted the decompiled smali codeine reddit, long side the native libraries, I was only able to find references to `PCSX2` and none to `Play!`, so at this stand, it's not verified if it's even legit or if it uses code from `Play!` or someone hide in a dark cave and rewrote `PCSX2`

**Comment by jpd002** [comment]
Quite impressive! From the comments on reddit, it would make more sense that he used code from PCSX2, since Play! can't run most of the games that are shown on the videos. It's quite a shame that he is ripping off other people's work without giving it back to the community though.

**Comment by M220** [comment]
But PCSX2 Libraries is for X86 Based system.
So it's possible that he used some codes from your emulator to Emulate X86 System in ARM ( play! ) and use x86 libraries on that ( PCSX2 ) because running those libraries in ARM Need a full rewrite of them and we sen in reddit that they aren't rewrited
So he used your codes to run those libraries in ARM Devices
