### ISSUE TITLE
Genji - Dawn of the Samurai : Nothing/crash

### ISSUE THREAD

**Issue by n1dminhd** [jpd002/Play-#66]
start the game, then crash
Play ! (2015/06/26) 64 bit

**Comment by jpd002** [comment]
Thanks for reporting. I'll take a look once I get the game.

**Comment by literalmente-game** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/521. This issue can be closed as the results presented by n1dminhd aren't valid anymore (Genji can reach in-game now).
