### ISSUE TITLE
How about "Playable" game state

### ISSUE THREAD

**Issue by sirdanielk** [jpd002/Play-#661]
Hello is it ok to update compatibility list with Playable state? What kind of games would be in there? Like small to none graphical issues, Save state working, no crashes no crippled sound no crawling speed, And can be played to the end? Would be that OK?

Does anybody tried a game to the end however? I think some 2D beatem ups, platforms, flying shooters are good candidates. 

What do you think?

**Comment by brand175** [comment]
i beat the whole campaign of Half-Life on the Play! emulator on my iPad Pro. It took a total of 46.5 hours (basically 2 days straight). It runs about 25-60 fps when looking at a wall or ceiling, runs 3-15 fps when looking straight. Megaman X Command Mission is another game that runs about 15 fps. Guitar Hero: Rocks the 80’s plays like 18 fps and is somewhat playable. Their are other games that don’t boot that i’m sure that can play at least 15 fps: 007 NightFire, Disneys PK out of the shadows, 007 Agent Underfire (only if overclock exists, then it would almost be fullspeed). The only game that is playable is Megaman X Collection at 30-58 fps.

**Comment by jpd002** [comment]
I've added a "playable" state in the [new compatibility tracker](https://github.com/jpd002/Play-Compatibility) I'm setting up. I've based the statuses on what we had before on the wiki and RPCS3's compatibility list.
