### ISSUE TITLE
Its clear now that this app is gone

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#662]
I don't want to be rude or anything but I've been dying  to see a build for android, its far too long, I'm just wondering if I should just stop thinking abt this app, my heart skip a few beat when I'm checking purei.org

**Comment by acocalypso** [comment]
This is an open source project so feel free to build it yourself.

Commits appearing from time to time what means the project ist still alive.

**Comment by jpd002** [comment]
I don't have as much time to work on this, but I still do. There's a few branches that fixes issues that I need to merge in master. Can't really give an ETA on a official build, sorry.
