### ISSUE TITLE
[macOS] Inputs not recognized

### ISSUE THREAD

**Issue by rien333** [jpd002/Play-#663]
I think I'm experiencing a combination of #489 an #620. For example, with Shadow of The Colossus,  I'm stuck at a screen where it tells me that the memory card is not found, but I can't move around to continue, eventhough I'm using the predefined keys from #489. Anybody know how to skip this dialogue? Testing with another game (Kingdom Hearts) it also does not seem to let me select anything. 

I'm on macOS and build Play! from source from the most recent commit.

**Comment by jpd002** [comment]
Does it only happen with those games? I'll test SoC and KH on macOS to see if it's specific to those games. Also, are you using an external keyboard of some sort?

Thanks!

**Comment by rien333** [comment]
These are the only ones I tested actually. I'm using my interal laptop keyboard. I actually haven't updated since I opened this issue, so I will try that and report back. If it works i'll just close this, thank you!

**Comment by Thunder07** [comment]
odd, I never had an issue with Kingdom Hearts on OSX.

**Comment by rien333** [comment]
Nope, version 0.30 (16-03-2018), which I have just build today from the latest HEAD, still has the same problem.

**Comment by rien333** [comment]
@Thunder07 shoot, I hope it's not specific for me then. I'll try booting in safe mode and then see if the issue persist. I'm launching Play! from the folder it is build in, and have it build with the XCode instructions on the github home page. The resulting app package is kinda small btw compared to the build folder however (3mb vs almost 400+mb), so maybe I did something wrong.

**Comment by Thunder07** [comment]
> 3mb

thats how big it is.

Only thing I can think of, is perhaps the keyboard region/ language, though I would have imagined a lot people would have had problem with this.

**Comment by rien333** [comment]
Booting into safe mode accomplish nothinh unfortunately. I'm on macOS 10.13.3 btw, and completely updated on brew packages. 

Maybe I'm using play! incorrectly, and I need to do some BIOS/ELF stuff or something. The only thing I've tried so far is booting up .iso files directly, without doing anything else first.

**Comment by Thunder07** [comment]
there isn't anything else to change.
`Play!` configuration are still simple and they're even more bare bone on OSX.

these are the settings `Play!` currently support https://github.com/jpd002/Play-/blob/master/Settings.md with Win32 & Ubuntu having button remapping as well.

**Comment by LoungeKatt** [comment]
@rien333 Are you using homebrew **exclusively** and does it override any other implementations of the same commands? Sometimes homebrew, macports, and xcode overlap and require specific routing for whose command to use in which situation.

**Comment by rien333** [comment]
hm, that could be it. I'll try and see if I can get it to work one day with just stuff from homebrew.

**Comment by LoungeKatt** [comment]
I'm sure it wasn't intentional, but I've had some random dependency end up with just enough priority to override something else. It's frustrating.

**Comment by jpd002** [comment]
The macOS port now uses Qt, so, the keyboard input handling code is very different. The key bindings can also be remapped using the configuration dialog. I'd suggest trying the latest [automated build](http://purei.org/downloads.php) to see if you still have these issues.

I'll close this since this is most likely not a problem anymore.
