### ISSUE TITLE
AppVeyor build speed

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#664]
this isn't particular an "issue", but I thought it might be worth while bring attention to it.

sometime in the past 6 months build speed changed from 6 minutes per Win bit build for a Total of about 12 mins to taking a full 30 minutes now (15 mins per build).
not sure if it's something on AppVoyer's side, or a change build settings, be it AppVoyer image or build flags/libraries.
![screen shot 2018-03-01 at 15 11 38](https://user-images.githubusercontent.com/5013823/36852219-0e1c8446-1d63-11e8-99ee-107dee2e7745.png)

**Comment by jpd002** [comment]
Just tried to re-run a build and the test discovery phase seems to take quite a long time (maybe 3-4 minutes per variant?). Turning off test discovery would probably help a lot to improve build times.

**Comment by Thunder07** [comment]
I just noticed that on AppVoyer, when you hover over a line it would show you the time it was executed at, looking at few different builds, i cant see the discovery taking any signficant time, just so yesterday I had few builds that took a total of 12 minutes between the 2 variant https://ci.appveyor.com/project/Thunder07/play/build/371 which leads me to believe that the build servers share resources, while perhaps travis divides resources, so appvoyer builds very from fast to slow, while travis is always consistant?

**Comment by jpd002** [comment]
Yeah, I noticed the same thing, disabling tests doesn't seem to make a big difference. Would make sense that the build servers resources are shared. There's not much we can do about this, so I'm going to close this for now.
