### ISSUE TITLE
[macOS] Gamepad Support & Input Configuration

### ISSUE THREAD

**Issue by jpd002** [jpd002/Play-#671]
Received an e-mail report requesting game pad support on macOS. Also, with game pad support, we would also need to allow configuration of the input bindings through an UI.

**Comment by spicybanners35** [comment]
The app called "Enjoyable" solves this problem.

**Comment by Zer0xFF** [comment]
since then, OSX client has switch to Qt and gamepad support added in #722
this can be closed
