### ISSUE TITLE
Patreon? 

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#672]
Hi Jean, a Patreon recently showed up on reddit under your name, before people start subscribing i wanted to confirm of it is yours?

I know github isn't the place for this question but I figured this is the fast way to get your attention.

**Comment by jpd002** [comment]
Yes, I’ve opened up a Patreon and put the link on the About page last Wednesday. I was going to make an official announcement at some point, but seems like someone beat me to it!

Thanks for checking with me!!

2018/03/24 11:38、Thunder07 <notifications@github.com>のメール:

**Comment by Thunder07** [comment]
haha ya it happen to Alex as well when he created discord channel for his Orbital PS4 emu.

anyway, glad you decided to open it one up :)

just quick few suggestions while I'm at it, since you didn't announce this yet I assume you'd get to them in time, but I might as well suggest it.
I'd recommend public Discord channel with tags for Patreon supports, as people will be more inclined to support if they knew they can get in touch. (while someone create a discord channel, I know that each channel is linked to the creator and can't be moved to another, so for an official channel, I think you should be the one starting)

settings goals, such as 700$ per month means you can work full time 7 days a month on `Play` 2/3000 full time etc etc as that shows them that their support can directly influence your time spent on the project.
finally a forum and a new front page :P are definitely in order now XD

**Comment by jpd002** [comment]
Thanks for the suggestions! I'll look at the possibility of opening a Discord channel and I'll add up some goals to make my objectives a bit clearer!

And yeah, a website revamp would be a good idea! There's a need for a better showcasing of what the emulator can do. I've been working on improving the compatibility status database situation using a [GitHub issue tracker](https://github.com/jpd002/Play-Compatibility) in hopes of being able to build something query-able that could be used on the website or in the app itself.
