### ISSUE TITLE
You have a thread on reddit!

### ISSUE THREAD

**Issue by spring568** [jpd002/Play-#673]
@jpd002 Looks like you're getting donations now from it too. I doubt you have time to be on it, but it might be nice to hear from you. Pretty exciting stuff : )

https://www.reddit.com/r/emulation/comments/86sa3b/play_ps2_emulator_now_has_patreon/

**Comment by jpd002** [comment]
Thanks for the heads-up! I was building up stuff till I was ready to make an announcement, but seems I was too slow! Very glad to see there's that much interest for the project! :smile: Thanks to everyone who pledged already, I'll make something official soon!

**Comment by spring568** [comment]
😺 No problem! Oh there's plenty of interest in your work. I've been following it pretty much since you started and i'm sure other people have too. I also wasn't sure if this was appropriate to post here either so I ended up closing it. I got too excited seeing the donation for your project up on reddit lol
