### ISSUE TITLE
uLaunchELF segfaults the emulator

### ISSUE THREAD

**Issue by Nine-H** [jpd002/Play-#679]
I wanted to see whether anything from the titles with memcard issues got written to the memory card but the filebrowser segfaults the emulator.

https://github.com/AKuHAK/uLaunchELF/releases

```
nine@deskshit:~/Projects/Play-Build/Play/build$ ./Source/ui_unix/Play 
Gtk-Message: Failed to load module "pantheon-filechooser-module"

(Play:9484): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(Play:9484): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(Play:9484): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(Play:9484): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
PS2VM: Error mounting cdrom0 device: Invalid file handle.
read: Resource temporarily unavailable
read: Resource temporarily unavailable
read: Resource temporarily unavailable
read: Resource temporarily unavailable
PS2VM: Error mounting cdrom0 device: Invalid file handle.
Segmentation fault (core dumped)
```

**Comment by jpd002** [comment]
Thanks for reporting. You can actually take a look at the contents of the memory cards by going in the "Play Data Files/mc0" or "Play Data Files/mc1" folders on the host filesystem (usually stored in the Documents folder).

Created a compatibility issue for that particular executable: https://github.com/jpd002/Play-Compatibility/issues/237.
