### ISSUE TITLE
[Android/Windows] ergonomics problem

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#680]
***Android***

-You can't change the settings on the fly which is necessary for some games (ONI for example).
-You don't have the ability to manage/import memorycard saves.
-No screen recording options

***Windows***

-There is no desktop icon
-You can't load a physical PS2 disc

**Comment by calebjosephchambers** [comment]
Also on Android TV there is no way to bring up the games information. 
![screenshot_2018-04-14-18-45-52](https://user-images.githubusercontent.com/38297072/38773520-1c14da0c-4014-11e8-8eea-11d6c5d89b76.png)
