### ISSUE TITLE
[Regression Alert!] Ratchet and Clank 3 don't anymore goes to menus

### ISSUE THREAD

**Issue by atomic83GitHub** [jpd002/Play-#681]
There is a regression introduced by one of the latest commmits beetwin https://github.com/jpd002/Play-/commit/7bcb74d8fc53de92f515c6801f94737c6aaaec8b and https://github.com/jpd002/Play-/commit/30dabba6689dee70a19eaecf06adab8001444c03. Ratchet and Clank 3 now load with FPS but shows nothing. I will try to find the bad commit.

**Comment by atomic83GitHub** [comment]
**The Apr 6, 2018 commits cause Ratchet and Clank 3 to load with FPS instead of menu**

https://github.com/jpd002/Play-/commit/30dabba6689dee70a19eaecf06adab8001444c03
https://github.com/jpd002/Play-/commit/34a1aff1235d59f397789430e1ac525444aff8c0

**Comment by jpd002** [comment]
Thanks for identifying that. It's most likely that one: 34a1aff1235d59f397789430e1ac525444aff8c0. I'll have to verify, but I think there's something with games checking the current thread id in their interrupt handlers. I encountered something similar with Metropolismania 2 yesterday.

**Comment by jpd002** [comment]
This fixes it: 3bcf06e618cfd343c8cc7391e2e0cdfeeccaf369. I know it breaks other games, but that commit is the right thing to do, so, I'll merge it in master later.

**Comment by atomic83GitHub** [comment]
Just for the curiosity, does it also solve Metropolismania 2?

**Comment by jpd002** [comment]
Nope, Metropolismania 2 got a different issue.

Closing this now that fix has been merged.
