### ISSUE TITLE
Jet Li : Rise to Honor isn't playable

### ISSUE THREAD

**Issue by jpd002** [jpd002/Play-#69]
Mentionned in #7.

**Comment by paulaz2** [comment]
@jpd002 Emmm isn't there any way you can make this game work but it also needs the right analog stick to fight

**Comment by jpd002** [comment]
Analog stick is being worked on : https://github.com/jpd002/Play-/tree/android_analog

**Comment by paulaz2** [comment]
@jpd002 I love your work keep it up keep on giving us hope...am sure ps3 emulator will be possible on android maybe 2020,that means on the next build we should be expecting the analog stick,what of the R1,R2,L1,L2?

**Comment by gambrio** [comment]
It does work (meaning it can boot), but the screen freezes whenever you send any input, and, if you wait for the intro movie to finish (10-20 minutes), it just hangs on a black screen. It "works" but it isn't playable yet, and I'm a bit confused as to what the issue from my testing/debugging of it.

**Comment by jpd002** [comment]
@gambrio Thanks for the precisions, I've updated the title of the issue. I don't have the game yet, so I can't debug that problem right now.

**Comment by paulaz2** [comment]
@jpd002 heres the link for the game http://www.emuparadise.mobi/Sony_Playstation_2_ISOs/Rise_to_Honor_(USA)_(En,Zh)/151184
and guys happy new month my friend also asked me to ask you that when will this emu have a stable version?

**Comment by jpd002** [comment]
Thanks for the information, but please refrain from posting links to copyrighted materials. I have bought the game and will be receiving it next week.

**Comment by paulaz2** [comment]
@jpd002 Ok thanks,i plan on buying the lenovo s8 tab any hope if play will work on it?

**Comment by jpd002** [comment]
@paulaz2 Won't play it at the moment because the emulator isn't compiled for x86 on Android. I do need to get an x86 Android device to test on though.

**Comment by paulaz2** [comment]
@jpd002 So when is the next building coming out?
@gambrio why are you showing as a ghost?

**Comment by paulaz2** [comment]
@jpd002 what about the R1,R2,L1 and L2 buttons?

**Comment by jpd002** [comment]
@paulaz2 Weekly builds are released every Sunday around 10PM EST. Shoulder buttons (R1/R2/L1/L2) will be in next build.

**Comment by paulaz2** [comment]
Thats cool,any idea of downhill domination is working? And i will like to get screenshots

**Comment by Fadi5555** [comment]
@jpd002 today is Sunday and as you said you release the weekly build every Sunday.
I hope to see something good.
We really exciting to see what's the new things which will included on this weekly build.

Anyway I wish all the best for you.

**Comment by paulaz2** [comment]
So no one wana give me answer about downhil domination?

**Comment by paulaz2** [comment]
@jpd002 I Thought you said you will have the jet li rise to honor this week have you?

**Comment by jpd002** [comment]
@paulaz2 Nope, sorry, I didn't get the game yet.

**Comment by paulaz2** [comment]
Ok now is downhill domination issue someone said its stuck on loading screen

**Comment by jpd002** [comment]
Added some missing instructions and the game goes a bit further:

![jetli_1](https://cloud.githubusercontent.com/assets/6760433/8632392/0c3ecc0a-2767-11e5-977d-3ccb64ed59f3.jpg)
![jetli_2](https://cloud.githubusercontent.com/assets/6760433/8632393/0c4127d4-2767-11e5-8c04-2fde1f5c8674.jpg)

There seem to be an issue with collision detection though as characters are going through the floor.

**Comment by paulaz2** [comment]
@jpd002 its buggy but nice work..i thinks its graphic issues bufferred or non-bufferred rendering might help just like ppsspp,but this is not ppsspp its PLAY! And i know ps2 emulation is hard...how about trying to add frameskipping to the emulator that might help,so what do u thinks is the problem with this game?

**Comment by paulaz2** [comment]
@jpd002 will the latest version be able to run jet li rise to honor well?

**Comment by jpd002** [comment]
@paulaz2 Nope, it's still broken at the moment. I don't think frameskipping will do much since rendering isn't the bottleneck

**Comment by paulaz2** [comment]
@jpd002 At first during the intro this game was running 22 f/s then when it got to in game it was running 12 f/s,what does this mean?

**Comment by paulaz2** [comment]
Please can you make openGL ES v2.0 for this emulator?

**Comment by paulaz2** [comment]
@jpd002 is there any new video or picture you wanna show me?

**Comment by jpd002** [comment]
@paulaz2 Nothing new to show, sorry. Also, I have no plans to support GLES 2.0.

**Comment by paulaz2** [comment]
Ok

**Comment by paulaz2** [comment]
Hi guys am back Happy New Year everyone

**Comment by paulaz2** [comment]
@jpd002 have done testing on this game on a Mali T-720 device the intro of the game have critical  graphic issues and when it reaches in game the emu force closes.

**Comment by paulaz2** [comment]
Intro glitches on android.....and app force closes at ongame

**Comment by jpd002** [comment]
When you say "intro", do you mean the cutscene where you see Jet Li speaking to the other guys?

**Comment by paulaz2** [comment]
Yes

**Comment by jpd002** [comment]
Ok, thanks, I'll take a look.

**Comment by paulaz2** [comment]
OK thanks

**Comment by jpd002** [comment]
Crash seems to be fixed on `master`, but intro is still glitchy. I'll look into it.

**Comment by paulaz2** [comment]
So can go in game now?

**Comment by paulaz2** [comment]
Please can I get the link to the fix?

**Comment by paulaz2** [comment]
Yes was not able to see anything

**Comment by paulaz2** [comment]
![screenshot_20170831-192859](https://user-images.githubusercontent.com/12880627/29939532-0ad424d8-8e84-11e7-83f3-f9f40659c83a.png)

**Comment by jpd002** [comment]
Yup, I got something similar on my end. It's probably due to a bug in AArch64 code generation. Still looking into it.

**Comment by paulaz2** [comment]
Nice.... When do you plan on the emulator speed development.

**Comment by jpd002** [comment]
Last version got some speed improvements, still working on others.

**Comment by paulaz2** [comment]
Well on which games cause I didn't noticed?

**Comment by jpd002** [comment]
I've reduced the overhead of executing recompiled CPU blocks, so, it improves games that have high CPU usage. But it's fairly minor, so, there might be a few FPS increase for these games. Most 3D games have high VU and VIF usage, so, it won't make a big difference for them.

I'm working on fixing a performance problem in the main thread/GS thread communication system. Still experimenting with this one, but it's most likely the source of the "FPS goes down when there's lots of text appearing on screen" problem.

**Comment by paulaz2** [comment]
Nice @jpd002 it seems if this game intro can be fixed the in game will be also.......please I will like you to do a test on the PC version for me please?

**Comment by paulaz2** [comment]
A video footage.

**Comment by jpd002** [comment]
What do you mean? Like record what happens with this game on the PC version of the emulator?

**Comment by paulaz2** [comment]
Yes 😁

**Comment by paulaz2** [comment]
Still waiting@jpd002

**Comment by paulaz2** [comment]
@jpd002

**Comment by jpd002** [comment]
Fixed the issue. 
![screenshot_20180322-104350](https://user-images.githubusercontent.com/6760433/37777805-51169be6-2de0-11e8-8ba4-2002a2f290ab.png)

It was broken because I had the wrong type for signed 8-bit values: https://github.com/jpd002/Play--Framework/commit/de517cefd3587dedc4287dbfe5e16d1825c69dde.

You can grab the latest build here: https://s3.us-east-2.amazonaws.com/playbuilds/6f60107a/Play-release.apk

Related compat issue: https://github.com/jpd002/Play-Compatibility/issues/61.
