### ISSUE TITLE
Thanks.

### ISSUE THREAD

**Issue by jerkstore369** [jpd002/Play-#692]
Thanks for making this. I'm blown away that there aren't more fully working ps2 emulators considering it's the biggest console of all time and considering pcsx2, engineering wise, is such a pathetic piece of garbage. I really hope you guys take after Dolphin and focus on accuracy and can get the compatibility and performance of this emulator to the top and reign as THE ps2 emulator of all time. Best of luck.

**Comment by atomic83GitHub** [comment]
If you want to know, the compatibility is the main priority of this emu.

**Comment by jpd002** [comment]
Hey! Thanks for the good words! Let's not be harsh on the people who made PCSX2, they did a great job making PS2 emulation a reality! I want to propose something different, but there's still lots of work to be done!

Feel free to join our discord server if you'd like to chat! https://discord.gg/jxAsjj
