### ISSUE TITLE
Funky textures in Baldur's Gate DA

### ISSUE THREAD

**Issue by glebm** [jpd002/Play-#693]
I've downloaded the latest build (May 2, 2018) of the emulator to try it out on the GPD XD+.

This is what it looks like in-game in Baldur's Gate DA:

![screenshot_20180505-052211](https://user-images.githubusercontent.com/216339/39659642-0e48d268-5025-11e8-902e-1dcb351ddf41.png)

The same happens on the corresponding Windows build but just in case here is the device information:

|System|General|SOC|
|-|-|-|
| ![screenshot_20180505-052444](https://user-images.githubusercontent.com/216339/39659645-288d8880-5025-11e8-8fa7-d5becdce548a.png) | ![screenshot_20180505-052518](https://user-images.githubusercontent.com/216339/39659646-28a70b7a-5025-11e8-80a5-80d4dd305fae.png) | ![screenshot_20180505-052422](https://user-images.githubusercontent.com/216339/39659647-28bf42bc-5025-11e8-8c43-770b2f436d49.png) |

**Comment by glebm** [comment]
Oops I see this is a duplicate: https://github.com/jpd002/Play-/issues/399

**Comment by jpd002** [comment]
No problems! Yeah, I still need to write that hardware test to implement the proper fix for Snowblind games.
