### ISSUE TITLE
Play Ubuntu Arm64 Building Error

### ISSUE THREAD

**Issue by natehaxx** [jpd002/Play-#696]
`-- Build files have been written to: /home/switch/Play-Build/Play/build
switch@switch:~/Play-Build/Play/build$ cmake --build .
[  0%] Built target glew_s
[  1%] Built target bz2
[  3%] Built target Boost_system
[  5%] Built target Boost_filesystem
[ 18%] Built target Framework
[ 18%] Built target Framework_Http
[ 20%] Built target Framework_OpenAl
[ 28%] Built target CodeGen
[ 66%] Built target PlayCore
[ 67%] Built target Framework_OpenGl
[ 69%] Built target gsh_opengl
[ 69%] Building CXX object Source/ui_unix/CMakeFiles/Play.dir/GSH_OpenGLQt.cpp.o
In file included from /usr/include/aarch64-linux-gnu/qt5/QtGui/QOpenGLContext:1:0,
                 from /home/switch/Play-Build/Play/Source/ui_unix/GSH_OpenGLQt.cpp:3:
/usr/include/aarch64-linux-gnu/qt5/QtGui/qopenglcontext.h:55:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
 #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  ^~~~~~~
/usr/include/aarch64-linux-gnu/qt5/QtGui/qopenglcontext.h:56:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h
  ^~~~~~~
In file included from /usr/include/aarch64-linux-gnu/qt5/QtGui/qopengl.h:105:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtGui/qopenglcontext.h:60,
                 from /usr/include/aarch64-linux-gnu/qt5/QtGui/QOpenGLContext:1,
                 from /home/switch/Play-Build/Play/Source/ui_unix/GSH_OpenGLQt.cpp:3:
/usr/include/GLES3/gl31.h:528:60: error: ‘void __glewActiveTexture(GLenum)’ redeclared as different kind of symbol
 GL_APICALL void GL_APIENTRY glActiveTexture (GLenum texture);
                                                            ^
In file included from /home/switch/Play-Build/Framework/build_cmake/FrameworkOpenGl/../../include/opengl/OpenGlDef.h:38:0,
                 from /home/switch/Play-Build/Play/Source/gs/GSH_OpenGL/GSH_OpenGL.h:8,
                 from /home/switch/Play-Build/Play/Source/ui_unix/GSH_OpenGLQt.h:3,
`

/home/switch/Play-Build/Dependencies/glew-2.0.0/include/GL/glew.h:17830:46: note: previous declaration ‘void (* __glewVertexAttribBinding)(GLuint, GLuint)’
 GLEW_FUN_EXPORT PFNGLVERTEXATTRIBBINDINGPROC __glewVertexAttribBinding;
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/qt5/QtGui/qopengl.h:105:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtGui/qopenglcontext.h:60,
                 from /usr/include/aarch64-linux-gnu/qt5/QtGui/QOpenGLContext:1,
                 from /home/switch/Play-Build/Play/Source/ui_unix/GSH_OpenGLQt.cpp:3:
/usr/include/GLES3/gl31.h:1520:88: error: ‘void __glewVertexBindingDivisor(GLuint, GLuint)’ redeclared as different kind of symbol
  void GL_APIENTRY glVertexBindingDivisor (GLuint bindingindex, GLuint divisor);
                                                                              ^
In file included from /home/switch/Play-Build/Framework/build_cmake/FrameworkOpenGl/../../include/opengl/OpenGlDef.h:38:0,
                 from /home/switch/Play-Build/Play/Source/gs/GSH_OpenGL/GSH_OpenGL.h:8,
                 from /home/switch/Play-Build/Play/Source/ui_unix/GSH_OpenGLQt.h:3,
                 from /home/switch/Play-Build/Play/Source/ui_unix/GSH_OpenGLQt.cpp:1:
/home/switch/Play-Build/Dependencies/glew-2.0.0/include/GL/glew.h:17834:47: note: previous declaration ‘void (* __glewVertexBindingDivisor)(GLuint, GLuint)’
 GLEW_FUN_EXPORT PFNGLVERTEXBINDINGDIVISORPROC __glewVertexBindingDivisor;
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
Source/ui_unix/CMakeFiles/Play.dir/build.make:250: recipe for target 'Source/ui_unix/CMakeFiles/Play.dir/GSH_OpenGLQt.cpp.o' failed
make[2]: *** [Source/ui_unix/CMakeFiles/Play.dir/GSH_OpenGLQt.cpp.o] Error 1
CMakeFiles/Makefile2:100: recipe for target 'Source/ui_unix/CMakeFiles/Play.dir/all' failed
make[1]: *** [Source/ui_unix/CMakeFiles/Play.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by natehaxx** [comment]
Its the Real Nintendo Switch Hardware using Ubuntu , can you tell me how to build without it ?

**Comment by jpd002** [comment]
I'm guessing removing the part referencing GLEW [here](https://github.com/jpd002/Play-/blob/master/Source/ui_unix/CMakeLists.txt#L29) would fix the issue.

Can I emulate your build setup using QEMU?

**Comment by mrcmunir** [comment]
@jpd002 I have been able to verify the code and the real problem is that the Qt for arm packages are compiled linker opengl es by default 

And apparently glew.h + gles headers come into conflict

would have to separate glew and opengl es for arm linux in OpenGLdef.h

https://github.com/jpd002/Play--Framework/blob/master/include/opengl/OpenGlDef.h

Also I change GL_BGR to GL_RGB because GL_BGR doesn't declared in gles headers.

glReadPixels(0, 0, width, height, GL_BGR, GL_UNSIGNED_BYTE, buffer) in Play-/Source/gs/GSH_OpenGL/GSH_OpenGL.cpp

**Comment by Specht2010** [comment]
I've been able to compile and run this on a Switch running L4T Ubuntu by replacing the glew include under the Linux define in OpenGlDef.h with gles3, and also removing the Android/iOS distinction for add_definition(-DGLES_COMPATIBILITY) in CMakeLists.txt in the GSH_OpenGL directory.  Otherwise no graphics appear in the window.

As far as I can tell I had no issues compiling with qt5.9.

**Comment by mrcmunir** [comment]
@Specht2010  Ah I see.  I only try was trying to compile to run it with the Opengl 4.6 core instead of Opengl es 3

And apparently the packages qt5 for arm only has support for Opengl es

**Comment by Specht2010** [comment]
I'll also add that I had to comment out a few Apple specific lines in GSH_OpenGLQt.cpp that stopped make after making those changes because it used glewInit().

**Comment by Zer0xFF** [comment]
@Specht2010 if you can push the code changes you made, that'd be great....

if you feel like sending a PR, for the header and source part you can probably use `__arm__` and `__aarch64__` to exclude the `glew` related code and include... as for the build script, I dont think there is currently a way to detected arch type (?) so it won't be possible to add a toggle for `GLES_COMPATIBILITY` yet.

**Comment by Specht2010** [comment]
I think I have something clean that works and doesn't break anything else.  I can push it and send a PR later today.  Thanks @Zer0xFF your suggestions worked.

**Comment by jpd002** [comment]
This is now in master. The emulator compiles and runs properly on AArch64 Linux. Thanks to everyone involved for making this work!
