### ISSUE TITLE
Purei.org website update

### ISSUE THREAD

**Issue by ghost** [jpd002/Play-#697]
I address this issue for the Play! website which in my opinion needs an update.

- [Remove weekly builds for Win32, Mac OS, IOS and Android]
- [update the .elf download section which can be hard to find and lacks a lot of Homebrews (some of these are hard to find nowdays, it would be nice to have a central website for those)]
- [Update the screenshots section with the help of the github compat tracker]
- [Add system requirements in the about section]

**Comment by atomic83GitHub** [comment]
If you want, I can help you to create the new .elf package.

**Comment by jpd002** [comment]
I've added the compat tracker summary recently. I still need to update other parts of the site, @atomic83GitHub's suggestions are good.

**Comment by jpd002** [comment]
Thanks for the suggestions, I've been trying to update the website a bit more recently.
