### ISSUE TITLE
Error parsing 'SYSTEM.CNF' for a BOOT2 value (Linux)

### ISSUE THREAD

**Issue by BlackLotus** [jpd002/Play-#699]
Happens with Person 3. The problem doesn't happen with Android.
Probably the same problem as #55 but this time in the Linux version.

**Comment by jpd002** [comment]
Humm, fseeko and ftello (used in https://github.com/jpd002/Play--Framework/blob/master/src/StdStream.cpp) should work properly on Linux (for files larger than 2GBs). Unless it's not the case? Maybe we're missing the _FILE_OFFSET_BITS=64 preprocessor flag somewhere?

**Comment by BlackLotus** [comment]
Ok this was sheer stupidity on my part. Used build_unix/build-ui/Play-Ui which _somehow_ existed in my setup.
After using Source/ui_unix/Play it just worked (tm). I'm very sorry to have bothered you with this bogus bug report. Thanks for your support
