### ISSUE TITLE
Some games make the emulator crash due to absence of SSE4.1 CPU extensions

### ISSUE THREAD

**Issue by jpd002** [jpd002/Play-#70]
CodeGen emits PMAXSD and PMINSD which are supported only on x86 CPUs that have the SSE4.1 extension.

Change CodeGen so that they don't use those instructions on CPUs that don't support them.

(reported in #54)

**Comment by paulaz2** [comment]
@jpd002 will you be ale to fix this easily?

**Comment by jpd002** [comment]
@SonOfUgly I've made a special build that fixes the problem: http://purei.org/downloads/play/weekly/Play-SSE41Detect-64.exe

**Comment by SonofUgly** [comment]
Thanks, both new game and loading a save are working for me now.

**Comment by jpd002** [comment]
Awesome :+1: Thanks for testing!
