### ISSUE TITLE
Need some resources to understand the code

### ISSUE THREAD

**Issue by usman791** [jpd002/Play-#704]
Hi play! Developer
Iam a unity developer and I like this project but can you please provide us some resources eg. Links,docs to learn about Ps2 architecture and try to evolve this project(fix bugs and improve some parts of it) and some tips also please.

**Comment by uyjulian** [comment]
Start here: http://lukasz.dk/playstation-2-programming/an-introduction-to-ps2dev/

**Comment by jpd002** [comment]
If there's a game you'd like to fix, I'd suggest building the emulator with the debugger on Windows (-DDEBUGGER_INCLUDED=on in CMake) and trace around to see if you can isolate the issue. There's also lots of things to improve on the UI side if you'd like to work on that.

Closing this for now, but feel free to open other issues if you got other questions.
