### ISSUE TITLE
Game crashing 

### ISSUE THREAD

**Issue by alix19** [jpd002/Play-#705]

**Comment by literalmente-game** [comment]
Issues here are related directly to problems in the emulator, for problems with specific games you should make an issue here https://github.com/jpd002/Play-Compatibility/issues. Don't worry about this one, I'll copy-paste your issue there, but keep this in mind for future issues ;)

**Comment by alix19** [comment]
Please fix it and fix scooby doo unmasked to

**Comment by literalmente-game** [comment]
As I've said, if you want to make issues for specific games, open one https://github.com/jpd002/Play-Compatibility/issues. You can close this one now and please, if you're going to open another one on the compatibility tracker, try to add some useful information (what game, game ID, device used when testing, some screenshot when possible, PC specs if you're using a PC), asking "please fix this game" means nothing

**Comment by alix19** [comment]
The game don’t load fast it’s really slow the game is ultimate spider man and device is Samsung galaxy 
![2b64df6a-f81f-48bd-a1e1-3b39df5e945f](https://user-images.githubusercontent.com/40809841/43039734-c957b964-8d2b-11e8-98d7-37f9b0db7750.jpeg)
![c23cf859-b06c-45d0-b6a3-c3b3d2c9062b](https://user-images.githubusercontent.com/40809841/43039736-c99b1e8e-8d2b-11e8-8643-6edf0d0e83e4.jpeg)

**Comment by alix19** [comment]
Are you looking into it
