### ISSUE TITLE
android issues and i can't build  

### ISSUE THREAD

**Issue by larbikhounti** [jpd002/Play-#706]
`Error while executing process D:\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\dev me\Desktop\Play--master\Play--master -BC:\Users\dev me\Desktop\Play--master\Play--master\build_android\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-19 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\dev me\Desktop\Play--master\Play--master\build_android\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=D:\sdk\ndk-bundle -DCMAKE_CXX_FLAGS=-frtti -DCMAKE_TOOLCHAIN_FILE=D:\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_ARM_NEON=TRUE -DANDROID_TOOLCHAIN=clang -DANDROID_CPP_FEATURES=exceptions rtti -DANDROID_STL=c++_static}
`

**Comment by jpd002** [comment]
I'm noticing a space in the project's path ("dev me"). Could you try again without the space in the folder's name?

**Comment by larbikhounti** [comment]
i change it but its still have the same issue 

Error while executing process D:\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\TEMP\Desktop\Play--master\Play--master -BC:\Users\TEMP\Desktop\Play--master\Play--master\build_android\.externalNativeBuild\cmake\release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-19 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\TEMP\Desktop\Play--master\Play--master\build_android\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=D:\sdk\ndk-bundle -DCMAKE_CXX_FLAGS=-frtti -DCMAKE_TOOLCHAIN_FILE=D:\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_ARM_NEON=TRUE -DANDROID_TOOLCHAIN=clang -DANDROID_CPP_FEATURES=exceptions rtti -DANDROID_STL=c++_static}

**Comment by larbikhounti** [comment]
this an image

![issue](https://user-images.githubusercontent.com/30549055/43356422-6a4a4922-9268-11e8-90f4-0ede804638c5.PNG)

**Comment by larbikhounti** [comment]
build issue

![save](https://user-images.githubusercontent.com/30549055/43356447-b911be82-9268-11e8-9010-366620207029.PNG)

**Comment by jpd002** [comment]
Did you clone the emulator through the Play-Build repository (https://github.com/jpd002/Play-Build)? 

CMake seems to be complaining about failing "add_subdirectory" which might be explained by missing dependencies folders (Dependencies, Framework, CodeGen, etc.) that are not present at the same level as the Play folder.
