### ISSUE TITLE
Games don’t let me move 

### ISSUE THREAD

**Issue by alix19** [jpd002/Play-#707]
I try play this game called Harry Potter and the half blood price on Samsung galaxy on drastic emulator one part of the game is student  don’t walk up to me as can see on screenshots green dots are student they meant walk to me nothing happens or I can’t move to them it don’t let me 
![bb8c0998-e59d-4a89-b87b-79c449e134c1](https://user-images.githubusercontent.com/40809841/43354587-dd61aa4e-9246-11e8-98d4-07a6821bfd80.jpeg)

**Comment by literalmente-game** [comment]
You can do it by clicking in the button "Close Issue"

**Comment by alix19** [comment]
Please help me find support that emulator

**Comment by literalmente-game** [comment]
You can try to contact the developer of DraStic with the info in the Play Store page (https://play.google.com/store/apps/details?id=com.dsemu.drastic), but please, close this issue as this has nothing to do with Play!

**Comment by alix19** [comment]
Please remove this report

**Comment by alix19** [comment]
Please delete it
