### ISSUE TITLE
Games slow 

### ISSUE THREAD

**Issue by alix19** [jpd002/Play-#708]
I try play this game called ultimate spider man on Samsung galaxy on play emulator the game doesn’t load fast it’s really slow it doesn’t let me play game because it that slow 
![ef3a3ec8-3d8a-49a9-9447-feb9cc505316](https://user-images.githubusercontent.com/40809841/43354823-be7c99b4-924a-11e8-9163-60a3eb576cbf.jpeg)
![58c530c1-83b4-4cf0-901e-8d1592a7ece9](https://user-images.githubusercontent.com/40809841/43354824-beab0c4a-924a-11e8-8929-fd66d28389c8.jpeg)

**Comment by literalmente-game** [comment]
You already made an issue about it and closed here https://github.com/jpd002/Play-/issues/705. I've moved it to here https://github.com/jpd002/Play-Compatibility/issues/527. Don't open any issue before checking here https://github.com/jpd002/Play-Compatibility/issues to see if we already have an open issue for the game you've tested. You can close this issue too

**Comment by alix19** [comment]
I don’t want to I want help ok

**Comment by alix19** [comment]
Please respond back

**Comment by alix19** [comment]
I’m getting annoyed now answer me

**Comment by jpd002** [comment]
The emulator is a work in progress, there's still lots of things that need improvement. But, it takes time to do things and my time is limited, please be patient, I'll surely look at this game sooner or later.

**Comment by alix19** [comment]
Oh please

**Comment by alix19** [comment]
Please reopen this case
