### ISSUE TITLE
No framelimiter...

### ISSUE THREAD

**Issue by ghost** [jpd002/Play-#71]
I would not consider this a serious issue but merely a slight enhancement that can be worked around to whenever the time comes in the future. I notice game speed will be improved with memory mapping so then would be good. Just a suggestion because if speed does increase, a super fast CPU will throw most games well over 100 FPS in some areas which is not accurate. Frame limiting will solve that issue, but that's whenever the time comes when speeds can be acceptable across many different specs.

Even now I'm sure, even with no speed optimizing, some games probably fly over 100 FPS too.

**Comment by jpd002** [comment]
Yep, that was on my TODO list. I'll be happy to fix it when it'll become a major issue :smile:

**Comment by ziiU** [comment]
Yeah, probably something that could be looked into once better performance is imprroved.

**Comment by atomic83GitHub** [comment]
This is fixed now. The topic can be close in my opinion.

**Comment by jpd002** [comment]
Yes, should be fixed by this: https://github.com/jpd002/Play-/commit/7bcb74d8fc53de92f515c6801f94737c6aaaec8b.
