### ISSUE TITLE
The game is slow

### ISSUE THREAD

**Issue by alix190** [jpd002/Play-#710]
I 
![0c7b609c-96ac-4c09-9240-185f77d6c036](https://user-images.githubusercontent.com/41872194/43368912-82b05e6c-935c-11e8-991a-fc3263b164e7.jpeg)
![e0d0a1fe-0f16-4f37-b819-24025f468e8c](https://user-images.githubusercontent.com/41872194/43368913-82d62f16-935c-11e8-9a57-72b0396ca00d.jpeg)

try play this game called ultimate spider man on Samsung galaxy on play emulator the game doesn’t load fast it’s really slow it doesn’t let me play game because it that slow

**Comment by alix190** [comment]
![c1f0880d-76ab-453d-9a86-37076b84511d](https://user-images.githubusercontent.com/41872194/43368894-1e89abf0-935c-11e8-9912-cc4710839901.jpeg)
![ecb3b4fe-aa55-4a86-9a86-5142a5af8f71](https://user-images.githubusercontent.com/41872194/43368895-1eb13efe-935c-11e8-855d-85585556a461.jpeg)

**Comment by HexyFify** [comment]
you can check games here:
https://github.com/jpd002/Play-/wiki/Compatible-games
if you like to add something to the list or help developers solve the issue  you can describe the state the game is in
try to be patient and see how far you can go
and then describe the issues you encounter

**Comment by alix190** [comment]
It’s on android on Samsung galaxy a5 and issue is I can’t play the game because is so slow and bad it doesn’t let me it does what I show you by screenshot

**Comment by HexyFify** [comment]
no i mean describe the issue in detail and give screenshots as evidence

**Comment by AcceptableSpare** [comment]
This wont be playable any time soon, It's seriously broken. Just a guess but I'd say because of unimplemented features the game needs to run properly or it's a major bug. If you have a very fast mobile internet connection run it on your pc using pcsx2 and stream it to it using steam link or parsec

**Comment by alix190** [comment]
WiFi speed is 13.0
Device is Samsung galaxy a5
Emulator is play
details is games seems very slow and the controls overlay block most of screen

**Comment by alix190** [comment]
Please fix it

**Comment by alix190** [comment]
Please sort it out

**Comment by jpd002** [comment]
Please give it some time, I'll eventually get to it. Closing for now.

**Comment by alix190** [comment]
Please fix it

**Comment by alix190** [comment]
Please reopen it now
