### ISSUE TITLE
Fails to compile, boost

### ISSUE THREAD

**Issue by kyledolichev** [jpd002/Play-#715]
Hello, I have been eyeing this emulator for quite some time, today I tried to compile it but it has failed on both an Arch derivative & on Void Linux MUSL, giving the same sort of error. I am aware this emulator may not actually play games as of yet, but wanted to give it a shot.
I am hoping that this output can help this project. I am more than happy to help in any way I can.

```
In file included from /home/user/.cache/pacaur/play-emu-git/src/Play-Build/Play/Source/saves/Icon.cpp:3:
/home/user/.cache/pacaur/play-emu-git/src/Play-Build/Play/Source/saves/Icon.h:9:10: fatal error: boost/tr1/memory.hpp: No such file or directory
 #include <boost/tr1/memory.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Play.dir/build.make:1766: CMakeFiles/Play.dir/home/user/.cache/pacaur/play-emu-git/src/Play-Build/Play/Source/saves/Icon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/Play.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```
The only difference is that on Void it fails at 91%, on Arch it fails on 75%. The errors are identical though.

**Comment by jpd002** [comment]
Hey!

Have you pulled the latest changes for submodules? The current version of `Icon.h` doesn't have that boost include anymore (https://github.com/jpd002/Play-/blob/master/Source/saves/Icon.h).

**Comment by Zer0xFF** [comment]
can be closed. boost has been removed, and this issue is referencing an old commit.
