### ISSUE TITLE
Instant Crash while launching game iOS

### ISSUE THREAD

**Issue by cppkyle** [jpd002/Play-#718]
The app crashes when I launch the game. I tried two games from different sources and they do the same thing.

**Comment by jpd002** [comment]
Could you try with this: https://s3.us-east-2.amazonaws.com/playbuilds/2a9af971/Play.ipa?

Is was built off the [ios_enablejit](https://github.com/jpd002/Play-/tree/ios_enablejit) branch which has a ptrace call to simulate a debugger. This has a side effect of making the application hang if it's killed through normal means requiring the device to be restarted if you want to restart the app.

**Comment by cppkyle** [comment]
It seems to work. Thank you!
