### ISSUE TITLE
Emulator crashes in Final Fantasy X during intro

### ISSUE THREAD

**Issue by jpd002** [jpd002/Play-#72]
Crashes when "Sinspawn Ammes" appears.

Reported by @HerPizzaFace in #27 

Screen shots:
https://cloud.githubusercontent.com/assets/12665021/8274006/025d7894-1853-11e5-8b79-b9bf545e43f5.jpg
https://cloud.githubusercontent.com/assets/12665021/8274007/03a87d70-1853-11e5-9672-eac4e070f926.jpg

Hardware specs:
CPU: i3-4160 (AVX 2.0, SSE4.1/4.2, MMX, SSE3, SSE2, SSSE3, FMA, MMX, SSE).
GPU: Intel HD 4400 (although I'm pretty sure the GPU isn't the issue).

**Comment by jpd002** [comment]
@HerPizzaFace From the looks of the crash dumps, it seems that an unhandled exception occurred, but there's no way to see where it happened. I've made a special build that will display a message box when an exception is caught:

http://purei.org/downloads/play/special/Play-HerPizzaFace-ExceptionCatcher.exe

So in theory, you should get a message box at the same moment you are getting the crash on that build. The message should give me more info about the cause of the problem.

**Comment by HerPizzaFace** [comment]
Okay, this is what it says:
![cantreadafterendplayffx](https://cloud.githubusercontent.com/assets/12665021/8506361/19ee012e-21de-11e5-91be-bf46d986e084.jpg)

**Comment by jpd002** [comment]
Thanks, I was not expecting that at all... You're playing from a ISO/BIN disk image?

**Comment by gambrio** [comment]
Yes, ISO dumped right from the disc.

**Comment by jpd002** [comment]
Ok, I could reproduce the issue using a .BIN dump of the disk. Shouldn't be too hard to fix now that I can debug the thing.

**Comment by jpd002** [comment]
Not a problem with large file support after all, it's just that Win32's ReadFile (called by fread) reports an error when trying to read a file on a write-protected memory region (rather than triggering an exception that the emulator could catch). 

Quite easy to fix and will be in Sunday's build.

**Comment by HerPizzaFace2** [comment]
Hey, my old account got deleted for some reason, but I made a new one.

How come if the problem wasn't experienced by you before? You mentioned in the other issue when I first brought this up that you got passed that part in testing. How come the issue didn't happen for you?

**Comment by jpd002** [comment]
@HerPizzaFace2 I'm testing games using ISZ files (UltraISO compressed disk images) for the most part and the crash doesn't happen because the protected memory is being written by user code (rather than a system call function) when using this compressed ISO format, which in turn causes the emulator's exception handler to be called.

The protected memory change is not so old (3 weeks ago), so people might have played the game successfully before that change was made. CSO files would also work properly.

**Comment by jpd002** [comment]
Fixed in c844eb3affe680978a417453337f58d8d03e3d2d

**Comment by HerPizzaFace2** [comment]
Thanks for the explanation and fix. I will definitely try it tomorrow from the save states I have.

**Comment by jpd002** [comment]
Awesome! Glad it works! :)
