### ISSUE TITLE
Game does not boot at all.

### ISSUE THREAD

**Issue by rbohannon89** [jpd002/Play-#721]
Armored core last raven.

**Comment by rbohannon89** [comment]
Just letting you dev know. Nothing more nothing less. Thank you.

**Comment by literalmente-game** [comment]
You can close this issue as we already have this information reported here https://github.com/jpd002/Play-Compatibility/issues/38 . Search there before trying to open any new issue to be sure you're not reporting an issue that we already know.

**Comment by jpd002** [comment]
Thanks for reporting!
