### ISSUE TITLE
Stuck at building collection

### ISSUE THREAD

**Issue by wiguna77** [jpd002/Play-#723]
I have been waiting like 5 hours. Can you make a alternative select a folder on the storage instead of scanning it

**Comment by 678GUY** [comment]
Im having the same problem.

**Comment by jpd002** [comment]
Can you show me what's going in your device's log while its scanning? Using adb logcat.

**Comment by jpd002** [comment]
We've recently changed the code that's responsible for scanning games. Have you tried the latest [automated build](http://purei.org/downloads.php)? If so, is there a difference in behavior?

**Comment by TheComputerGuy96** [comment]
> We've recently changed the code that's responsible for scanning games. Have you tried the latest [automated build](http://purei.org/downloads.php)? If so, is there a difference in behavior?

I tried it, and found out that game scanning doesn't work with SELinux set to Enforcing

Here are the relevant SELinux denials:
`02-20 19:58:12.005 W/mount   (23239): type=1400 audit(0.0:66514): avc: denied { search } for name="vendor" dev="tmpfs" ino=14641 scontext=u:r:untrusted_app:s0:c189,c256,c512,c768 tcontext=u:object_r:mnt_vendor_file:s0 tclass=dir permissive=0
02-20 19:58:12.005 W/mount   (23239): type=1400 audit(0.0:66515): avc: denied { search } for name="vendor" dev="tmpfs" ino=14641 scontext=u:r:untrusted_app:s0:c189,c256,c512,c768 tcontext=u:object_r:mnt_vendor_file:s0 tclass=dir permissive=0
02-20 19:58:12.009 W/mount   (23239): type=1400 audit(0.0:66516): avc: denied { getattr } for path="/system/bin/mke2fs" dev="sde48" ino=1811 scontext=u:r:untrusted_app:s0:c189,c256,c512,c768 tcontext=u:object_r:e2fs_exec:s0 tclass=file permissive=0
02-20 19:58:12.009 W/mount   (23239): type=1400 audit(0.0:66517): avc: denied { getattr } for path="/system/bin/dpmd" dev="sde48" ino=1819 scontext=u:r:untrusted_app:s0:c189,c256,c512,c768 tcontext=u:object_r:dpmd_exec:s0 tclass=file permissive=0
02-20 19:58:12.009 W/mount   (23239): type=1400 audit(0.0:66518): avc: denied { getattr } for path="/system/bin/mediadrmserver" dev="sde48" ino=1828 scontext=u:r:untrusted_app:s0:c189,c256,c512,c768 tcontext=u:object_r:mediadrmserver_exec:s0 tclass=file permissive=0`

But with SELinux set to Permissive, games can be scanned without any issues and I could even load GTA San Andreas:
[GTA San Andreas loading screen](https://i.imgur.com/wqzGOqF.jpg)

Device: Pocophone F1, Android version: 9.0

**Comment by jpd002** [comment]
Could you show us what your mounted devices look like? Using `adb shell` then typing in `mount`.

I think there might be another bug that cuts the game scanning process short if there's a path that can't be searched into.

Thanks!

**Comment by TheComputerGuy96** [comment]
> Could you show us what your mounted devices look like? Using `adb shell` then typing in `mount`.
> 
> I think there might be another bug that cuts the game scanning process short if there's a path that can't be searched into.
> 
> Thanks!

Here you go:
https://del.dog/berylliummountswithmagisknoroot.sql

**Comment by TheComputerGuy96** [comment]
This issue still exists in the latest version of Play!

**Comment by jpd002** [comment]
I saw the issue occurring on Android, but I couldn't reproduce it easily. I think it might be related to the fetching of the box art being interrupted by an internet connection cut.

**Comment by TheComputerGuy96** [comment]
> I saw the issue occurring on Android, but I couldn't reproduce it easily. I think it might be related to the fetching of the box art being interrupted by an internet connection cut.

You should look at those SELinux denials in that log I provided

**Comment by jpd002** [comment]
Could you try that build? https://s3.us-east-2.amazonaws.com/playbuilds/0422a220/Play-release.apk

I've been trying to debug the infinite scanning problem with someone else and something was wrong with the way we are waiting for the `mount` command to complete. That build fixed his problem, I'm wondering if it's going to help you.

If not, I'd like to see what is being output by Play! in logcat, I've added some logs to check where it's hanging. You can use `adb logcat Play!:V *:S` to make sure you only get the messages from the emulator.

Thanks!

**Comment by wiguna77** [comment]
This build fixed the issues, the loading only take a few sec!! Good job man!!
