### ISSUE TITLE
Dokapon Kingdom iOS not working

### ISSUE THREAD

**Issue by TheHopelessHero** [jpd002/Play-#724]
I spent the past ten hours getting your play! app and the dokapon kingdom iOS rom all working for it to show up in your app but when I open it just show a blank screen. I know you listed it as a FPS status. Any chance you could fix it asap? I loved this game and its popular. and the fact that it literally goes for 500 dollars online now would be a great pull for you to get even more users and downlaoders.

**Comment by literalmente-game** [comment]
Don't open new issues for games already reported here https://github.com/jpd002/Play-Compatibility/issues/134 . Close this issue and add any new information to the already open issue if you want to report something

**Comment by jpd002** [comment]
Moving discussion to compat tracker.
