### ISSUE TITLE
[Feature Request] SaveStates on Mobile (iOS, Android)

### ISSUE THREAD

**Issue by brand175** [jpd002/Play-#726]
I was wondering at some point this feature would be implemented. I'm hoping that SaveStates via PC or MacOS would be compatible on mobile with the same build version.

**Comment by boberto5888** [comment]
Am I missing something? AFAIK they already have save states and they're already compatible with save states created on PC.
You just swipe in from the left side of the screen once you've loaded the game and you get the option to save state or load state.

**Comment by Alissonjos** [comment]
Hi somebody can tell me where's the savestates locations on pc?

**Comment by jpd002** [comment]
You can move save states around from Windows to macOS and Android, there's no platform specific info in them. iOS still lacks a menu to allow saving and loading states though.
