### ISSUE TITLE
Automated Builds Link Broken

### ISSUE THREAD

**Issue by spicybanners35** [jpd002/Play-#730]
Hi. I just noticed that the link for automated builds on the purei.org site isn't working. Can you fix it?
EDIT: Sorry for 2 issues in a row.

**Comment by jpd002** [comment]
Yup, I messed up with that merge. Fixing it as we speak.

**Comment by jpd002** [comment]
Should be back to normal now.

**Comment by calebjosephchambers** [comment]
Not working for me

**Comment by uyjulian** [comment]
Clear your cache

**Comment by calebjosephchambers** [comment]
And cookies?  Cache did nothing..  why does it get broken so often?

**Comment by jpd002** [comment]
Or make sure you refresh the page, the links change at every build.

**Comment by Mar2ck** [comment]
They seem to not be working again

**Comment by uyjulian** [comment]
They still work for me. Are you checking http://purei.org/downloads.php ?
