### ISSUE TITLE
Android, OGL multithreading

### ISSUE THREAD

**Issue by Alissonjos** [jpd002/Play-#731]
I was thinking, its possible to add OGL Multithreading or to use more cpu threads on android
![screenshot_20181210-164247](https://user-images.githubusercontent.com/24876699/49753804-95e8ea00-fc9b-11e8-8121-98ac220046b1.png)

my phone specs: android 8.1, snapdragon 616, 2Gb Ram,  adreno 405 gpu

**Comment by Emulatorer** [comment]
Same as ppsspp after they multithreaded the OpenGL it's boost almost all games
increase their performance.

hoping this will happen soon in Play! :)
(I hated Damonps2 😈)

**Comment by jpd002** [comment]
Not sure it will help a lot in the current state of things. All OpenGL calls are already done in another thread. Did a quick test, disabling rendering on iOS, playing FF12 (that generates hundreds of draw calls). Frame rate did not change.

**Comment by Emulatorer** [comment]
Damonps2 Supported Feature :

* Support 2X~5X Enhanced Resolution (1080p HD)

* Support Bilinear Texture Filtering

* Support HID Gamepad (Only During the Game )

* Support Skip BIOS boot screen

* Support Multi-threading Acceleration

* Support NEON Vector Instruction Acceleration

* Support OpenGL ES 3.1 Rendering Acceleration

* Support Multi-format ROM File (Include: *.iso\bin\img\nrg Format)



Future Support Feature :

* Future Support Cheat Code

* Future Support Frameskip

* Future Support No BIOS file required

* Future Support Widescreen Patch(16:9 and 18:9 full-screen game)

* Future Support Native Widescreen Games

* Future Support Vibration for HID Gamepad

* Future Support Mipmap (Trilinear Texture Filtering)

* Future Support Save/Load Game State in Cloud Network

* Future Support Import MemoryCard from pcs*2 format

* Future Support Compressed ISO ROM File : *.cso

* Future Support MEPG2 Video Decoding Hardware Acceleration

* Future Support More HLE(High-level Emulation) Feature

* Future Support ARM-v8 Instructions Acceleration

* Future Support OpenGL ES 3.0 Device for Andoird

* Future Support X86 Device for Andoird

* Future Support Better APP UI

* Future Support Vulkan API

* Future Support 95% of PS2 Games Run Perfectly (Perfect Level)

Hope this will happen too in Play! :)

You can also create a donation version of Play! Gold like PPSSPP Gold to fund & maintain the development. (just my opinion don't mind it)

**Comment by Sarkie** [comment]
> Damonps2

Please remove comment or ban user

**Comment by jpd002** [comment]
The question has been answered, closing this.
