### ISSUE TITLE
Play! Minimum Requirements For Android Specifications

### ISSUE THREAD

**Issue by Emulatorer** [jpd002/Play-#733]
I try to install Play! in my phone equip only with Mali-450 GPU and only 32bits processor but I tried a lot of hembrew games no one work/play :(

So what's the minimum hardware requirements of Play! in android phone?

**Comment by Emulatorer** [comment]
Mali-450 Support Only OGL 2.0 :(

**Comment by jpd002** [comment]
How were you able to install it on your device though? I've added a restriction in the AndroidManifest to require OpenGL ES 3.0.
