### ISSUE TITLE
Builds?

### ISSUE THREAD

**Issue by spicybanners35** [jpd002/Play-#734]
Hi, I noticed that the builds haven't been updated since December 10th. What's up with that?

**Comment by uyjulian** [comment]
Did you know that there are holidays in the western world called "Christmas" and "New Year's"?

**Comment by jpd002** [comment]
The automated builds are synchronized with commits on this repo. The last commit was made on December 10th.

There’s some branches in the work (SoulCalibur3 and Capcom Classics Collection 2) but I’m on vacation right now, so, progress is slower than usual...
