### ISSUE TITLE
Text characters rendered badly in game but ok in frame debugger

### ISSUE THREAD

**Issue by bigianb** [jpd002/Play-#738]
I'm guessing this is an issue in the OGL renderer because it looks okay in the frame debugger.
Looking at the main menu of Tribes Ariel Assault:

![image](https://user-images.githubusercontent.com/2781371/51004685-a0650080-1533-11e9-916b-6174cf6f1aef.png)

Frame debugger:
![image](https://user-images.githubusercontent.com/2781371/51004722-d0140880-1533-11e9-8a86-f75eab3454ea.png)

**Comment by jpd002** [comment]
The OpenGL pixel shader has some custom bilinear filtering code, which might be the source of this problem. Maybe we need to adjust the way samples are being taken (with some kind of bias) to compute the final color.

**Comment by bigianb** [comment]
That’s interesting but the colour of the buttons is also different as if the alpha is wrong. I ran it up on my iMac today (2018 top end one) and it looks better on that which is odd. The pic above is from my 2014 vintage dell XPS 15 so different graphics card.

**Comment by jpd002** [comment]
Related issue: #773.
