### ISSUE TITLE
[SLUS21078] Budokai Tenkaichi 3 works, but has graphics issues!

### ISSUE THREAD

**Issue by ghost** [jpd002/Play-#74]
![play budokai3graphicsissues](https://cloud.githubusercontent.com/assets/13189357/8512984/a970eaba-2327-11e5-87a5-e8c8bf762d0a.jpg)

I can see shadows moving, but for some reason the models aren't being rendered in battle. Is there any word on this issue? It is Dragon Ball Z Budokai Tenkaichi 3. I do not know if this but I see other threads here talking about the game so I am think some users have debugged the game and if so is there hope it can improve the graphics errors anytime in the forseeable future? 

I notice you said it okay to open issues for games to keep track of their status and stuff, but I don't want to overwork because you have lots of issues already and you are only one developer @jpd002 so sorry if this is too much but I just wondering on the graphics issue and if it's possible to fix.

I am okay waiting so it doesn't have to be looked into, just don't want you to overwork or too much.

**Comment by jpd002** [comment]
Thanks for reporting. I can take a look, but I'll need to get the game first.

**Comment by jpd002** [comment]
Reported not to work properly on iOS in #346.

**Comment by jpd002** [comment]
Just to give an update on this, I didn't have the chance to look at this problem yet.

**Comment by 3miliokas** [comment]
Black screen on Android version ;-;
![screenshot_2016-08-22-11-22-56](https://cloud.githubusercontent.com/assets/21169885/17848571/e100853c-685c-11e6-9b72-5c11a313201c.png)
![screenshot_2016-08-22-11-23-01](https://cloud.githubusercontent.com/assets/21169885/17848570/e0ff644a-685c-11e6-9940-b7d190fc69c2.png)
![screenshot_2016-08-22-11-23-17](https://cloud.githubusercontent.com/assets/21169885/17848572/e1025d1c-685c-11e6-81c7-44d6cb0e0c66.png)

**Comment by atomic83GitHub** [comment]
There is a compat report for that game, this should be close.

**Comment by jpd002** [comment]
Compat tracker issue: https://github.com/jpd002/Play-Compatibility/issues/135.
