### ISSUE TITLE
Textures Severely Corrupted Across Multiple Games

### ISSUE THREAD

**Issue by iinickb** [jpd002/Play-#741]
Textures in the game 'Spongebob Battle for Bikini Bottom' as well as 'The Spongebob Movie Game' (to a slightly lesser extent) are extremely corrupted. They flicker whenever something on screen moves.

Ex
![image](https://user-images.githubusercontent.com/46337545/51718350-e1b8de00-2012-11e9-9b2b-ad53d90ad61e.png)

and then a few frames later...
![image](https://user-images.githubusercontent.com/46337545/51718364-f09f9080-2012-11e9-8a2c-e62e05bc671f.png)

It also looks like when this issue occurs, a lot of the time it's simply putting the wrong texture on the wrong thing.

![image](https://user-images.githubusercontent.com/46337545/51718428-293f6a00-2013-11e9-9711-adbb50ac2de8.png)

Also, when certain objects aren't on screen, the issue disappears all together...

 
![image](https://user-images.githubusercontent.com/46337545/51718471-4ecc7380-2013-11e9-8a25-df50d3a574f6.png)

It's likely this issue affects more games as well, I just haven't seen it. (I've only tested ~10 games on this emulator.)

**Comment by atomic83GitHub** [comment]
It's a common issue in "Heavy Iron" games.

**Comment by jpd002** [comment]
Should be better now that PATH3 masking is supported.
