### ISSUE TITLE
graphical issues Devil May Cry 3

### ISSUE THREAD

**Issue by Altaiar** [jpd002/Play-#743]
Hi I tested DMC 3 with emulator in PC its a little blur and have a little shaking(screen jumping a little up and down) or something like that in screen and in android same shaking effect and  I cant see characters and ………… (android phone I used galaxy note 8)
PC
![dmc](https://user-images.githubusercontent.com/12981994/52331300-0ea2c300-2a0d-11e9-8f13-ea0c1ccee56c.PNG)
Android
![play_2019-02-06-12-47-01](https://user-images.githubusercontent.com/12981994/52331430-68a38880-2a0d-11e9-8956-919db05a77b5.jpg)

**Comment by literalmente-game** [comment]
Please, don't open game specific issues here, we have a compatibility tracker for this (here https://github.com/jpd002/Play-Compatibility/issues/118). You can close this issue and report any new information to the issue that already exists.

**Comment by Altaiar** [comment]
ok I didn't know that

**Comment by jpd002** [comment]
That one is device specific, it belongs here.

I've spotted a few 3D problems in games I'm playing on my iPhone but I didn't find one that was this obvious. Thanks for reporting that one, I'm going to investigate.

**Comment by jpd002** [comment]
Tested on iOS, looks like UV coordinates are all over the place... going to debug.

**Comment by jpd002** [comment]
After investigation, the problem seems to come from this commit:
https://github.com/jpd002/Play-/commit/0ef4e81547123b3f90891477ea8bb19f9f5cd6e7.

The trick worked well on desktops GPUs, but it breaks on mobile GPUs. Time to move to an integer pipeline?

**Comment by jpd002** [comment]
@Altaiar Would you mind trying this build to see if it fixes the problem on your device? https://s3.us-east-2.amazonaws.com/playbuilds/880d8707/Play-release.apk

It fixed the issues I had on my iPhone, hopefully, it will also fix problems on your end.

Thanks!

**Comment by jpd002** [comment]
I've merged the fix in master since it gives better results than what I had previously. Going to close this for now, feel free to reopen if it's still occurring on your phone.

**Comment by Altaiar** [comment]
its fixed now but its still very slow to play on phone

**Comment by jpd002** [comment]
Awesome, thanks for testing!
