### ISSUE TITLE
Game cover art no longer loads. 

### ISSUE THREAD

**Issue by rbohannon89** [jpd002/Play-#744]
After updating my firmware on my S9 to Andriod 9.0 the cover art no long loads when you launch the app. This has never happen to me untill I update the firmware. The games boot fine I also try to rescan  the games to see if it fixes this issue but does not.  Running Play! Version 2/6/19 Thank you.

**Comment by jpd002** [comment]
Hi! It's broken due to the missing TheGamesDb API key. I'm working on getting a proper setup for that.

**Comment by rbohannon89** [comment]
Great thanks!

**Comment by jpd002** [comment]
Latest automated build should now have covers working again.
