### ISSUE TITLE
Flatout 2 Polygones Explosions

### ISSUE THREAD

**Issue by Fewnity** [jpd002/Play-#747]
Hey,
I have try Flatout 2 on Play! and there are missing polygones and Polygones Explosions 😢
I use the last version of play.
Have good days!
![screenshot_20190226-083409](https://user-images.githubusercontent.com/39272935/53395549-61cfbc00-39a2-11e9-8fde-010cdeae2f68.jpg)
![screenshot_20190226-083118](https://user-images.githubusercontent.com/39272935/53395589-76ac4f80-39a2-11e9-93c4-48eaef046b8b.jpg)

**Comment by jpd002** [comment]
Thanks for reporting. Out of curiosity, is it the same on PC (Win32/macOS/Linux)?

**Comment by Fewnity** [comment]
Yeah, it's the same

**Comment by ojay5280** [comment]
Y

**Comment by jpd002** [comment]
Moved here: https://github.com/jpd002/Play-Compatibility/issues/1401.
