### ISSUE TITLE
AutoTest build is broken

### ISSUE THREAD

**Issue by Zer0xFF** [jpd002/Play-#750]
AutoTest build has been broken as of this commit https://github.com/jpd002/Play-/commit/e232abd197466bc59fc20a5c12059a64b55588b1

**Comment by jpd002** [comment]
This commit https://github.com/jpd002/Play-/commit/fe20a20223b037589aae783204017bf8e2321913 fixes it. I'll bring it in master.

**Comment by Zer0xFF** [comment]
right 👍 
haha, I guess i was over thinking it, i thought you'd need to change AutoTest to use Qt for it, but that's just a surface XD

**Comment by jpd002** [comment]
I don't know why it wasn't caught by AppVeyor though, I probably need to add building the tests in the config.

**Comment by Zer0xFF** [comment]
tests build is on by default https://github.com/jpd002/Play-/blob/master/CMakeLists.txt#L18
the build also failed on that commit https://ci.appveyor.com/project/jpd002/play/builds/23697311/job/3qkcgjqibfu39500#L1901 but it continued on regardless

**Comment by jpd002** [comment]
Right... It might be the appveyor_build.cmd file that's not stopping on error then.

**Comment by jpd002** [comment]
Ok, this is fixed now. Thanks!
