### ISSUE TITLE
key layout

### ISSUE THREAD

**Issue by devilgoldy** [jpd002/Play-#76]
I suggest you to hide d pad and put the left analogue stick to d pad place and  put d pad on up and  because d pad is not really  important or many games or make hideable d pad

**Comment by devilgoldy** [comment]
my first comment is wrong you should add a option for adjust the position of buttons  and when gamepad connect all on screen buttons are hide

**Comment by Evolution0** [comment]
You can edit comments.

**Comment by adriandennis17** [comment]
@devilgoldy the emulator is still in beta stage and that option can be added anytime as it continues to build and get better.

**Comment by literalmente-game** [comment]
This isn't a valid issue and can be closed
