### ISSUE TITLE
Menu issues on iPad Pro (9.7 inch)

### ISSUE THREAD

**Issue by brand175** [jpd002/Play-#763]
Clicking the white menu rectangle while playing a game causes Play! Emulator to instantly crash. Doing this on my iPhone 6 doesn't crash.

**Comment by jpd002** [comment]
Strange, that button doesn't do much: https://github.com/jpd002/Play-/blob/master/Source/ui_ios/EmulatorViewController.mm#L233.
Which version of iOS is running on your iPad?

**Comment by jpd002** [comment]
[This](https://stackoverflow.com/questions/31577140/uialertcontroller-is-crashed-ipad) might be the problem, I'll try to see if I can make it happen on a device or simulator.

**Comment by brand175** [comment]
I'm using iOS 10.2. I've also noticed that the resolution scale factor has ... instead of 2x, 8x etc. I updated my iPad Pro to iOS 12.3.1 and I saw that the resolution scale factor was now working correctly.

**Comment by jpd002** [comment]
Don't know how you get your builds into your iPad, but here's a potential fix: https://github.com/jpd002/Play-/tree/ipad_pause_fix.

**Comment by jpd002** [comment]
I've merged the fix in master. Closing this. Lemme know if the crash still happens.

**Comment by brand175** [comment]
Clicking the Menu button now freezes instead of instantly crashing. Im on iOS 12.4 now.

**Comment by brand175** [comment]
Never mind. It works. I forgot to update the app.
