### ISSUE TITLE
Simplify cloning for building

### ISSUE THREAD

**Issue by Zer0xFF** [jpd002/Play-#767]
for cloning and building atm we need to go through `Play-Build` (which is outdated, for our setup it doesn't matter, but not following the instruction leaves you with a 3 year old build) to setup dependencies hierarchy, it does keep things simple, but its still requires few steps to get started, unfortunately Libretro's build bot setup is rather simple (and was built by someone who isn't around, so changing it to work `Play!` is probably too much of effort to even consider, but I think restructuring this project is long due).

so I prepose we move `CodeGen`, `Dependencies`, `Framework` & `Nuanceur` into this repo, perhaps under `extern` or `deps`.

this will have the side effect of allowing you to finely control the build system.
so you can select which commit to use for each submodule, which then will also apply to the CI.
so if you have a change in `Framework` that would break `Play` master, but you need it for experimental branch, you specify that commit inside the experimental branch.

**Comment by jpd002** [comment]
The PR has been merged.
