### ISSUE TITLE
(Feature Request) Build a Compatibility Tracker Template from within Play!

### ISSUE THREAD

**Issue by gamerminstrel** [jpd002/Play-#771]
Hi there, I'm sorry if I'm doing this wrong. I've never actually made a bug report before. 

I just now discovered Play! a few days ago. I'm aiming to test out my library of PS2 games on it, and I'd like to contribute to the Compatibility Tracker. 

When I saw that there is an official compatibility list, I got hyped and ready to roll, then immediately got a bit nervous/turned away when I found out I need to file a bug report for every game I try. I was expecting something like a wiki page the way Dolphin and PCSX2 track their entries, but I guess it would make sense to not have that. That seems tedious, and a lot of work to maintain.

My feature request is: If something like a wiki database is not possible, is it feasible to request something like a bug report generator to be built into Play!? Hear me out first:

-I'd like to be able to click "Options", then there be an option like "make game status report"; -This would open up a new window with a template that auto-fills the following:
    -commit hash of your current Play! Build, 
    -the ID of the game you're playing, 
    -game title (if it's even possible to identify that), 
    -and takes a screenshot, saved to the same directory as the .appimage or some default location
-Then there would maybe be a drop down menu to select which "state" the game fits into (state-playable, etc)
-Then there would be a text field underneath for any additional notes or quirks observed testing out the game.

Extra credit would be the option to hit a "send" or "submit" button that sends/creates the bug report automagically, but I can't even begin to wrap my head around how to make that happen.

If this tool existed, it could create a text field with all of that information so one could just open a new issue on github, paste it all in and drag/drop a screenshot. I think that would help lower the barrier of entry for people reporting on bugs, and make the process faster/easier.

If this is an unfeasible request, that's fine too. I'm no programmer, but I would like to contribute if possible.

**Comment by literalmente-game** [comment]
Read the guidelines here: https://github.com/jpd002/Play-Compatibility
Also take a look at other open issues on the tracker before reporting anything to be sure you're providing all the information needed (be sure you're _not_ opening a new issue for a game that already have one, just search for your game in the tracker first).

Btw, when you click to create a new issue on the tracker there is already a template that you can fill.
You can close this issue after reading this comment.
