### ISSUE TITLE
VS 2019 build

### ISSUE THREAD

**Issue by bigianb** [jpd002/Play-#776]
I'm seeing this in the VS2019 cmake build. Is it just me or is anyone else seeing that?
I also had to add include <stdexcept> to a number of files because std::runtime_exception was not defined.

```
1>------ Build started: Project: PlayCore, Configuration: Release x64 ------
1>MA_VU_Lower.cpp
1>MA_VU_Upper.cpp
1>C:\emu\play\play_clean\Source\ee\MA_VU_Upper.cpp(491,26): error C2248:  'CMIPSInstructionFactory::Illegal': cannot access protected member declared in class 'CMIPSInstructionFactory'
1>C:\emu\play\play_clean\Source\MIPSInstructionFactory.h(37): message :  see declaration of 'CMIPSInstructionFactory::Illegal'
1>C:\emu\play\play_clean\Source\MIPSInstructionFactory.h(21): message :  see declaration of 'CMIPSInstructionFactory'
```

**Comment by Zer0xFF** [comment]
I had this issue with my new laptop, since I installed VS 2019, issue mostly because the build default to the new build tool instead of v141 (aka vs 2017).

Long story short, I gave up on it, as using that build tool, the project built but I still can't run the binary. I've been meaning to get back to it, but that never happened.

**Comment by bigianb** [comment]
So it’s not just me ... that’s useful info. In that case I will take a deeper look this week.

**Comment by jpd002** [comment]
Same on my end. 

Not sure about the protected member access error, it works on every other compiler out there, so I don't know if it's a compiler bug or something like that. Anyways, I guess making the `Illegal` member function public would be an good fix.

**Comment by bigianb** [comment]
So thinking about this, I think the compiler is right. The issue is that your storing a pointer to a member function in a static array. That means the compiler can't be 100% certain that the function will always be called with this .... i.e. I think I could write some code which would allow object A to call the Illegal() function of object B. That's explicitly disallowed for protected and private. So I agree that making Illegal public is the correct fix.

**Comment by bigianb** [comment]
so with the public change, the stdexcept includes and boost boosted to 1.68 (via pulling master from dependencies) then it compiles and runs under vs 2019 with the latest toolchain. Happy to provide a PR if it helps.

**Comment by Zer0xFF** [comment]
you should push a PR, else this will become an issue for someone else (or us) in the future and will have to solve it again.

**Comment by bigianb** [comment]
ok made 2 pull requests which allow this to build under vs 2019 without the xp toolchain (i.e. with the modern one).

**Comment by jpd002** [comment]
Thanks for the PRs, the changes were merged.
