### ISSUE TITLE
Ios 12 instant crash when open app

### ISSUE THREAD

**Issue by HorrorTroll** [jpd002/Play-#779]
So i download automated build, and install it. But when i run the app, it just instant crash!

I'm use iPhone 8 Plus (iOS 12.1.1 Beta 3), i jailbreak it with unc0ver tool

**Comment by jpd002** [comment]
Do you see the game selector at all? The black splash screen shows up and the app just vanishes?

**Comment by HorrorTroll** [comment]
The black splash screen shows up and the app just vanishes

**Comment by jpd002** [comment]
Do you happen to have access to the Console application on a Mac? If so, could you send the log of your device when the crashes happen?

Thanks!

**Comment by HorrorTroll** [comment]
:/ i didn’t have Mac OS. Is there anyway to get the app log though windows?

**Comment by WhiteRedWolf** [comment]
The same Happens to Me on an iPhone 7,

**Comment by hyperkraz** [comment]
![2E1CCC5B-2E97-44A2-9D1F-E61EAE627066](https://user-images.githubusercontent.com/53255360/61778329-66629a00-adb3-11e9-8f76-cde20c84ca94.png)


Same here; to be specific, it crashes after selecting a game. The game icons load just fine, but after selecting a game, a black screen with a “Menu” button appears for just a second before crashing.

Iphone 8, ios 12.3.1. Automated build dated jul 24, 2019. Attempted kingdom hearts 1, kingdom hearts 2, final fantasy x, jak 2, and dynasty warriors 6. Same with all.

Thank you for all your work!

**Comment by HorrorTroll** [comment]
Fixed on automated build dated Aug 15, 2019. Closed issue

**Comment by microadam** [comment]
I am having the same issue as above, using 20th August nightly build
