### ISSUE TITLE
Sponsor link not working on github

### ISSUE THREAD

**Issue by hazrpg** [jpd002/Play-#784]
The new feature of github showing a sponsor's link isn't working. @jpd002 I think you need to set up your github account to be a sponsor by going to https://github.com/sponsors

I get the following when clicking on it:

![image](https://user-images.githubusercontent.com/115112/62193287-5cbad280-b36f-11e9-9026-fe8e29975ce3.png)

**Comment by jpd002** [comment]
Hi!

I’ve applied for the beta a month or so ago, but I haven’t received any response as of now.

Thanks!

**Comment by hazrpg** [comment]
Hi @jpd002 

Great, I hope they get back to you soon. I hope both you and @Zer0xFF keep up the great work. And that you get many supporters to the project - especially now that you have a libretro core too!

**Comment by Zer0xFF** [comment]
can be closed.

**Comment by jpd002** [comment]
Indeed, the link now works!
