### ISSUE TITLE
Gzip (GZ) ISO support / compressed ISO's?

### ISSUE THREAD

**Issue by goedzo** [jpd002/Play-#785]
In order to save space, I have GZipped my ISO's as most of the PS2 ISO files contain a lot of empty space.  This method is supported by PCSX2, and it works very good, as they also create an index to speed up the loading, without the need to unpack. 

So my question is, can this gz support also be added to play? Or is there already compressed file support available?

**Comment by jpd002** [comment]
There's already support for CSO and ISZ (UltraISO image files). We could also add support for gzip, but AFAIK, it's not really a great fit for disc images.

**Comment by goedzo** [comment]
Ok that is interesting to know there are other formats available. Do you want me to close this issue?

**Comment by jpd002** [comment]
I'll close it, thank you!
