### ISSUE TITLE
Locale Error

### ISSUE THREAD

**Issue by sodomon2** [jpd002/Play-#786]
I have an error with the locale when running the emulator I saw a similar error here  [#703](https://github.com/jpd002/Play-/issues/703) Here's the mistake. 

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-diego'
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted

**Comment by jpd002** [comment]
Hi! Which Linux setup are you using?

**Comment by sodomon2** [comment]
I don't quite understand what you mean by linux configuration.

**Comment by JohnHolmesII** [comment]
Which Linux distro? Ubuntu? Void? Arch? Alpine?

**Comment by sodomon2** [comment]
Alpine

**Comment by sodomon2** [comment]
Apparently if I run it so LC_ALL=C Play works no longer gives the previous error but has a segfault

**Comment by sodomon2** [comment]
fixed
