### ISSUE TITLE
Hang with Knockout kings 2002

### ISSUE THREAD

**Issue by prafullpcsx2** [jpd002/Play-#793]
I have been trying play! with lot of games recently. One interesting problem that I faced is with the game Knockout kings 2002. It seems to work well in the menus but hangs as soon as a fight starts. Same problem exists in PCSX2 as well and I am pretty sure fixing it in one emulator will also provide solution to fix it in other emulator.

**Comment by Gamemulatorer** [comment]
Move this issue to https://github.com/jpd002/Play-Compatibility/issues

**Comment by jpd002** [comment]
Moved to https://github.com/jpd002/Play-Compatibility/issues/1350.
