### ISSUE TITLE
Add sw_buffer for android version please

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#796]

**Comment by Emulatorer** [comment]
What is sw_buffer?

**Comment by ericsonia** [comment]
https://youtu.be/90k29ZJAeyQ

**Comment by jpd002** [comment]
That experimental branch relies on fragment shader interlock to work properly. 

The extension was added very recently to Vulkan (`VK_EXT_fragment_shader_interlock`) and is supported by desktop nVIDIA and Intel drivers right now now. It also just has been added to MoltenVK (https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.37).

I'm not sure how it's gonna work for mobile devices, but the newest iOS GPUs support that kind of feature through [raster order groups](https://developer.apple.com/documentation/metal/gpu_features/understanding_gpu_family_4/about_raster_order_groups). I guess this is also going to be supported by other mobile GPUs in the future.

My current plan regarding adding support for the `sw_buffer` branch on mobile is to build a simple Vulkan based renderer, use MoltenVK to build an iOS version and see how it fares on a real device. If everything goes well, the Vulkan renderer will become the "next gen" renderer based on `sw_buffer` branch and it should theorically work out of the box once GPUs supporting `VK_EXT_fragment_shader_interlock` start appearing on Android devices.

**Comment by jpd002** [comment]
Kinda related to #847. Closing this.
