### ISSUE TITLE
unable to compile on windows

### ISSUE THREAD

**Issue by supernoodled** [jpd002/Play-#799]
CMake Error at Source/ui_qt/CMakeLists.txt:185 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

Just done exactly what the readme said on windows, and this happens every time.

**Comment by Zer0xFF** [comment]
>Just done exactly what the readme said on windows, and this happens every time.

did you update the `-DCMAKE_PREFIX_PATH` path to match your installed version of Qt?

**Comment by akasarx** [comment]
Yep. I have the latest version of Qt 5.13.1

**Comment by Zer0xFF** [comment]
can you please post the cmd you're using to setup the build?
