### ISSUE TITLE
Add Frameskip and Config Controller

### ISSUE THREAD

**Issue by zminhquanz** [jpd002/Play-#80]
Please , add this

**Comment by adriandennis17** [comment]
all in due time...just be patient.

**Comment by atomic83GitHub** [comment]
Frameskip will not be usefull in this emulator, the major bottleneck is the cpu part and custom controller config is already possible.
Close the issue.

**Comment by jpd002** [comment]
Yeah, I fear frameskip could cause more problems and wouldn't help many games (depending on how it's implemented). I had frame skipping before, but I removed it because it was causing instability.

Also, controller config? On which platform?

Closing for now, but feel free to comment.
