### ISSUE TITLE
OSX Compile

### ISSUE THREAD

**Issue by iosdec** [jpd002/Play-#800]
To compile on OSX, do the following:

```
brew install cmake
brew install qt5
```

Then compile by doing:

```
mkdir build
cd build
cmake .. -G"Xcode" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.13.1/
```

**Comment by jpd002** [comment]
Since you've opened up #801, I'm assuming you were able to compile for macOS. Closing this issue. Feel free to reopen if you still have issues building.
