### ISSUE TITLE
Play debug concern and endless loading times

### ISSUE THREAD

**Issue by Askmewho** [jpd002/Play-#802]
HI! I am on rpi4, and after see the actual performance on high end devices...well the actual performance on rpi4 wasnt that bad, there is a long road on the jit side (and I hope you get all the devs and millions of dollars on support you need to achieve that hahahah )

the question:
In order to get ANY dev output on terminal you need to compile it on releasewithdebinfo or debug or you can set any argument to se at least whats happening on the emulator???

because some games didnt really start...and not even crash, for example shadow of the collosus shows a loading graphic and never start and FFXII (which is on the playable list) load but...never load, just an endless black screen.

**Comment by jpd002** [comment]
If you're running a Debug build, you can enable the `log.showprints` config option in `config.xml` to enable verbose logging. The resulting log files will be present in the `~\Play Data Files\logs` directory.

Regarding the specific issues with the games, I know only the US version of FF12 works, but I can play it on my iPhone. Shadow of the Colossus not working might be a bug, I'll give it a quick spin on my device.

**Comment by Askmewho** [comment]
Indeed, now ff12 its working!

**Comment by Askmewho** [comment]
I made a video trying to advertise your emulator, hope you like it. Sorry if you disagree on some technical point of view (you are the expert here). Its the best I could right now. https://youtu.be/MOooOYSS3S4

**Comment by jpd002** [comment]
I tried Shadow of the Colossus on my iPhone and there's indeed an infinite loading problem. Could be an ARM64 code generation problem, I'll look into it.

**Comment by Askmewho** [comment]
Thanks, I make an all video about your emulator on rpi4 to gain attention...its on his firsts steps, but I have to give you a plus for the graphics, at least on the supported games... it looks great

Hope you get more help

**Comment by jpd002** [comment]
After investigation, SotC was broken on all platforms. This branch fixes it: https://github.com/jpd002/Play-/tree/sotc_regression_fix.

**Comment by Askmewho** [comment]
So, we close the issue!
