### ISSUE TITLE
Can't detect disc in disc drive

### ISSUE THREAD

**Issue by happygreenfrog** [jpd002/Play-#806]
Emulator doesn't seem to acknowledge the existence of the drive at all, even when a disc is inserted. In significantly older versions (I think the initial "stable" 0.30 version is one such example, but I could be remembering wrong?), this was not an issue and the drive worked correctly.
![image](https://user-images.githubusercontent.com/41273098/66003929-08b29400-e46d-11e9-85a4-5c9342469ebb.png)

Windows version is Windows 10 Home, Version 10.0.18362 Build 18362. The Blu-Ray drive is an external LG-CP40NG10 Slim Portable Blu-ray Multi Drive. Game disc pictured in the drive in the screenshot is Mega Man X Command Mission, but I also tested with Mega Man X Collection and Midway Arcade Treasures to no avail.

Curiously, when I pressed "refresh" while the computer itself was still actively loading the disc, it did pause, so maybe the problem is that it can't detect that the disc is inserted, but can see the drive itself...?

**Comment by jpd002** [comment]
@Zer0xFF's PR fixed the UI. Made changes to make physical disc support work again: https://github.com/jpd002/Play-/tree/win32_volume_fix.

**Comment by happygreenfrog** [comment]
The good news is, I tested the automated builds, and now it is indeed detecting the disc drive.

The bad news is... apparently I need to open a new issue related to the disc drive.

...actually, upon further inspection, that issue might have to get split into two separate issues, I can't tell if they're both one larger issue or two unrelated smaller issues... hmm...

...but I'm getting ahead of myself, I think I can mark _this_ issue as closed pretty safely now...

...but before I do that, I do just want to make sure that the automated builds would indeed have the _complete_ disc support fix, or if for one reason or another there's some elements of it that still aren't on the main branch, just in case the new issues are because of something like that instead of something that actually needs to be reported.

**Comment by jpd002** [comment]
Could you try this build: https://s3.us-east-2.amazonaws.com/playbuilds/50fc4e5d/Play-0.30-64.exe? That's the one with the changes from the branch I linked in my previous post.

**Comment by happygreenfrog** [comment]
Have done so now. There are indeed new problems as I thought earlier, the issue is no longer that the drive itself can't be detected so much as it can't tell the disc actually has SYSTEM.CNF and also seems to revert the selection from "disc drive" to "disk image" no matter what you do the moment you open the window.

The two issues _could_ be related, it could be that it's trying to read the disc drive as a disc image (somehow) and then not finding the SYSTEM.CNF file in the non-existent disc image that it thinks it is reading, or they could both be separate issues.

Sounds to me at least like these are probably both issues that belong as a separate report, since neither one technically fits the problem of "it doesn't see a disc".

But in any case I've attached screen-shots here to demonstrate what I mean. If you'd rather keep those issues all here since it's still related to the disc drive not working, that's fine, but I guess that's up to you to make that call.
![image](https://user-images.githubusercontent.com/41273098/66086765-b5a71280-e53a-11e9-9c86-cf92869f214c.png)
![image](https://user-images.githubusercontent.com/41273098/66086779-c22b6b00-e53a-11e9-99ca-f175d7eea0d2.png)

**Comment by Zer0xFF** [comment]
they're 2 issues, one is UI, once in the way the emu tries to read the disc.

no need for a new issue, this will do.

the fix for both are already here https://github.com/jpd002/Play-/commit/a413ecd8c03c2936b6ed3431c081d275fc1e3fc8 + https://github.com/jpd002/Play-/tree/win32_volume_fix

**Comment by jpd002** [comment]
All fixes are merged in master. I've tried a physical disc this morning and it was working good on my end. Let us know if you still have issues with the latest automated build.

**Comment by happygreenfrog** [comment]
I have tested, it all works now!

Keep up the awesome work with the emulator, btw

Closing the issue now
