### ISSUE TITLE
nlohmann_json is too big

### ISSUE THREAD

**Issue by guoyunhe** [jpd002/Play-#816]
The whole repo is around 290MB, while deps/Dependencies/nlohmann_json is 250MB huge. For such a small tool that dealing with JSON, the size is crazy...

**Comment by Zer0xFF** [comment]
I just had a look at it, it seems they have tests and benchmarks included in the repo to the tone of 200+MB, and issue has been raised on their repo before, but nothing has been done, so I'll remove them as submodule and include the needed files directly instead.

**Comment by Zer0xFF** [comment]
can be closed with merger of #820
