### ISSUE TITLE
Android x86 Support

### ISSUE THREAD

**Issue by LinkofHyrule89** [jpd002/Play-#82]
Several devices such as the Nexus Player are x86 and would do much better if they had Android x86 based builds instead of using the same builds as arm. Although technically the x86 version of Android is capable of running the same apps having a separate x86 version solves problems and keeps things more optimized.

**Comment by zminhquanz** [comment]
I know , PCSX2 on Windows it written on x86 Artitecture , it Play! written on x86 from port similar code PCSX2 to , it's optimize and capability better than ARM Artitecture

**Comment by jpd002** [comment]
Shouldn't be an issue to port to x86, but still waiting for hardware to test on my side.

**Comment by jpd002** [comment]
I've added x86 support in the latest weekly build. Works fine on my Lenovo S8-50 tablet, but we still need to figure out issues that occur on Nexus TV Player. @LinkofHyrule89 provided some info, but it's still unclear and more testing will be needed.

**Comment by zminhquanz** [comment]
@jpd002 , not working on ASUS Zenfone 4 , Intel Atom Z2520 , game is black screen

**Comment by LinkofHyrule89** [comment]
@zminhquanz this doesn't give us enough information because every game reacts differently and most games take a while to start.

**Comment by jpd002** [comment]
Problem with Nexus Player (and maybe other devices) seems to come from this: https://code.google.com/p/android/issues/detail?id=179410

Don't know if Google is planning to fix that in the next NDK version.

**Comment by LinkofHyrule89** [comment]
Well it's good you found out what the problem is can you fix it do you think?

**Comment by jpd002** [comment]
If they don't fix it in the next NDK release, I could do what the bug reporter is suggesting, but that might have other side effects. I think it's better to wait for now.

**Comment by LinkofHyrule89** [comment]
@LoungeKatt @Thunder07 basically the new update never gets past the loading games on the nexus player and just closes not that it really matters since only the one demo actually runs right now anyways.

**Comment by Thunder07** [comment]
I'm not home nor in front of a computer to be able to look into it, but nothing in that update touches any of the launch/loading  codes. 
But I have noticed non clean build that involve native code edits tend not to boot correctly, debug builds in general too, you should probably do a clean release rebuild

**Comment by LinkofHyrule89** [comment]
Yeah I tried cleaning but maybe I'll try again. But most likely it's not actually your code but the same problem that's be plaguing this and probably other apps on x86 when using the NDK. Hopefully we are able to figure out a solution to fix the problem last build the game list loaded and when you tried to play a game it closed but the now after a while at the loading games it just closes. Anyways maybe you guys can look at the logs anyways to see what you can't find out from it.

**Comment by LoungeKatt** [comment]
07-24 02:16:31.073: A/libc(32559): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 32559 (plications.play)

http://stackoverflow.com/a/16970161

Gotta love CM's duct tape builds and the log spam they create. The error was at line 4750.

**Comment by LinkofHyrule89** [comment]
Yeah cm has a lot of log spam it's annoying. Do you think you can make a patch to fix the problem? Hopefully you guys can figure it out I'm sure it'll benefit other x86 devices. Just to be clear I've tested on stock and a couple versions of Android so I know it's not cm that's causing it in addition to the fact that it works fine on my OnePlus One.

**Comment by LoungeKatt** [comment]
http://stackoverflow.com/a/18507287

**Comment by LinkofHyrule89** [comment]
Hopefully those are more useful to @jpd002 than they are to me. Thanks for finding those maybe we can pinpoint the bugs in x86 better and get them fixed.

**Comment by LoungeKatt** [comment]
That's how to get a precise log of the error. I'm not sure how that would be any less useful to someone with the hardware that is experiencing the error than to the person attempting to fix it.

**Comment by LinkofHyrule89** [comment]
Multiple people have said that the app loads games fine on other x86 devices so I'm wondering what it is exactly that's causing it if it's Android TV x86 specific or something else.

**Comment by LinkofHyrule89** [comment]
Since I know this isn't too priority for the project because other stuff needs to be worked on first I created a thread on xda to try and find some other devs to help with the problem. Hopefully someone takes interest and can help with this problem and the overall project http://forum.xda-developers.com/showthread.php?t=3169436

**Comment by jpd002** [comment]
Just for info: https://code.google.com/p/android/issues/detail?id=179410

Everything should work normally when they release the next version of the NDK.

**Comment by LinkofHyrule89** [comment]
Not really sure what fixed this issue but apparently on the Android N Beta 1 using the latest build of play it works and doesn't crash anymore on my Nexus Player.

**Comment by atomic83GitHub** [comment]
What is the status about this? By the way Android X86 have a ARM compatibility mode wich can maybe work for Play.

**Comment by jpd002** [comment]
That should work fine now, but if anyone still got a problem running the emulator on x86 Android, feel free to reopen.
