### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Askmewho** [jpd002/Play-#827]
Hi? Why did you take the LLE targeting arm64 devices... It will be ever be fast enough? At least from what other devs said dobbieststion it's HLE and it doesn't perform better, but should be a matter of time. Also? Why you don't just add and arm64 hit to pscx2 instead of starting from scratch. I know than there are other non arm targets for this emu also. 
Thanks

**Comment by JhonLoveJoy** [comment]
Taking the emulator to ARM was a mistake from the start, smartphones do not have enough power to emulate PS2, even using tons of hacks.

**Comment by jpd002** [comment]
This is my personal project and I want it to work on x86, ARM and whatever. I also want people to be able to play without a BIOS file. That's how I see it, other projects have other views on how PS2 emulation should work.

If you have specific problems with games/devices, please lemme know. I'm not going to change the direction of the project, so I'm closing this issue.

**Comment by Askmewho** [comment]
Daemon ps2 it's a double jit pscx2 (from mips to x86 and then to arm) and it does run better than your emu than does not this kind of horrible approach. So,I can't understand why you say that. Arm it's evolving, and flagships phone should emulate it on a HLE like yours approach. I am a bit sad to hear you say so.

**Comment by JhonLoveJoy** [comment]
This emulator uses hacks to look like the game is running well, when in fact tons of errors are happening underneath, resulting in bugs that can never be fixed...

**Comment by kenshen112** [comment]
That's how the PS2 works

**Comment by Askmewho** [comment]
Obviusly, daemon ps2 it's a horrible emulator. They not only are violating gpl from pscx2, they are also doing double emulación at the same time! If they even reach that kind of performance, million hacks included, it means than ps2 emulation it's clearly possible on arm hardware if we had a decent how emulator. That's my point.
