### ISSUE TITLE
Sims 2 Castway - Not detecting a controller/keyboard input

### ISSUE THREAD

**Issue by Dragon20C** [jpd002/Play-#834]
When starting the game it just gives a controller not detected message, and I'm pretty sure this isn't the only game but this is the one I know right now.

I would love to help, but I'm not sure how to debug this

![Screenshot_20191206_101317](https://user-images.githubusercontent.com/15175043/70315177-efcdb280-1810-11ea-99e4-5b493c70b489.png)

**Comment by jpd002** [comment]
Fix is being worked on here: https://github.com/jpd002/Play-/tree/sims2. It had nothing to do with controllers. The game still has 3D rendering issues, looking at that.

Gonna close this in favor of: https://github.com/jpd002/Play-Compatibility/issues/406
