### ISSUE TITLE
Build without unrar

### ISSUE THREAD

**Issue by guoyunhe** [jpd002/Play-#839]
unrar isn't FOSS. So when I submit the package to openSUSE official repository, it is not accepted.

Can I build Play! without unrar?

**Comment by Sanaki** [comment]
In theory unrar-free might work as a substitute. Not sure how much work it'd take to support that though.

https://packages.debian.org/sid/utils/unrar-free

**Comment by Zer0xFF** [comment]
unrar is only used in the PsfPlayer (read: not in emulation part of the project, aka not actual referenced or built), so it shouldn't be an issue. The PsfPlayer also need to be explicitly built `-DBUILD_PSFPLAYER=on`, which I presume you dont do, but having said all of that, the PsfPlayer doesn't actually have any packing script associated with it, so even if it was built, it won't be included in any packages created by the build system, so it can't be "distributed" anyway.

regardless of all of that, that particular code it can be disabled with arg `-DPSF_RAR_SUPPORT=off` during the cmake config step.

**Comment by guoyunhe** [comment]
Thanks for the explanation. I removed unrar source for now and it is built well.
