### ISSUE TITLE
Android version case sensitive to file extensions 

### ISSUE THREAD

**Issue by Flav900** [jpd002/Play-#84]
The android app only detects file extensions in lower case. 

I've noticed with myself and other people have the issue that their file extension is .ISO and not .iso which leads at first to some confusion as to why the app does not pick up the file.

Request to change the following lines in android ui MainActivity.java from:

private static boolean IsLoadableDiskImageFileName(String fileName)
	{
		return 
				fileName.endsWith(".iso") || 
				fileName.endsWith(".bin") ||
				fileName.endsWith(".cso") || 
				fileName.endsWith(".isz");
	}

to 

private static boolean IsLoadableDiskImageFileName(String fileName)
	{
		return 
				fileName.toLowerCase().endsWith(".iso") || 
				fileName.toLowerCase().endsWith(".bin") ||
				fileName.toLowerCase().endsWith(".cso") || 
				fileName.toLowerCase().endsWith(".isz");
	}

I have also submitted a pull request with the change

**Comment by adriandennis17** [comment]
@Flav900 good job..

**Comment by jpd002** [comment]
@Flav900 Good one, thanks for spotting this and fixing it! It'll be in the next weekly build (2015-07-12).

**Comment by Flav900** [comment]
No problem! Thanks! Glad I could be of help.  

I'm thinking the IsLoadableExecutableFileName method needs the same treatment for the .elf extension. I overlooked that by accident.

**Comment by jpd002** [comment]
Thanks, your fixes are in this week's build (2015-07-12).

**Comment by Flav900** [comment]
No problem! Awesome! Thanks!
