### ISSUE TITLE
iPhone version of emulator does not enter game play for Metal Gear Solid games

### ISSUE THREAD

**Issue by derekR14** [jpd002/Play-#844]
For different Metal Gear Solid games tested on iPhone, game will load intro screens and game menus, but goes to an indefinite black screen when trying to move to game play.  I've seen other issues noting the game will play for them on other systems (Windows, MacOS and/or Android).  It seems there is an issue with the iOS version of the emulator for Metal Gear games.  Can you confirm if this is something that can be fixed?

The following games were tested:
SLUS-20144 Metal Gear Solid 2: Sons of Liberty
SLUS-20915 Metal Gear Solid 3: Snake Eater 
SLUS-21359 Metal Gear Solid 3: Subsistence

All 3 games were tested on both iPhone 7 and iPhone 8, both running iOS 13.3.

All versions of tests were using commit 988607a.
https://github.com/jpd002/Play-/commit/988607ae5f70a5bdfd0e571e61d68f83b7cc5e31

**Comment by dragon212c** [comment]
I dont think the focus for the developer(s) at the moment is fixing bugs at the moment is just trying to get the best performance as possiable then bug fixes but then expect that any time soon

**Comment by derekR14** [comment]
Understood, just wanted to share the issue. Fixing this may not be a main focus of the dev team, but I figured I’d let the team know in case the fix isn’t too much work.

**Comment by jpd002** [comment]
Seems this was due to the write protection being disabled on iOS. I turned it back on here: https://github.com/jpd002/Play-/tree/ios_ram_write_exception. I remember I turned it off for a reason, but it seems to work well on my iOS 13.3 device.

Take note that MGS2 and MGS3 still don't run properly on all platforms. This branch just brings iOS on par with the rest.

Lemme know if that worked for you.

**Comment by derekR14** [comment]
Awesome thanks for the response. Ill try it out and will let you know

**Comment by derekR14** [comment]
I don't use GitHub much and am having a hard time getting that branches contents into my phone. I usually download the latest .IPA from the purei site and use Xcode to push it to my device.  I don't see an .xcodeproj file in the branch. Can you (or anyone else) give some advice how to get this branch to my device. Thanks in advance.

**Comment by Zer0xFF** [comment]
this is IPA from automated build for that branch, http://playbuilds.s3-us-east-2.amazonaws.com/db27efb1/Play.ipa

**Comment by derekR14** [comment]
You guys are great thanks for the quick response.  I was able to put that version on my phone, and it does advance past the initial game menus, but Im only able to see the first cutscenes and character dialogue.  Still can't enter gameplay.  Is this for sure the same version you're able to play?  My device is an iPhone 8, iOS 13.3

Snake Eater and Subsistence tests: first few cutscenes play but there is some duplicate video shown in the upper left corner, same as current issue (https://github.com/jpd002/Play-Compatibility/issues/3).  After that the game will either crash or advance to gameplay but the image is cluttered with colored pixels and character seems to fall through the ground and dies.

Sons of Liberty test: first few cutscenes play and initial character dialogue starts, but part of the way through the first conversation the game sits and wont advance.  Not frozen, just wont advance.

Game images attached.  The version shown in the settings menu seems to match the version shown in github.  
![IMG_4970](https://user-images.githubusercontent.com/56484195/74611388-5f8dd280-50c9-11ea-81e4-66ed23cd03eb.PNG)
![IMG_4971](https://user-images.githubusercontent.com/56484195/74611389-6288c300-50c9-11ea-9102-ec1b8a1fe6e6.PNG)
![IMG_4972](https://user-images.githubusercontent.com/56484195/74611390-6288c300-50c9-11ea-8a0c-e15d4cab5075.PNG)
![IMG_4973](https://user-images.githubusercontent.com/56484195/74611391-63215980-50c9-11ea-996a-0f7ccb5dabd0.PNG)
![IMG_4974](https://user-images.githubusercontent.com/56484195/74611393-64528680-50c9-11ea-9f1e-9a341d3d8e2d.PNG)
![IMG_4976](https://user-images.githubusercontent.com/56484195/74611394-6583b380-50c9-11ea-875b-1dbccfb1d811.PNG)

**Comment by jpd002** [comment]
Thanks for testing. Yeah, these games don't work well ATM unfortunately and it's the same on all platforms. There seem to also be some memory issues in MGS3 on iOS, running at 2x+ is making it very unstable.

I've merged the fix for the original problem in `master`, so I'm going to close this issue.
