### ISSUE TITLE
frame rate and Audio issues 

### ISSUE THREAD

**Issue by wrapyjam** [jpd002/Play-#846]
whilst running shadow of the colossus on the emu it runs at very low frame rates(around 4 fps)
and audio goes in and out probably due to low fps 
on Mac btw

**Comment by DukeSkinny** [comment]
This is to be expected. The game is far, far from playable and is particularly demanding.

**Comment by jpd002** [comment]
Thanks for reporting. This is a general issue with the emulator, we're always trying to improve performance and as @DukeSkinny mentioned, that game is quite demanding.

Closing this since this is not specific to a game.
