### ISSUE TITLE
OpenGL and Vulkan Games missing things that openGL has/works

### ISSUE THREAD

**Issue by Dragon20C** [jpd002/Play-#853]
Just a quick note if the vulkan compiler isnt complete you may remove this issue as it means nothing if the compiler isnt ready.

OpenGL

![GL](https://user-images.githubusercontent.com/15175043/74266146-b6775e80-4cfb-11ea-85e1-0d21ebd91e9c.png)

Vulkan

![VK](https://user-images.githubusercontent.com/15175043/74266156-ba0ae580-4cfb-11ea-911a-009c6720bd06.png)

As you can see vulkan has missing ui while opengl doesn't I also have another game where on opengl it renders the game (2D) while on vulkan it doesnt but it still works, I should also say this is on arch linux (Manjaro).

**Comment by literalmente-game** [comment]
> Just a quick note if the vulkan compiler isnt complete you may remove this issue as it means nothing if the compiler isnt ready

That's pretty much the case, there's even a new branch (https://github.com/jpd002/Play-/tree/vulkan_phase2) to continue the work on it, no point in making issues about code that isn't even complete yet

**Comment by Dragon20C** [comment]
@literalmente-game  Oh I was unaware I do follow @jpd002 development and the branches I just noticed that a new branch is available, Maybe so he doesn't get random users complaining about vulkan maybe add "experimental" at the end of vulkan so users understand that it wont work for all games
