### ISSUE TITLE
Play! RetroArch core does not load on Debian Buster

### ISSUE THREAD

**Issue by jstolarek** [jpd002/Play-#858]
Attempting to load Play! on latest Debian results in:

```
[ERROR] Failed to open libretro core: "/home/jstolarek/.config/retroarch/cores/play_libretro.so"
[ERROR] Error(s): /home/jstolarek/.config/retroarch/cores/play_libretro.so: symbol _ZNSt10filesystem7__cxx114path5_ListC1Ev version GLIBCXX_3.4.26 not defined in file libstdc++.so.6 with link time reference
```

Not sure whether this is the right place to report RetroArch core errors - if it isn't I'd appreciate pointing me to the right place.

**Comment by Zer0xFF** [comment]
this has recently become an issue on linux, I wonder if we could just solve this, by statically linking against libstdc++.

though this is definitely a surprise, if you're on the latest debian and they're not using latest libstdc++??

**Comment by jstolarek** [comment]
My system reports:

```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
```

> though this is definitely a surprise, if you're on the latest debian and they're not using latest libstdc++??

Not at all a surprise. Debian has a philosophy that differs from other Linux distributions: safety and stability first. The way this philosophy is implemented is by regularly providing stable distribution with bug fixes and security updates, but not doing any package version updates. And this gives you a really stable system,  where updates don't break things - something I really learned to value over the course of years. A downside is that by the end of a release cycle (these tend to be around 2 years) you have packages that are a few years old.

Anyway, if static linking is an option I would really appreciate it. I think new Debian isn't coming out at least until 2021.

**Comment by jstolarek** [comment]
I can confirm that it works. Thanks!

**Comment by Zer0xFF** [comment]
Thanks for confirming
