### ISSUE TITLE
Audio issues not enough buffer

### ISSUE THREAD

**Issue by gurukin** [jpd002/Play-#861]
audio.spublockcount max 400, with 10, 100 and 400. 400 not enough. the lower the more audio cuts has, the bigger the less audio cuts.

**Comment by Zer0xFF** [comment]
without going into too much detail into the purpose of the buffer, the buffer was mainly used to avoid audio breakup in slow games, however, by nature, it introduces a lag sync lag between video and audio the bigger it gets.

in games with high fps you want to use small buffer, and games with low fps high buffer.
however, if you need a buffer size of larger than 400, then the game is running soooo slow, its probably not worth playing.

**Comment by jpd002** [comment]
Can you give us more details about your use case? Which game you're playing, which platform you're playing on and the frame rate you're having?

**Comment by gurukin** [comment]
hello, the games in general play at around 45 fps, sometimes 60 fps. i have a Red nubia 3 10gb ram, and a Vivo nex 2 double screen 8gb ram, i play kingdom hearts I, II, and final fantasy x-2. the sound always gets cuts, the more buffer the less audio cuts, the less the more and longer audio cuts. less buffer looks like it as not enough memory too process all game data (graphics and sound) it happens more durinng videos, like the start of the game ones. on script videos theres audio cuts but like sound for 3 4 secs a small audio cut and again comes audio. isnt it possible to use vulkan intead of opengl?

**Comment by jpd002** [comment]
@Zer0xFF explained it pretty well. Improving performance is probably what is going to fix the sound issues. Also, in Kingdom Hearts 1, there were issues with sounds and music that got fixed recently.
