### ISSUE TITLE
vulkan isntead of opengl

### ISSUE THREAD

**Issue by gurukin** [jpd002/Play-#862]
Changing from opengl to vulkan in the confix.xml works. 
here how i.have my config: renderer.vulkan.enablehighresmode
renderer.vulkan.forcebilineartextures renderer.vulkan.resfactor

the games work. isnt there any intention to support vulkan in future builds?

**Comment by Zer0xFF** [comment]
I'm going to take a wild guess and say you're refering to your mobile?
if so, changing the config does absolutely nothing in this case.

Vulkan is still being worked on, and should it be possible to support mobile devices, it will be.

**Comment by jpd002** [comment]
As @Zer0xFF mentioned, Vulkan is not ready for mobile yet, but it will be later.
