### ISSUE TITLE
libretro displays only black screen while appimage sort of works

### ISSUE THREAD

**Issue by soredake** [jpd002/Play-#868]
Trying these game https://wiki.pcsx2.net/JoJo_no_Kimyou_na_Bouken:_Ougon_no_Kaze

[jojo-libretro-play.log](https://github.com/jpd002/Play-/files/4324363/jojo-play.log)

Some graphics is dislayed in appimage version:
![Screenshot_20200312_151810](https://user-images.githubusercontent.com/5204968/76525766-1d13a780-6475-11ea-86b0-fe9f52ec5b2b.png)

**Comment by gouchi** [comment]
Did you update Play! core ? As using latest one from buildbot (0.30-8af8a75) I can launch the game in RetroArch.

**Comment by soredake** [comment]
Yes, i update core, vulkan -> black scree, gl -> crash ->, glcore -> blackscreen

**Comment by gouchi** [comment]
I tested only with Nvidia driver.

May you try to update your Mesa driver to 20.0.3 ?

**Comment by soredake** [comment]
Yeah, my config was somehow wrong, removing it makes game work, thanks
