### ISSUE TITLE
Finally Downhill Domination in game (play! Android)

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#869]
Play! Android version (Automatic build 2020-03-12)
My device Android Snapdragon 845
![Screenshot_20200314-133815395](https://user-images.githubusercontent.com/55049420/76677108-00a27700-65fd-11ea-82d6-9c8116f0bf13.jpg)
![Screenshot_20200314-134336812](https://user-images.githubusercontent.com/55049420/76677112-08621b80-65fd-11ea-9222-d9231c38d86e.jpg)
![Screenshot_20200314-134533471](https://user-images.githubusercontent.com/55049420/76677113-0b5d0c00-65fd-11ea-83f0-5b169e93e4f5.jpg)
![Screenshot_20200314-134608957](https://user-images.githubusercontent.com/55049420/76677115-0dbf6600-65fd-11ea-81dd-74099dfd73c7.jpg)

**Comment by jpd002** [comment]
Glad you are enjoying it :)
I've updated the compatibility entry with your results: https://github.com/jpd002/Play-Compatibility/issues/232

Thanks!

**Comment by ericsonia** [comment]
So, when you add vulkan feature for android version? :(

**Comment by ericsonia** [comment]
> Glad you are enjoying it :)
> I've updated the compatibility entry with your results: [jpd002/Play-Compatibility#232](https://github.com/jpd002/Play-Compatibility/issues/232)
> 
> Thanks!

So, when you add vulkan feature for android version? :(

**Comment by zerra2691-lang** [comment]
Bro how to find source code?
