### ISSUE TITLE
Link error with std::filesystem

### ISSUE THREAD

**Issue by KingDuckZ** [jpd002/Play-#871]
Building on Gentoo with gcc 8.3.0 I ran into linker errors about `make_directory` and other stuff from std::filesystem. I think this patch fixes the problem:

```patch
diff --git a/Source/CMakeLists.txt b/Source/CMakeLists.txt
index f3d9fcfc..2df5cccb 100644
--- a/Source/CMakeLists.txt
+++ b/Source/CMakeLists.txt
@@ -428,7 +428,7 @@ if(TARGET_PLATFORM_MACOS OR TARGET_PLATFORM_UNIX)
 endif()
 
 add_library(PlayCore STATIC ${COMMON_SRC_FILES} ${PLATFORM_SPECIFIC_SRC_FILES})
-target_link_libraries(PlayCore ${PROJECT_LIBS})
+target_link_libraries(PlayCore ${PROJECT_LIBS} stdc++fs)
 target_include_directories(PlayCore
        PUBLIC
                ${CMAKE_CURRENT_SOURCE_DIR}
```

I just attempted a simple build like this:

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j8

**Comment by Zer0xFF** [comment]
this is gcc specific library naming, so it wont work with other compiler, as is. I do think cmake has variable which can be used to specifiy this for gcc compiler only.
though I believe officially we're using gcc 9 to work around this instead?

**Comment by KingDuckZ** [comment]
Right, I'm not aware of a platform-independent way of linking to that, but worst case one could check if the compiler is gnu and conditionally link to that lib. Maybe I can look into it.

As for the compiler, I did try with gcc 9.2 and I got the same error. I'm 70% sure you just have to link to stdc++fs if you want to use std::filesystem, it's not a version-specific thing. Emerging 9.3.0 now but I don't think it will make any difference.

**Comment by Zer0xFF** [comment]
ummm... if you had to explicitly link against the library, the CI build wouldnt work, since its using 9.2 https://travis-ci.org/github/jpd002/Play-/jobs/662849987#L874

**Comment by KingDuckZ** [comment]
I just found this interesting statement [here](https://gitlab.kitware.com/cmake/cmake/issues/17834):

> Note libstdc++fs has been merged into libstdc++ in gcc9, but it still makes it a pain to support older versions of libstdc++ (<=8).

It's also reported in the [changelog](https://gcc.gnu.org/gcc-9/changes.html). I can confirm Play! compiles with gcc 9.3.0, and the previous failure with 9.2.0 was likely due to a local configuration problem on my system. Sorry about the flaky issue report! I think this can now be closed.

**Comment by jpd002** [comment]
Thanks for clearing that up!
