### ISSUE TITLE
Splinter Cell Demo lags on iPhone SE

### ISSUE THREAD

**Issue by BurlySaturn620** [jpd002/Play-#878]
The audio and the video of the game is too laggy and when i press Start button, it says "loading" and freezes the game. iPhone SE is a powerful device which i can play PUBG Mobile in high graphics settings and Play! app is too laggy to play game. Hope you can fix this issue and raise to final version of the emulator someday.

**Comment by jpd002** [comment]
Thanks for reporting. This is being discussed here: https://github.com/jpd002/Play-Compatibility/issues/187
