### ISSUE TITLE
Play libretro core crashes when built with gcc-8

### ISSUE THREAD

**Issue by kwyxz** [jpd002/Play-#891]
Using the libretro buildbot recipe to build the Play! libretro core:

`SINGLE_CORE=play NOCLEAN=0 FORCE=YES ./libretro-buildbot-recipe.sh recipes/linux/cores-linux-x64-generic` 

This builds fine and generates a working play_libretro.so with gcc-7 and g++-7 however the following happens with gcc-8 and g++-8 :

`retroarch: symbol lookup error: /usr/local/lib/libretro/play_libretro.so: undefined symbol: _ZNSt10filesystem7__cxx114path14_M_split_cmptsEv`

**Comment by Zer0xFF** [comment]
gcc-8 is an out lier... it reports filesystem support, but the library for it is listed separately,  aka it so doesn't automatically link, that was changed with gcc-9.

if you really want to use 8, you need to add the library to the cmake script.

**Comment by kwyxz** [comment]
Unfortunately gcc-8 is the default version of gcc in at least Debian stable :(

I tried adding this to CMakeLists.txt :
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lstdc++fs" )`
But it looks like it's not enough.

**Comment by Zer0xFF** [comment]
I'd try adding `stdc++fs` directly to the `target_link_libraries` `ui_libretro` cmake

**Comment by kwyxz** [comment]
Thanks, it helped. Since it could be useful to others I created a pull request, #894
