### ISSUE TITLE
McServ folders not properly jailed

### ISSUE THREAD

**Issue by kernle32dll** [jpd002/Play-#892]
Need for Speed Underground 2 starts the game right of the bat with an ChDir command of `../`. This allows is to write folders outside the memory card folder.

![Screenshot from 2020-04-30 00-32-41](https://user-images.githubusercontent.com/1338408/80653891-69459600-8a7b-11ea-8e49-f297043fb9fd.png)

This should not be the case ;-)

**Comment by jpd002** [comment]
Ouch, that's pretty bad indeed. :disappointed:

**Comment by kernle32dll** [comment]
Solved
