### ISSUE TITLE
Burnout 3 fails to hook LibMc2 functions

### ISSUE THREAD

**Issue by kernle32dll** [jpd002/Play-#899]
What the title says.

It trips [this assert](https://github.com/jpd002/Play-/blob/c950bf43d0d8528e3bbabcd75b11dc0aad055d3f/Source/ee/Ee_LibMc2.cpp#L188), as both `m_readFile2AsyncPtr` and `m_writeFile2AsyncPtr` above are 0 (aka, they failed to be recognized in `AnalyzeFunction`). 

Something about `m_checkAsyncPtr` seems off, too, as it segfaults on each `reinterpret_cast` [here](https://github.com/jpd002/Play-/blob/c950bf43d0d8528e3bbabcd75b11dc0aad055d3f/Source/ee/Ee_LibMc2.cpp#L191) (the address is obviously not 0).

**Comment by jpd002** [comment]
Hi!

I'll change the assert for a warning, ReadFile2Async and WriteFile2Async are optional functions.

Could the segfault be happening because the RAM memory page is protected by `EeExecutor`? If so, it's harmless, but there's nothing that can be done to avoid it (the signal will be caught by the emulator and handled properly).

**Comment by kernle32dll** [comment]
> I'll change the assert for a warning, ReadFile2Async and WriteFile2Async are optional functions.
I don't think a warning is the right choice then - maybe just don't calling `WriteSyscall`, if the address for `m_readFile2AsyncPtr` and `m_writeFile2AsyncPtr` being zero respectively?

> Could the segfault be happening because the RAM memory page is protected by `EeExecutor`? If so, it's harmless, but there's nothing that can be done to avoid it (the signal will be caught by the emulator and handled properly).

Good question. It only happens for `m_checkAsyncPtr`. Shouldn't that happen for all calls of `WriteSyscall` then?

**Comment by jpd002** [comment]
Maybe `CheckAsync` happens to be within the same page boundary (I don't remember how large it is on Linux) as code that's been compiled before while the other functions are not.

**Comment by jpd002** [comment]
There were a few problems with memory cards in Burnout, but it should be fixed now (saving and loading works).
