### ISSUE TITLE
Libretro port

### ISSUE THREAD

**Issue by Hydro5** [jpd002/Play-#9]
Unlike other PS2 emulators, Play! is much more portable. Have you thought about a port to Libretro? It would give much more attention to the project, and would allow it to be ported to a wide variety of platforms. 

libretro.com

**Comment by ppssppios** [comment]
I'm not a developer, but if i can help in any way, please let me know

**Comment by vgturtle127** [comment]
You can help by testing games and reporting any bugs or issues. You can also request features, but not everything is emulated so that should be somewhat on the back burner. :smile:

**Comment by ppssppios** [comment]
I would love to test, but is there any build for android?

**Comment by vgturtle127** [comment]
No. Test it for WIndows or Linux. Once the emulation is there, we can think about porting it to other platforms. At least that is what I would do. I never release an emulator for mobile/embedded devices or game consoles until I test and make sure everything works on a computer.

**Comment by Fadi5555** [comment]
When we can see iOS port of this project?
iOS support libretro core through Retroarch
Please do your best for iOS port of it.

You can't imagine how we exciting about this project.

**Comment by vgturtle127** [comment]
Ugh...iOS.

That will take a while, iOS is really hard to develop open-source applications for emulators of complex systems on it, since jailbreaking is required and you have to have access to all of the complicated custom hardware. It is a real chore. But if somebody can do it, it will be there eventually. Like I said before though, testing and development of the Linux/Windows port should be focused on first probably.

**Comment by Fadi5555** [comment]
Thanks bro for replay.

Me and thousands of people who have iOS devices are more exciting about this project so much.
It doesn't matter if your work need jailbreak. The important thing is to continue and never give up to make iOS port of this amazing project.
Keep your doing up.

**Comment by twinaphex** [comment]
>  since jailbreaking is required and you have to have access to all of the complicated custom hardware.

You don't really know what you're talking about. There is no 'custom hardware' involved for jailbreaking other than your USB cable and a Mac.

**Comment by vgturtle127** [comment]
I was talking about the custom hardware inside iOS devices.

**Comment by Fadi5555** [comment]
Mr vgturtle 127
Can you tell us about custom hardware inside iOS devices please.
Because I really exciting about it.

Also when we can see in the menu (iOS port) as android and MacOS and windows as well.
As I told you my bro. Please please please do your best to make iOS port of this project
You know we don't even have dolphin emu until now.
We really want our devices see the light of this one.
I hope you'll get a good progress about it.
We believe and count on you.

Keep your doing up.

**Comment by Embrendassy** [comment]
I'm certainly no pro on this matter, but I'm pretty sure that the custom features would be the system-on-a-chip design that houses the device's CPU/memory/GPU/etc. Apple's newest iPhone 6 features a 64-bit-capable CPU that implements ARM machine code. By that definition, it's simply an "ARM" processor (like Android phones) with an intricate micro-design (the bare bones of how the CPU works with machine code) of its own that's unique (Cyclone latest). I think the device's have image sensors as well (mostly or only useful for photos), but aside from that I don't think there's much else custom about it (hardware wise at least). The fact that it uses 64-bit and the new micro-design is much more efficient (supposedly) with the CPU capable of peaking 2 GHz clock speeds or higher says that Apple has stepped up their game a bit. I'd say that the latest devices are soon-to-be closing in on being capable of handling optimized PS2/GC ports near perfectly for at least the low-to-mid demanding titles. I have a repo of some preliminary work I'm considering for a PS2 emulator (open-source, using parts of PCSX2, and my own implementations I'll soon upload). I am going to leave room for a dynarec for ARM for Android/iOS test versions eventually, but it may take years to get everything "well enough" to even consider commercial games (few) to work on these devices.

**Comment by vgturtle127** [comment]
Yeah, what he said.

I'm not positive about this, but I remember something about dynamic recompilers having trouble on iOS devices. Something to do with software limitations setup by Apple? Just something I heard.

Regardless, it is possible. And will most definitely happen at some point. When is the real question.

**Comment by Fadi5555** [comment]
Thank you Embrendassy so much about all what are you said about it to make it clear for us.
I think you have many knowledge about it. You can make a good progress about iOS port.
You said you have a repo? Can you give me?
It's my pleasureto be a tester and give you report of issues.
I have newest Apple device. (iPad Air 2) with A8X Chip and 2 GB ram. Also Ppsspp runs pretty good on it. I think if someone make a port of dolphin emu it'll run faster than newest android devices.

another thing: can you make a port of (Play! Ps2 emu) on Ps Vita? Even when get native hack?
Thank you for your all your hard work.

**Comment by Oggom** [comment]
The PlayStation Vita is way too underpowered to handle something like PS2 emulation.

**Comment by vgturtle127** [comment]
I hope your joking, it plays PS2 classics. LOL

**Comment by Fadi5555** [comment]
Yeah I agree with you Vgturtle.
I think vita is powerful device.
Also I think it could handle ps2 games.Specially If Sony makes ps2 Classic games playable on vita.

Vita a good for handling ps2 games. So if you can see there is many ports of ps2 games on vita
For example: final fantasy x/x2. Metal gear solid 2/3 collection. sly copper collection. jak and dexter collection. and so many of ps2 games. So vita may could run ps2 games if has a good develop to optimize it and improve it. Or maybe sony will support ps2 Classic on vita on the future. No one knows?

**Comment by Qard** [comment]
There's a huge difference between ports and emulation.

While I think Vita is technically capable of it, it's very borderline. It'd take some serious optimization effort.

**Comment by vgturtle127** [comment]
I have a feeling since most of the PS2 classics and HD collections are basically just copies of the game you could probably do it, but like Qard said it might take some work. And by "some work" I mean you might have to spend months optimizing it. :smile:

**Comment by zxcvbad** [comment]
I wonder what would be requirements in terms of openGL/ES features if it Play gets ported to Android (I would start from Android if to think going mobile and as standalone project free + $5 donate version like the dolphin and ppsspp). This year is going to be exciting with things like X1, GLES Next, Cortex A72, 14nm etc, announcements just about to happen on MWC

**Comment by vgturtle127** [comment]
For PS2, not that much as far as I can estimate. Especially with as much desktop-grade stuff coming up in the next few months, we should be able to get something running soon. Everything I said before still stands though.

**Comment by NelsonRosenberg** [comment]
Reviving an old issue but it seems the discussion diverged from the topic a bit. 

So, is a port to libretro still on the table?

Thank you.

**Comment by mcronce** [comment]
Hey, just chiming in to see if this still looks like a thing that's happening ;)

**Comment by ProfessorKaos64** [comment]
Please do not necro-bump threads..

**Comment by mcronce** [comment]
It's not really a thread, it's an issue ticket.  What do you recommend, filing a new ticket for the same thing?

**Comment by jason-oliveira** [comment]
looking to see if there was any update to this issue.

**Comment by legluondunet** [comment]
It will be great!

**Comment by ptkato** [comment]
Any news on this port?

**Comment by ilovelinux** [comment]
https://www.libretro.com/index.php/category/play/
