### ISSUE TITLE
##SOME ISSUES PIC##

### ISSUE THREAD

**Issue by faroukabd000** [jpd002/Play-#901]
VERSION : 04 May 2020 64BIT
IF I CAN RUN THE DVD GAMES!!!! AM GONNA POST MORE ISSUES IF THEY ARE PRESENT.
![breath of fire](https://user-images.githubusercontent.com/64847752/81485324-81bc6a00-924c-11ea-95d6-83df454fb757.PNG)
![SLUS_208 93;1_09-05-2020_00 18 21 485](https://user-images.githubusercontent.com/64847752/81485332-926ce000-924c-11ea-9d18-8b9b3b0aea28.PNG)
![SLUS_208 93;1_09-05-2020_00 17 49 905](https://user-images.githubusercontent.com/64847752/81485336-9567d080-924c-11ea-9572-3bcd838b85a8.PNG)
![SLES_556 05;1_09-05-2020_00 09 31 666](https://user-images.githubusercontent.com/64847752/81485340-98fb5780-924c-11ea-9a17-1f34b8b36e81.PNG)
![fffff](https://user-images.githubusercontent.com/64847752/81485344-9bf64800-924c-11ea-9152-49cf81477e93.PNG)

**Comment by faroukabd000** [comment]
SYSTEM.CNF AS YOU CAN SEE IS NOT DETECTED I DONT KNOW WHY!!!!!!

**Comment by faroukabd000** [comment]
I creat new telegram group if someone want to join please @jpd002  join the group as admin

https://t.me/joinchat/QQ8ysBw3VN57dVFDVPVJNQ

**Comment by ilovelinux** [comment]
Hi @faroukabd000,
this repository is intended only for software issues - not for compatibility issues.

- Breath of Fire V: Dragon Quarter issue has already been reported here: https://github.com/jpd002/Play-Compatibility/issues/879
- Way Of The Samurai seems working: https://github.com/jpd002/Play-Compatibility/issues/355 try to run it with a clean Play! installation.
- Naruto Shippuden: Ultimate Ninja 5 seems working too: https://github.com/jpd002/Play-Compatibility/issues/309

No Detective Conan's compatibility issue has been reported yet. If you want, you can open a issue on https://github.com/jpd002/Play-Compatibility/ following the instructions on README.md, it would be very useful for devs!

Also please, use proper title for issues and don't write with CAPS.
