### ISSUE TITLE
Altered beast

### ISSUE THREAD

**Issue by Nokki97** [jpd002/Play-#904]
The game goes at 15 fps

**Comment by faroukabd000** [comment]
Depending on the device power of course

**Comment by Nokki97** [comment]
It is an ipad 2017 is possibile to play with this maybe in future?

Inviato da iPhone

**Comment by faroukabd000** [comment]
Yes maybe
Depending on the emulator updates  too👍

**Comment by Nokki97** [comment]
Thanks for all I hope an emulator’s update as soon as possibile

Inviato da iPhone
