### ISSUE TITLE
Shadow of the colossus slow

### ISSUE THREAD

**Issue by grandmasterlevi** [jpd002/Play-#912]
Graphics are glitchy and game is running slow on iPhone XR.
![7CD17763-D5FC-4C62-AFB3-F0F10E3CB325](https://user-images.githubusercontent.com/66197579/83382200-6ea64100-a397-11ea-88f2-25d5a847cf03.png)

**Comment by jpd002** [comment]
Graphics are a bit better now on mobile. Don't think speed has improved a lot though, that's an ongoing challenge, not worth an issue.
