### ISSUE TITLE
Unsupported Vulkan Extension in 750Ti

### ISSUE THREAD

**Issue by AkagiShiroe** [jpd002/Play-#913]
![image](https://user-images.githubusercontent.com/14356240/83712848-43527900-a659-11ea-98dd-48692acc13e2.png)

**Comment by jpd002** [comment]
Hello!

Unfortunately, the Vulkan GS handler requires VK_EXT_fragment_shader_interlock to work.

Here's the list of GPUs that support it:
https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_EXT_fragment_shader_interlock&platform=windows

I'm not planning to add support for Vulkan without that extension on desktop platforms ATM. Maybe on mobile at some point using framebuffer storage.

**Comment by AkagiShiroe** [comment]
so, no plan for supporting Vulkan 1.0 devices? i see.. since only NVIDIA 9XX or newer lineup and AMD 5XXX XT(Navi) support Vulkan 1.1 at this moments.
(some older GCN GPU Support some extension but not full list of 1.1)

**Comment by boberto5888** [comment]
Shader interlock lets the blending and alpha testing stuff 'just work'.
If jpd added support for GPUs without shader interlock the user experience/compatibility probably wouldn't be all too different from the OpenGL renderer.

And it'd be a ton of extra work for jpd.

**Comment by AkagiShiroe** [comment]
yeah i am not complaining about it, just clarifying(verifying).. its good there's another PS2 emulator and it was an HLE going in progress, lets not bump this closed thread anymore.
