### ISSUE TITLE
VIF DIRECT Crash in Tennis no Oji Sama Smash Hit 2

### ISSUE THREAD

**Issue by mini536** [jpd002/Play-#921]
I can't use play! for android launch Tennis no Oji Sama Smash Hit 2(SLPM-65454),it crashed with no information.

**Comment by jpd002** [comment]
Tentative fix here: https://github.com/jpd002/Play-/tree/vif_direct_partial. Will be merged soon.

**Comment by jpd002** [comment]
Changes have been merged. This is now fixed.
