### ISSUE TITLE
iOS Crash

### ISSUE THREAD

**Issue by jimmersrandom** [jpd002/Play-#922]
crashing on iPad Pro, the first launch after installing opens fine, but after closing it from task manager and reopening the app it is just a black screen and crashes my iPad Pro if it locks up.

also dont know if it is just the roms but when i try and play a rom it is just a black screen too.

hope this can be fixed

many thanks

**Comment by jpd002** [comment]
Hey there!

I've made a few changes to the way ptrace is used to simulate a debugger (and let JITed code run on a non-jailbroken device), should help with the app hanging when closing it from the task manager: https://github.com/jpd002/Play-/commit/80bfc0a09951da497a2101ff45fde94a4a312e46. I'll merge that soon.

Which games are you trying to play?
