### ISSUE TITLE
GCC 10 build error for the libretro core

### ISSUE THREAD

**Issue by alucryd** [jpd002/Play-#923]
Hi there, building the libretro core currently fails with GCC 10: https://buildbot.alucryd.xyz/#/builders/287/builds/51/steps/7/logs/stdio

**Comment by jpd002** [comment]
Hello!

Looking at the logs, seems the Framework's commit that's being checked out is https://github.com/jpd002/Play--Framework/commit/77caebd7a980ed60b9a44067268b285cc083a242.

There's some new ones (https://github.com/jpd002/Play--Framework/commits/master) that fixed building on GCC10. I dunno who maintains the repo which has the submodule link to Framework, but I guess updating this will fix the issue.

Thanks!

**Comment by alucryd** [comment]
It was an old commit indeed, my apologies :( Thank you very much!
