### ISSUE TITLE
Selected vulkan graphics card reset after selection on ubuntu 20.04

### ISSUE THREAD

**Issue by LittleStinky123** [jpd002/Play-#927]
When I run from the app image, select my nvidia graphics card and press on close, the intel iGPU is selected upon reopening the graphics settings.
Prime-select is set to nvidia.
At the same time the vendor- and device-id in the config.xml are of the nvidia card though, so it's maybe just not loading the saved value from the config file.

**Comment by jpd002** [comment]
Whoops, little something I forgot in the UI code. Fix in here: https://github.com/jpd002/Play-/tree/vulkan_device_setting_fix (will merge soon).

**Comment by jpd002** [comment]
Merged in master. Thanks for reporting this!
