### ISSUE TITLE
Libretro port crash on Linux when connected with dual display

### ISSUE THREAD

**Issue by guoyunhe** [jpd002/Play-#930]
Condition:
1. Linux
2. X display server
3. Dual screen setup, left is 1080p, right is 4k.

Run retroarch in terminal and use Play! core to open a PS2 game ISO. It crashed with:

```
$ retroarch
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  26 (X_GLXMakeContextCurrent)
  Serial number of failed request:  71
  Current serial number in output stream:  71
```

**Comment by gouchi** [comment]
@guoyunhe Is it still an issue  with latest RA stable ?

Thank you.

**Comment by guoyunhe** [comment]
@gouchi i cannot reproduce because Play! core is not available for download anymore. Other cores works fine.

**Comment by gouchi** [comment]
It is available on the Core Update for Linux [x86_64](https://buildbot.libretro.com/nightly/linux/x86_64/latest/play_libretro.so.zip) and [x86](https://buildbot.libretro.com/nightly/linux/x86/latest/play_libretro.so.zip).
