### ISSUE TITLE
Play rule of rose(cn) screen filker in Oneplus 8

### ISSUE THREAD

**Issue by fuckeditcs2d** [jpd002/Play-#931]
animation screen filker
After the opening animation is over,no menu and black screen only
Device: Oneplus 8
Android 10

**Comment by jpd002** [comment]
Thanks for reporting.

Probably requires the Vulkan GS handler to work properly (which is not supported on Mobile ATM).

Reports:
https://github.com/jpd002/Play-Compatibility/issues/120
https://github.com/jpd002/Play-Compatibility/issues/248
