### ISSUE TITLE
Harvest Moon Save The Homeland Bug

### ISSUE THREAD

**Issue by ericsona02** [jpd002/Play-#934]
![Screenshot_2020-08-18-21-59-57-787_com facebook lite](https://user-images.githubusercontent.com/69852530/90522573-75767000-e19e-11ea-9a80-b3733a2d45d5.jpg)
Bug The Games

**Comment by jpd002** [comment]
Already reported here: https://github.com/jpd002/Play-Compatibility/issues/209.
