### ISSUE TITLE
Bujiangi: The forsaken City (Black Render Bug or something)

### ISSUE THREAD

**Issue by Tayoikoo** [jpd002/Play-#936]
Here's Black Render bug

![Screenshot_20200819_053430](https://user-images.githubusercontent.com/67594827/90576960-c8c1e000-e1e9-11ea-85b0-c17d22c5156a.jpg)
![Screenshot_20200819_053533](https://user-images.githubusercontent.com/67594827/90576978-d4150b80-e1e9-11ea-8551-4addbfa37506.jpg)
![Screenshot_20200819_052742](https://user-images.githubusercontent.com/67594827/90577008-e2632780-e1e9-11ea-8c67-3d26c48cf065.jpg)

Something:
Object missing when come closer (i forgot to capture this)

**Comment by jpd002** [comment]
This only render mostly good on Vulkan (which is not supported on mobile ATM).

Closing this because there's already a report: https://github.com/jpd002/Play-Compatibility/issues/1168
