### ISSUE TITLE
Mortal Kombat Shaolin Monks Bug Graphic

### ISSUE THREAD

**Issue by ericsona02** [jpd002/Play-#938]
![FB_IMG_15978002415923152](https://user-images.githubusercontent.com/69852530/90584105-662a0d80-e204-11ea-9770-860ba44f5458.jpg)
Bug And Slow

**Comment by jpd002** [comment]
Already reported here: https://github.com/jpd002/Play-Compatibility/issues/758.

Please post game compatibility reports in the tracker (https://github.com/jpd002/Play-Compatibility) and do not create new issues for already existing games.

And most importantly, do not create new issues for the same things over and over again. Posting in that manner again will result in being blocked.

**Comment by ericsona02** [comment]
Thans I Love You
The Best
