### ISSUE TITLE
Macos can't startup

### ISSUE THREAD

**Issue by SolaWing** [jpd002/Play-#940]
crash because -[NSOpenGLContext setView:] must be called from the main thread.

**Comment by jpd002** [comment]
Hey! 

I think this comes from when you run a binary that was compiled using macOS SDK 10.15 (Catalina) / Xcode 11. The binaries that are auto generated from Travis are built against macOS SDK 10.14 / Xcode 10. So, my question is, where did you get the emulator binaries from?

Thanks!

**Comment by SolaWing** [comment]
@jpd002 I compile it according to the document. it’s indeed macos 15 and xcode 11.6.

where can I get the prebuilt binary?

**Comment by jpd002** [comment]
You can get the latest binaries here: https://purei.org/downloads.php.

**Comment by jpd002** [comment]
Should work fine now. Also added signing and notarization to allow installation of builds coming from Travis (otherwise, we would end up with a damaged app that macOS wouldn't start).
