### ISSUE TITLE
5.4.59-v7l+ #1337 Can't overclock over 2000mhz anymore

### ISSUE THREAD

**Issue by myzar** [jpd002/Play-#943]
I've upgraded to this kernel hoping to fix my m2 ssd disconnecting randomly introduced in latest stable kernel released few days ago. That is fixed but with this kernel i can't overclock over 2000mhz , anything above that is refused and the cpu is stuck at 600169920 relevant logs:

[    1.134005] cpufreq: cpufreq_online: CPU0: Running at unlisted freq: 2100000 KHz
[    1.134076] cpufreq: cpufreq_online: CPU0: Unlisted initial frequency changed to: 2294967 KHz

[    1.124136] cpufreq: cpufreq_online: CPU0: Running at unlisted freq: 2147000 KHz
[    1.124206] cpufreq: cpufreq_online: CPU0: Unlisted initial frequency changed to: 2294967 KHz

pi@retropie:/sys/devices/system/cpu/cpu0/cpufreq $ uname -a
Linux retropie 5.4.59-v7l+ #1337 SMP Wed Aug 26 11:03:21 BST 2020 armv7l GNU/Linux

pi@retropie:/sys/devices/system/cpu/cpu0/cpufreq $ cat ./scaling_available_frequencies
2294967
pi@retropie:/sys/devices/system/cpu/cpu0/cpufreq $ cat ./cpuinfo_max_freq
2294967

pi@retropie:/sys/devices/system/cpu/cpu0/cpufreq $ cat ./scaling_max_freq
2294967
pi@retropie:/sys/devices/system/cpu/cpu0/cpufreq $ cat ./scaling_available_governors
conservative ondemand userspace powersave performance schedutil
pi@retropie:/sys/devices/system/cpu/cpu0/cpufreq $ cat ./scaling_governor
performance
pi@retropie:/sys/devices/system/cpu/cpu0/cpufreq $ vcgencmd measure_clock arm
frequency(48)=600169920

**Comment by jpd002** [comment]
Humm, did you post this on the wrong repo?
