### ISSUE TITLE
Flickering due to Field bobbing? Play! build from Aug28 on MacOS

### ISSUE THREAD

**Issue by mrjschulte** [jpd002/Play-#944]
Hi,
Noticing quite a bit of flicker, most likely due to field "bobbing", when using Play! at 2x with the "Fill Screen" option. Would you be open to considering implementing a field de-interlacing algorithm or simple CRT shader to help mitigate this visual artifact when viewing 480i games on a progressive display ? Or is this Issue limited to the macOS build only?

**Comment by jpd002** [comment]
Hey!

It's an issue with many games and it occurs on all platforms. There's a discussion here: https://github.com/jpd002/Play-/pull/752.
