### ISSUE TITLE
Request: Easy way to make the Play! OS window 1x, 2x, 3x, bigger on macOS/Windows/Linux?

### ISSUE THREAD

**Issue by mrjschulte** [jpd002/Play-#945]
Hi,

Wonder if there were any plans to add an additional but simple 1x, 2x, 3x, etc integer scaling mode, under Video -> Presentation mode, to Play! for Operating systems that use a Free floating window like macOS/Windows/Linux?

**Comment by jpd002** [comment]
Hey!

Just to be sure, you mean like having an option to make the size of the window 1x/2x/3x the native resolution?

**Comment by mrjschulte** [comment]
Yes. That is it.

**Comment by mrjschulte** [comment]
Where would this ideally take place? Perhaps I can take a look at the code and hack in a proposal.

**Comment by jpd002** [comment]
I think it would ideally be something that's placed in the `Virtual Machine` menu, under the `Capture Screen`. A menu item called `Window Size` with sub menu items that has the different multipliers (ex.: 640x448 (x1), 1280x896 (x2), etc.)

**Comment by mrjschulte** [comment]
Yeah. That could work.

**Comment by mrjschulte** [comment]
Hi, wanted to see if there was any news around this? Anything I can do to help?

**Comment by jpd002** [comment]
Hi! It's been added in https://github.com/jpd002/Play-/commit/288e4e86efda4e521e90d5b55bee2b2a69d75f87. Lemme know if you have feedback about that feature!
