### ISSUE TITLE
Android 10 Force Close Launch Apk 

### ISSUE THREAD

**Issue by Ihsan02** [jpd002/Play-#946]
https://www.facebook.com/groups/625876318330330/permalink/655651058686189/?app=fbl

**Comment by Ihsan02** [comment]
![Screenshot_2020-09-02-09-41-23-719_com facebook lite](https://user-images.githubusercontent.com/70615146/91922427-97c0cf80-ed00-11ea-8ecb-059f29343fc1.jpg)

**Comment by jpd002** [comment]
Out of curiosity? Are you using a Motorola Moto G7?

**Comment by Ihsan02** [comment]
Yes

**Comment by jpd002** [comment]
I've created a build that does additional logging:
https://playbuilds.s3.us-east-2.amazonaws.com/6fd34222/Play-release.apk

Could you install it on your phone and capture the logcat (using this command: `adb logcat Play!:V *:S`)?

Thanks!

**Comment by Ihsan02** [comment]
Thanks 
The Best For You Developer 
And Support 100% Really

**Comment by jpd002** [comment]
I tested it myself on an Android 10 device and reproed the crash. Fix is here 29c5ca7a2a1d2a9dea5164aa6e49016711cc0ed4.

Pushed it on Google Play if that's where you're getting the app from. Should be available soon.
