### ISSUE TITLE
Play! Android - Fatal Frame 1 Fix Crash & Camera Auto Focus Works Fine

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#947]
#ss #play_emulator # ps2 #android # sd845
Update 03 September 2020
Great! Fatal Frame 1 Fix Crash! And the camera auto focus works fine. With this play! back has an advantage over d*m*nps2. Because if you play on D*m*nPS2 there is a problem with the camera's auto focus. I am more and more sure that someday I will play! can beat damonps2 completely!
Ooyeeee ooyeeeee
One day it will definitely glow.

Play !: Not fantasy that I give, but real belief.
Damonps2: It's not real belief that I give, but delusion.
![Screenshot_20200904-142311590](https://user-images.githubusercontent.com/55049420/92227653-c68da000-eed0-11ea-9fd8-5b75356f8774.jpg)
![Screenshot_20200904-142329117](https://user-images.githubusercontent.com/55049420/92227685-d2796200-eed0-11ea-9450-16c841a7780a.jpg)
![Screenshot_20200904-110040406](https://user-images.githubusercontent.com/55049420/92227710-dc9b6080-eed0-11ea-8021-af7cc8b3eae2.jpg)
![Screenshot_20200904-110055760](https://user-images.githubusercontent.com/55049420/92227725-e3c26e80-eed0-11ea-8b38-94b39a68933c.jpg)
![Screenshot_20200904-142635423](https://user-images.githubusercontent.com/55049420/92227749-ea50e600-eed0-11ea-9ff7-0b5114d444fc.jpg)

**Comment by Ihsan02** [comment]
Wow

**Comment by jpd002** [comment]
Nice! :) Thanks for reporting!
