### ISSUE TITLE
Tested Device OS Nougat 7.1.2

### ISSUE THREAD

**Issue by Ihsan02** [jpd002/Play-#949]
![IMG_20200908_071344](https://user-images.githubusercontent.com/70615146/92419907-de03ac00-f1a2-11ea-8890-17625d233ca5.jpg)
OS Nougat Bug All Games And Me Try Upgrade OS Oreo 8.1 Not Bug

**Comment by jpd002** [comment]
Which device are you testing on?

**Comment by Ihsan02** [comment]
Device Xiomi Redmi Note 5A Tested

**Comment by Ihsan02** [comment]
Snapdragon 425
