### ISSUE TITLE
OS Nougat 7.1.2 Bug All Games Tested 

### ISSUE THREAD

**Issue by Ihsan02** [jpd002/Play-#952]
Just right I try Upgrade OS Oreo 8.1 Me Try No Bug The same Once

**Comment by Ihsan02** [comment]
Device Xiomi Redmi Note 5A Tested

**Comment by vimal199** [comment]
How much approximate time it will take to fully develop this emulator on android??

**Comment by Margen67** [comment]
![image](https://user-images.githubusercontent.com/3462541/93139158-128cd180-f695-11ea-9bda-42c1948bfe90.png)

**Comment by jpd002** [comment]
Not much I can do about this. The emulator works on all my Android devices. If you can provide some logs or if you can debug it in Android Studio (or other), I can probably help.

@vimal199  A very long time.

**Comment by Ihsan02** [comment]
Ok

**Comment by Gomoboom** [comment]
O emulador está funcionando no meu celular, porem os jogos não são jogáveis. Queria que você otimiza-se o resident evil 4 para o emulador 🙃

**Comment by Gomoboom** [comment]
The emulator is working on my phone, but the games are poorly optimized. I really wanted to play Resident evil 4 on ps2🙃🙃
