### ISSUE TITLE
BGDA cellar too bright.

### ISSUE THREAD

**Issue by bigianb** [jpd002/Play-#953]
Baldur's gate dark alliance. Open GL
Heading down to the first cellar, everything is too bright.

This pic from the Sept 14th auto build.

![SLES_506 72;1_14-09-2020_15 37 36 177](https://user-images.githubusercontent.com/2781371/93101427-2d197780-f6a2-11ea-8bcb-cca34adf58c1.png)

**Comment by jpd002** [comment]
Was the lighting correct before on OpenGL (like in March 2020)? I know some things changes in the blending formulas recently, I wonder if that might have broken the game.

**Comment by bigianb** [comment]
I don't really remember. It used to be slow enough that I never really got past the tavern when testing. Now it's getting quick enough to test a bit more. It's odd because I think the tavern and the town cut scenes are ok.

**Comment by bigianb** [comment]
Blend mode 2000 was not implemented.
https://github.com/jpd002/Play-/pull/975 fixes it.

**Comment by jpd002** [comment]
Fix merged in master.
