### ISSUE TITLE
Clock Tower 3 Fix Crash

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#961]
Date: 2020/09/22
![118535952_1153528795031055_4026219431825315992_o](https://user-images.githubusercontent.com/55049420/94098250-6eecaf80-fe52-11ea-9815-ba0d57733e3f.jpg)
![118768761_1154188411631760_8270263189207276161_o](https://user-images.githubusercontent.com/55049420/94098260-7449fa00-fe52-11ea-9987-76f4a944ff29.jpg)

**Comment by literalmente-game** [comment]
Could you please stop with this spam? If you want to report anything game specific, use the compatibility tracker (and only if it's new or valid information). Compatibility tracker link: https://github.com/jpd002/Play-Compatibility/issues

**Comment by ericsonia** [comment]
> Could you please stop with this spam? If you want to report anything game specific, use the compatibility tracker (and only if it's new or valid information). Compatibility tracker link: https://github.com/jpd002/Play-Compatibility/issues

I'm already do that. But you always delete my post on compatibility.

**Comment by literalmente-game** [comment]
If any report you've made was deleted, it's because it was invalid in some way (not enough information usually). It's not that hard, simply open any of the other valid issues on the tracker and provide the same amount of information you see there. You're not helping anyone by doing this spam and this issue will also be closed as well

**Comment by ericsonia** [comment]
> If any report you've made was deleted, it's because it was invalid in some way (not enough information usually). It's not that hard, simply open any of the other valid issues on the tracker and provide the same amount of information you see there. You're not helping anyone by doing this spam and this issue will also be closed as well

But i always give new infomation. Example: Armymen Soldiers Of Misfortune. This game not availabe on your compability list. But your delete my post.

**Comment by ericsonia** [comment]
Edit: not delete, but you close my post.

**Comment by literalmente-game** [comment]
No, you've gave us a lie. The report said "playable" to something you can barely even understand on the screen (menus aren't readable/visible so you can't change setting or load your progress, and in-game it's even worse). We don't need this kind of report, please, this is the last time I'm talking to you about it.

**Comment by ericsonia** [comment]
> No, you've gave us a lie. The report said "playable" to something you can barely even understand on the screen (menus aren't readable/visible so you can't change setting or load your progress, and in-game it's even worse). We don't need this kind of report, please, this is the last time I'm talking to you about it.

I'm already say this
![Screenshot_20200924-110237059_1](https://user-images.githubusercontent.com/55049420/94099693-c17b9b00-fe55-11ea-8b70-7c46b9af9adf.jpg)

**Comment by ericsonia** [comment]
Sorry. I must edit playable to in game right?
