### ISSUE TITLE
Resident Evil Dead Aim Running on Play! old build better than latest build

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#962]
Build Date: 2019/12/10
![Screenshot_20200924-102253015](https://user-images.githubusercontent.com/55049420/94098942-eb33c280-fe53-11ea-8395-e3461095f9cf.jpg)
Build Date: 2020/09/22
![Screenshot_20200924-102533673](https://user-images.githubusercontent.com/55049420/94099008-1b7b6100-fe54-11ea-86b7-5a76d49764ac.jpg)

**Comment by Gomoboom** [comment]
I think he is still optimizing the games. Let's trust that in the future the games will be optimized.

**Comment by jpd002** [comment]
This (https://github.com/jpd002/Play-/commit/c1c2cef8b46278149c5aba3681946d2fc426a69e) fixes it. Should be in next release.

![image](https://user-images.githubusercontent.com/6760433/94313835-717fff80-ff4d-11ea-9010-1eb192719585.png)

**Comment by vimal199** [comment]
Approximately In what time games will be fully playable on android???

**Comment by Gomoboom** [comment]
when support for control in play! for Android?

**Comment by Gomoboom** [comment]
The good thing is also to put control support in the play emulator! Android.

**Comment by jpd002** [comment]
It's been merged in master.

**Comment by ericsonia** [comment]
Amazing! You are the best @jpd002  !!! 😘
![Screenshot_20200928-220715408](https://user-images.githubusercontent.com/55049420/94505174-ab465400-0234-11eb-974d-c2ebe93ca937.jpg)
![Screenshot_20200928-221341810](https://user-images.githubusercontent.com/55049420/94505189-b4cfbc00-0234-11eb-84f8-f3501153d7a3.jpg)
![Screenshot_20200928-221702640](https://user-images.githubusercontent.com/55049420/94505195-b9947000-0234-11eb-8bdc-9d2c7f64689d.jpg)
![Screenshot_20200928-221753572](https://user-images.githubusercontent.com/55049420/94505206-bef1ba80-0234-11eb-9ed9-faacff98fc33.jpg)

**Comment by Gomoboom** [comment]
Como você conseguiu?
