### ISSUE TITLE
Very Good Graphic

### ISSUE THREAD

**Issue by ihsanAndrew** [jpd002/Play-#966]
![FB_IMG_16017693415741910](https://user-images.githubusercontent.com/68217552/95003932-55e4bb00-0617-11eb-8f0f-cd8651de448d.jpg)
![FB_IMG_16017693486516756](https://user-images.githubusercontent.com/68217552/95003933-5b420580-0617-11eb-8cfc-4448863a97eb.jpg)
You Is The Best

**Comment by ihsanAndrew** [comment]
Very Cool Graphic

**Comment by Gomoboom** [comment]
is playing on android

**Comment by Gomoboom** [comment]
How did you do it

**Comment by Gomoboom** [comment]
😳😳😳😳
