### ISSUE TITLE
PCSX2 code

### ISSUE THREAD

**Issue by yuraPIMENOV** [jpd002/Play-#967]
Hi Jean-Philip, why are you wasting so many years on this emulator? Some Chinese developers forked PCSX2's code to create a commercial emulator named Damon. Couldn't you use PCSX2's code with Play emulator? The whole world waits for a good PS2 emulator for mobile platforms.

**Comment by tiagomouradjesus** [comment]
Yes. Man, we need a good emulator for Android, play is always updating twice a month, some games have almost 0% graphics errors, but they are not playable at all. Really wanted see a PS2 emulator like Play! for Android ... But I still trust the play project 😃

**Comment by jpd002** [comment]
My goal is not to port PCSX2 to mobile. I want to build something different, it’ll take the time it has to take.

**Comment by tiagomouradjesus** [comment]
I totally agree, doing something unique is perfect. It may take as long as it takes and I will be here to accompany the Play! The best Playstation 2 emulator for Android 🥳🥳🥳🌟🌟🌟✨
