### ISSUE TITLE
Galaxy Tab Pro 8.4 - Black Screen

### ISSUE THREAD

**Issue by hyakki-** [jpd002/Play-#97]
Tried several games and even though I see F/S and dc/f moving (currenlt 4 /fs 127 dc/f) 
I am getting no graphics, I tested known compatible games like ff10, ff10-2 , FF12 , my images are in iso format and are good since they work in pcsx2..

So I don't know if its an issue with my device or what, it has a snapdragon 800 / adreno 330 gpu

I even tried GLTools to emulate other card but to no avail.

**Comment by zminhquanz** [comment]
The Emulator is alpha test , and not Compatibility on all Android device because there a lot of processor from ARM and Intel x86

**Comment by hyakki-** [comment]
yeah I know, let me know if you need any info to get it better supported (or does the emulator only support x86?)

The Adreno 330 should support OPENGL ES 3 
https://en.wikipedia.org/wiki/Adreno

**Comment by maximu** [comment]
adreno 300 support Opengl 3.0  but has bug drivers In many emulators that require OpenGL ES 3.0 is a headache for these devices.

But anyway I Working with Adreno 305 with v84 driver on android 5.0 lolipop maybe you driver outdate version???

**Comment by hyakki-** [comment]
I am using stock firmware from Samsung, 4.4.2, I expect them the release lollipop soon though and hopefully it will fix any Adreno bugs,.

Maybe i'' try some ps2 homebrew first see if I can get anything to display that way

**Comment by maximu** [comment]
@hyakki- you can try some demos http://purei.org/downloads/ps2demos/ 
Note : for quake.elf need id1 folder .

**Comment by jpd002** [comment]
I've made a fix for Adreno devices that had the black screen problem: fb141c71148f2b667be5405236d7aa47a4c79a9f. It's also in today's weekly build. This might also fix your problem.

**Comment by hyakki-** [comment]
I did a quick test on ar tonelico 1 - and I did see a graphic of the no memory card inserted dialog but black screen after that *(I dunno the compatibility of this game yet), I will do some further testing with a more popular game like ff10 or 12 , and the quake demo, just have to copy them over to my device

**Comment by jpd002** [comment]
That black screen in Ar Tonelico is the movie playing and can be skipped by pressing start.

**Comment by hyakki-** [comment]
excellent work so far so good, seems like graphics are working now, speed isn't too bad either :)
ar tonelico
http://i.imgur.com/ft3O5H2.png
http://i.imgur.com/egEHRt7.png
http://i.imgur.com/Aeef3OX.png

ff12
http://i.imgur.com/3htw6BJ.png
http://i.imgur.com/jKMXhYl.png
http://i.imgur.com/eNRSorc.png

**Comment by IllusionMan1212** [comment]
Issue is fixed, therefore should be closed.

**Comment by jpd002** [comment]
Indeed! Thanks!
