### ISSUE TITLE
GT4 Graphical bug

### ISSUE THREAD

**Issue by NatG34** [jpd002/Play-#971]
Gran Turismo 4 has a graphical bug impacting the all screen. Playing a race is impossible
![image](https://user-images.githubusercontent.com/31066076/97805181-ce5d8c80-1c54-11eb-84aa-9ac4ccbe3e9c.png)

**Comment by ilovelinux** [comment]
Duplicate of https://github.com/jpd002/Play-Compatibility/issues/152

**Comment by jpd002** [comment]
Indeed! Thanks for pointing this out!
