### ISSUE TITLE
Graphical glitches in Persona 3 fes and Persona 4.

### ISSUE THREAD

**Issue by Snappermaw** [jpd002/Play-#972]
Android
Device :Redmi k20 pro
Processor:Snapdragon 855
Ram :6 gb
Graphical glitches present throughout both the games.![IMG_20201104_020124.jpg](https://user-images.githubusercontent.com/73879387/98037755-1392e180-1e42-11eb-883e-80eae3260d52.jpg)

**Comment by Dragon20C** [comment]
please provide some screenshots and maybe a debug log.

**Comment by Snappermaw** [comment]
![IMG_20201104_020124.jpg](https://user-images.githubusercontent.com/73879387/98037652-eba37e00-1e41-11eb-909d-204857fa37fb.jpg)

**Comment by Snappermaw** [comment]
It's like this through out the game ,even the letters are barely visible.Same for Persona 4.

**Comment by jpd002** [comment]
These are known problems. Please don't open game specific issues here.
https://github.com/jpd002/Play-Compatibility/issues/93
https://github.com/jpd002/Play-Compatibility/issues/103
