### ISSUE TITLE
Android: Persona 3 FES is having graphics problems

### ISSUE THREAD

**Issue by CaioMel360** [jpd002/Play-#974]
He has graphics problems and is very slow, I made comparisons with the DAMONPS2 free version and the performance is better in 480p, I know the project is still under development but they could optimize for the SNAPDRAGON660?
In the cutscenes the frame rate is much lower, I will show it in the screenshots
My Phone
Asus Zenfone Max Pro M2
Snapdragon 660 
4 GB RAM 2.2 GHZ
![Screenshot_20201105-132001](https://user-images.githubusercontent.com/53277803/98268902-d62a7300-1f6b-11eb-9bec-84a007b9c3f7.png)
![Screenshot_20201105-132127](https://user-images.githubusercontent.com/53277803/98268937-e2aecb80-1f6b-11eb-919c-2d11f5151d98.png)
![Screenshot_20201105-132155](https://user-images.githubusercontent.com/53277803/98268941-e3dff880-1f6b-11eb-9b53-3b27d26f186f.png)
![Screenshot_20201105-132205](https://user-images.githubusercontent.com/53277803/98268942-e5112580-1f6b-11eb-93d5-eab918f39a36.png)
![Screenshot_20201105-132247](https://user-images.githubusercontent.com/53277803/98268947-e5a9bc00-1f6b-11eb-9412-3c4058c9b031.png)
![Screenshot_20201105-132348](https://user-images.githubusercontent.com/53277803/98268948-e6425280-1f6b-11eb-8877-4d5059476821.png)
![Screenshot_20201105-132403](https://user-images.githubusercontent.com/53277803/98268952-e6dae900-1f6b-11eb-90ec-d9a263c672e6.png)
![Screenshot_20201105-132439](https://user-images.githubusercontent.com/53277803/98268962-e93d4300-1f6b-11eb-9323-ac0c0a90cf12.png)
![Screenshot_20201105-132451](https://user-images.githubusercontent.com/53277803/98268965-e9d5d980-1f6b-11eb-8d06-068c1fca2d2d.png)
![Screenshot_20201105-132500](https://user-images.githubusercontent.com/53277803/98268973-eb9f9d00-1f6b-11eb-98de-cc5c3d704992.png)

**Comment by jpd002** [comment]
This is known. Please don't open issues for game specific problems here.
https://github.com/jpd002/Play-Compatibility/issues/103
