### ISSUE TITLE
[iOS] Emulator crashes on game load

### ISSUE THREAD

**Issue by FourteenCoast** [jpd002/Play-#978]
Tested with NTSC-U God Hand and NTSC-U Shin Megami Tensei: Nocturne

**Comment by ilovelinux** [comment]
Both games doesn't work well on Play! but these issues should not lead to a crash.
Could you confirm that the issue is not the game that hangs but the iOS app that crashes?

**Comment by jpd002** [comment]
@FourteenCoast Which version of iOS are you using? I'm assuming you are running on a non-jailbroken device with iOS 14? 

Going to close this one, since it's probably related to #1017.
