### ISSUE TITLE
Repair

### ISSUE THREAD

**Issue by huaihuai11oo** [jpd002/Play-#980]
WILD_ARMS_ALTER_CODE_F 
number:SCPS-17002
Keep pressing the button in the ring.The number of frames will be increased
![1605449022503](https://user-images.githubusercontent.com/74244597/99186919-3615dc00-2719-11eb-8d46-16ccb3c3bb45.jpg)

![1605449102529](https://user-images.githubusercontent.com/74244597/99186946-60679980-2719-11eb-98c2-ce00375a11c9.jpg)

**Comment by huaihuai11oo** [comment]
Model MATE40 Kirin 9000

**Comment by ilovelinux** [comment]
Hi, could you open an issue on Play! Compatibility repository? Here's the link: https://github.com/jpd002/Play-Compatibility/
Please follow the guidelines on README.md before opening a issue there.
This repository is not intended to report compatibility issues :slightly_smiling_face:
