### ISSUE TITLE
Fatal Frame 1 | After open the door, the character stuck.

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#983]
https://youtu.be/eqsZB4DBgO4

**Comment by ilovelinux** [comment]
Hi @ericsonia! The compatibility issues with Fatal Frame are actually tracked here: https://github.com/jpd002/Play-Compatibility/issues/124
Could you post that link there and close this issue? Thanks

**Comment by ericsonia** [comment]
> Hi @ericsonia! The compatibility issues with Fatal Frame are actually tracked here: [jpd002/Play-Compatibility#124](https://github.com/jpd002/Play-Compatibility/issues/124)
> Could you post that link there and close this issue? Thanks

Ok
