### ISSUE TITLE
How to build iOS ver resolution down? to enhance fps 

### ISSUE THREAD

**Issue by Softdrink87** [jpd002/Play-#984]
IMO, does downgrading resolution  really enhance fps on iOS version?
If it’s correct, I want to build my custom resolution.

Anyone help me do right? Thanks

**Comment by darkpigeon** [comment]
No, the performance is nearly the same between 1x and 2x resolution as i have tested so far

**Comment by brand175** [comment]
@Softdrink87 Play! Emulator is 100% CPU bound. My i9-9900K and RTX 2080 can't even get 60fps in shadow of colossus even at native resolution. Some games run close to fullspeed or fullspeed with minor slowdowns

**Comment by Softdrink87** [comment]
Thank you for getting information I’ve wondered.
