### ISSUE TITLE
What does that mean - bootable.db ? 

### ISSUE THREAD

**Issue by spotanjo3** [jpd002/Play-#985]
Operation not permitted: '/Users/username/Documents/Play Data Files/bootables.db

**Comment by jpd002** [comment]
Hi there!

Where/when are you getting that message? I assume this is on macOS, is this right?

Thanks!

**Comment by spotanjo3** [comment]
> Hi there!
> 
> Where/when are you getting that message? I assume this is on macOS, is this right?
> 
> Thanks!

Yes, sir.

**Comment by StLouisCPhT** [comment]
In a general sense it would mean there is an issue with either your document folder or the bootable.db database file. First thing to do is check System Preferences > Security & Privacy > Privacy > Files and Folders to be sure that Play has permission to access your Documents folder.

**Comment by spotanjo3** [comment]
> In a general sense it would mean there is an issue with either your document folder or the bootable.db database file. First thing to do is check System Preferences > Security & Privacy > Privacy > Files and Folders to be sure that Play has permission to access your Documents folder.

Thank you. And here:

No 'SYSTEM.CNF' file found on the cdrom0 device.

**Comment by spotanjo3** [comment]
???

**Comment by jpd002** [comment]
Which game file are you trying to load?

**Comment by spotanjo3** [comment]
> Which game file are you trying to load?

Hi. Rockman Power Battle Fighters (JP) - *Bin/Cue but Castlevania: Lament of Innocence (US) - iso runs ok, thought.

**Comment by StLouisCPhT** [comment]
Very strange. I don't have the Rockman game, but I do have both Phantasy Star remakes as bin/cue images and do not get that error with either the Intel build or my Apple Silicon build.

**Comment by spotanjo3** [comment]
> Very strange. I don't have the Rockman game, but I do have both Phantasy Star remakes as bin/cue images and do not get that error with either the Intel build or my Apple Silicon build.

Very strange too because I got the Rockman game in iso file and it works just fine but not bin/cue files. @_@

By the way, Virtual Audio QSound logo glitches but ingame is playable great. :)

**Comment by spotanjo3** [comment]
One question: You can't boot bios on the screen ? I like to see bios like a real PS2 console. Can you ? There is no settings to enable it, is there ?

**Comment by spotanjo3** [comment]
And is Klonoa 2 Europe playable ? Black screen to me.

**Comment by jpd002** [comment]
Fixed the original issue from this thread: https://github.com/jpd002/Play-/commit/dc1a5a7049e495ebcec04bf1669142ba232c3fdc

For your questions: 
- No, you can't boot to the BIOS.
- Klonoa 2 doesn't work (https://github.com/jpd002/Play-Compatibility/issues/843).
