### ISSUE TITLE
Xcode error trying to build Play- on ARM MacBook Pro using Rosetta 2 mode

### ISSUE THREAD

**Issue by StLouisCPhT** [jpd002/Play-#986]
When trying to build the latest Play- code on my Arm Mac with Terminal, I receive an error that Play.xcodeproj does not exist. The error occurs with the Xcode cmake command presented on the main page under Building for macOS & iOS and happens as an arch -x86_64 build under Rosetta 2.

**Comment by StLouisCPhT** [comment]
I have checked the entire git directory as cloned and the Play.xcodeproj file is nowhere to be found.

**Comment by jpd002** [comment]
Hi!

Strange... Does the CMake project generation succeed? If it succeeds, you should find a Play.xcodeproj in the build folder.

Haven’t tried building on an Apple Silicon yet, so maybe there’s something wrong with the CMake config.

**Comment by StLouisCPhT** [comment]
Would you believe me if I said it was all down to a typo?
Seriously, I don't know what was going on. 3 tries with clean git clones all had the same issue, but I just tried again and it worked this time.
