### ISSUE TITLE
Xiaomi mi4 

### ISSUE THREAD

**Issue by lifeiseternal** [jpd002/Play-#99]
I'm beta testing Play on Xiaomi Mi4(Snapdragon 801,Adreno 330),i tried with many games like Gradius V that result in the list of playable games but the screen remains Black,FPS arrive to 25/30 and Dc/f to 110/170 but also after several minutes nothing happens.

**Comment by jpd002** [comment]
Thanks for the report. Maybe it's related to #97 ? That Galaxy Tab also has an Adreno 330.

**Comment by lifeiseternal** [comment]
@jpd002 Thank to you for your answer.
Yes it's seems the same problem.
Thank you for your work.

**Comment by MiNote** [comment]
Confirmed not working on my Xiaomi Redmi Note 4G and my Mi Note also.

**Comment by jpd002** [comment]
I'm getting a Mi 4 to investigate that problem myself. Don't know when it'll arrive though.

**Comment by MiNote** [comment]
Cool, thanks for your taking active effort for help. :)

**Comment by prafullpcsx2** [comment]
Any update on this? I too got this mobile today. Does it work now?

**Comment by jpd002** [comment]
Yup, just got my Mi 4 today and I was able to reproduce the problem. I'll be able to do some tests to see why we're having that black screen.

**Comment by lifeiseternal** [comment]
thank you very much @jpd002

**Comment by MiNote** [comment]
Yeah thank you so much @jpd002

**Comment by jpd002** [comment]
Fixed here: fb141c71148f2b667be5405236d7aa47a4c79a9f. It's in today's weekly build.

**Comment by MiNote** [comment]
Thank you. It works. The script is so complicated Lol. I'm sorry if the question has been asked before? Is there no sound in the current build? Or is it just me?

**Comment by jpd002** [comment]
Glad it worked! And nope, there's no sound yet.
