### ISSUE TITLE
Cannot find save data on Sdcard

### ISSUE THREAD

**Issue by leading-egg0382728920** [jpd002/Play-#994]
I had my .iso file on Sdcard and encountered an error like this
https://i.imgur.com/aVKcb9f.jpg
Someone, tell me how to solve this problem, Please!

**Comment by jpd002** [comment]
Does it prevent you from starting the game? Did you have a save file on your sdcard that you wanted to load inside the game?

**Comment by leading-egg0382728920** [comment]
No, jpd002
I don't have such a file like that in the first place due to an obvious reason is that I haven't even played this game previously.

**Comment by leading-egg0382728920** [comment]
This game is called Ar tonelico: Melody of Elemia (undub) and it's fully a .iso file format.

**Comment by jpd002** [comment]
So, you're stuck on that screen? You are unable to skip that message by pressing a button?

**Comment by leading-egg0382728920** [comment]
jpd002, thanks you very much
I did tap buttons but I never tried pressing the buttons
I'm sorry for such a trivial thing like this.

**Comment by jpd002** [comment]
No worries! Glad I could help!
