### ISSUE TITLE
Android build doesn't detect games in .cue format

### ISSUE THREAD

**Issue by darkpigeon** [jpd002/Play-#996]
As the title said. Unlike the windows and ios build, play! only detects games which are in .iso format on android(as of 0.36). Please look into this issue. Also some games doesn't boot in .iso format while their .cue ones still play normally on all platform, Zombie Virus is an example.
My apology if this has been reported before.

**Comment by jpd002** [comment]
Reproed the problem, working on a fix.

**Comment by jpd002** [comment]
Fixed in https://github.com/jpd002/Play-/commit/86632da338a635ef7c735b11114a8885bad8a3e6.

Thanks for reporting!
